- lib/termsupport.zsh
In termsupport, add a chpwd hook that notifies Apple Terminal.app of current working directory changes using the undocumented '\e]7;%s\a' sequence, instead of the normal window/icon title controls. 
Fixes https://github.com/robbyrussell/oh-my-zsh/issues/2646, letting new tabs always open in the correct directory.
This is done using chpwd_functions instead of the prompt/preexec hooks and is intentionally not controlled by DISABLE_AUTO_TITLE, so the directory is properly updated even when auto-titling is off (e.g. when user is setting window and icon titles themself).
> termsupport: add chpwd hook for setting pwd in Apple Terminal.app

- tools/install.sh
Use `--depth=1` to clone just the lastest version rather than every version in git.
> Fast installation time by shallow copying git repo

- lib/completion.zsh
- oh-my-zsh.sh
- plugins/last-working-dir/last-working-dir.plugin.zsh
- plugins/zsh_reload/zsh_reload.plugin.zsh
We are running oh-my-zsh on a shared install and the only issue is each
user having a custom cache dir. This will allow us to set the cache dir
to ZSH_CACHE_DIR=~/oh-my-zsh/cache/ .
> Allow custom cache dir

- lib/termsupport.zsh
Fixes #3524, where terminal control characters emitted from a chpwd hook can contaminate results of scripts or functions. Moves the control output to the precmd hook so it only shows at a prompt, when it's safe to do so. 
The pwd update code is done in the omz_termsupport_precmd function, instead of in title(), so it works even when DISABLE_AUTO_TITLE is set, so #2646 is still taken care of.
> Move pwd update output to precmd to avoid contamination

- plugins/cake/cake.plugin.zsh
See https://github.com/robbyrussell/oh-my-zsh/pull/1655#issuecomment-67301041 for context.
----
In the old version, the function returned true (0) if the cache file was newer than the Cakefile, which was *always* unless the Cakefile had been updated. Therefore we generated the file every time unless the Cakefile was updated, which was precisely when we needed to regenerate the cache file.
Now it generates the cache file only when the Cakefile has been updated.
> [Plugin: cake] switch newer-than logic to get the desired behavior

- plugins/ant/ant.plugin.zsh
Fix regenerating .ant_targets on most tab completions (which made ant support sloooow). 
Also make ant do the work of enumerating targets which fixes edge cases.
Note that this change does make it so that "internal" targets (those with no description) are no longer shown, which could possibly be considered a breaking change. I'd argue this is good though, as `ant -projecthelp` also doesn't output these.
closes #1827
> Improved ant completion

- plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
If user manually deactivates the virtualenv when using this mode, zsh
will produce following error:
deactivate:12: command not found: virtualenv_deactivate
To avoid this, check that the VIRTUAL_ENV flag is set before trying to
automatically deactivate the virtual environment.
Fixes #2185
> virtualenvwrapper: Deactivate only if in virtualenv

- lib/aliases.zsh
- lib/directories.zsh
- lib/history.zsh
- lib/key-bindings.zsh
- lib/misc.zsh
- lib/theme-and-appearance.zsh
- plugins/autoenv/autoenv.plugin.zsh
- plugins/common-aliases/common-aliases.plugin.zsh
- plugins/git-prompt/git-prompt.plugin.zsh
- plugins/jump/jump.plugin.zsh
- themes/adben.zsh-theme
- themes/apple.zsh-theme
- themes/gnzh.zsh-theme
- themes/half-life.zsh-theme
- themes/jonathan.zsh-theme
- themes/kolo.zsh-theme
- themes/mikeh.zsh-theme
- themes/simonoff.zsh-theme
- themes/steeef.zsh-theme
- themes/zhann.zsh-theme
Repost of #2422 by @LFDM: 
> - Provides a more useful approach to directory switching, as suggested in #2412
> - Deletes aliases.zsh, as almost all things defined in their can find a place in other files present
>   - The directory aliases (some of the which duplicate functionality) are all in directories.zsh
>   - The history alias is in history.zsh. Also refactored to a nicer case switch
>   - Remaining pieces like the please alias for sudo are in misc.zsh
>   - Deletes the .. aliases from the common-aliases plugin, they are in lib anyway
> - Moves a bindkey statement from misc.zsh to key-bindings.zsh
> - Avoids sourcing of autoenv with every call to cd. This plugin related code is also taken out of the lib directory. Its activation file is now sourced only once - if its not present, …
> Repost #2422: cleaning lib

- plugins/sudo/sudo.plugin.zsh
I.e. when prefixing the current command-line with 'sudo ' maintain the
current cursor position instead of jumping to the end of the line.
This takes advantage of the fact that LBUFFER always contains all text left of the cursor and also happens to contain all text at the start of the buffer currently being edited.
> sudo: maintain cursor position

- plugins/dircycle/dircycle.plugin.zsh
This pull request fixes the error introduced in #3395, which changes `pushd -q -0` to `pushd -q +0`, which doesn't do anything unless you have the `pushd_minus` option set. But, if that's the case, then `pushd -q +1` doesn't work correctly. 
To that end I standardised that option since it seems to change between different zsh setups. You can read more in the [`PUSHD_MINUS` section of the `zshoptions` manpage](http://zsh.sourceforge.net/Doc/Release/Options.html#index-PUSHDMINUS).
I also removed the evals and cleaned up the plugin a little bit. 
I added in commit d63120501ed924b801774359fb3e8be902cbd0e5 the hability to switch between directories and redraw the prompt without using a new line to run the `pushd` command. 
Here are a couple of screencasts showcasing the difference:
- [Current …
> dircycle plugin: clean and fix logic once and for all

- plugins/last-working-dir/last-working-dir.plugin.zsh
Error encountered when installed with antigen: "chpwd:2: no such file or directory:".  Solution described in https://github.com/zsh-users/antigen/issues/75
> Removing 'local' usage to prevent issue when installed with antigen

- plugins/command-not-found/command-not-found.plugin.zsh
Fedora support by comment from [this issue](https://bugzilla.redhat.com/show_bug.cgi?id=678934) to close #3482.
> Add Fedora support for command-not-found plugin

- themes/rkj-repos.zsh-theme
From #2606 by @pfault:
> 'git rev-parse HEAD' call without existing commits in repo will fail with error message, breaking the theme
Close #2606 
> Repost #2606: fix git status in rkj-repos theme

- plugins/composer/composer.plugin.zsh
-------
This pull request is a compilation of the following:
- #2000: use `$_comp_command1` instead of `composer` to allow using `composer.phar` command; also complete `composer.phar` commands as well.
- #2049: add `composer global` aliases.
- #3375: little change in awk regular expression to parse composer commands in newer versions.
Also, I removed the requisite of having a `composer.json` file in the working directory to show composer commands. This I did because, as it was before, commands in the else statement weren't all that were available to run. Now, all commands will be shown instead (deprecates #2143).
**If no one agrees with this change I can get rid of it**.
Fix #2000, fix #2049, fix #3375.
Close #2143.
Close #3514, #3555.
> [Plugin composer] Multiple fixes

- lib/misc.zsh
This temporarily closes #2012 since it provides a complex solution that is possibly not useful. If we still have unicode issues with just this solution, we'll open it again and test it.
In most systems, `LC_CTYPE` will be correctly set while `LANG` will not be set (since it's optional). This generates a lot of messed up prompts and other problems. A cleanup of unicode-related issues will be needed after this gets merged.
> Fix Unicode problems by only setting LC_CTYPE if not set

- plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
From #2819 by @bsandrow:
> Ubuntu and Debian store the system-installed virtualenvwrapper in
/etc/bash_completion.d/virtualenvwrapper, so that it gets automatically sourced
at startup in Bash. By not putting it somewhere in $PATH, they end up excluding
others (e.g. Zsh) that might want to use that file. Oops!
> The virtualenvwrapper plugin should account for this so that Ubuntu (or Debian)
users don't end up with this message:
> ```
zsh virtualenvwrapper plugin: Cannot find virtualenvwrapper.sh. Please install with `pip install virtualenvwrapper`.
```
> even when they have a virtualenvwrapper installed to a known location.
I also fix indentation ([whitespace agnostic diff](https://github.com/robbyrussell/oh-my-zsh/pull/3567/files?w=0)) and adding to chpwd hook.
Close #2819.
/cc …
> Repost #2819: fix virtualenvwrapper for Ubuntu and Debian

- lib/termsupport.zsh
From #3426 by @apjanke:
> This moves the DISABLE_AUTO_TITLE check from title() itself to the precmd/preexec hook functions that call it. It also allows single-argument use by defaulting the long window title ($2) to the short icon title ($1).
> I'd like to do this because it would allow the title() function to be used directly by the user or other callers. In my workflow, I like to set the terminal tab title manually, and had my own settitle() function set up to do that. The OMZ title() function is already out there in the global function namespace, so it makes more sense to do that.
> This arrangement of the check in the hooks was discussed in #266 but dismissed as DRY/not needed for performance. But I think it's worth reconsidering: this isn't for performance, but an …
> Repost #3426: move DISABLE_AUTO_TITLE check to hooks

- lib/termsupport.zsh
This fixes the bug introduced in #3568 combined with #3525, which prevents the routine to notify current working directory to Apple Terminal _**if**_ the auto-title functionality is disabled (if `DISABLE_AUTO_TITLE == true`). 
Fixes #3570, fixes #1527.
> Extract CWD notifier back out of auto-title hooks

- plugins/laravel4/laravel4.plugin.zsh
- plugins/laravel5/laravel5.plugin.zsh
Laravel 5 inserts less spaces in in front of help items . So the logic changed and both plugins are now compatible with any artisan version
> Laravel 5 support

- lib/directories.zsh
The `-h` options in `l`, `ll`, and `la` were lost in 25b1cd6 when `ls` variants were factored from `aliases.zsh` into `directories.zsh`. There's no reason to remove the `--human-readable` option.
> Bring back -h (--human-readable) option to ls variants

- plugins/composer/composer.plugin.zsh
See http://www.gnu.org/software/gawk/manual/gawk.html#Regexp, section: 3.5 gawk-Specific Regexp Operators
> Fix composer completion: "\s" is a gawk-specific regexp operator.

- plugins/jhbuild/README.md
- plugins/jhbuild/jhbuild.plugin.zsh
This is a bunch of alias for the JHBuild tool.
A well known tool in the GNOME dev project.
> Add initial JHBuild plugin support

- plugins/docker/_docker
docker container autocomplete listing uses containers ID instead of names.
Most users identify their containers by name. ID is only needed and used on a dynamic environment more suited in scripts.
This modification uses the name of the container rather than the ID to autocomplete.
> docker containers based on defined names

- plugins/taskwarrior/_task
This is done by calling `_task` at the end of the _task completion file, as is standard in completion files.
Fixes #2044.
> Fix first-tab completion in task command

- README.textile
This reverts commit b6cbba9dfee5985232b473e94595c2fb1ab83715.
Use full Github URL until support for HTTPS in [ohmyz.sh](http://ohmyz.sh) is available.
Close #3459
Close #3461
> Revert usage of install.ohmyz.sh URL, until HTTPS support.

- lib/completion.zsh
Fixes #3550. Leave $cdpath at its default (`()`) instead of adding explicit `.`, which runs in to a file normalization bug on cygwin.
> Remove '.' from $cdpath to avoid Cygwin breakage

- plugins/vi-mode/vi-mode.plugin.zsh
Fix the problem with running zle commands when it is not active. This is to fix https://github.com/robbyrussell/oh-my-zsh/issues/3605.
Relevant documentation (http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html):
With no options and no arguments, only the return status will be set. It is zero if ZLE is currently active and widgets could be invoked using this builtin command and non-zero otherwise. Note that even if non-zero status is returned, zle may still be active as part of the completion system; this does not allow direct calls to ZLE widgets.
> Verify zle is active before trying to reset-prompt.

- themes/awesomepanda.zsh-theme
Fixes a bug where color of status arrow in prompt is red even when the exit code was zero (or success). This fix correctly returns green arrow on success and red for non-success exit code.
> Fixes incorrect prompt arrow color

- plugins/ubuntu/readme.md
- plugins/ubuntu/ubuntu.plugin.zsh
* Easy to remember consistent aliases
* Simplified, no more switch between apt-get and aptitude, just uses apt-get ans assumes sudo is installed
* Added aar() function for `sudo apt-add-repository xxxx && apt-get upgrade && apt-get install xxxx`
* More complete autocompletion ;)
> Create Ubuntu/Debian/Mint/... plugin, based on Debian plugin

- plugins/npm/npm.plugin.zsh
Shorthand for installation that's also saved to your package.json file.
Useful for Node.js devs that use OhMyZsh. 
See https://docs.npmjs.com/misc/config#default-configs
> Add convenience aliases for installation of npm modules

- themes/trapd00r.zsh-theme
in the trapd00r theme vcs info is already displayed on the first line if in a version controlled directory. the second vcs info was displayed at the end of the second line without providing additional information. this was removed.
> removed superfluous vcs_info_msg in trapd00r theme

- plugins/git/git.plugin.zsh
> Add alias for git add --all

- plugins/vagrant/_vagrant
A command I personally end up having to use in my day-to-day. I thought maybe others could benefit from it. I found that ssh-config was not autocompleting the list of available vagrant machines. Found it was missing from the list of supported autocomplete commands in the _vagrant script.
> Adding ssh-config to vagrant plugin autocomplete. Was missing

- plugins/tmuxinator/_tmuxinator
Plugin find works with symlinked configuration folders (eg when using some kind of dotfiles management)
@phstc is it possible to check that it works well on OSX too?
Also completion now supports the shorthand syntax `mux project_name`
> Tmuxinator plugin improvements

- themes/ys.zsh-theme
This small change basically lets the `ys` theme use hg repo info, in addition to the git info it already supports. We don't use vcs_info because all we want to know is if the repo is clean or dirty.
Original Git implementation:
New HG implementation:
I haven't done much in the shell, so please let me know if there are any issues!
> Let 'ys' theme use hg repo info too

- plugins/bgnotify/README.md
- plugins/bgnotify/bgnotify.plugin.zsh
Get background notifications for long running commands! *Running a build? A deploy? Moving files?* Anything that takes more than 6 seconds (easily configurable) sends you a slick and unobtrusive system notification: 
It works with osx notification center (using terminal-notifier), ubuntu's native `notify-send`, and cygwin:
**Linux**
**Windows**
It supports having a custom message hook (in case you need it to say 'holy smokes batman' for example).
There are a few hacks to do the same thing-- often making heavy use of AppleScript and being very platform-spesefic. This plugin makes a point to run on all three major platforms.
> Background notifications on long-running commands

- plugins/sublime/sublime.plugin.zsh
Added alias `sst` (sudo sublime text) for run sublime with root rights
> Sublime Text plugin: sst alias for sudo run sublime

- plugins/grunt/grunt.plugin.zsh
Update @yonchu's Grunt plugin to its most recent version.
Changes include:
- Preserve colons in completion.
- Fix subtasks with multi colons.
- Rename function (_grunt > __grunt)
> Update Grunt plugin to 0.1.2

- plugins/bgnotify/bgnotify.plugin.zsh
On my OS X Mavericks bgnotify only used the first word when I created a custom message in the bgnotify_formatted function.
> Fixing spaces in title and message given to bgnotify on OS X

- plugins/bgnotify/bgnotify.plugin.zsh
This patch will re-order the if statements when checking what operating system the user is running.
This is useful for people that already have a `notify-send` binary in their $PATH but are running OSX. An example of such requirements is anyone running `vagrant-notify` is required to have a `notify-send` binary on their $PATH.
See [link](https://github.com/fgrehm/vagrant-notify#os-x).
> Re-order OS detection if..else statement in bgnotify plugin.

- plugins/npm/npm.plugin.zsh
A member of the community contacted me, letting me know they use an npm module that is globally installed as npmd. This module does not have very wide adoption, but it does highlight that I could have done better to prevent conflicts. As these aliases are for devs that use npm, and npm enforces lowercase names, a potential solve is to use camelCased aliases.
Fixes #3640
> Use camelCase for npm aliases

- plugins/frontend-search/frontend-search.plugin.zsh
Removing `https://` because this informations already added in stackoverflow search url
> fix stackoverflow url in search

- plugins/docker/_docker
Fixing some issues where show repeated weird values, and fixed commands that need the container not running, like start. 
Now it autocompletes showing all the containers so you can start a stopped container by selecting it from the autocomplete list.
> Some fixes for Docker plugin

- tools/install.sh
Running the install script on Fedora 20 (after having yum-installed zsh) throws the following error:
chsh: "/usr/bin/zsh" is not listed in /etc/shells
This is caused by the following line:
chsh -s `which zsh`
The explaination is the following:
* Running `which -a zsh` return `/usr/bin/zsh` and `/bin/zsh`, but running `which zsh` returns only the first one: `/usr/bin/zsh`.
* Checking the available shells with `chsh -l | grep /zsh$` only returns `/bin/zsh`
* That's why the `chsh -s` command fails.
Both zsh paths should be present in `/etc/shells`, but it looks like it's a Fedora bug (see [bug 1034060](https://bugzilla.redhat.com/show_bug.cgi?id=1034060)).
One way to make the shell switching more robust is to set zsh from the list of available shells returned by `chsh -l` instead. The …
> Install script's chsh not working on Fedora

- plugins/extract/_extract
- plugins/extract/extract.plugin.zsh
Prior to this commit, the extract plugin did not know what .ipsw file was.
This commit adds .ipsw files to the extract auto-completion list and extracts it with `unzip`.
> Add .ipsw to the extract plugin.

- themes/minimal.zsh-theme
Set the closing square-brace's FG colour to white, to match the opening brace, when the repo directory is dirty.
> Minor cosmetic fix to minimal theme

- themes/candy-kingdom.zsh-theme
- themes/fino-time.zsh-theme
- themes/fino.zsh-theme
`echo` doesn't care about empty argument, so, if $SHORT_HOST doesn't exist, it's just print space or so.
> Fix echo nothing if $SHORT_HOST doesn't exist.

- plugins/git/git.plugin.zsh
This is a hot fix for the last Git plugin update #2790.
**STATUS: READY for MERGE**
***
**TODO:**
***
Closing forgotten issues: fixes #3751, fixes #3756
> [HotFix] Git plugin

- plugins/sublime/sublime.plugin.zsh
Adds paths for Sublime Text 3, which are slightly different. Tested and working on arch linux, and seems to be the same for most other package manager installation locations.
> Add sublime text 3 paths to check list

- themes/agnoster.zsh-theme
Quick fix to solve odd separator char when using agnoster theme on Mac
> Fixed odd chars on mac for agnoster theme

- lib/misc.zsh
Partially fixes #3614 by checking to see if url-quote-magic exists before loading it.
> Only load url-quote-magic if it is available.

- plugins/gitfast/_git
The gitfast plugin file `_git` tries to find the `git-completion.bash` file by looking in several directories, including the directory containing `_git`. However, if there are spaces in that directory name (like there are for me because I have my home directory on a secondary hard drive), the search list looks like:
```
/etc/bash_completion.d/git
/usr/share/bash-completion/completions/git
/usr/share/bash-completion/git
/Volumes/Secondary
HD/michael/.oh-my-zsh/plugins/gitfast/git-completion.bash
```
when it should look like:
```
/etc/bash_completion.d/git
/usr/share/bash-completion/completions/git
/usr/share/bash-completion/git
/Volumes/Secondary HD/michael/.oh-my-zsh/plugins/gitfast/git-completion.bash
```
This pull request adds quotes to the directory parsing to fix this issue.
> Adding quotes to git completion discovery path

- themes/minimal.zsh-theme
6ce08acb27 broke minimal.zsh-theme's check for SVN repos.  I've updated minimal.zsh-theme to use the return code instead of output value.  Additionally took the time to add support for mercurial as well.
> Fix minimal.zsh-theme's check for in_svn and add support for mercurial

- plugins/vundle/vundle.plugin.zsh
Vundle changed the command names during an interface update. The old commands will be deprecated. Ref https://github.com/gmarik/Vundle.vim/blob/v0.10.2/doc/vundle.txt#L372-L396
> Use the newest Vundle commands

- plugins/gradle/gradle.plugin.zsh
This fixes the gradle plugin. The regular expression used to pull task names didn't include a colon. Subprojects in gradle are of the form foo:fooTask, so they weren't being included. This fixes the bug.
> Fixes gradle autocomplete so it includes subproject tasks

- plugins/history-substring-search/history-substring-search.zsh
When history-substring-search is loaded, it would set extendedglob globally.  This can lead to problem when user do not want extendedglob, for instance, ^ would be interpreted like *.
The proposed change pushes extendedglob to -begin() and -end() as local options.
> Don't leak extendedglob to global environment.

- plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
This patch allow the autoactivation of virtualenv in any parent directory.
This is useful when the .venv directory is not at the root of the git repository.
In addition, it works even if the .venv is not in a git repository.
> Detect the .venv in any parent directory of the current directory

- plugins/debian/debian.plugin.zsh
Improving with "safe-upgrade" for aptitude and "upgrade" for apt-get on debian plugin
> Debian Plugin: Differing upgrade and safe-upgrade

- plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
PR #3918 introduced a dependency on the command `realpath` to the virtualenvwrapper plugin. This is a problem because `realpath` is not installed on many systems by default. (It's not even available in the main Homebrew tap for OS X.) This caused problems for some users (#4079).
This PR removes the `realpath` dependency by replacing `realpath` calls with `zsh`'s native `:A` [parameter expansion modifier](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Modifiers), which does the same thing as `realpath`, except portably and with no external dependency. This is also a performance win because it avoids the need to shell out to an external command.
The original code also called `realpath` at every step of the directory tree it was walking up. This is unnecessary because the first …
> virtualenvwrapper: Remove `realpath` dependency using zsh `:A`

- plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
Makes `virtualenvwrapper` see git repos as project roots again, which was lost in the #3918 change.
Fixes #4110
Closes #4070 
Depends on #4106 
In #3918, the virtualenvwrapper plugin logic was changed so that `.venv` dirs at any point created a virtualenvwrapper project root, but Git repos without a custom `.venv` were no longer treated as project roots. This was unexpected by some users, who are using non-customized Git repos as project roots. (See #4110, #4070, discussion in #4106, discussion in #3918).
This PR restores the old behavior of treating any Git repo as a project root, in addition to #3918's use of `.venv` as defining a project root. Combined with #3918, this means that the lowermost Git repo or customized `.venv` project will be treated as the project root.
There appear to …
> virtualenvwrapper: Treat git repos as project roots again

- lib/termsupport.zsh
Display the hostname when running Mosh (http://mosh.mit.edu/).
Same thing as displaying "hostname" when running "ssh hostname".
> Added ssh-like mosh window title

- plugins/vundle/vundle.plugin.zsh
Instead of quiting each window manually, quit all directly.
> Use 'quit all' instead of counting needed quits

- plugins/systemd/systemd.plugin.zsh
I added few aliases, which I miss when managing systemd:
* `sc-cat` -> `systemctl cat` 
* `sc-edit` -> `sudo systemctl edit`
> Add alias for "systemctl cat" and "systemctl edit"

- lib/termsupport.zsh
Adds `emulate -L zsh; setopt prompt_subst` to `title()` for portability. This prevents it from malfunctioning when `setopt prompt_subst` is off.
Fixes #4199.
> termsupport: protect title() with `emulate -L zsh` for portability

- plugins/dirhistory/dirhistory.plugin.zsh
- plugins/dirpersist/dirpersist.plugin.zsh
- plugins/last-working-dir/last-working-dir.plugin.zsh
dirhistory and last-working-dir clobber each other's chpwd functions when used together. This PR changes them both to append to chpwd_functions instead of clobbering chpwd
> Fix chpwd clobbering in dirhistory and last-working-dir

- lib/functions.zsh
- plugins/fasd/fasd.plugin.zsh
- plugins/frontend-search/frontend-search.plugin.zsh
- plugins/jira/jira.plugin.zsh
- plugins/lighthouse/lighthouse.plugin.zsh
- plugins/node/node.plugin.zsh
- plugins/web-search/web-search.plugin.zsh
This PR implements an oh-my-zsh standard open function that is cross-platform and easy to use for all plugins and users as well to create their aliases.
The function is called `open_command` and it uses the `$OSTYPE` value to decide which command to run. 
This PR also changes those plugins that used old logic so that we have consistent, non-duplicate code throughout the project codebase. Plugins changed: `fasd`, `frontend-search`, `jira`, `lighthouse`, `node` and `web-search`.
These other plugins also have open commands but are OSX specific, so there's no need to use a cross-platform open command: `atom`, `bwana`, `marked2`, `osx`, `textmate` and `xcode`.
Fixes #1478.
Fixes #2988.
Fixes #3920.
> Implement and use a standard, cross-platform open command

- plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
This PR fixes #4226:
> You can reproduce it by following the steps below:
> ```
$ mk "long dir"
$ cd long\ dir
$ git init repo
$ cd repo
workon_cwd:local:5: not valid in this context: dir/repo
```
> [virtualenvwrapper] Add quotes to support folders with whitespace

- oh-my-zsh.sh
PR #3617 moved the loading of custom scripts up, just before loading core lib files. This broke backwards compatibility, so we should revert it before we come up with a long-term solution.
Fixes #4072.
Related #3282, #3617.
This reverts commit a28dbc83937cbe624ec726199b4bbe7b65b2b2a0.
> Revert commit a28dbc8 ("Move custon *.zsh file sourcing up ...")

- lib/termsupport.zsh
Apple's Terminal.app displays the current directory in the window title bar independently. So if the dir is included in the window title, you get a redundant copy.
This PR has termsupport detect Terminal.app and remove the current directory from the default window title format.
Fixes #4213.
> termsupport: avoid repeated dir in window title in Terminal.app

- plugins/fbterm/fbterm.plugin.zsh
This PR modifies the fbterm plugin in the following ways:
- Checks if `fbterm` is installed.
- Only exits if `fbterm` finished correctly, _i.e._ with exit code equal to 0.
~~This presupposes that `fbterm` will start without and error. There's currently no mechanism to test if fbterm will start correctly  (see [fbterm#73](https://code.google.com/p/fbterm/issues/detail?id=73)). This means that if `fbterm` fails, the shell session will be closed, due to how `exec` works.~~
~~Maybe a better solution is to get rid of the `exit` statement, which will make the `fbterm` error visible. On the other hand, if `fbterm` starts correctly, once the user logs out of it the first shell session will be open.~~
Now it will only exit if `fbterm` finishes correctly. Remains to be checked that if `fbterm` …
> Fix fbterm autostart

- plugins/web-search/web-search.plugin.zsh
This plugin adds baidu commands to launch the default
web browser to do web search:
e.g.
baidu oh-my-zsh
> Add Baidu support to web-search plugin

- plugins/fuck/fuck.plugin.zsh
- plugins/thefuck/README.md
- plugins/thefuck/thefuck.plugin.zsh
[The Fuck](https://github.com/nvbn/thefuck) plugin — magnificent app which corrects your previous console command.
Press `ESC` twice to correct previous console command.
> The Fuck plugin (https://github.com/nvbn/thefuck)

- tools/install.sh
Fixes #3367 
Fixes #3612
Closes #4186
The installer uses the nonstandard `sed -i` extension for in-place editing. This makes it not portable to systems whose `sed` doesn't have the `-i` extension, in particular OpenBSD (#3367). This replaces the `sed -i` with explicitly-managed temp files.
This also fixes the problem of leaking `~/.zshrc-e` files due to incorrect use of the `-i` option in the current installer (#3612).
To test this, run the following in a user account that does not already have OMZ installed. (Careful... it seems a little difficult to copy and paste from this little field in some browsers.)
```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/apjanke/oh-my-zsh/remove-sed-i/tools/install.sh)"
```
> Installer: Remove "sed -i" for portability and hygiene

- plugins/osx/osx.plugin.zsh
Remove redundant semicolon to make tab() works better in iTerm 2.
> Remove redundant semicolon

- plugins/ubuntu/ubuntu.plugin.zsh
I use that command a lot of times, and there's no shortcut for that.
Now it does :)
> added apt-get autoremove in ubuntu plugin

- plugins/jira/_jira
- plugins/jira/jira.plugin.zsh
This combines and merges the changes from #4202 (optional dashboard default action), #4158 (help message for JIRA_URL), and #4132 (`$JIRA_PREFIX`) and adds some other stuff, too.
This way you can see how all the changes go together, and have one PR that has all the merging taken care of.
* Adds a `jira new` for completeness
* Adds `jira dashboard` to open up the dashboard
* Adds `$JIRA_DEFAULT_ACTION` to configure what plain `jira` does (per #4202)
* Adds completion support for the `jira` command, so `jira d<tab>` turns in to `jira dashboard` and `jira<tab>` lists the special argument values
* Expands the documentation to cover all currently implemented argument forms and environment variables
* Refactors
Closes #4202
Closes #4158 
Closes #4132
> jira: prefix variable dashboard, default action, and completion

- plugins/symfony2/symfony2.plugin.zsh
with symfony 2.7 command group titles are listed as commands. this commit prevents it.
> plugin symfony2 sf2.7 compatibility fix

- plugins/emoji/emoji.plugin.zsh
- Uses the right variable name (`$group` instead of `$group_name`)
- Check that the names array has any element before attempting to pick an emoji out of it. This fixes the same problem on groups that don't exist (_e.g._ `random_emoji 404notfound`).
Fixes #4245.
/cc @robbyrussell @fallwith @apjanke
> Fix divide by zero in emoji plugin

- plugins/rand-quote/rand-quote.plugin.zsh
This plugin was designed so that if there is any failure, it simply calls itself recursively. Which means that if you were working offline, and `quote` was called in your `.zshrc`, you would be unable to open a new terminal session.
I fixed this by allowing the plugin to output nothing if a quote could not be fetched.
> Rand-quote plugin overflows stack when site is unreachable

- plugins/autojump/autojump.plugin.zsh
It seems like there is only one file to source now, see https://github.com/Homebrew/homebrew/blob/master/Library/Formula/autojump.rb (the autojump.zsh file got removed).
> Update autojump plugin for latest brew installation

- plugins/rbenv/rbenv.plugin.zsh
The existing rbenv plugin code calls the same `brew --prefix` twice: once for detecting if rbenv is installed via brew, and again to get the path. This inlines the call so we only need to call it once. The call is expensive -- about 150ms each time on my mac. 
```zsh
~/.oh-my-zsh > @ rbenv_plugin_load_performance $ repeat 10 /usr/bin/time zsh -i -c exit
0.31 real         0.21 user         0.10 sys
0.32 real         0.22 user         0.10 sys
0.31 real         0.21 user         0.10 sys
0.30 real         0.21 user         0.10 sys
0.31 real         0.21 user         0.10 sys
0.31 real         0.22 user         0.10 sys
0.31 real         0.21 user         0.10 sys
0.32 real         0.22 user         0.10 sys
0.31 real         0.21 user         0.10 sys
0.31 real         0.21 user …
```
> reduce rbenv plugin load time by 150ms by removing additional brew call

- tools/install.sh
Check if Zsh is installed before installing anything else.
New-comers, or people who don't read the disclaimers(ex. me) will go
straight to stack overflow if chsh -s returns an error.
Fixes #3300
> Check if Zsh is installed prior to installing Oh My Zsh

- plugins/docker/_docker
By default docker images use the official docker hub, however by prefixing the image name with a URL it is possible to push and pull images from a different registry. This URL can also contain a non standard port number e.g. `web.address:port/namespace/repo`. 
When the current docker plugin encounters such an image the _describe function it splits the images into name = `web.address` description = `port/namespace/repo`. To fix this the command that fetches the image list needs to escape the `:` with a backslash.
> Add support for Docker images from custom registries

- plugins/git-prompt/git-prompt.plugin.zsh
- plugins/git-prompt/gitstatus.py
This PR pulls in the latest version from olivierverdier/zsh-git-prompt and adds the following modifications:
- Single call\* to `git status --porcelain -b`, thanks to @wkentaro (https://github.com/olivierverdier/zsh-git-prompt/pull/65, https://github.com/mcornella/oh-my-zsh/pull/2)
This avoids using up to 4 calls to git, while also fixing the problem with locales other than English (fixes #3460):
```
$ export LC_ALL=fr_FR.UTF-8
$ git status
Sur la branche dev
Votre branche est en avance sur 'origin/dev' de 5 commits.
(utilisez "git push" pour publier vos commits locaux)
Fichiers non suivis:
(utilisez "git add <fichier>..." pour inclure dans ce qui sera validé)
asdf
aucune modification ajoutée à la validation mais des fichiers non suivis sont présents (utilisez "git add" pour les suivre)
$ …
```
> Fix git-prompt plugin

- plugins/ember-cli/README.md
- plugins/ember-cli/ember-cli.plugin.zsh
1. `ember install:addon <addon-name>` is deprecated, and `ember install <addonName>` is to be used instead.
2. Bower and npm package installs are now managed by the user (The commands are removed.). `bower install <packageName> --save-dev --save-exact` and `npm install <packageName> --save-dev --save-exact` are to be used instead.
> Updates to ember-cli plugin

- plugins/frontend-search/README.md
- plugins/frontend-search/frontend-search.plugin.zsh
This PR refactors and cleans up the frontend-search plugin, and improves the documentation.
The changes include:
- Use of an associative array to define the necessary URLs.
This makes it trivial to add another search context: just append a new entry to the `urls` array, add the alias and update the help messages .
- Uses all arguments passed instead of just the second, to enable for multiword queries.
Now `frontend <context> multiple words or a whole phrase` will also work.
- Clarifies the README and removes duplicate information.
- Includes a better help message adapting it from PR #2930.  
This is how it looks:
Fixes #2930
/cc @willmendesneto
> Refactor frontend-search plugin

- lib/compfix.zsh
- oh-my-zsh.sh
- tools/install.sh
This pull request fixes #630 for Cygwin as well as [babun](https://github.com/babun/babun) issues [#159](https://github.com/babun/babun/issues/159), [#281](https://github.com/babun/babun/issues/281), and [#322](https://github.com/babun/babun/issues/322). For non-Cygwin platforms (e.g., Linux, OS X), this only partially addresses #630 by improving startup error reporting in a platform-independent manner. In theory, that should both improve the readability of related bug reports *and* enable end users to locally fix this issue themselves.
The `oh-my-zsh.sh` startup script currently caches completions as follows:
compinit -i -d "${ZSH_COMPDUMP}"
**That's a problem.** The `-i` option instructs `compinit()` to silently ignore all top-level completion-dependent directories having insecure …
> Repair `zsh` Path Permissions on `oh-my-zsh` Startup under Cygwin

- plugins/capistrano/_capistrano
- plugins/capistrano/capistrano.plugin.zsh
Uses `shipit` because [cap is a reserved word](http://zsh.sourceforge.net/Doc/Release/Zsh-Modules.html#The-zsh_002fcap-Module), so `cap` completion doesn't work.
```bash
$ shipit |
production staging
$ shipit production |
deploy                       -- Deploy a new release
deploy:bundle                -- Bundle
deploy:check                 -- Check required files and directories exist
deploy:check:directories     -- Check shared and release directories exist
deploy:check:linked_dirs     -- Check directories to be linked exist in shared
deploy:check:linked_files    -- Check files to be linked exist in shared
deploy:cleanup               -- Clean up old releases
deploy:cleanup_rollback      -- Remove and archive rolled-back release
deploy:finished              -- Finished
deploy:finishing …
```
> Adds support to capistrano multistage completion

- lib/theme-and-appearance.zsh
Retry of PR#2225, with help from ncanceill.  Will close the old PR now.
> add check for colored ls on openbsd. (retry of #2225)

- plugins/gradle/gradle.plugin.zsh
Gradle wrapper is typically in the current directory, not on PATH.
Closes #4166
> Fix invocation of gradlew

- lib/git.zsh
In addition to the already existing variables ZSH_THEME_GIT_PROMPT for behind, ahead and diverged remote, I added ZSH_THEME_GIT_PROMPT_EQUAL_REMOTE.
> added ZSH_THEME_GIT_PROMPT_EQUAL_REMOTE

- lib/diagnostics.zsh
This adds a new `lib/diagnostics.zsh` library file for OMZ/ZSH diagnostic functions, and defines the `omz_diagnostic_dump()` function that will dump a lot of info about the user's current shell state and configuration files to a dump file suitable for posting as a gist.
The intention is that this could be made part of the normal debugging and support workflow by asking bug reporters to just "run `omz_diagnostic_dump()` and post the results" instead of having to ask a series of questions and request individual files.
I've been using this in my custom dir for a while and it's been helpful with diagnosing some issue reports already (#3913, #3356, #3724, #3350).
Closes #3915
> Add omz_diagnostic_dump() to help with bug reporting

- plugins/scw/README.md
- plugins/scw/_scw
Adds autocomplete options for all [scw](https://github.com/scaleway/scaleway-cli): Manage Bare Metal servers from Command Line (as easily as with Docker) commands.
> Support for 'scw' command (Scaleway CLI)

- themes/gnzh.zsh-theme
Fixes #3425.
This clears up issues related to `eval` and the use of eager vs lazy evaulation in the `gnzh` theme. The `eval` was the one causing user-visible problems, but there's a small tangle of related issues, and this addresses them all.
The outcome of this PR is that:
* Prompt effect escapes are all lazy-evaluated at prompt time, using `%F`/`%f`
* Variables used to build the `$PROMPT` string are all eager-evaluated at theme loading time
* Except for ones that deliberately use `$(...)` to call functions at prompt time
* Variables are all `local`-ized
This PR removes the problematic `eval` usage by switching to [normal `zsh` %F/%f prompt escapes](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Visual-effects) to avoid "eval" and the associated global variables.
There were …
> gnzh theme: fix "eval" and related scope problems.

- plugins/rails/rails.plugin.zsh
Some background on the PR -
**1. Reasons behind the need of this alias**
* Often times we'd like to know what is the REST path of a certain rails resource and for that we use the command `rake routes | grep resource_name` from the command line.
* Sometimes we'd like to even know what is the URL corresponding to a specific resource action and we'd use the above command for the same.
**2. The alias that gives you the above information**
We can now cover the above mentioned use cases with the alias `rrg resource_name`. 
* Example
* Assuming the resource name is `users`, one could benefit from this alias via `rrg users`.
> Adds an alias to search for the rails routes that pattern match a string

- plugins/sudo/sudo.plugin.zsh
This change improves the behaviour of the sudo plugin. By pressing esc-esc once the sudo command is added at the beginning as usual; pressing it once more removes "sudo " from the beginning of the line.
> Esc-esc toggles sudo

- themes/steeef.zsh-theme
steeef theme sets colors depending on $TERM, however if %F is
used, it must be closed by %f instead of %{$reset_color%}.
Further on, all %f directives have been replaced by %F and color
support of current TERM is checked more properly.
> [theme] Fix color problem of steeef theme

- plugins/gnu-utils/gnu-utils.plugin.zsh
findutils (gfind, gxargs, glocate) are installed with Homebrew,
```sh
$ brew install findutils
```
> gnu-utils: add findutils (find,xargs,locate)

- plugins/npm/npm.plugin.zsh
Option to execute a command from closest ancestor node_modules folder
Example
```zsh
$ls
node_modules
other_folder
$npmE gulp
No gulpfile found
$cd other_folder
$npmE gulp
No gulpfile found
```
> Adds npmE alias

- plugins/xcode/README.md
- plugins/xcode/_xcselv
- plugins/xcode/xcode.plugin.zsh
This PR does the following:
- Fix the `xc()` function by only looking for `.xcworskpace` and `.xcodeproj` files.
It also cleans it up by using zsh arrays and localized variables.
- Change `xcsel` function into an alias, since it doesn't do anything extraordinary and `"$*"` might have side effects.
Closes #3259, #3950.
> Fix xcode plugin

- lib/completion.zsh
This PR solves the annoying problem of new line prompt being redrawn each when the terminal is small enough that the prompt + 5 chars being drawn don't fit the line. This is done by disabling automatic line wrapping using terminfo's `rmam` sequence.
It uses `%F{red}` as well, instead of `\e[31m` which might not be that bad for portability but it looks better and is clearer what the color is.
----
**Instructions:** you need a prompt that is sufficiently big that it occupies almost all the line space. There are 5 completion dots, so you'll need to have a prompt that is `$COLUMNS - command length - 4` minimum to trigger the new line prompt redraw. You also need to uncomment the line `COMPLETION_WAITING_DOTS=true` in your zshrc file to enable the feature.
Once that is in place, trigger the …
> Fix completion waiting dots function

- themes/cypher.zsh-theme
This fixes an issue in cypher's theme which occurs when the previous command's return status is non-zero and the prompt is redrawn. The ``fg[red]`` was not escaped, resulting in occasional graphical issues.
**Test**
When using cypher's theme, do any command resulting in a non-zero return status. Then try to make or edit a multi-line command. On the terminals I've tried this out on it overwrites the current line when hitting the end of a line, and when backspacing it starts to delete characters from line above the command.
It should also trigger when doing an ambiguous tab completion, where the first few characters of the command are drawn twice.
> Fix graphical bug in cypher theme when return status is non-zero

- plugins/vim-interaction/vim-interaction.plugin.zsh
This commit fixes the problem with special chars in filenames for vim-interaction plugin.
When opening a file with
```
v some\ long\ file\ name\ with\ spaces.txt
```
6 new files will be created in gvim instead of opening an existing one.
> [vim-interaction plugin] Escape special chars in filenames.

- plugins/fancy-ctrl-z/README.md
- plugins/fancy-ctrl-z/fancy-ctrl-z.plugin.zsh
Use Ctrl-Z to switch back to Vim
I frequently need to execute random command in my shell. To achieve it I pause Vim by pressing Ctrl-z, type command and press fg<Enter> to switch back to Vim.
The fg part really hurt sme. I just wanted to hit Ctrl-z once again to get back to Vim. I could not find a solution, so I developed one on my own that works wonderfully with ZSH:
Source: http://sheerun.net/2014/03/21/how-to-boost-your-vim-productivity/
> Added Fancy-ctrl-z plugin

- themes/agnoster.zsh-theme
Problem
On detached-refs, the git prompt is very slow because it uses a command
to output all refs, which takes 32s on the twitter internal git repo.
Solution
Use git-rev-parse instead of git-show-ref to only output the head ref.
Runtime drops to 0.03 seconds.
Note
Interestingly, git-rev-parse isn't slow without the --head arguement so
I'll probably be cooking up a patch for the git team to speed this up
eventually, but it's still pointless to sigpipe git as it walks the
filesystem.
> agnoster: speed up git prompt

- themes/agnoster.zsh-theme
Updates the agnoster theme to define its special Powerline characters using Unicode escape sequences, and use the current Powerline code point for SEGMENT_SEPARATOR on all platforms.
This makes the theme consistent with the current definition of Powerline, and removes the spurious Mac special case. There is no special handling necessary for Mac; that's just a result of users with old fonts misdiagnosing it.
In 2012, Powerline changed which Unicode code points are used for its special prompt characters, which has resulted in confusion. There are old versions of the Powerline-patched fonts out there that have the glyphs in the old code point slots. This means that whether Powerline looks "right" depends on which version of the fonts you have installed, which version of the code points your …
> agnoster: Use current Powerline chars everywhere, and clarify behavior

- plugins/golang/golang.plugin.zsh
- plugins/golang/templates/package.txt
Using `_path_files` for completing the package names makes the completion significantly faster.
Also, `godoc` is used to complete exported package identifiers.
> golang: improve go doc completion

- plugins/gradle/gradle.plugin.zsh
Instead of requiring to add `cwd` to path, just use `gradlew` from the local folder. This is how most gradle wrapper projects are laid out
> Use local gradlew

- plugins/jira/README.md
- plugins/jira/_jira
- plugins/jira/jira.plugin.zsh
Adds a README.md based on existing comments.
Adds "emulate -L zsh" to a couple functions to defend against possible quoting issues.
Adds a "dumpconfig" action. (The "dumpconfig" action is for verifying the configuration behavior against what's documented in the README now, which is why I included this new behavior in a "add README" PR.)
Adds "error" to some of the error messages.
> jira: add README.md

- plugins/chruby/chruby.plugin.zsh
Iʼm not quite sure why this was here in the first place, but it was causing these errors for me:
```
_source_from_omz_settings:4: permission denied: /usr/share/chruby/chruby.sh
_source_from_omz_settings:8: permission denied: /usr/share/chruby/auto.sh
```
As far as I can tell, it should be enough to just check if the file exists and is readable?
> chruby: donʼt try to execute .sh files before loading

- plugins/aws/aws.plugin.zsh
Multiple calls to `asp` pollutes `RPROMPT`. E.g. calling `asp foo` then `asp bar` will set `RPROMPT` to `<aws:bar><aws:foo>`. This patch makes sure only last value is presented.
> Fix aws plugin RPROMPT pollution

- plugins/atom/README.md
- plugins/atom/atom.plugin.zsh
This is a small scripting edit to the atom plugin to fix compatibility with Linux systems, so `at` works correctly instead of throwing a useless error.
Also slightly clarified readme for the plugin.
> Fix Atom Plugin for Linux Users

- themes/emotty.zsh-theme
When using completion (TAB) the cursor would sometimes be misaligned when the prompt showed emojis.
> Fix issues with character widths in emotty theme

- themes/amuse.zsh-theme
This will fix the git branch icon not showing in the Amuse theme.
> Fixed broken git branch icon

- plugins/capistrano/_capistrano
``shipit -v``, print only Capistrano version instead output all tasks when generating .cap_tasks\~ file.
> Fix capistrano problem when generating autocompletion

- plugins/chruby/chruby.plugin.zsh
Homebrew installed chruby couldn't be found due to erroneous test expression. This PR fixes said issue.
> Fix invalid test expression.

- lib/grep.zsh
cvs's metadata is under CVS and not .cvs
> Correct repo dir

- lib/git.zsh
Uniform git prompt equal remote to all others prompts, setting the correct symbol
(if applicable) to $git_remote_status, instead of echoing it.
It also solves the problem pointed out in #3911
> Uniform git prompt equal remote

- lib/misc.zsh
Incompatibilites between 5.0.8 and 5.1:
bracketed-paste-magic may also be necessary in order to apply url-quote-magic.
Reference: 
https://github.com/zsh-users/zsh/blob/a9df6aaa702abf761b155cd842a7f6917be44139/Functions/Zle/url-quote-magic#L11
> fix url-quote-magic not working issue

- plugins/fedora/README.md
- plugins/fedora/fedora.plugin.zsh
I've added fedora plugin.
As there are distro-specific plugin I thought to rename yum plugin, adapt to use dnf instead of yum (from Fedora 22 onwards, yum is deprecated).
> Added fedora plugin, based on dnf/yum plugin

- themes/amuse.zsh-theme
Change to print `ruby version` with `gemset name` in right prompt.
It was `<ruby-2.1.5>`
It become `<ruby-2.1.5@project-name>`
> Fix print rvm version in amuse theme

- plugins/git/git.plugin.zsh
New alias `gdct` for print the latest tag name of current repository
> Add alias for print latest tag name

- plugins/chucknorris/chucknorris.plugin.zsh
Fixes #4112
Fixes #4334
Depends on #3611 
This plugin depends on fortune and strfile, which is part of fortune. But that's not immediately obvious to many users, per #4112.
This PR has chucknorris check for `strfile` when it needs it, and if not found, issue a more helpful error message that suggests a "fortune" package, and doesn't attempt to use strfile to update the fortunes dir. Still puts the aliases in place, since they'll produce more obvious error messages if used when `fortune` is not installed.
Also handles Cygwin installing `strfile` to `/usr/sbin`, which is not on the path by default, by directly checking for `/usr/sbin/strfile` if the plain `strfile` command is not found.
Adds an anonymous function for hygiene, to avoid clobbering the global `$DIR` variable, and uses a …
> chucknorris: check for fortune/strfile dependency

- plugins/chucknorris/chucknorris.plugin.zsh
Adds auto-updating of the compiled fortune data cache file for when the input Chuck string file is updated. Otherwise, if the fortunes are updated, the stale cache file will prevent any new sayings from Mr. Norris from appearing. The source string file would get updated during an oh-my-zsh update, but since the data file was already built, it wouldn't attempt to build it unless user manually removed the old cache file. Better to do it automatically.
To test this, just `touch chucknorris` and open a new zsh login session.
```
$ pwd
/Users/janke/.oh-my-zsh/plugins/chucknorris/fortunes
$ touch chucknorris
$ zsh -l
"/Users/janke/.oh-my-zsh/plugins/chucknorris/fortunes/chucknorris.dat" created
There were 447 strings
Longest string: 374 bytes
Shortest string: 1 byte
$
```
I threw in an …
> chucknorris: Keep Chuck's fortunes fresh

- oh-my-zsh.sh
This turns off the insecure-completion-dir checking from #3889 by default but still leaves it in the codebase. Adds a `$ZSH_DISABLE_COMPFIX` to control it, and makes it true by default.
This will let us do some more testing on the #3889 stuff before making it the default for everyone. It's complex.
Fixes #4383 
Fixes #4388
> completion: turn off the #3889 compfix check by default

- plugins/gulp/gulp.plugin.zsh
This plugin works properly now.
> gulp plugin: missing opening double quote

- lib/misc.zsh
I have tested it on my Mac, and Ubuntu 14.04 in the virtual box.
> The executable command on Mac OSX is 'ack' rather than 'ack-grep'.

- lib/misc.zsh
Redirect STDERR along with STDOUT when looking for ack-grep
Fixes #4454
Closes #4456
> Fix 'ack-grep' bug for non-ubuntu users

- plugins/git-extras/README.md
- plugins/git-extras/git-extras.plugin.zsh
This changes all the __git_* functions it was defining to __gitex_* to avoid collisions with the internal functions used inside _git from zsh. Those internal functions are subject to change, so redefining them can cause compatibility problems with different versions of zsh.
Adds a README with notes on compatibility.
Fixes #4395.
> git-extras: fix for compatibility with zsh _git

- plugins/encode64/encode64.plugin.zsh
Currently, encode64 plugin using `echo -n` to print the content
of `$1` variable. This approach will not work with arbitrary data,
which contains sequence of escaped characters, since when many
`echo` implementation will expand them:
```
encode64 '\t\n'
```
is wrong since when it try to generate base64 of string contains a tab, a newline instead of literal `\t` and `\n`.
This commit change the usage to `printf`, which is builtin in all
POSIX shells and can print arbitrary data reliability:
```
printf '%s' '\t\n' | base64
```
will generate base64 of literal `\t` follow by `\n`
> Encode64 Plugin - Fix wrong `echo` usage

- tools/uninstall.sh
I lost a bunch of configs this afternoon because uninstall_oh_my_zsh was in my path and I accidentally executed it (betrayed by tab completion...), so here is a patch to ask before removing stuff, so this doesn't happen again.
> Ask for confirmation before uninstall

- plugins/autoenv/autoenv.plugin.zsh
Homebrew installs autoenv into `/usr/local/opt`. This PR has the plugin look there, too.
Closes #4147 (because it depends on and includes its commits)
Fixes #4438 
Also fixes an issue with #4147 where if you don't already have `autoenv` loaded, you'll see a spurious `autoenv_init not found` error message.
> autoenv: support homebrew-installed autoenv

- plugins/autoenv/autoenv.plugin.zsh
Fixes bug introduced in #4440. This bug will prevent autoenv from actually being loaded, even if it is found.
> autoenv: actually source autoenv once located

- plugins/git/git.plugin.zsh
an alias I find very helpful when checking the most current version of a project to prevent cases such as:
v2.3.17
v2.3.18
v2.3.19
v2.3.2 -> this isn't a most current version
with "| sort -V"
v2.3.2
v2.3.3
v2.3.4
v2.3.5
v2.3.6
v2.3.7
v2.3.8
v2.3.9
v2.3.10
v2.3.11
v2.3.12
v2.3.13
v2.3.14
v2.3.15
v2.3.16
v2.3.17
v2.3.18
v2.3.19 -> Now we have the current version \o/
> add alias to sort by version

- plugins/pyenv/pyenv.plugin.zsh
I use pyenv a lot, but the inbuilt plugin is missing a few things, so I thought I'd update it.
1. 8a95ced - Initialize pyenv virtualenvs, to get autocompletion for them.
2. 8a362b2 - Re-enable pyenv rehashing. It's useful, so not sure why it's disabled.
Let me know if this is OK!
> Tweak pyenv plugin

- lib/misc.zsh
Fixes #4434 (at least as much as it can be fixed).
Fixes #4452 
There is a bracketed-paste-magic bug specific to zsh 5.1.1 that can cause input to hang after pasting certain characters if bracketed-paste-magic is enabled as an input widget. To reproduce, run `zsh 5.1.1` and paste 日本語 into your terminal.
This PR works around it by checking for zsh 5.1.1, and not enabling bracketed-paste-magic for that version. Also disables url-quote-magic for that version, because since zsh 5.1, url-quote-magic requires bracketed-paste-magic.
> Disable bracketed-paste-magic in zsh 5.1.1, where it is buggy

- tools/install.sh
This is a hack to keep the installer working on systems without tput/terminfo, including FreeBSD (at least in the default installation for 10.2).
Fixes #4404.
Follows up on #3664.
> installer: ignore errors in color setup, for FreeBSD portability

- plugins/git-extras/git-extras.plugin.zsh
I fixed typo in `plugins/git-extras/git-extras.plugin.zsh`.
https://github.com/robbyrussell/oh-my-zsh/issues/4525
> [FIX #4525]: Fix typo

- tools/install.sh
This changeset wraps all of the commands in tools/install.sh in a
function and then calls that function as the last line of the
script.
The current install instructions ask the user to download the install
script using `curl` and pass the result to `sh`. This is totally
fine (as long as both the instructions and the script itself are served
using HTTPS), but the script should be written in a way such that it
doesn't start trying to actually *do* anything until the very last line.
The reason is due to the way `curl` works: if the socket drops before the
request is complete (server abruptly hangs up, client's internet flakes
out, etc.), `curl` will return the partial data that it received. Here
is an example of that:
A way this might cause issues for tools/install.sh is if the connection …
> Make install script safer

- tools/install.sh
- tools/upgrade.sh
@fcrozat's original fix assumes `which` not to output anything to STDOUT
in case the command is not found. That is not necessarily true on all
systems. A better solution is to check the return value instead.
Fixes #4376.
Supersedes #4496.
> Fix install.sh/upgrade.sh for tput-less systems

- plugins/rake-fast/rake-fast.plugin.zsh
I refactored rake-fast plugin.
If this plugin condition is `[[ "$OSTYPE" = darwin* ]];`,  the case of my stat An error will occur.
My stat doesn't have -c option because I'm using GNU core utilities that was installed in the Homebrew.
My environments:
OS: OS X Yosemite
stat: 8.24 (GNU core utilities)
```
$ rake [TAB] 
Try 'stat --help' for more information.
stat: invalid option -- '%'
Try 'stat --help' for more information.
_rake_does_task_list_need_generating:10: bad math expression: operand expected at `>='
stat: invalid option -- '%'
Try 'stat --help' for more information.
stat: invalid option -- '%'
Try 'stat --help' for more information.
_rake_does_task_list_need_generating:10: bad math expression: operand expected at `>='
stat: invalid option -- '%'
Try 'stat --help' for more …
```
> [FIX ERROR] Refactor for function in plugins/rake-fast/rake-fast.plugin.zsh

- README.markdown
The custom directory command is needed to match the current syntax we are using now. Otherwise, `chsh` errors would happen as well.
> [README] Update custom directory command and fix code blocks

- plugins/mercurial/README.md
Closes #4616
Changes the `plugins=(... mercurial ...)` to be closer to correct zsh syntax, removing commas and extra spaces.
Revises discussion on configuring themes to avoid sounding like users should modify the theme definition file in the main OMZ folder. Prioritizes the suggestion of using a theme which already supports hg_prompt_info.
> Mercurial plugin: revise README

- themes/agnoster.zsh-theme
I noticed that for certain projects with unstaged changed I would get a 'U' character instead of the '●' character. This should fix that.
Original:
With fix:
(edit: I also have a custom coloring for virtualenvs active. You can ignore that)
> Fixing strange git unstaged prompt behavior

- plugins/dircycle/dircycle.plugin.zsh
In bindkey strings, "^[" and "\e" mean the same thing. They're both notations for Escape.
This removes the redundant bindings and unnecessary `iTerm.app` test, which suggests special behavior for iTerm2. iTerm2 does behave differently, but this sequence isn't it: by default, Ctrl-Shift-Arrow doesn't send anything. There's an "xterm with Numeric Keypad" key preset you can load; that gives you these same character sequence bindings. (The "Terminal.app" compatibility one looks more like `urxvt`.)
> dircycle: remove redundant key bindings

- lib/functions.zsh
Apparently `nohup` is not needed in OSX, and using it has the side that it may break under tmux with the error
nohup: can't detach from console: No such file or directory
For now, this commit only drops the use of `nohup` in OSX. But it *may* not be necessary under other similar platforms.
Fixes #4520
> Drop the use of nohup on OSX for tmux compatibility

- plugins/vi-mode/vi-mode.plugin.zsh
The zle-line-init and zle-line-finish definition changes introduced in #1533 were broken with
respect to `smkx`/`rmkx` because their "if" logic had fallthrough where it shouldn't,
so the mode was left in `rmkx` ("local" keypad mode) all the time. This breaks anything that uses terminfo or application ("transmit") mode escape sequences for cursor key bindings, including key bindings in some other plugins.
This PR just removes those widgets entirely, because they're now defined (correctly, I think) in `lib/keybindings.zsh` and not needed in plugins any more. (As long as the intent is to enable application cursor mode; see Caveats.)
Partially fixes #2735.
This fixes `vi-mode` so the terminal will be in "application cursor" aka "transmit" mode while editing the command line, instead of …
> vi-mode: fix smkx/rmkx by removing broken line-init/finish widgets 

- tools/check_for_upgrade.sh
When getting asked whether you want to update your zsh and you type in "yes" oh-my-zsh doesn't accepts this as an valid answer.
```
[Oh My Zsh] Would you like to check for updates?
Type Y to update oh-my-zsh: yes
```
This kind of sucks from a user experience point of view because the software was not doing what I expected it to do.
This patch allows oh-my-zsh to accept any forms of `Yes`, `Y`, `y`, `yes` as a valid answer.
> Also accept any forms of yes as an answer to the "do you want to update?" prompt

- lib/termsupport.zsh
This PR:
- changes the current messy code of the title function to a `case` statement to make it more readable and easier to expand. Tested by artificially setting `$TERM` and `$TERM_PROGRAM`.
- quotes all variables used in `if` statements per our style guide.
- reorders the Terminal.app working directory function for a more compact code.
I'd merge this PR directly but I'd like a review by another set of eyes, given the recent mistakes I made.
cc @apjanke
> Make code in lib/termsupport.zsh more readable

- plugins/web-search/web-search.plugin.zsh
Adds the [Ecosia search engine](https://www.ecosia.org) to the web-search plugin.
> Add Ecosia to web-search plugin.

- plugins/mercurial/mercurial.plugin.zsh
Rather than trying to emulate `git commit --amend` using mercurial queues (which might have side effects if you're using MQ for other things) use the `commit --amend` command which was introduced in Mercurial 2.2 (2012-05-01).
> Use actual `commit --amend` command for Mercurial

- plugins/common-aliases/common-aliases.plugin.zsh
Uses `is-at-least` instead of a numeric comparison hack, so versions with non-numeric bits like "4.5.0-dev5" don't throw errors.
Fixes an issue noted in https://github.com/robbyrussell/oh-my-zsh/issues/4441#issuecomment-163790819.
> common-aliases: handle "dev" versions in version check

- lib/spectrum.zsh
This "hides" the values of the `FG`, `BG`, and `FX` parameters defined in `lib/spectrum.zsh` by giving them the `-H` attribute. This means that when they're listed in the output of `set` or related commands, only their names are included, and their values are hidden. This is the same mechanism that Zsh's own `colors` function uses to hide the contents of the `$fg` and `$bg` arrays.
When the parameters aren't hidden, doing `set` sends junky output to the terminal, since the control sequences are emitted literally, and there may not be a `$reset_color` bracketing them. This makes the output of `set` harder to read, and makes `grep` fussy when searching through it, complaining about it being a binary file. (Doing `| grep -a` works around it, but it's an annoyance to have to remember to do …
> Hide spectrum.zsh var values to avoid junky output to terminal

- lib/spectrum.zsh
Fixes #3964 
The current `spectrum_ls` is using `%F/%f` prompt codes. These don't seem to support 256 colors. This changes it to use the control sequences it's defined in `$FG`.
Also adjusts the spectrum_bls implementation so the leading number is not included in the coloration, to ensure that it's always readable, even when the background color being displayed is close to the foreground text color.
> Make spectrum_ls implementation consistent with $FG and spectrum_bls

- plugins/zsh-navigation-tools/README.md
- plugins/zsh-navigation-tools/n-list
- plugins/zsh-navigation-tools/n-panelize
Colorifying code has been reorganized and allows e.g. n-history to start even more instantly. Updated README.md
Also, Zsh's starting from 5.0.8 and before 5.2 have a specific heap handling that makes ZNT slower. Introduced are workarounds for this making ZNT much faster with large inputs
> znt: faster startup of tools using colorifying (e.g. n-history), optimized heap usage for older Zsh's

- plugins/git-flow/git-flow.plugin.zsh
Looks like the original link wasn't working, and this should be the right one.
> Update link to git completion

- plugins/composer/composer.plugin.zsh
Composer might display warning messages to stderr (xdebug enabled, version older than 30 day, etc). In those cases it can become user-unfriendly :)
> [Composer] redirect stderr to /dev/null for completion commands

- themes/fishy.zsh-theme
When the current path is `/home/user/.config/doublecmd` the prompt now reads `/h/u/.c/doublecmd`, not `/h/u/./doublecmd` as was the case. This matches what the Fish shell does.
Enclose the Perl snippet in single quotes instead of double quotes.
> "fishy" theme: Shorten path .foo to .f, not .

- lib/termsupport.zsh
Currently, the title is only set on supported terminals (i.e. xterm, urxvt, screen etc.). Using terminfo entries to set the terminal title adds support for many more terminals.
> Default to using terminfo to set the terminal title

- themes/agnoster.zsh-theme
Looks like people still aren't picking up on the documentation for the Powerline characters in Agnoster.
This adds stronger language asking people not to change it, and puts it immediately next to the line with the Unicode value for `$SEGMENT_SEPARATOR`, so it will show up within the window of Git context diffs for someone who's making a commit that might change it.
Closes #4544
Follows up on #4091, #4083
> agnoster theme: stronger warning about changing SEGMENT_SEPARATOR character

- lib/git.zsh
- plugins/git/git.plugin.zsh
- themes/eastwood.zsh-theme
- themes/gallois.zsh-theme
- themes/josh.zsh-theme
- themes/juanghurtado.zsh-theme
- themes/mortalscumbag.zsh-theme
- themes/peepcode.zsh-theme
- themes/sunrise.zsh-theme
Moves the `current_branch()` function from the `git` plugin to the core `lib/git.zsh`, since there are other functions in core OMZ or in themes that depend on it, and we don't want any core -> plugin dependencies.
Fixes #4085 
Fixes #4059 
Fixes #331
Fixes #4581
> Git: move current_branch() to core

- plugins/zsh-navigation-tools/README.md
- plugins/zsh-navigation-tools/n-list
Optimizations towards heap management of set of Zsh versions. Search of three letter keyword is 6.7 sec vs. 15.3 sec in one of tests
> znt: more optimizing workarounds for 5.0.6 <= zsh < 5.2

- plugins/colored-man-pages/colored-man-pages.plugin.zsh
The `colored-man-pages` plugin breaks the `man` command on NixOS. This commit fixes the issue by using `/usr/bin/env` to determine the path to the `less` command.
> colored-man-pages: Use Portable `less` Path

- lib/git.zsh
In places, the local statement will override the exit code and the written command won't have the effect intended when it was written.
For example, when it's not inside a git repo the exit code won't be true, but the local statement will make it true regardless. See #4708.
Fixes #4708
> Put `local var` declaration in its own line in lib/git.zsh

- lib/git.zsh
Re-added $ZSH_THEME_GIT_PROMPT_EQUAL_REMOTE variable which was removed in 9f55213
> Re-added $ZSH_THEME_GIT_PROMPT_EQUAL_REMOTE

- plugins/chruby/chruby.plugin.zsh
The locals `_chruby_auto` and `_chruby_path` were previously declared at the top of the plugin, but they only seem to be used inside of `_source_from_omz_settings()`. This caused the following odd behavior when using this plugin (locals & their values are printed when sourcing `.zshrc`:
```
$ source ~/.zshrc
_chruby_path=''
_chruby_auto=''
```
@webframp feel free to chime in if there was some rationale that I'm missing - I'm no shellscripting pro
> chruby plugin locals moved inside function

- plugins/command-not-found/command-not-found.plugin.zsh
Added support for Brew on OSX.
Using command-not-found for Brew found at https://github.com/Homebrew/homebrew-command-not-found.
Close #4150
> Add OSX support for command-not-found

- plugins/forklift/README.md
> forklift: update homepage URL and tweak formatting

- plugins/zsh-navigation-tools/.config/znt/n-cd.conf
- plugins/zsh-navigation-tools/README.md
- plugins/zsh-navigation-tools/n-history
- plugins/zsh-navigation-tools/n-list
- plugins/zsh-navigation-tools/n-list-draw
- plugins/zsh-navigation-tools/n-list-input
- plugins/zsh-navigation-tools/znt-history-widget
ZNT: Final optimizations for zsh <= 5.2, n-history won't use $BUFFER if it comes from history, backspace key triggers previous page, updated comments, README.md and done some code polishing. Was testing the changes for 4 weeks
> znt: optimizations for zsh<=5.2

- plugins/pylint/pylint.plugin.zsh
The flag `--include-ids` is soon to be deprecated for Pylint. This pull request
removes that option from pylint-quick
> pylint.plugin.zsh: Remove include-ids=y

- plugins/git/git.plugin.zsh
My Go vendoring tool https://github.com/FiloSottile/gvt is picking up some popularity, and many users have trouble initially because of the `git verify-tag` alias.
Now, this is a bit awkward.
I clearly am to blame here for not vetting the name, but the damage is done (I honestly didn't expect gvt to become popular...). Now, I honestly doubt `verify-tag` is that much used (or at all), so maybe you will consider scrapping the alias for the users convenience? :pray: :relaxed: 
See FiloSottile/gvt#19 and FiloSottile/gvt#4 for user reports.
> git.plugin: remove the conflicting gvt alias

- plugins/frontend-search/README.md
- plugins/frontend-search/_frontend-search.sh
- plugins/frontend-search/frontend-search.plugin.zsh
The plugin alias for `compass` is overriding default `compass` calls via CLI. Now `compassdoc` is used instead `compass`.
@robbyrussell Can you take a look in this PR, please?
> Fix bug in compass docs search

- themes/ys.zsh-theme
Remove most of the old hacks. Keep the theme clean and expressive.
Make the root user name highlight color more visible.
Add exit code indicator.
Add tty info.
> Optimize the ys.zsh-theme make it more expressive

- themes/avit.zsh-theme
- themes/bira.zsh-theme
This pull request contains a fix for the use of `$CARETCOLOR` in the avit theme, so that a sudo change to root makes the caret red. 
The pull request also contains a small improvement to the theme: it makes the colours of the current directory, return status and two git symbols bold so that they stand out more on dark terminals (like in the Ubuntu default theme).
> Avit theme fixes

- README.markdown
The "Mac" prefix was dropped from "Mac OS X" in 2012; it's just called "OS X" now. This PR updates the name accordingly.
> Remove "Mac" from "Mac OS X"

- themes/ys.zsh-theme
Remove the tty info, and optimized the exit code.
```
$
$
```
The `C:127` is the last exit code, it appears only when the exit code is not zero.
> Optimize the ys.zsh-theme make it simpler

- plugins/symfony2/symfony2.plugin.zsh
I've been using the "dev" and "prod" aliases for a while.
They've proven to be really useful when you type in commands based on symfony environment.
Credit for this tip goes to @hhamon 
The only downside I see is that the names of these aliases might not be specific enough.
> Added environment based shortcuts in symfony2 plugin

- plugins/textmate/textmate.plugin.zsh
It seems counter-intuitive to me that `tm file1 file2` or `tm foo.*` only opens the first file. Thus, I took it upon myself to update `textmate.plugin.zsh` to open multiple files if specified. I kept all the existing functionality the same. In particular, if the first arg is a directory, the function ignores everything after it and opens the directory in TextMate.
> Update 'tm' function to take multiple files on the command-line

- plugins/git/git.plugin.zsh
Remove `--color` flag from `git log` aliases
Fixes #4727
> Remove --color flag from git log aliases

- plugins/asdf/README.md
- plugins/asdf/asdf.plugin.zsh
[asdf](https://github.com/asdf-vm/asdf) is an extendable version manager with support for Ruby, Node.js, Elixir, [and more](https://github.com/asdf-vm/asdf#usage).
```
asdf plugin-add nodejs git@github.com:asdf-vm/asdf-nodejs.git
asdf install nodejs 5.9.1
```
This plugin simply loads asdf if it finds it. asdf provides the zsh completion for us. The corresponding issue for this is https://github.com/robbyrussell/oh-my-zsh/issues/4942 .
> Add asdf version manager plugin

- lib/git.zsh
Add functions for `git config user.name` and `git config user.email`.
Useful as visual indicator for people who need to switch between different work and home user accounts often.
> Add git user profile functions for prompt display

- themes/bureau.zsh-theme
This PR fixes a bug introduced in #2752 where a repository being ahead or behind the remote won't be displayed unless there is some change in the staging area or the working directory. 
It also uses `grep -q` instead of the construct `grep ... &>/dev/null`.
cc @mtbtiago @mtnbikenc
> Bureau theme fixes

- themes/sunrise.zsh-theme
`nvm` complains about `PREFIX` when using sunrise theme:
```
nvm is not compatible with the "PREFIX" environment variable: currently set to "---"
Run `unset PREFIX` to unset it.
```
Renaming `PREFIX` to something else fixed this issue.
> Avoid using "PREFIX" that cause nvm to complain about.

- plugins/github/github.plugin.zsh
git.io now redirects to https. So the current function break. Changing it to https fixes the issue.
> Moved git.io url to https

- plugins/osx/osx.plugin.zsh
[iTerm2 v3](https://www.iterm2.com/version3.html) is currently in beta and it doesn’t have a backward compatible [applescript syntax](https://www.iterm2.com/applescript.html).
This commit adds support for it in the `osx` plugin.
> Add iTerm2 v3 support

- plugins/mvn/mvn.plugin.zsh
add "-Dmaven.test.failure.ignore=true" .
This option will not ignore all tests but will ignore the failures when running tests.
> add mvn option to ignore test failures

- themes/avit.zsh-theme
The function _ruby_version() which is called in prompt only checks for RVM. I just added rbenv support. It works as expected.
> Add rbenv support for ruby version display in the Avit theme

- plugins/jira/jira.plugin.zsh
JIRA Plugin will open rapidboard instead of dashboard if JIRA_RAPID_BOARD is true.
> JIRA Plugin will open rapidboard

- plugins/zsh-navigation-tools/.config/znt/n-aliases.conf
- plugins/zsh-navigation-tools/.config/znt/n-cd.conf
- plugins/zsh-navigation-tools/.config/znt/n-env.conf
- plugins/zsh-navigation-tools/.config/znt/n-functions.conf
- plugins/zsh-navigation-tools/.config/znt/n-history.conf
- plugins/zsh-navigation-tools/.config/znt/n-kill.conf
- plugins/zsh-navigation-tools/.config/znt/n-list.conf
- plugins/zsh-navigation-tools/.config/znt/n-options.conf
- plugins/zsh-navigation-tools/.config/znt/n-panelize.conf
- plugins/zsh-navigation-tools/README.md
- plugins/zsh-navigation-tools/_n-kill
- plugins/zsh-navigation-tools/n-aliases
- plugins/zsh-navigation-tools/n-cd
- plugins/zsh-navigation-tools/n-env
- plugins/zsh-navigation-tools/n-functions
- plugins/zsh-navigation-tools/n-help
- plugins/zsh-navigation-tools/n-history
- plugins/zsh-navigation-tools/n-kill
- plugins/zsh-navigation-tools/n-list
- plugins/zsh-navigation-tools/n-list-draw
- plugins/zsh-navigation-tools/n-list-input
- plugins/zsh-navigation-tools/n-options
- plugins/zsh-navigation-tools/n-panelize
- plugins/zsh-navigation-tools/znt-history-widget
- plugins/zsh-navigation-tools/zsh-navigation-tools.plugin.zsh
Hello,
new features:
1. Approximate matching – every tool can handle typos after pressing `Ctrl-F`. This will make 1 or 2 errors to be allowed in what's searched (in every word). Near fuzzy matching, but aimed at typos
2. Most Frequent History Words – new view in n-history, allows to browse words in history instead of entries
3. Themes – predefined themes for all tools. I've sent a patch to Zsh developers and next Zsh version will support 256 colors in zcurses. Zsh-navigation-tools are ready:
http://imagizer.imageshack.us/a/img924/8896/0kmijJ.gif
4. Private history – n-history tracks what's executed on its own, shares this information across sessions
5. Predefined search keywords: pressing F2 in each tool will iterate over predefined keywords: https://www.youtube.com/watch?v=DN9QqssAYB8 …
> znt: update to v2.1.15

- plugins/rust/_rust
This is taken from my PR for rustc (https://github.com/rust-lang/rust/pull/17306), which is getting merged once the CI system is fixed.
> Add zsh completion plugin for rustc

- plugins/branch/branch.plugin.zsh
After `hg init` command, sometimes Mercurial does not create `.hg/branch` file so we'll use 'default' as fallback, which is the master branch in Mercurial repositories.
> Use default branch on recently created Mercurial repository

- plugins/rails/rails.plugin.zsh
Even if current directory is not rails project, _rake_command and bundler should be useable.
Because user is using bundler plugin and rails plugin so rake command is overrode as a _rake_command.
So We cannot use rake command with bundler.
In my developed gem:
```
$ rake -T
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
/Users/sachin21dev/Projects/github.com/sachin21/space2underscore/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```
And this error can be reproduced in all gem products. because _rake_command using rake without bundler.
FYI some of my zshrc:
```shell
plugins=(
autojump
brew
brew-cask
bundler
docker
gem
git
go
heroku
history
pip
pyenv
rails
rake-fast
ruby
sublime
tmux
vagrant
)
```
> Support bundler

- tools/install.sh
The test added in #3646 to prevent use of the incompatible MSYS `git` isn't working because the test ended up after the `git clone` call. This moves it to the right location.
Fixes #4551.
> installer: fix ordering of Cygwin MSYS git check

- plugins/systemd/systemd.plugin.zsh
This is useful for listing "cron like" systemd jobs
> Add list-timers to systemd user commands

- plugins/knife/_knife
Currently any of the `knife * from file` commands autocomplete by the knife plugin only look in the current directory for the relevant files. This fix searches upwards for a .chef folder and then looks in the folder relative to that folder (this is similar to the way knife itself functions). This should affect the following subcommands: 
- `knife node from file`
- `knife environment from file`
- `knife role from file`
- `knife data bag from file`
It also adds an option (`KNIFE_RELATIVE_PATH`) that lets `knife cookbook upload` work in the same way. This is useful when you have multiple local Chef orgs and can't set a path to a single cookbooks folder.
> Fix: Plugin knife: Add relative local path for commands which upload files

- plugins/kitchen/_kitchen
This fixed #5008 for me. It's a copy from https://github.com/zsh-users/zsh-completions/ and I'm not sure about the license text but I hope it's good to merge. 👍
> Replace _kitchen completion with the version from zsh-users

- themes/peepcode.zsh-theme
Copied from #4971, created from a feature branch instead
I just installed oh-my-zsh and I immediately fell for the Peepcode theme. The only problem is that it keeps trying to access the Ruby Version Manager (rvm-prompt) which I don't have installed, giving the same error after each command:
`zsh: no such file or directory: /home/harald/.rvm/bin/rvm-prompt`
This small piece of code checks for the existence of the ~/.rvm folder, and if it's not there it just disregards that part of the prompt.
> Peepcode theme: Don't try to use RVM if not installed

- plugins/mvn/README.md
- plugins/mvn/mvn.plugin.zsh
It doesn't need to check the latest dependency for the most part.
> add 'mvn clean install -DskipTests --offline' alias to speed up maven compile

- templates/zshrc.zsh-template
- tools/install.sh
See b67961d for why hardcoding the PATH into zshrc is a bad idea and why it's better to allow the user to make those customizations as needed.
> Remove undesirable hardcoding of PATH into zshrc

- plugins/zsh-navigation-tools/.config/znt/n-kill.conf
- plugins/zsh-navigation-tools/.config/znt/n-list.conf
- plugins/zsh-navigation-tools/n-help
- plugins/zsh-navigation-tools/n-history
- plugins/zsh-navigation-tools/n-list
Changes:
1. Fix for https://github.com/robbyrussell/oh-my-zsh/issues/5120
2. Updated n-help, the documentation tool
3. Lines starting with "-" weren't supported by n-history
4. Ensured immunity to zsh-autosuggestions and zsh-syntax-highlighting
> znt: update to v2.2.1

- plugins/bundler/bundler.plugin.zsh
Calling awk is not necessary here, sysctl has the `-n` flag to print the value.
> bundler plugin: Simplify retrieval of CPU count on OSX

- lib/git.zsh
When updating my git prompt, I noticed there was a function for git_commits_ahead, but not one for git_commits_behind. The whitespace edit was an unintentional side effect from emacs.
> lib/git.zsh: Added git_commits_behind function

- plugins/phing/phing.plugin.zsh
The phing plugin currently drops a `.phing_targets` cache file wherever you run it.  This isn't necessary, `phing -l` takes .03 seconds (on my system) so I can stand to run it each time.
I don't know of any other plugins that cache wherever you are like this, but I'm not a fan of things making messes on my filesystem.
Closes #3415.
> Removes .phing_target generation from phing plugin

- themes/agnoster.zsh-theme
Fixes #5217: a bug when `you can install hg by typing ...` is shown like git branch. Also saves time for those who don't want hg to be installed and have command-not-found enabled as there is no need to search repo for hg each time prompt is being printed.
> Fix hg call when missing on archlinux with command-not-found

- lib/git.zsh
* Function wasn't returning correct value
* Updated underlying git command
* Kept echo command from previous function for backwards compatibility
* Kept function consistent with git_commits_behind
> Updated git_commits_ahead function

- plugins/git/git.plugin.zsh
The alias `gbda` actually doesn't work if `git config color.ui = always`.
Some invisible characters are included in branch names wich causes the following :
- master branch is not excluded
- on deletion, the output is : `error: branch 'x' not found.` And there is no deletion at all.
The `--no-color` option solves this problem.
Also, `command` seems unnecessary.
I excluded `develop` and `dev` branches to make it usable with Git Flow. Should I do this in another PR or is it ok to keep it here ?
> Fix gbda alias to support `color.ui = always` + exclude dev branches

- lib/nvm.zsh
- plugins/nvm/_nvm
- plugins/nvm/nvm.plugin.zsh
`nvm` isn't always installed in ~/.nvm. These changes allows nvm to be installed in any directory. It also now properly exports the `$NVM_DIR` env var if it hasn't been set and checks it in the completion and `nvm_prompt_info` rather than assuming `nvm` is in ~/.nvm.
Fixes #5270
> nvm plugin improvements

- lib/functions.zsh
- tools/check_for_upgrade.sh
This makes things work even on system lacking /bin/sh, such as on non-rooted Android systems (with [Termux](https://termux.com/) being my use case here).
> Replace /bin/sh with sh for portability

- plugins/ubuntu/ubuntu.plugin.zsh
Use of alias  `allpkgs` =`aptitude search -F "%p" --disable-columns ~i`
is deprecated and exits with an error <br/>
The script new script `dpkg --get-selections | grep -v deinstall` works perfectly ok
> update alias of get a list of packages installed locally

- plugins/shrink-path/README.md
- plugins/shrink-path/shrink-path.plugin.zsh
Shrink directory paths, e.g. `/home/me/foo/bar/quux` to `~/f/b/quux`.
For a fish-style working directory in your command prompt, add the following to your theme or zshrc:
```zsh
setopt prompt_subst
PS1='%n@%m $(shrink_path -f)>'
```
The following options are available:
```
-f, --fish       fish simulation, equivalent to -l -s -t.
-l, --last       Print the full name of the last directory.
-s, --short      Truncate directory names to the first character. Without
-s, names are truncated without making them ambiguous.
-t, --tilde      Substitute ~ for the home directory.
-T, --nameddirs  Substitute named directories as well.
```
The long options can also be set via zstyle, like:
```
zstyle :prompt:shrink_path fish yes
```
Note: Directory names containing two or more consecutive spaces are …
> Add shrink-path plugin to shorten directory paths (e.g. ~/f/b/quux)

- plugins/git/git.plugin.zsh
Add alias to push new branch to origin, and set up local branch to track it.
I can update the Wiki if this change is accepted.
/cc @ncanceill as you're set up as maintainer.
> (git): Add gpsup alias

- plugins/rake-fast/rake-fast.plugin.zsh
Hi!
I have found that in Rails app file `.rake_tasks` doesn't refresh.
This happens because `Rakefile` always stays the same.
But all `rake` tasks and `.rake` files are placed in `lib/tasks` folder.
So I have prepared this PR in order to refresh `.rake_tasks` when something has changed in `lib/tasks` folder.
I'm new to shell scripting so any comments are welcome.
Thank you.
> refresh .rake_tasks when lib/tasks changed

- plugins/urltools/urltools.plugin.zsh
Some linux distribution are using python 3 as default python interpreter now.
> plugins/urltools: add suport for python 3

- plugins/git/git.plugin.zsh
Similar to `grba` and `grbc`, this adds `gcpa` and `gcpc` aliases to the git plugin.
/cc @ncanceill @mcornella
> Add gcpa and gcpc aliases to git plugin

- plugins/sublime/README.md
- plugins/sublime/sublime.plugin.zsh
`stp` commands works in following way:
1. If the current directory is a part of a Git repo and if there is a `.sublime-project` file among its ancestor directories, the command opens up that sublime project.
1. If the current directory is a part of a Git repo but there isn't a `.sublime-project` file among its ancestor directories, the command opens up the root of the repo.
1. If the current directory is not a part of a Git repo, the command opens up the current directory.
> Create an alias to open up sublime project

- plugins/pj/README.md
- plugins/pj/pj.plugin.zsh
This Pull Request fixes various issues with the `pj` plugin. 
It also adds a Readme with better instructions and refactors a big chunk of the code to make it more zsh-friendly.
Fixes #5266
Fixes #5267
Fixes #5284
> Fix pj plugin

- plugins/ssh-agent/ssh-agent.plugin.zsh
To prevent
```
_plugin__start_agent:7: file exists: $HOME/.ssh/environment-$HOST
starting ssh-agent...
Could not open a connection to your authentication agent.
```
> Clobber ssh environment regardless of setopt

- themes/dogenpunk.zsh-theme
The parsing output for full git log output too slow so it replaced
with last commit show request, wich cause error if repository is empty
> Fix git emptiness check in dogenpunk theme

- plugins/golang/golang.plugin.zsh
*  Also gfa conflicts with git shortcut - `gfa=git fetch --all --prune`
Fixes #4919. Fixes #5214. Fixes #5288.
> Add more golang aliases

- plugins/osx/osx.plugin.zsh
Fixes the "syntax error: expected line end ..." (-2741) errors that occur when using the tab, split_tab, and vsplit_tab commands in iTerm2 v3
> iTerm2 v3 tab commands syntax error fix

- plugins/pip/pip.plugin.zsh
Certain pip install commands which involve square brackets such as `pip install requests[security]
` or `pip install -e .[testing]` fails with the following error: `zsh: no matches found:`
This patch disables globbing for the pip command, and makes the pip command works for such cases.
> Disable zsh file globbing when running pip

- plugins/perms/README.md
- plugins/perms/perms.plugin.zsh
I added a new plugin for recursively setting all files' permissions to 644 recursively in a directory and for recursively setting all directories' permissions to 755.
This has been useful primarily for websites, but I've found other uses for it. I also wrote a function to do both at the same time with verification.
> Added perms plugin

- plugins/ssh-agent/README.md
- plugins/ssh-agent/ssh-agent.plugin.zsh
- Repost of #5261: deletes useless `/usr/bin/env` calls.
- Adds a README file.
- Formats to tabs, renames local variables and fixes needlessly complex variable syntax.
- Simplify PID check of last ssh-agent.
- Uses `ssh-agent -s` to force Bourne-style syntax on systems that have Csh-like default shells (for example, colleges or workplace).
Close #5261.
> Refactor of ssh-agent plugin

- lib/git.zsh
It seems that `git_prompt_status()` does not show the current branch's ahead/behind/diverged status correctly when branch or remote names contain `ahead`, `behind`, or `diverged`.
For example when the current branch name is `behind-foobar` and is not behind but ahead the upstream branch, output of `git status --porcelain -b` is like:
```console
```
The first line contains `behind` so the current branch is recognized as behind by mistake.
This PR makes branch and remote names ignored when checking ahead/behind/diverged status.
> Fix git_prompt_status() not showing ahead/behind/diverged status correctly

- plugins/lein/lein.plugin.zsh
I often run lein on files, like `lein run -m some-class/some-fn
<path-to-some-file`, and it would be useful to be able to have file name
completions to make that `<path-to-some-file>` easier.
> Add file completions for lein

- plugins/vi-mode/vi-mode.plugin.zsh
This PR fixes a crash that happens on OS X when using the vi-mode plugin with iTerm 2 and re-sizing a window.
> Fix iTerm crash on window re-size

- plugins/docker-compose/docker-compose.plugin.zsh
Readded docker-compose aliases as asked here https://github.com/robbyrussell/oh-my-zsh/issues/5408.
They went missing in https://github.com/robbyrussell/oh-my-zsh/commit/0950f9c56da1f22bbddc45cf179a80a712908b19.
I just readded the plugin file as having a plugin file and a `_*` (completion) file seems to be common practice in most plugins.
Fixes #5408.
> Readded docker-compose aliases

- plugins/battery/battery.plugin.zsh
I have a machine which outputs the following when `acpi` is run:
```
❯ acpi
No support for device type: power_supply
```
This ends up showing everywhere I include `battery_pct()` - including my prompt!  It's an easy fix - just make it consistent which arguments we're passing to `acpi` in the battery plugin.
> Fix battery.plugin when acpi writes to stderr

- plugins/gradle/_gradle
- plugins/gradle/_gradlew
- plugins/gradle/gradle.plugin.zsh
Added _gradle and _gradlew as symbolic links to gradle.plugin.zsh,
otherwise the plugin was not properly loaded.
Output from `gradlew tasks --all` is now parsed in two levels,
first we find segments between `------...` and a newline.
Second, all those lines are parsed and cleaned using awk
and added to .gradletasknamecache.
Tested on gradle 2.13, and gradlew 2.14.
> Improve gradle plugin task parsing

- plugins/git/git.plugin.zsh
- Simple addition to the set of aliases available for `git`.
- Wondered why it was not available by default (let me know if there is a special reason).
- No other `git` alias has the same string (`gbd`) defined for it.
> Added 'gbd' alias for 'git branch -d'

- plugins/rails/rails.plugin.zsh
The command `rails console —sandbox` loads our Rails application, connects to the database and automatically starts a database transaction. All database operations performed within this console
session are rolled back upon leaving the console. Reference -
https://www.codeschool.com/blog/2014/06/17/rails-console-sandbox/
> Add an alias for Rails console sandbox

- themes/peepcode.zsh-theme
The ruby prompt info was not interpolating properly in the "peepcode" theme. Switching to use `ruby_prompt_info` helper. This addresses the interpolation issue and addresses part of https://github.com/robbyrussell/oh-my-zsh/issues/4182.
Before:
After:
>  Fix peepcode theme ruby prompt info

- themes/agnoster.zsh-theme
the agnoster theme is now able to render basic information
if the user is currently residing inside a bazaar folder.
if so, it will render a green promt segment with "bzr" and
the current revision number in it. if there are untracked
files, the bar will be rendered in yellow. if there are
changes to already tracked files, a + character will be
printed.
> added support for bazaar in agnoster theme

- plugins/xcode/README.md
- plugins/xcode/xcode.plugin.zsh
I've found myself doing this:
```sh
> xc
No xcworkspace/xcodeproj file found in the current directory.
> cd Project ; xc ; cd ..
```
To open a project in a subdirectory from the command line. And sometimes I forget to `cd ..` 😬 
So I thought I would add the option to the plugin. It's my first contribution, so let me know if there's anything I need to change in the PR.
> Adds option for directory to Xcode xc function.

- themes/agnoster.zsh-theme
Plugin command-not-found on Arch returns 0 if git or bzr is found in repos, hence outputting unwanted pkgfile output.
Checking if the commands exist first fixes all such issues. It unifies the check with hg_prompt (where it is already implemented)
> Add check for git and bzr to agnoster theme

- plugins/docker-compose/docker-compose.plugin.zsh
Adds the following aliases:
```zsh
alias dco='docker-compose'
alias dcr='docker-compose run'
alias dce='docker-compose exec'
```
And sorts the aliases similar to `docker-compose help` order
> Add more docker compose aliases

- plugins/pip/_pip
As noticed several times before, pip plugin is outdated, @kottenator was the last one addressing this in issue #5337. Fixes #5337.
I didn't want to break backwards compatibility, so it is just commented as (deprecated). It is still missing all new second level arguments (--something) for the newly added first level arguments.
> Update pip plugin to last stable release

- plugins/git/git.plugin.zsh
When making a WIP commit, we generally just want to save the state of the current branch temporarily, maybe because we want to push our work for backup purposes, or change branch to work on something else. Therefore, it's generally undesirable to run Git hooks, which might do things like run linters, because we probably don't care if our WIP has lint errors.
> git.plugin.zsh: Don't run Git hooks when making a WIP commit

- plugins/last-working-dir/README.md
- plugins/last-working-dir/last-working-dir.plugin.zsh
This PR checks if we're in `$HOME` before jumping to the last working directory.
It also cleans up the source and adds a README.
Fixes #5392
Fixes #5450
> Fix last-working-dir plugin unwanted jumps

- plugins/autoenv/autoenv.plugin.zsh
The current list of directories to search for autoenv on misses the default location on Ubuntu systems if you just do a normal `pip install autoenv` - [it will place](https://github.com/kennethreitz/autoenv/blob/master/setup.py#L16) `activate.sh` in `/usr/local/bin` unless you manually override the `--prefix` or something.
The `/usr/local/opt/autoenv` is fine for macOS/homebrew installations but it would be nice not to have to manually patch on Linux :)
> Add /usr/local/bin to autoenv search path

- tools/check_for_upgrade.sh
This would fix #3766 and is a better solution than #5430 because it avoids even the rare race condition mentioned in the discussion there by using a proper, atomic locking mechanism (mkdir).
See http://mywiki.wooledge.org/BashFAQ/045 for reference.
Related: #5257.
Fixes #3766.
Closes #5430.
> Implement a locking mechanism to avoid multiple update prompts

- plugins/cp/README.md
- plugins/cp/cp.plugin.zsh
Fixes #5420.
- Changed `-h` for `-hhh` which shows numbers in units of 1024 (k, M, G, T).
- Added `-r` to recurse directories.
- Removed `--`: use only if needed. That way we can do `cpv --help` and other combinations.
> Fix cp plugin completion

- plugins/jump/jump.plugin.zsh
This allows for the user to combine the jump command with
something else. In my example cd and jump are now combined
like this:
```bash
jumpcd() {
jump $1 > /dev/null || cd $1
}
alias cd="jumpcd"
```
> Add non 0 exit code for missing jump targets

- plugins/common-aliases/common-aliases.plugin.zsh
The m4a file format can be opened in the command line with mplayer
> Add m4a format in the common aliases plugin

- plugins/ubuntu/ubuntu.plugin.zsh
Removing one "apt-get autoremove" alias because it is duplicated.
> remove duplicate alias

- lib/clipboard.zsh
For better speed. There are a lot of other using of `which`, but this is in `lib` thus more impacting...
> Use $+commands to check the existence of a command in clipboard.zsh.

- themes/suvash.zsh-theme
Refactors theme code:
* Use `${var:t}` instead of `basename $var`.
* Use `[[ -n "$var" ]]` instead of `[ $var ]`.
* Use `(( $+commands[cmd] ))` instead of `cmd >/dev/null 2>&1`.
* Use `%F{color}text%f` and `%Btext%b` for color and boldness.
* Use a single Ruby prompt function instead of multiple prompt definitions. This also fixes #5514.
> Display suvash prompt w/o Ruby; refactor code

- themes/bira.zsh-theme
I saw the latest update that changed the color of the name when you're in root. I thought it would be neat to have the symbol also change from '$' to '#' as a root prompt is always represented with '#'.
I also put  the return code in bold as I think it is not visible enough when not bold.
> Update bira theme

- plugins/droplr/droplr.plugin.zsh
This plugin wasn't working for me on MacOS.
- Sierra 10.12
- Droplr 4.6.3
See commit for changes to get the plugin working.
> Droplr Plugin: Fix regex for optional http(s), and variable reference inside osascript.

- plugins/zsh-navigation-tools/NEWS
- plugins/zsh-navigation-tools/README.md
- plugins/zsh-navigation-tools/n-history
- plugins/zsh-navigation-tools/n-list
- plugins/zsh-navigation-tools/znt-tmux.zsh
- plugins/zsh-navigation-tools/zsh-navigation-tools.plugin.zsh
Hello,
Tmux integration has been added – bind file znt-tmux.zsh in Tmux as described in README.md and e.g. run local history on remote hosts. Tmux opens new window with n-history, and pastes selected history entry into immediate previous window (e.g. a remote session). Fixed plugin.zsh file to not use (outer scope) positional parameters. Also, the file now doesn't use "test" builtin (but [[ instead), because it can be shadowed by alias or command. Private history has been fixed to not overwrite its history file with the same content. This improves performance when switching to private history view.
> znt: Update to v2.2.7

- lib/theme-and-appearance.zsh
`gls` seems to be installed by default or on most macOS systems, but its default color scheme sucks. This fix will make sure to only use it if it has been customised prior to running OMZ.
Fixes #5552
Related: #5516, #5520.
> Check dircolors settings before using gls on darwin

- plugins/node/node.plugin.zsh
This would be easy for a user who wants to refer modules in specific, Module will be passed as an argument. For example,  **node-docs fs** will result in opening https://nodejs.org/docs/v6.7.0/api/fs.html. If no argument is passed it will open https://nodejs.org/docs/v6.7.0/api/all.html
*note I'm using node version 6.7.0
> add conditions to open module specific node documentation

- templates/zshrc.zsh-template
OpenSSH 7.0 [disabled DSA keys by default](https://www.gentoo.org/support/news-items/2015-08-13-openssh-weak-keys.html) for a wide variety of reasons that are discussed [here](http://security.stackexchange.com/a/112818). This PR is merely updating the template for `.zshrc` file to use the now-standard `~/.ssh/rsa_id`.
> Changed dsa --> rsa in zshrc.zsh-template file

- lib/misc.zsh
Sourcing oh-my-zsh happens in zshrc, which will override settings of
profile and zshenv.  Treat misc values, `PAGER` and `LESS`, as default
settings without overriding existing values.
Fixes: #1, robbyrussell/oh-my-zsh#3016
> Do not override misc env set before sourcing oh-my-zsh

- plugins/git/git.plugin.zsh
I've been working with my team using ohmyzsh for a couple months now and it's going great! 
One problem is that since we pair program a lot, we find ourselves `gwip`ing and `gunwip`ing frequently to share WIP and switch drivers etc. This leads to a lot of CI resources being used unnecessarily. Since `[skip ci]` is used by the likes of TravisCI, CircleCI, GitLab CI and others I think it's fair to include here. Feedback is welcome! And if not mergeable, we'll probably just put this in our aliases ourselves, but I thought others could benefit. 
Thanks!
> feat: no CI on WIP commits

- plugins/debian/debian.plugin.zsh
- plugins/ubuntu/ubuntu.plugin.zsh
Changing from `zcat` to `zgrep` because some `zcat` implementations do not work
if the file is not compressed.
> debian & ubuntu plugins: use zgrep for `apt-history list`

- plugins/dotenv/README.md
- plugins/dotenv/dotenv.plugin.zsh
This plugin automatically loads project specific ENV variables from `.env` file when you `cd` into project root folder.
Storing project configuration in the environment becomes very popular lately. It's is one of the tenets of a [twelve-factor app](http://www.12factor.net). Anything that is likely to change between deployment environments, such as resource handles for databases or credentials for external services, should be extracted from the code into environment variables.
There already a lot of projects who embrace this type of configuration and `.env` file format:
[Ruby dotenv](https://github.com/bkeepers/dotenv)
[Node.js dotenv](https://github.com/motdotla/dotenv)
[PHP dotenv](https://github.com/vlucas/phpdotenv)
It's also [recommended by …
> add dotenv plugin

- plugins/mix/_mix
Fixes #5672
Allow file completion when using the `mix run` command
> mix run takes file arguments

- plugins/react-native/README.md
- plugins/react-native/react-native.plugin.zsh
Adds a couple of aliases:
- `rn` for `react-native`
- `rns` for `react-native start`
Also fixes the README and organises the rest of the aliases in the plugin.
> Add a React Native itself alias, and to start the web server

- plugins/osx/osx.plugin.zsh
Spotify command UX is a little weak for people who live and work almost entirely in shells.
- `spotify quit` should not open Spotify if it is not already running. Should confirm that Spotify is indeed not running.
- `spotify quit` should not blow away the user's shell once Spotify is quit. This can be a disruption to work flow.
This PR looks to add a few little checks which will help improve this experience.
This PR also adds a space to line 477 between `break` and `;;` for consistency. Doesn't seem like a big enough change to put in its own PR.
> Improve UX for Spotify quit command in osx plugin

- plugins/gradle/gradle.plugin.zsh
This adds missing flags for gradle completion, reflecting what's in the [latest Gradle CLI docs](https://docs.gradle.org/3.2.1/userguide/gradle_command_line.html).
```
--continue              -- Continues task execution after a task failure.
--daemon                -- Use the Gradle daemon
--gui                   -- Launches the Gradle GUI app
--no-daemon             -- Do not use the Gradle daemon
--profile               -- Profile the build time
--refresh-dependencies  -- Refresh the state of dependencies.
--rerun-task            -- Specifies that any task optimization is ignored
--stop                  -- Stop the Gradle daemon
-D                      -- System property
-I                      -- Specifies an initialization script.
-P                      -- Set a project property
-a …
```
> Improved gradle options (arguments) completion

- plugins/autoenv/autoenv.plugin.zsh
If autoenv was installed with pip and modifier --user, activate.sh will be at .local/bin
> Adding new path to look for activate.sh

- themes/af-magic.zsh-theme
I love `af-magic` theme because of it's simplicity!
but its coloring is too simple to recognize which branch is now on.
so I changed branch color from 075, almost same color as path(prefix) color, to 078(same tone but green color)
And also I removed 'branch:' description for displaying branch information.
I think it is conceptually duplicated because the part is only for the branch status.
From
To
> Change af-magic theme's branch color

- plugins/docker/_docker
missing \ was causing command not found errors when tab completing docker build -t <tab>
> add missing new line escape

- plugins/composer/composer.plugin.zsh
Add the proper config bin directory to `PATH` instead of the previously (incorrect) fixed `~/.composer/vendor/bin`. Nowadays the right config dir is `~/.config/composer/vendor/bin`.
> Use proper config bin directory

- themes/bira.zsh-theme
The whitespace in line 13 creates a double whitespace when combined with line 24. Therefore 2 whitespaces appear between ${user_host} and ${current_dir}.
> Remove wrong whitespace in bira theme

- plugins/mix/_mix
The mix tasks have changed for the Phoenix framework as of version 1.3.0. I added the new relevant tasks while leaving the existing <1.3.0 version tasks.
> Update to mix plugin to support Phoenix v1.3.0+ tasks

- README.markdown
- oh-my-zsh.sh
- templates/zshrc.zsh-template
Allow oh-my-zsh to load random themes from a list of user favorite, as discussed [here](https://github.com/robbyrussell/oh-my-zsh/issues/4647).
> Random theme from list

- plugins/terraform/_terraform
-backend-config flag was introduced in terraform 0.9.1 version
> add -backend-config flag to terraform init command

- plugins/jira/_jira
- plugins/jira/jira.plugin.zsh
@tresni I'd like to add a `br` shortcut/command to the jira plugin that will allow you to open the Jira ticket named after the git branch of the current directory. This works well for projects that name branches after ticket numbers and saves the user from having to type out the whole ticket reference.  
I doubt it would clash with any existing workflows in use because it is such a short command and it doesn't fit the regex for Jira tickets.  
Let me know what you think - I was already using an alias setup to achieve this but thought it might be useful to others.
> Add shortcut for opening current branch in Jira

- plugins/jira/jira.plugin.zsh
@tresni This ties in with my other PR #6366 to allow file based configuration of the default action. I like the file based config of the other settings and I can save a few lines from my zshrc and shave some environment variables.
> Allow jira default action file based setting

- README.md
Fix typo in
```
ZSH_THEM_RANDOM_CANDIDATES=(
"robbyrussell"
"agnoster"
)
```
into 
```
ZSH_THEME_RANDOM_CANDIDATES=(
"robbyrussell"
"agnoster"
)
```
> Fixed a Typo.

- plugins/rails/rails.plugin.zsh
I've started to use stubbed bin's for rails application in order to avoid the use of bundle exec.
With this, it checks in bin/stubs directory before bin/
> Check first for bin/stubs directory in _rails_command and _rake_command

- plugins/laravel5/laravel5.plugin.zsh
This simple enhancement adds the colon if tab is pressed.
Previously, you could type `php artisan m` and hit tab. This resulted in `php artisan make`. To get to the end of the command, it was required to type ":mo" to get to `php artisan make:model`
The change in this PR automatically adds the colon and typing `php artisan ma` results in `php artisan make:`.  While looking like a very small change, it results in much faster autocompletition because you have to type 2 keys less (shift+:).
> Enhanced Laravel 5 Plugin

- plugins/ubuntu/readme.md
- plugins/ubuntu/ubuntu.plugin.zsh
While both commands have the same functionality, `full-upgrade` is now the standard.
> Change `agud` alias from `dist-upgrade` to `full-upgrade`

- plugins/rbenv/rbenv.plugin.zsh
This is the default behavior of rbenv and what users are expecting
most of the time.
It allows users to have their own set of rubies and gems. It also
prevents losing all rubies when rbenv is updated using Homebrew which
is not true when RBENV_ROOT is set to /usr/local/opt/rbenv.
> Set RBENV_ROOT to "$HOME/.rbenv" if not already set

- plugins/npx/README.md
- plugins/npx/npx.plugin.zsh
This plugin automatically registers npx command-not-found handler if `npx` exists in `$PATH`. npx is actively maintained by npm5 developer. [more info](https://github.com/zkat/npx)
> [plugin] npx

- plugins/composer/composer.plugin.zsh
The standard error redirection was redirecting the output from export instead of the output from composer. This would print the message `Changed current directory to /home/username/.composer` for every new shell.
Moving the redirection inside the parentheses fixes this.
> Fix Standard Error Redirection for composer plugin

- plugins/pyenv/pyenv.plugin.zsh
This pull request attempts to optimize the load of pyenv with homebrew installed. As `homebrew --prefix pyenv` is a quite slow command(approx. 0.3s on my laptop). It would be better use the command less. Thus I added it to the last, and append the default homebrew pyenv installation path. As well as I eliminated the triple check into one check for the sake of speed.
I've tested for several cases. Looking forward to your response.
> optimize load of pyenv with homebrew

- plugins/kubectl/kubectl.plugin.zsh
Each of our developers was developing their own shortcuts making working together more difficult so I thought i'd try a few sane defaults and share them upstream to consolidate. If you have any questions about the frequency of these types of commands in standard devops work I'm happy to answer them but they are very common bordering on hundreds of times a day for kubectl in general.
> Add aliases for kubectl to speed up repetitive commands.

- plugins/kops/kops.plugin.zsh
Hi @robbyrussell,
This PR adds plugin for [Kops](https://github.com/kubernetes/kops "Kubernetes Operations")
> plugins: adds kops (kubernetes operations) plugin

- plugins/aws/aws.plugin.zsh
- plugins/chruby/chruby.plugin.zsh
We don't need to call 'brew --prefix' 3 times.
In worst case we need to call it once or in case of default brew installation - never.
Single call to brew is about 200-400 ms , so we save almost a second of shell startup time in worst case.
> speed up chruby plugin by eliminating(as much as possible) calls to brew

- plugins/gpg-agent/gpg-agent.plugin.zsh
The gpg-agent plugin did not work for gpg versions above or equal to
2.1 because of the `--write-env-file` option deprecation. This new version
works fine and also enables the ssh-agent support only if it is enabled in the
gpg-agent config file.
> Fixed the gpg-agent plugin for new gpg versions

- plugins/git/git.plugin.zsh
This PR adds the ability to use `ggfl` to force push but with the option of `--force-with-lease` so you don't overwrite someone else's code.
> Added --force-with-lease method to git plugin

- plugins/iterm2/iterm2.plugin.zsh
This plugin works when running in iTerm2 on OSX.
Currently it contains one function, `iterm2_profile()`, which allows easily changing the current user settings profile, without creating a new tab or window, just by calling the function.
For example, this is handy for switching from a dark to a light colored
profile without having to re-open anything.
In addition, it also works within tmux running inside iTerm2.
A usage example:
This allows running `bg_dark` or `bg_light` to switch between the two solarized themes (and also update the tmux bar).
``` shell
if [[ "$OSTYPE" = darwin* ]] ; then
if [[ "$plugins" =~ "iterm2" ]]; then
function bg_dark() {
iterm2_profile "Solarized Dark"
update_tmux_colors
}
function bg_light() {
iterm2_profile "Solarized Light"
update_tmux_colors
}
function …
```
> Plugin for iTerm2

- plugins/gpg-agent/gpg-agent.plugin.zsh
$GNUPGHOME variable was used incorrectly and caused a grep error when
set. See #6140 for more details.
> Fix wrong $GNUPGHOME usage in gpg-agent plugin

- plugins/archlinux/archlinux.plugin.zsh
`pacaur -Syua` only updated AUR pakcages, wihch is incompatible with semantics of `pacupg` and `yaupg`. Removing `-a` here it would work for both main repos and aur.
> Fixed Pacaur aliases

- plugins/terraform/README.md
- plugins/terraform/terraform.plugin.zsh
Current function name do worse. I always use `terr<TAB>` and before those prompt it was add space in the end. Now because we have multiple functions and binaries started with terraform there are no space.
> Fix the terraform function name

- lib/git.zsh
With zsh 5.4 a simple "local FLAGS" meant as an array must be explicitly declared so.
This fix avoids the dreaded "parse_git_dirty:3: FLAGS: attempt to assign array value to non-array".
> zsh fix for parse_git_dirty: declare local array FLAGS as such

- lib/git.zsh
Add match for `MM` (file modified, some modifications added, but modifications still exist) to git_prompt_status.
Steps to repro:
```
cd /tmp
mkdir foo$$
cd foo$$
git init
touch foo
git add foo
git commit -m foo
echo 'asdf' > foo
git add foo
echo 'asdf' >> foo
```
Expected:
Shows modifications added, and modifications exist.
Actual:
The repo is shown as dirty, but no reason for it being dirty.
> Add match for `MM` in git prompt status

- plugins/colorize/colorize.plugin.zsh
updated the created alias to be more user friendly/intuitive
updated exception message to reflect the proper python package.
pygmentize (0.2.1) does not install into current python3 version.
"Could not find a version that satisfies the requirement pygmentize (from versions: )
No matching distribution found for pygmentize"
Pygments (2.2.0) does install
> Colorize plugin

- plugins/dirhistory/dirhistory.plugin.zsh
Add shortcuts for mac keyboards as an alternative to alt+left
abd alt+right: mac users can now use opt+left and opt+right.
On acceptance of this PR, I will update the wiki page accordingly.
Review of @jeffwilliams would be appreciated, thanks.
> Add support for Mac to dirhistory plugin

- plugins/eecms/eecms.plugin.zsh
ExpressionEngine 4 introduced a CLI binary, this plugin adds autocompletion.
It is a common practice in the EE CMS community to rename the default `system` directory, so I have used `find` to locate the binary if the user has done so.
> Add plugin for ExpressionEngine CMS

- plugins/terraform/_terraform
```shell
$ terraform version
Terraform v0.11.2
$ terraform apply --help
Usage: terraform apply [options] [DIR-OR-PLAN]
Builds or changes infrastructure according to Terraform configuration
files in DIR.
By default, apply scans the current directory for the configuration
and applies the changes appropriately. However, a path to another
configuration or an execution plan can be provided. Execution plans can be
used to only execute a pre-determined set of actions.
Options:
-backup=path           Path to backup the existing state file before
modifying. Defaults to the "-state-out" path with
".backup" extension. Set to "-" to disable backup.
-lock=true             Lock the state file when locking is supported.
-lock-timeout=0s       Duration to retry a state lock.
-auto-approve          Skip …
```
> add -auto-approve flag to terraform apply command

- plugins/lol/lol.plugin.zsh
```
$ curl -s whatthecommit.com/index.txt
So my boss wanted this button ...
$ curl -s whatthecommit.com/index.txt
A long time ago, in a galaxy far far away...
$ curl -s whatthecommit.com/index.txt
Switched off unit test 15 because the build had to go out now and there was no time to fix it properly.
```
> Adding whatthecommit to lol plugin

- plugins/bundler/bundler.plugin.zsh
This PR adds `hanami` to the list of gems wrapped by the `bundler` plugin. [Hanami](http://hanamirb.org/) is a Ruby web framework.
> add hanami to the list of wrapped gems

- plugins/kubectl/kubectl.plugin.zsh
logs doesn't have "pods" parameter
> fix "kubectl logs"

- plugins/jira/README.md
- plugins/jira/jira.plugin.zsh
The `br` action is the only action that is used as an abbreviation. 
This PR aims at:
1. Change the `br` action to `branch` to be aligned with other actions which don't use appreviations and also to be more consistent with the name of other actions.
2. Add the `branch` action in the list of possible actions in `README.md` which was not previously listed.
> Change the "br" action to "branch" in the jira plugin to be more consistent with other actions

- plugins/web-search/web-search.plugin.zsh
Add the Qwant search engine url to the "web_search" plugin.
> Add Qwant engine - web_search plugin

- themes/avit.zsh-theme
The avit theme's _git_time_since_commit function was running git up to
three times, one of which piped the entire git log for the current
branch to /dev/null. Replace it with a single call to `git log`,
checking the exit code for success.
> Reduce prompt delay in large git repos

- plugins/archlinux/README.md
- plugins/archlinux/archlinux.plugin.zsh
This PR add commands for calling the trizen aur helper/pacman front-end for Arch to the `archlinux` plugin
trizen is the recommended solution for using the Arch User Repository.
both yaourt and pacaur have some issues.
If you have trizen installed on your system, the aliases for it will be added, and the "upgrade" command will be run with trizen. If you don't have it installed, no behaviour will be changed. 
Signed-off by: Arthur Brainville (Ybalrid) <ybalrid@ybalrid.info>
> Added trizen to the archlinux plugin

- lib/git.zsh
If @{u} is not defined, git rev-list will give an error; redirect
to stderr the error and deal with this case in what follows.
This fixes #6656
> Fix git_commits_{ahead,before} when no upstream branch is defined

- README.md
The git:// transport is completely unauthenticated. An attacker on the local or upstream network can easily man-in-the-middle an oh-my-zsh update and get remote code execution on your system. Only the https:// git transport should be used.
> Use HTTPS for manual git clone to avoid  MITM

- themes/rkj-repos.zsh-theme
Move the `hg prompt` check inside the hg_prompt_info function so that
it returns an empty string if hg-prompt isn't installed.
Fixes #6743.
cc @Lavoaster @cori
> [rkj-repos] Make `hg prompt` check less strict

- plugins/gpg-agent/gpg-agent.plugin.zsh
I discovered a few problems with the gpg-agent plugin changes on some machines. 
1. ${XDG_RUNTIME_DIR}  isn't always set
2. Older versions of gpg-agent do not use the "default location", therefore multiple agents are opened.
Therefore my solution is to use the gpgconf file to get the default location of the socket. We use this as the test to see if we need to start the agent.
Adding -use-standard-socket to starting the daemon means that older versions of gpg-agent behave in the same was as newer versions. 
I applied the same idea for the ssh agent. We can check if we have an ssh socket, if so then we set the SSH_AUTH_SOCKET - The reason for this is that newer versions of gpg-agent default to enabling ssh-agent therefore checking for the config variable wasn't reliable.
Hope this all makes …
> Fix gpg-agent plugin checks

- plugins/zsh_reload/README.md
- plugins/zsh_reload/zsh_reload.plugin.zsh
- Use `exec zsh` instead of `source ~/.zshrc` which is a bad practice because it can have side effects.
- Ignore insecure files on `compinit`.
- Add README.
- Fix code style.
Motivated by https://github.com/robbyrussell/oh-my-zsh/issues/5243#issuecomment-256362806.
cc @toddmbloom
> Refactor zsh_reload plugin

- lib/history.zsh
Allow passing in other `fc` arguments (complain in #789) and provides a simple workaround to the lack of `history -c`-like command (as seen in #739).
I also reorganized the script a little bit and removed the `append_history` ~~and `hist_verify` which seem to not be good defaults.~~ I've put it back in because at this point that's the expected behavior. Use `unsetopt hist_verify` in your zshrc files if you want to disable it.
> Enhance history alias

- plugins/pyenv/pyenv.plugin.zsh
The current version of the pyenv plugin searches for pyenv using a predefined list of paths. If found, the plugin adds the pyenv bin directory to the user's `PATH` variable, and finally runs pyenv to load it into the environment. This is backwards. No matter which pyenv installation method you use, the `pyenv` utility will already be in your path.
I've refactored the plugin to simply load pyenv directly. It will also load pyenv-virtualenv if it's available, as in the original version. If pyenv is not in the user's path, it gracefully falls back to displaying the system-installed python version in the prompt.
After refactoring, I noticed this made the plugin much faster. Let's profile it (with python of course):
profiler command: `$ python -m timeit "__import__('subprocess').call(['zsh', …
> pyenv plugin refactor (8x faster)

- themes/steeef.zsh-theme
Currently, in each preexec hook, the steeef theme runs `history $HISTCMD` which has the effect of iterating through your entire history and runs `git ls-files` **every time** you run any command. For people with lots of history, this takes a really long time and makes the terminal feel much more sluggish. If I read the intention of this correctly, it seems like the steeef theme only intended to read the last command.
This change fixes that (and uses `fc` directly instead of `history` which is an alias for `fc -l`). It also uses `whence` to expand any aliases so that if you type `gst`, for example, it'll expands to, say, `git status` and the `PR_GIT_UPDATE` environment variable will be properly set.
One notable issue is that this may feel like it breaks a piece of `steeef`'s functionality …
> Make steeef theme much faster by not iterating through all history

- plugins/github/_hub
- plugins/github/github.plugin.zsh
The current version makes 2 calls to `hub`, which can be quite slow. Since `hub alias -s` just outputs `alias git=hub` we can substitute it altogether.
> Simplify hub check and hardcode aliasing

- lib/functions.zsh
This will work only on files and directories in a DrvFs mount, i.e. that can be translated to a Windows drive path. For example: `/mnt/c/Users/user`.
Files and folders inside the LXSS directory can't be handled in Windows, they must be ONLY used by the WSL subsystem. That's why you won't be able to open your $HOME directory, for instance.
See https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/
> Check for Microsoft's WSL in open_command

- plugins/gitignore/gitignore.plugin.zsh
Deals with app error page, saving true error instead.
Upon app failure, Heroku returns HTML "Application Error" page.
Finding HTML page in .gitignore is confusing, so I replaced `-s` with `-f` in curl calls, which cuts such output (and errors with 22 instead, in Heroku case it also outputs the error message, so you know what happened if you scripted `gi` call or redirected it to a file).
Replace instead of addition as no progress meter outputs either.
> Better app error handling in curl

- plugins/git/git.plugin.zsh
`glol` and `glola` use a custom format string, which uses `%h` (abbreviated hash), so `--abbrev-commit` is not needed
> Remove unneeded option in glol and glola

- plugins/git-prompt/gitstatus.py
Inside a fresh git repo, i.e. immediately after a `git init`, usually no
commit template exists yet. In this case, git renders a different
status message than "Initial commit on". We should consider this message
when attempting to parse out the branch name.
Fixes #6301
> Parse branch-name for fresh repo

- lib/completion.zsh
Fixes #3775, fixes #6543.
This makes zsh treat `.` and `..` as directories to be completed. That means it will insert a slash (`/`) when these directories are provided in the command line.
> Allow completion of dot directories

- plugins/gradle/gradle.plugin.zsh
This change allows the gradle plugin to recognise build.gradle.kts files and
thus generate the autocomplete entries.
-=david=-
closes #6528
> gradle plugin should support kotlin gradle build files

- plugins/minikube/minikube.plugin.zsh
[Minikube](https://github.com/kubernetes/minikube) can generate zsh completion code since [version v0.24.0](https://github.com/kubernetes/minikube/blob/master/CHANGELOG.md#version-0240---11292017).
This PR allows to enable this easily with oh-my-zsh.
> Add autocomplete plugin for minikube

- plugins/aws/aws.plugin.zsh
Using `which` to determine the path `aws_zsh_completer.sh` is vastly faster than using brew to determine the base path first. Often the completer is already in your PATH, so it makes more sense to check which first.
Also added additional check for in case the file isn't found.
I can't give you comparison benchmarks, as which is a shell builtin, and time doesn't show the times:
```
$ time brew --prefix awscli
/usr/local/Cellar/awscli/1.15.0
brew --prefix awscli  0.33s user 0.15s system 96% cpu 0.499 total
$ time which aws_zsh_completer.sh
/usr/local/bin/aws_zsh_completer.sh
$ type -f which
which is a shell builtin
```
> Update AWS completion

- plugins/last-working-dir/last-working-dir.plugin.zsh
This PR tries to make `last-working-dir` work more nicely with other shell plugins that change directory internally under subshells, e.g. [shrink-path](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/shrink-path/shrink-path.plugin.zsh#L96-L124).
`shrink-path` relies on the subshell exit to return the user to the correct working dir, but subshell exit does not trigger `chpwd_functions`. As a result, `last-working-dir` gets confused, recording the subshell's last working dir, and forgetting my actual working dir.
This PR works around the issue by disabling `chpwd_last_working_dir` in subshells.
Here is a minimal reproduction of the current symptom:
```bash
> cd /usr
> cd /var
> pwd
/var
> cat "$ZSH_CACHE_DIR/last-working-dir"
/var
```
Up to here everything is …
> last-working-dir: disable chpwd_last_working_dir in subshells

- plugins/dirhistory/dirhistory.plugin.zsh
This change addresses side-effects of PR #6533 experienced on Mac terminals other than the default provided with OSX.
See the exchange with @NAR8789 attached to PR #6533 for more details.
> Fine-tune dirhistory plugin mappings for Mac

- plugins/dirhistory/dirhistory.plugin.zsh
Changes to be committed:
modified:   dirhistory/dirhistory.plugin.zsh
New Feature:
Navigate directory hierarchy using ALT-UP and ALT-DOWN. (mac keybindings not yet implemented)
ALT-UP moves to higher hierarchy (cd ..)
ALT-DOWN moves into the first directory found in alphabetical order
> Add directory hierarchy navigation to dirhistory

- plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
The `virtualenvwrapper` script has been relocated to
`/usr/local/bin/virtualenvwrapper.sh`. Update the
plugin to look in the new location first. See:
http://virtualenvwrapper.readthedocs.io/en/latest/#introduction
to confirm the change in location for this script.
This addresses issue #3047 where the solution was to source this file
from your zshrc.
> Fix default location of the virtualenvwrapper script

- plugins/ubuntu/ubuntu.plugin.zsh
`apt` replaces `apt-get` on Ubuntu 16.04.
So this code figures out which Ubuntu version we are running, and then uses the correct Apt version.
> Use 'apt' instead of 'apt-get' for Ubuntu >=16.04

- plugins/fasd/fasd.plugin.zsh
If `EDITOR` variable contains arguments to an editor such as mine:
`export EDITOR=emacsclient -t -c --alternate-editor=''`
Then, the editor's arguments are passed on to `fasd`. To fix this, pass the EDITOR program in quotes.
> Quotes around EDITOR variable for proper argument passing

- tools/check_for_upgrade.sh
`[Oh My Zsh] Would you like to check for updates? [Y/n]: ` does not make sense, since answering yes will download/apply the new updates instead of checking for them.
Fixes #6643
> Reword the update prompt

- plugins/pyenv/pyenv.plugin.zsh
This reverts back to looking for pyenv in predefined directories if the `pyenv` command is not found, but discards the setting of `PYENV_ROOT` which should [default to `$HOME/.pyenv` as per their documentation](https://github.com/pyenv/pyenv#environment-variables).
Such search will only be done if the pyenv command is not found, and we will only look for the homebrew prefix if all else fails. This way the load will take progressively longer as is needed, not taking so long for everybody as it did before.
This should satisfy users who complained that, after #6165, they can no longer use pyenv due to it not being found in their `$PATH` (see https://github.com/robbyrussell/oh-my-zsh/pull/6165#issuecomment-385840876, https://github.com/robbyrussell/oh-my-zsh/commit/8efcf2776b2e7e00c073b149f76c …
> pyenv: add back the logic to search for the pyenv command if not found

- plugins/shrink-path/shrink-path.plugin.zsh
This avoids side-effects if the user has set any `chpwd_functions` which cause output, such as is the case if the user is using `auto-ls`.
I was using `auto-ls` plugin alongside shrink-path in `agnoster` them. I had, in my `.zshrc` file:
```
ZSH_THEME="agnoster"
plugins=(git autojump lol colored-man-pages copyzshell shrink-path)
AUTO_LS_COMMANDS=(ls)
AUTO_LS_NEWLINE=false
```
Without this fix, my prompt was filled with the contents of my home directory. It took up the whole terminal, hahaha.
> [shrink-path plugin] unset chpwd_functions before running `cd`

- themes/agnoster.zsh-theme
This PR improves performance, especially when we're not in a git repo, by cutting down the number of forks/execs needed just to render the prompt. It's a particularly noticeable speedup on Cygwin.
There are three sub-commits here for three distinct performance bugs; any of them could be applied independently if you don't like some of the others.
I've also submitted similar changes upstream as https://github.com/agnoster/agnoster-zsh-theme/pull/44
> agnoster: cut down on fork/execs improve performance when not in a repo

- lib/directories.zsh
Fixes #6761
>I am the lead maintainer for po, a tool that provides a great command line experience for Particle users.
>
>Many po users are oh-my-zsh users. Those who are oh-my-zsh users annoyed when they are unable to use po because of the popd conflict. Several users are not savvy enough with the command line to disable the po alias to resolve the conflict, and it pains me to hear from a user that oh-my-zsh is interfering with their Particle workflow.
>
>All I ask is that you no longer make po be an alias for popd. It conflicts with po, and popd is a pretty uncommon command. I don't see why it is necessary to make a two letter alias for a four letter command.
>
>Thanks
> Remove po alias

- plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
This gives much faster start up times and only loads virtualenvwrapper
when needed.
Fix #6839
> Prefer virtualenvwrapper_lazy

- lib/compfix.zsh
- oh-my-zsh.sh
This error message will give information on what exactly has happened and how to either solve ownership and permissions or disable the check entirely.
Also, gets rid of the purge of compinit caches since with the current logic insecure completion directories are ignored and therefore haven't tainted the cached files.
Finally, let the rest of secure completion directories load even if there were insecure directories found. The previous logic was unnecessarily harsh.
> compfix: better error message and loading of completions

- tools/install.sh
The install script fails if the user's home directory contains a space or other white-space character. This fixes that error. See issue #4470 for some discussion around this. This patch doesn't solve any issues in other software, only in OMZ.
Fixes #4470
> Quote $ZSH where necessary in install script

- plugins/meteor/_meteor
Update arguments to handle new meteor 1.2 arguments.
Meteor is automatically updated to latest version therefore the arguments there will always be relevant.
> Meteor-1-2 arguments update

- plugins/yarn/yarn.plugin.zsh
Yeoman cli alias is 'yo' so 'yarn outdated' can't be aliased to 'yo'.
See: http://yeoman.io/
Fixes #6435
Fixes #6502
Closes #6778
Closes #6635
> Fix yarn alias that conflicts with yeoman cli

- plugins/thefuck/thefuck.plugin.zsh
The `thefuck` plugin currently directly users who don't have `thefuck` to install it with `pip`. This pr adds a note about installing via `homebrew`, the route `thefuck` recommends for macOS (which oob doesn't have `pip`)
> Thefuck: homebrew install documentation and thefuck repo link

- plugins/common-aliases/common-aliases.plugin.zsh
According to #5003
if one exports EDITOR with parameters, say:
`export EDITOR='subl -w'`
running command:
`zshrc`
will result in:
`zsh: command not found: subl -w`
This can be fixed by updating common-aliases.plugin.zsh line 16 with:
`alias zshrc='${=EDITOR} ~/.zshrc' # Quick access to the ~/.zshrc file`
Fixes #5003
> Fix zshrc alias when $EDITOR uses parameters

- plugins/autojump/autojump.plugin.zsh
The last version of autojump available on Macports does not have anymore different shell scripts (.sh, .zsh, .bash ...) to be sourced but just one autojump.sh that takes care of that located at `/opt/local/etc/profile.d/autojump.sh`
fix #4625
> Fix autojump sourcing on OSX with Macports

- lib/functions.zsh
* Simplifies code
* Fix WSL code:
- Add double quotes to command so that the next argument isn't interpreted as the title for the start command.
- If the first argument is a valid path, convert it to Windows path notation. If `wslpath` fails—because it's a path from inside WSL, which cannot be converted to Windows path notation— fail with an error code.
This last circumstance will show an error like so:
> wslpath: path: Result not representable
> Fix open_command for WSL environment

- plugins/ssh-agent/ssh-agent.plugin.zsh
When invoking a shell as root using `sudo -s`, the ssh-agent plugin starts a new agent although it already exists.
The problem boils down to a check if ssh-agent is running using `ps x`. If that is extended to `ps ax` for root, then the existing ssh-agent will still work.
> Use existing ssh-agent when invoking a sudo shell

- tools/install.sh
Otherwise these files are not sourced:
1. /etc/zprofile
2. ~/.zprofile
3. /etc/zlogin
4. ~/.zlogin
5. ~/.zlogout
6. /etc/zlogout
Which can cause confusion.
> Login shell after install

- plugins/ufw/_ufw
This adds completions for the UncomplicatedFirewall:
https://wiki.ubuntu.com/UncomplicatedFirewall
Supports all `ufw` commands and subcommands.
Everything except rules should be included.
Tested on Debian 8 - if your system does something different please let me know.
> add ufw completion script

- plugins/magic-enter/Readme.md
- plugins/magic-enter/magic-enter.plugin.zsh
Allows commonly used commands to be binded to the Enter key.
I found this trick on some forum (perhaps it was stack overflow.)
> Add magic-enter plugin

- plugins/vagrant-prompt/README.md
- plugins/vagrant-prompt/vagrant-prompt.plugin.zsh
I use Vagrant on a daily basis and I thought it would be useful to see at a glance the status of the VM(s) when I'm into a directory containing a Vagrantfile, without the need to issue a `vagrant status` each time.
Maybe it could fit better the already existent plugin `vagrant`, I don't know.
> Adding `vagrant_prompt_info` function to display VMs status on prompt

- plugins/vagrant/_vagrant
When completing `vagrant` commands, it says “Completing _gem_ subcommand.” Oops. :P
> Fix `vagrant`'s completion

- plugins/vim-interaction/vim-interaction.plugin.zsh
If you are working with many GVim sessions, you need to be able to specify which server to send a file to. This does just that. For example:
$ gvim --servername test file1.txt
$ vvsp -n test file2.txt
> Added "-n name" option to vim-interaction plugin

- lib/correction.zsh
we currently don't autocorrect for file operations mv, mkdir, adding cp for consistency
> Don't correct cp commands

- lib/functions.zsh
This change enables the `take` function to support multiple directories (mirroring `mkdir`). Before this change, `take A B C` would create a directory `A` and `cd` into it, while silently ignoring `B` and `C`. Now it will make all three directories and `cd` into `C`.
It also allows passing arguments to `mkdir`. Before this change:
$ take --mode=777 xyz
mkdir: missing operand
Try 'mkdir --help' for more information.
take:cd:2: no such file or directory: --mode=777
but this change allows the above to work correctly.
This should not break any current usage of `take`, since before only a single argument was supported. If someone had been doing `take A B C` before, it will now have a different result, but since that was almost certainly not doing what they intended, it seems like a safe …
> Enable passing multiple directories to take

- plugins/dotenv/README.md
- plugins/dotenv/dotenv.plugin.zsh
FIxes #6083, closes #6074, #6075
This PR fixes a bug reported in #6083, when in most cases `dotenv` plugin ignored lines without `export`. Now it recognises them by temporarily enabling `set -a` option. If this option was enabled before, it stays unmodified:
```sh
if [[ -o a ]]; then
source .env
else
set -a
source .env
set +a
fi
```
Now the plugin accepts both file formats as was stated.
Also, clarified the README and added disclaimer about plugin's capabilites, while offering alternative solutions, which should close #6074 and #6075 issues.
> Fix dotenv plugin accepted file format and clarify README

- plugins/wp-cli/README.md
Fixes typo in `wptu` command for wp-cli plugin's README file. Was previously `wp theme updatet` and now, it's `wp theme update`
> wp-cli: fix README typo for wptu command

- lib/history.zsh
- templates/zshrc.zsh-template
As per discussion in https://github.com/robbyrussell/oh-my-zsh/pull/6589, this PR adds the ability to define a custom format for timestamps shown by the `history` command.
1. If `HIST_STAMPS` is unset or empty the default behavior is maintained and no timestamps are shown. 
2. The custom formats `mm/dd/yyy`, `dd.mm.yyyy`, and `yyyy-mm-dd` are kept as well.
3. Otherwise `HIST_STAMPS` is used as a format string passed to the `fc` command via the `-t` option. The format string — as per [`fc`'s manual](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html) — "is formatted with the strftime function with the zsh extensions described for the `%D{string}` prompt format in [Prompt Expansion](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Prompt-Expansion)." . More info …
> Add support for custom timestamp format in history

- plugins/git-flow-avh/git-flow-avh.plugin.zsh
This updates the git-flow-avh plugin to the latest version
from https://github.com/petervanderdoes/git-flow-completion
(0.6.0 at the time of this commit).
This mainly adds support for the "git flow bugfix" command.
This PR replaces #4626 as well as #4705, both of which adds support for the bugfix command but doesn't use the official version from https://github.com/petervanderdoes/git-flow-completion
Fixes #4705
Fixes #4626
Fixes #5903
> Update git-flow-avh to 0.6.0

- lib/misc.zsh
The option '-F' causes 'less' to automatically quit if the contents fit 
the screen and the option '-X' causes 'less' to not clear the screen after 
quit. I think both options are generally useful for terminal applications.
They are in particular useful for Git as it runs all output through a
pager. Git will run 'less' with '-FRX' by default if the environment 
variable $LESS is not defined [1]. Since oh-my-zsh used to set $LESS to 
'-R', Git would not override this setting. Consequently, Git would 
display even a single line of output in a pager and the user would need
to explicitly quit that pager (see mailing list discussion [2]).
Therefore, lets change the oh-my-zsh default value for $LESS to '-FRX'.
This would be useful for oh-my-zsh Git users and likely for users of
other …
> add -F and -X to default $LESS environment variable

- plugins/git-prompt/gitstatus.py
When a commit has multiple tags associated to it, the git-prompt will
throw the following error:
git_super_status:[:4: integer expression expected: v0.21.x\ntags/v0.21.5,
git_super_status:[:7: integer expression expected: origin/v0.21.x,
git_super_status:[:11: integer expression expected: origin/v0.21.x,
git_super_status:[:14: integer expression expected: v0.21.x
git_super_status:[:23: integer expression expected: v0.21.x
This is due to the prompt expecting the tag field to be a single word
with no spaces in between but if there are multiple tags the python
script returns a string with ', ' space separated list of tags.
This throws off the parser. The solution is to ensure that the python
script returns a space-less string ensuring the git-prompt parser to
properly parse the data. …
> git-prompt: fix error when multiple tags exist

- plugins/asdf/asdf.plugin.zsh
* Modifies the search logic for asdf to include Homebrew when it is
installed.  The implementation is adapted from the pyenv plugin.
* Includes command completions for both regular and Homebrew installs.
This enhancement was inspired by PR #6046.
> Adds Homebrew and completion support to asdf plugin

- plugins/forklift/forklift.plugin.zsh
This adds support for ForkLift 3, which uses a different
application id and also uses a popover instead of a sheet for
entering the directory to go to.
This also improves the handling of different versions of ForkLift,
by first choosing any currently running instance, and if none is
running starting the newest available version.
Fixes #6565.
> Add support for ForkLift 3

- plugins/git/git.plugin.zsh
Add alias `gav='git add -v'`
fixes #6793
> Add alias for git add --verbose

- plugins/git/git.plugin.zsh
An alternative alias for `gdca = git diff --cached`:
> `gds` = `git diff --staged`
Equivalent option according to [git-diff man page](https://linux.die.net/man/1/git-diff).
Mentioned in #3167.
> Add Git alias for `git diff --staged`

- plugins/bundler/bundler.plugin.zsh
The white space is causing an error and bundler cannot find any commands!
```sh
bundler: command not found: _rails_command
Install missing gem executables with `bundle install`
```
> Remove the white space

- themes/trapd00r.zsh-theme
This is a tentative fix for issue #5468. It is a bit of a hack, since the external script basically gets hardcoded inside the theme, but it makes the theme work right away and doesn't force the user to download additional files from github to get things going. Feel free to reject if it doesn't meet quality standards.
From https://github.com/robbyrussell/oh-my-zsh/issues/5468#issuecomment-256511479:
> It still requires you to have the Term::ExtendedColor module installed, but that could definitely be avoided too, if someone is willing to devise a workaround for the perl code.
Fixes #5468
> Fix for external dependency in trapd00r theme

- plugins/github/github.plugin.zsh
Change `git add .gitignore` to `git add -f .gitignore`.
> .gitingore prevents adding itself, so breaks the function.

- plugins/firewalld/firewalld.plugin.zsh
`firewall-cmd --get-active-zones` returns something like this:
```
dmz
sources: ipset:dmz-hosts
public
interfaces: eth0
```
if zone binding is based on source ips, so strings with `sources: ...` should be excluded along with `interfaces: ...` to get zones list.
> Fixed `fwl` function in `firewalld` plugin when `sources` used

- plugins/vi-mode/vi-mode.plugin.zsh
This pr fixes two things:
* [bug-6404](https://github.com/robbyrussell/oh-my-zsh/issues/6404): Indicator is shown after window resize. In case the window is maximized, the indicator is shown but an error message is displayed: `widgets can only be called when ZLE is active`. Haven't found out yet how to get rid of it, but it works.
* Makes sure `MODE_INDICATOR` is drawn when the terminal is started. This is not the case with the actual plugin.
> fix bug-6404

- themes/fino-time.zsh-theme
- themes/fino.zsh-theme
- Check if `rmv-prompt` is installed before trying to use it
> Fix rvm-prompt usage in fino* themes

- plugins/jump/jump.plugin.zsh
Using the `jump` plugin, using the `marks` command will yield this output:
```
$ marks
desktop marks:printf:5: bad option: ->
dotfiles        marks:printf:5: bad option: ->
home    marks:printf:5: bad option: ->
```
the `marks` function uses `printf` with `->` and I believe `-` is used by `printf` for left-justification.  changing this to `-- "->"` seems to render the appropriate output.
```
desktop -> /Users/uname/Desktop
dotfiles        -> /Users/uname/.dotfiles
home    -> /Users/uname
```
> Fixes jump plugin printf path output

- plugins/fasd/fasd.plugin.zsh
I really got used to that autojump alias which got into my muscle memory, so I am now bringing fasd closer to an autojump drop-in replacement.
> fasd: drop-in replacement for the autojump j alias

- plugins/fzf/fzf.plugin.zsh
A small change to fix #7110, I keep it minimal to stay as close possible to the [upstream install script](https://github.com/junegunn/fzf/blob/8540902a35361dba217cc3ad86ff2215ae51918e/install#L266-L278).
I also made a change to not clutter PATH if `fzf` is already available.
I tested these changes on the following `fzf` installations:
* MacOS + brew
* Archlinux + Pacman
* Fedora + RPM
* Linux + Git
> fzf: Fix shell directory for archlinux package

- plugins/dash/dash.plugin.zsh
At some point the bundle identifier for Dash updated.
> dash: update dash bundle identifier

- plugins/react-native/README.md
Added new iPhone XR, XS and XS Max simulator aliases to the README documentation
--Sorry, should have made it all one PR
> added new iphone model simulators to readme

- themes/agnoster.zsh-theme
Hide the git prompt when the oh-my-zsh.hide-status git config option is set.
> make git config oh-my-zsh.hide-status work with the agnoster theme

- plugins/bgnotify/bgnotify.plugin.zsh
The options for kdialog in KDE use double dashes.
> kdialog title option with double dash

- plugins/sudo/README.md
I have created a [readme file](https://github.com/grikomsn/oh-my-zsh/blob/master/plugins/sudo/README.md) for the `sudo` plugin, with steps to add the plugin to the `.zshrc` file, and some usage examples. I was planning to add a `asciinema` embed example but I can't replicate some "permission denied" examples, so here's just the readme.
Feedbacks appreciated, and [happy Hacktoberfest](https://hacktoberfest.digitalocean.com/)! 🎉
> Added readme file for sudo plugin

- plugins/chruby/chruby.plugin.zsh
Detect system Ruby in default `PATH`, and provide "system" completion if Ruby is found. Tested with [the Dockerfile](https://gist.github.com/franklinyu/b8deda6a5093a17b575679b5808b371f).
> Add "system" to the completion list for plugin "chruby"

- plugins/kubectl/kubectl.plugin.zsh
Tiny addition to the `kubectl` plugin for interacting with `namespaces` & `configmaps`.
> add aliases for interacting with k8s namespaces & configmaps

- plugins/jump/jump.plugin.zsh
Force the mark to point to the new dir, replacing the old one.
Fixes the unexpected behavior reported on #7195.
> Fix behavior when reusing a mark

- plugins/jump/jump.plugin.zsh
The flag '-h' isn't universal across implementation. According to FreeBSD man page for ln you can use 'n'.
> More compatible flag for ln

- plugins/dircycle/README.md
This PR adds a readme file for the `dircycle` plugin, which includes detailed usage examples and an asciinema cast demonstrating directory traversals.
> Added dircycle readme file

- plugins/go/README.md
This adds a new README.md for the go plugin, which explains to the user that the go plugin is a duplicate of the golang plugin and now symlinks there. 
For #7175
> Create README.md for go plugin

- plugins/docker-compose/README.md
Current readme file of docker-compose plugin doesn't have aliases included. It is added.
Contributes to #7175
> Added aliases to readme of docker-compose plugin

- plugins/dircycle/README.md
I have updated the `dircycle` readme for readability and uniformity. For example, at PR #7213, the `dircycle` readme describes on how to rebind keys. This should be described on another section unrelated to the "Functions" section. This PR changes the following:
+ Changed keypresses to use the `<kbd>` tag
+ Added "rebinding keys" section
- Removed line break on description
- Removed line break on "rebinding keys"
> Update dircycle readme for readability and uniformity

- plugins/catimg/README.md
I have created a readme for the `catimg` plugin, which contains how to enable the plugin and an asciinema usage example.
> Added readme for catimg plugin

- plugins/terraform/terraform.plugin.zsh
in the home directory there is a .terraform file for modules but it is most likely not an actual directory of terraform scripts. this disables checking for a workspace in the home directory which defaults to [default] if there is no workspace defined, which is unlikely in the home directory. It is possible others have a usecase where this would be desirable though, so maybe this patch should only be enabled with some disable_tf_prompt_in_home_dir type var.
> disable terraform prompt info in home directory

- plugins/archlinux/README.md
- plugins/archlinux/archlinux.plugin.zsh
[Yay](https://github.com/Jguer/yay) another Yogurt - An AUR Helper written in Go
Considering the  [Arch wiki: AUR helpers](https://wiki.archlinux.org/index.php/AUR_helpers), I think `yay` is more robust and powerful than `yaourt`.
I alias `yay` with the same commands as `yaourt`, I think most people will not use them together.
> [plugins/archlinux] add alias for yay

- plugins/sublime/sublime.plugin.zsh
Fixes broken sublime plugin for cygwin environment. Typo in variable name was introduced in cea941ce42b5d550489367608dd1ac4401151c97.
> [subl] Fix sublime plugin for cygwin. Typo in path variable was introduced by cea941c

- plugins/mvn/mvn.plugin.zsh
The problem that can occur is ocassionally mvnw will not be executable. This can happen if mvnw is included from an archetype, as unix permissions aren't preserved within the jar they're stored in. Only using mvnw if it exists AND is executable
> mvn-or-mvnw: Changing check from -f to -x

- plugins/git-flow-avh/README.md
- plugins/git-flow-avh/git-flow-avh.plugin.zsh
This adds a readme file for the git-flow-avh plugin as requested in #7175
> Add readme for git-flow-avh

- plugins/git-hubflow/README.md
- plugins/git-hubflow/git-hubflow.plugin.zsh
This adds a readme file for the git-hubflow plugin as requested in #7175
> Add readme for git-hubflow

- plugins/transfer/README.md
- plugins/transfer/transfer.plugin.zsh
Signed-off-by: Arvindraj <arvindultimate7352@gmail.com>
----
Fixes #7371
Co-authored-by: Stephen Ward <stephen@whilenotzero.com>
> transfer: Add deprecation notice (#7371)

- plugins/transfer/README.md
- plugins/transfer/transfer.plugin.zsh
Reverts robbyrussell/oh-my-zsh#7372
Transfer has now backing from Storj Labs and will live on, as the website indicates.
> Revert "transfer: Add deprecation notice (#7372)"

- plugins/vagrant/_vagrant
I added three commands to the completion that were not there before. I took the wording from the output of `vagrant --help` on Vagrant 2.2.0
Tagging @robbyrussell , since you are listed as the maintainer for the Vagrant plugin
> Add new vagrant commands

- plugins/jump/jump.plugin.zsh
Before, when typing the `marks` command, longer mark keys would cause
the tabs to spill over to the next tab stop, like so:
rc      -> /home/ahlex/.rc
repos   -> /home/ahlex/repos
a-longer-string         -> /tmp
Implement better key display by running through all of the marks twice,
once to get the longest key length, and the second time to format
everything according to that length:
rc -> /home/ahlex/.rc
repos -> /home/ahlex/repos
a-longer-string -> /tmp
> Provide even spacing between marks

- plugins/aws/aws.plugin.zsh
aws_porfiles regex is catching more lines than profiles, thus breaking completion.
Example is when have a profile with assume_role like this:
[profile sandbox]
region = eu-west-1
output = json
role_arn = arn:aws:iam::XXXXXXXXX:role/XXX
source_profile = admin
mfa_serial = arn:aws:iam::XXXXXXXXX:mfa/XXX
> aws_porfiles completion problem

- plugins/ssh-agent/ssh-agent.plugin.zsh
Fixes ssh-agent plugin.
With the last change, the plugin check each time if all identities are loaded, using *ssh-add -l command* and check the id file presence. But the command can return the key comment instead of the key file. Thus, the check miss and the key is re-loaded each time.
To fix that, I changed the function to use the key fingerprint to check if it is loaded or not.
Fixes #5128
Closes #5537
> ssh-agent: use hash signature to check ids

- plugins/ssh-agent/ssh-agent.plugin.zsh
With this PR the ssh-agent plugin loads all identities which are not yet
loaded in a single call to ssh-add. If a passphrase is shared between
loaded identities it only needs to be entered once.
Fixes #7506
> ssh-agent: autoload identities in one go

- plugins/git/git.plugin.zsh
context: I had a branch name that started with `#`
/cc @ncanceill
> [git plugin] Add quotes to the branch name in ggpull and ggpush aliases

- templates/zshrc.zsh-template
The OMZ template used to have the plugins section defined as `plugins=(git)` which was very easy to manage using provisioning tools like puppet and salt. Since it was a single line, simple regex was required to match and update them. 
However, it was changed in 7a7480b987c00bd916e2abf7179f92164ac44362 to improve readability.
I maintain a module for puppet that allows automated deployment and management of OMZ on puppet nodes. Currently it clones the OMZ repo and copies the template before applying user defined themes and plugins. However, since the `plugins` section is no longer a single line, puppet is unable to reliably match and replace this section. and we have made many attempts to fix this as following:
- https://github.com/rehanone/puppet-ohmyzsh/pull/11
- …
> Allow automation tools to manage plugins by removing multiple lines in template

- plugins/ssh-agent/ssh-agent.plugin.zsh
This change makes the plugin check if an identity is loaded by looking first at the key filename reported by `ssh-add -l`. This fixes the use case where ssh-keygen is not able to output the fingerprint of a key, such as the one reported on #7516.
Now, for an identity to be passed onto ssh-add, it has to fail both the match for a loaded identity's filename and signature.
Fixes #7516
> ssh-agent: check for loaded id filenames first

- plugins/git/git.plugin.zsh
On my MacOS (Mojave) ggfl aliast is not working:
```
> ggfl
zsh: command not found: ggfl
```
Looks like these spaces were missing, because it works now.
> Fix ggfl command not found error

- plugins/asdf/asdf.plugin.zsh
* The check for the asdf installation directory is more precise.
* Completions, while installed with homebrew, are now expected on an alternative location.
——
The existence of the directory `$HOME/.asdf` does not mean that it is the installation directory of `asdf`. It will also be created after installing at least one asdf plugin.
@robbyrussell  @mcornella @RobLoach
> asdf: fix homebrew installation path

- plugins/brew/README.md
- plugins/brew/brew.plugin.zsh
Technically we could use cask as a prefix too, as it should not cause any overlaps. 
for example caskout for outdated check and caskup for update.
> Ads brew cask update to brew plugin

- plugins/timer/README.md
- plugins/timer/timer.plugin.zsh
This plugin allows to display command's execution time in a very nonintrusive way.
Timer can be tuned by these two variables:
- `TIMER_PRECISION` allows to control number of decimal places (default `1`)
- `TIMER_FORMAT` allows to adjust display format (default `'/%d'`)
Tested on OSX and Ubuntu.
Sample session:
```
me@here:~$ sleep 1                                         /1.0s
me@here:~$ sleep 73                                     /1m13.0s
me@here:~$ TIMER_FORMAT='[%d]'; TIMER_PRECISION=2        [0.00s]
me@here:~$ head -c50 < /dev/urandom | hexdump
0000000 b2 16 20 f0 29 1f 61 2d 8a 29 20 8c 8c 39 5a ab
0000010 21 47 0e f9 ee a4 76 46 71 9e 4f 6b a4 c4 51 cb
0000020 f9 1f 7e b9 6f 2c ae dd cf 40 6d 64 a8 fb d3 db
0000030 09 37
0000032 …
```
> Timer plugin

- plugins/jenv/jenv.plugin.zsh
recent `brew install jenv` installs to `/usr/local/bin/jenv`, auto-discover it for recent brew installs to avoid secondary, slower search
> add brew install path to search

- plugins/kubectl/README.md
- plugins/kubectl/kubectl.plugin.zsh
With default kubectl commands, there is no like this functions. So  i added  this two short commands `kcn` and `kres` with workaround.
1) Changing current namespaces: `kcn`  
example: 
```sh
kcn test-1
```
2) Restarting all pods in deployments with zero-downtime: `kres`  
example:
```sh
kres deploy/nginx
```
> Changing namespace and restarting pods with kubectl

- plugins/adb/_adb
Currently it shows for example the following
DEVICE_ID  -- transport_id:2
Which doesn't really ease device selection, I've adapted the awk script to print device name with it's model name, see the example below
DEVICE_ID  -- Pixel_3(blueline)
> Improve adb -s completion to show helpful info

- README.md
- tools/install.sh
- tools/upgrade.sh
Linking directly to the Oh My Zsh inventory vs the top-level store with non-OMZ items.
> Updating Oh My Zsh shop URLs

- README.md
Just a very simple README change.  The existing link to the themes section no longer works.  Hopefully this follows the guidelines!
> Fixed themes link in README.md

- plugins/wp-cli/wp-cli.plugin.zsh
> wp-cli: fix typo

- lib/compfix.zsh
Issue produces following output on login:
```zsh
[oh-my-zsh] Insecure completion-dependent directories detected:
ls: cannot access : No such file or directory
[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.
[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w
[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] …
```
> Current check in compfix fails for empty strings

- lib/termsupport.zsh
There are minor but important differences between tmux and screen terminal features. Modern GNU distributions now come with `tmux` and `tmux-256color` termcaps and it is preferable to use these when using tmux. The small change in this PR allows functional tmux window title updates using existing oh-my-zsh functionality when using a "tmux*" `$TERM` .
> Enable tmux window title updates when using proper tmux* $TERM values.

- themes/agnoster.zsh-theme
Adds the AWS_PROFILE environment variable to the command prompt for the agnoster theme. 
Setting the AWS_PROFILE to anything containing `production` or ending in `-prod` will set the colour to yellow on red, otherwise it will be black on green
> Add AWS_PROFILE env var to prompt for agnoster theme

- plugins/otp/otp.plugin.zsh
This plugin allows you to create one-time passwords using oathtool, able to replace MFA devices.
The oathtool key is kept in a GPG-encrypted file so the codes can only be generated by an user able to decrypt it.
Provided aliases:
- otp_add_device - creates a new encrypted storage for an oathtool key and stores it on the disk. For encrypting the key, it will ask for a GPG user ID(your GPG key's email address). Then the OTP key needs to be pasted, followed by a ^D character inserted on an empty line.
- ot - generates a MFA code based on the given key and copies it to the clipboard(on Linux it relies on xsel, on MacOS X it uses pbcopy instead)
> otp: new plugin for MFA one-time passwords using oathtool, integrated with the clipboard

- plugins/aws/README.md
- plugins/aws/aws.plugin.zsh
Many popular themes display the current profile inline so this update adds the option to disable the addition to the RPROMT if required.
~~update aws.plugin.zsh to use a $HIDE_AWS_PROMPT option~~
update aws.plugin.zsh to use a $SHOW_AWS_PROMPT option
add usage to the readme
Tagging @cristim (Are you still the primary maintainer?)
----
UPDATED: fixes #6127
> Update the AWS plugin to support disabling RPROMT display

- plugins/fd/_fd
In debian package, fd executable is renamed to fdfind.
(https://packages.debian.org/buster/fd-find)
> Fix fd-find completions for debian

- plugins/pyenv/pyenv.plugin.zsh
This makes `pyenv` plugin load faster if `pyenv` is installed using Homebrew. Adding a new search path prevents `brew --prefix pyenv` from being called which is very slow.
**rb**env plugin already has a similar path:
https://github.com/robbyrussell/oh-my-zsh/blob/9509fd6a9193e32e5c2d460786253ba0e98fd741/plugins/rbenv/rbenv.plugin.zsh#L6
> Detect pyenv from Homebrew faster

- oh-my-zsh.sh
A simple change to make the warning more informative when requesting a plugin in `~/.zshrc` that is not found.
In my case I just received the following text at the top of a new console window:
`Warning: plugin hub not found`
I surmised it must be an Oh My Zsh error but it took me a while to realise it was referring to the plugin called 'hub' not something called the 'plugin hub'. With the new version it would have said:
`Warning: Oh My Zsh plugin 'hub' not found`
which would have been easier to debug.
> More informative warning if plugin not found

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
Based on the Contributor Covenant. Adding links from the README and CONTRIBUTING pages to this, too, along with an email address for reporting abusive behavior to. Closes #7733
> Introducing a Code of Conduct based on the Contributor Covenant

- plugins/git/git.plugin.zsh
Add the alias 'gtl', which does the following:
1. List the tags that match the pattern(s) passed through the argument.
2. Displays the first line of the annotation message along with the tag, or the line of the first commit message if the tag is not annotated.
3. Sorts and displays tags in descending order.
Suppose there are several tags:
v1.2.1
v2.5.1
v2.5.2
v3.5.1
...
When running gtl v2.5 this will result in
v2.5.2  -commit message 
v2.5.1  -commit message
> Git Plugin: Add the git alias 'gtl', that list the tags that match the pattern(s)

- plugins/git-prompt/gitstatus.py
As described in #6086 there will be an error when one set another
language than default (Unix: LANG=C).
Now setting the default language to english by the environment variable
LANG.
Fixes #6086.
> Add environment variable LANG=C to gitstatus

- plugins/swiftpm/README.md
- plugins/swiftpm/_swift
Fixes #7743
Updates autocompletion to Swift 5.0
Generated automatically using:
```
swift package completion-tool generate-zsh-script > ~/.oh-my-zsh/plugins/swiftpm/_swift
```
> Update the swiftpm plugin autocompletion for Swift 5.0

- lib/history.zsh
When using the history wrapper and not passing any parameters the usage of @[-1] on line 15 throws an error. This can be resolved by allowing zsh to have a default parameter value during the usage.
HIST_STAMPS also is undefined when trying to source this file directly which also can be resolved by using a default value.
Fixes #7432
> history: fix issues with nounset and parameters being used before defined

- plugins/git/git.plugin.zsh
CC: @ncanceill 
> Migrating to `git stash push`
> As of late October 2017, there has been extensive discussion on the Git mailing list, wherein the command `git stash save` is being deprecated in favour of the existing alternative `git stash push`. The main reason for this is that `git stash push` introduces the option of stashing selected pathspecs, something `git stash save` does not support.
> 
> `git stash save` is not going away any time soon, so don’t worry about it suddenly disappearing. But you might want to start migrating over to the push alternative for the new functionality.
The Pro Git book, in the chapter about Stashing and Cleaning, now reports the above note. The new command was introduced with Git 2.13, which came out 2 years ago. I'm using the latest version of Git and …
> [Git plugin] Use stash 'push' instead of the deprecated 'save'

- plugins/aws/README.md
- plugins/aws/aws.plugin.zsh
- themes/fishy.zsh-theme
Fix issue related to #7615
After the update, aws prompt (which should be visible out of the box) disappears when a user uses a theme fishy, because of fact that plugins are loaded before themes.
This line:
```
/Users/jw/.oh-my-zsh/plugins/aws/aws.plugin.zsh:47> export RPROMPT='$(aws_prompt_info)${return_status}$(git_prompt_info)$(git_prompt_status)%{$reset_color%}'
```
is overwritten during startup by below line:
```
/Users/jw/.oh-my-zsh/themes/fishy.zsh-theme:17> RPROMPT='${return_status}$(git_prompt_info)$(git_prompt_status)%{$reset_color%}'
```
This pull request fixes issue with not showing aws prompt in theme fishy, by appending RPROMPT in theme fishy instead overwriting (way mentioned in #6346) and adds information about it in documentation.
> Fix showing aws prompt out of the box for 'fishy' theme

- plugins/vi-mode/vi-mode.plugin.zsh
Given that traps are global, it's uncool to set them without a good reason. vi-mode plugin traps SIGWINCH with a generic function unrelated to the functionality of the plugin. This PR removes it.
If calling `zle reset-prompt` on SIGWINCH was generally useful (it isn't), it would've been done in zsh itself or in the core of oh-my-zsh.
Note that `reset-prompt` triggers a bug in zsh that causes completion menu disappear. See https://www.zsh.org/mla/workers//2019/msg00161.html.
> Remove TRAPWINCH from vi-mode plugin

- plugins/emacs/emacsclient.sh
Revert cab1ac6e682038b2ceca9d16f8c458c0e79149ca
The change from the above commit breaks opening a new emacs frame if
there isn't a existing frame open.
When emacs is running in daemon mode, there will always be a frame
associated with the daemon, even if there are no visible frames.
The lisp function `frame-list`, will always return 1 frame.
```
emacsclient --eval '(frame-list)'
(#<frame F1 0xa3c680>)
```
When an real frame is open, two frames are reported by the `frame-list`
function.
```
emacsclient --eval '(frame-list)'
(#<frame F1 0xa3c680> #<frame emacs Prelude - ~/oh-my-zsh/plugins/emacs/emacsclient.sh 0xf50e10>)
```
See:
https://emacs.stackexchange.com/questions/44537/extra-frame-in-visible-frame-list-when-started-in-daemon-mode-is-causing-prob …
> Revert cab1ac6e682038b2ceca9d16f8c458c0e79149ca

- themes/bira.zsh-theme
`venv_prompt` add extra space before `user_host` when is not activated. It's must be fixed to restore traditional behaviour:
P.S. You can use [bira-original.zsh-theme](https://gist.github.com/KillWolfVlad/f9c65c8578f50ac969de15eafb7c31c6) to get this solution right now!
> bira: remove extra space

- plugins/kubectl/README.md
- plugins/kubectl/kubectl.plugin.zsh
This uses `ku` instead of `k` as an alias for kubectl ~~if [supercrabtree/k](https://github.com/supercrabtree/k) has been installed. Requires that k has been sourced before the kubectl plugin.~~
Fixes #6408
> kubectl: rename k alias

- tools/install.sh
When oh-my-zsh is installed, the welcome message has twitter url, when click it redirects to non existent profile.
> Remove a dot from twitter url in installer

- lib/theme-and-appearance.zsh
Enable colored "ls" output in FreeBSD (#[7565](https://github.com/robbyrussell/oh-my-zsh/issues/7565))
> Colored ls output in FreeBSD #7565

- plugins/colorize/colorize.plugin.zsh
"mktemp --template" fails in macosx
"mktemp -t" works in macosx and linux.
this bash function should use "mktemp -t" instead.
> mktemp --template doesnt work in macosx.  mktemp -t works in macosx AND linux

- templates/zshrc.zsh-template
I noticed this option was missing from the template. When I followed the directions in README to enable it, I put it below line 59 without noticing it wouldn't have any effect by then. Prevent others from making a rookie mistake like mine.
> Adds option to disable auto update prompt

- plugins/frontend-search/README.md
- plugins/frontend-search/_frontend-search.sh
- plugins/frontend-search/frontend-search.plugin.zsh
As described in #7802, the angularjs URL for the frontend-search zsh plugin was outdated. An update was needed to point to the new URL when the user runs "frontend angularjs ...".
I updated the README.md of the frontend-search plugin to include the new URL for angularjs, and made the appropriate change in frontend-search.plugin.zsh to point to the new URL 'https://angular.io/?search='. I also updated the code that adds a + between the search terms when appending them to the URL to be encoded (so + now becomes %20). I did this because the new search URL for angular drops the search terms in the angular search bar with the + included, instead of a space. I verified that this does not break any of the existing searches we have.
Fixes #7802
> frontend-search: add Angular 2 context

- plugins/jira/jira.plugin.zsh
_git_query() expects command line arguments to be passed in but when set as default action, both assigned and reported fail with an error.
> jira: fix error when assigned or reported are default

- lib/directories.zsh
Replace the alias with a function. Call `dirs` if arguments are given to `d`.
I think this should be purely feature-enabling, if there's a better way to do this let me know.
> Allow arguments to `d` to be passed to dirs

- plugins/ssh-agent/ssh-agent.plugin.zsh
- Simple edit from `starting ...` to `Starting ...`
**Background**
In zsh and in most operating systems the log messages are capitalized. Yet when the `ssh-agent` plugin runs (screenshot below) we see a lowercase log message. This doesn't look too good...
Even in the zsh / oh-my-zsh documentation images show mostly uppercased log messages:
> Consolidate uppercase echo in ssh-agent plugin

- plugins/pyenv/pyenv.plugin.zsh
- plugins/rbenv/rbenv.plugin.zsh
This should speed up the loading due to lazy-searching for homebrew-installed rbenvs.
This PR makes the the rbenv-related changes in #6637 unnecessary.
closes #6168
closes #4998
fixes #3093
closes #3931
closes #3808
> rbenv: improve rbenv loading based on pyenv

- plugins/sdk/README.md
- plugins/sdk/sdk.plugin.zsh
[SDKMAN!](http://sdkman.io/) is a tool for managing parallel versions of multiple Software Development Kits on most Unix based systems.
It is commonly used in the JVM community for downloading tools like ant, maven, gradle, groovy and of late, java too.
> Add Plugin for SDKMAN

- plugins/aws/aws.plugin.zsh
When running `asp` without arguments to clear an exported profile, the variables `AWS_DEFAULT_PROFILE`, `AWS_PROFILE` and `AWS_EB_PROFILE` are left "blank". There are not removed from the envrionment variables.
This causes the AWS CLI (and I guess some SDKs also) to try to find a profile with an empty name.
Example when no profile is exported (no `AWS*PROFILE` variable is exported):
```bash
$ aws s3 ls
Unable to locate credentials. You can configure credentials by running "aws configure".
```
Example  when `asp` is run without arguments to clear an exported profile:
```bash
$ aws s3 ls
Traceback (most recent call last):
File "/usr/local/bin/aws", line 27, in <module>
sys.exit(main())
File "/usr/local/bin/aws", line 23, in main
return awscli.clidriver.main()
File …
```
> aws: really unset AWS*PROFILE variables in asp function

- plugins/vi-mode/vi-mode.plugin.zsh
Fixes #7797
This resets the `$VI_KEYMAP` variable back to `main` when <kbd>Enter</kbd> is pressed. For some reason, `zle-keymap-select` isn't triggered when that happens.
Another option is using `zle-line-init` which *is* called when Enter is pressed, since a new command *line* is drawn, but it could have side-effects for multiline prompts (see https://unix.stackexchange.com/a/1019).
> vi-mode: reset KEYMAP on accept-line

- README.md
- plugins/dotenv/README.md
- plugins/dotenv/dotenv.plugin.zsh
Fixes #7579 
-
- Reads env file from exported variable `ZSH_DOTENV_FILE`.
- If file, nothing is exported to the variable it takes `.env` as default file name
> dotenv: add support for custom env file names

- plugins/kubectl/README.md
- plugins/kubectl/kubectl.plugin.zsh
Small tweak to add an alias for listing all contexts. Tried to use it and realised it wasn't here.
> Add new kubectl alias to list all contexts

- plugins/frontend-search/README.md
- plugins/frontend-search/_frontend-search.sh
- plugins/frontend-search/frontend-search.plugin.zsh
With this pull request I am:
- Updating docs;
- Removing `aurajs` command. It's not available anymore;
- Adding commands for:
- jestjs;
- typescript;
- flowtype;
- github;
- vuejs;
- nodejs;
- bundlephobia;
> frontend: add frontend search commands

- plugins/ng/ng.plugin.zsh
I looked for an option with "word" and "split" and I found this piece of source code:
```
setopt shwordsplit
reply=($opts)
unset shwordsplit
```
However, `unset`doesn't work for inverting the previous zsh option. 
This PR only replaces `unset`by `unsetopt`.
> ng: fix shwordsplit option use

- plugins/fasd/fasd.plugin.zsh
For the `v` alias to work in its current state, the environment variable
EDITOR must already be defined by the time `source $ZSH/oh-my-zsh.sh`
happens. However, in the included zshrc template, EDITOR is set from
within the "User configuration" section, which begins immediately after
the above line. This means that, unless the user knows to move their
`export EDITOR` statements, EDITOR will be undefined when fasd.plugin.zsh
loads, and therefore the alias will have the value 'f -e ""', preventing
it from functioning.
With this change, `"$EDITOR"` will be evaluated each time the alias is
invoked, instead of just once when the alias is created. This allows for
EDITOR to be set from "User configuration" in the zshrc, and has the
additional flexibility of allowing a user to specify a different …
> Update fasd `v` alias to evaluate $EDITOR lazily.

- plugins/kube-ps1/kube-ps1.plugin.zsh
This fixes color bleeding when using tab complete with the kube-ps1 plugin active.
Steps to reproduce
* Enable the kube-ps1 plugin, and add `$(kube_ps1)` in your prompt
* start typing a command, and press <TAB>
The command you just typed would change color, and the color would bleed out to other output from the command.
> kube-ps1: fix color bleeding in prompt

- plugins/gitfast/_git
- plugins/gitfast/git-completion.bash
- plugins/gitfast/update
The new completions require a version of Git that is at least v2.17, better use the completions right before that so our users don't run into issues inadvertently.
> gitfast: downgrade to upstream v2.16

- plugins/pip/pip.plugin.zsh
Zsh may be configured such that ">>" will error if the file doesn't exist.
> pip: Fixes no such file or directory: /tmp/zsh_tmp_cache

- plugins/ubuntu/README.md
- plugins/ubuntu/ubuntu.plugin.zsh
- Clean up plugin and README
- Rename ag to age to avoid conflict with The Silver Searcher:
* Fixes #3866
* Closes #5752
> ubuntu: plugin cleanup and rename of ag alias to age

- plugins/dnote/README.md
- plugins/dnote/_dnote
This PR adds a completion plugin for Dnote (https://github.com/dnote/dnote) which is an open source note-taking software for developers.
I would like to contribute this so that users can save time.
> Add a completion plugin for dnote

- plugins/colorize/README.md
- plugins/colorize/colorize.plugin.zsh
These commits add an environment variable, `ZSH_COLORIZE_STYLE`, which allows users to set a custom `Pygments` theme for use within the oh-my-zsh colorize plugin.
> Add style environment variable to colorize plugin

- plugins/git-auto-fetch/git-auto-fetch.plugin.zsh
Redirect stderr to avoid printing errors to the console when the ssh key is not unlocked.
> Silence Errors

- plugins/git/README.md
#7841 adds support for the `grev` alias for `git revert`, however this is not reflected in the documentation.
> git: Add missing `grev` alias to docs

- README.md
The original suggestion for an unattended install downloads the installation script to a file, then runs that file with the --unattended argument. The install.sh file would be left behind after the suggested command was run.
This change pipes the file from curl into bash while passing the --unattended argument into bash. So, it's a nice one-liner like the default installation script, and it doesn't leave a dangling install.sh script.
> Make unattended installation command a one-liner

- plugins/colored-man-pages/README.md
- plugins/colored-man-pages/colored-man-pages.plugin.zsh
This allows you to use `colored git log --help` for example, to get
colored output.
> Add option to color any help command

- plugins/git-escape-magic/README.md
- plugins/git-escape-magic/git-escape-magic
- plugins/git-escape-magic/git-escape-magic.plugin.zsh
The plugin simply autoloads git-escape-magic which is included here and
copied from https://github.com/knu/zsh-git-escape-magic .
This addresses #1115
> Plugin to magically escape zsh meta-characters in git commands

- plugins/fabric/_fab
Hi @robbyrussell / @mcornella ! 
New major fabric version is using another option to list targets. This commit adds the fallback to the newer version listing in case of errors.
> fabric: support fabric 2+ completion targets

- themes/af-magic.zsh-theme
I've been using the `af-magic` theme for a while now and I love it, just had a couple tweaks inspired by my workflow that I thought would be widely useful.
- Added mercurial support to af-magic, so now the vcs prompt will show in either a git or hg repository
- The virtualenv prompt was white and bumped up against the user@hostname output. Fixed that so its green (which I thought highlighted it more thematically) and has a space before user@hostname
Before virtualenv fix:
After virtualenv fix:
cc @mcornella as last one to touch this theme and @andyfleming as original theme-writer
> Add hg to af-magic, and tweak the virtualenv support a bit

- plugins/autojump/autojump.plugin.zsh
`commands[autojump]` block errs out when autojump is not found, and the rest, which is intended to be used for loading `autojump`, does not get executed.
> autojump: fix autojump loading

- plugins/wd/wd.plugin.zsh
https://github.com/robbyrussell/oh-my-zsh/issues/8117
Save you a click to the failing integration:
```
+main:97> echo 'Adding labels to PR #8116 on robbyrussell/oh-my-zsh:' \''Area: plugin'\''...'
564
Adding labels to PR #8116 on robbyrussell/oh-my-zsh: 'Area: plugin'...
565
+main:98> HTTP_STATUS=+main:98> cat
566
+main:98> HTTP_STATUS=+main:98> curl -w '%{http_code}' -o /proc/self/fd/13 -XPUT -sSL -H 'Authorization: token ***' -H 'Accept: application/vnd.github.v3+json' --data '{"labels":["Area: plugin"]}' https://api.github.com/repos/robbyrussell/oh-my-zsh/issues/8116/labels
567
{
568
"message": "Resource not accessible by integration",
569
"documentation_url": "https://developer.github.com/v3/issues/labels/#replace-all-labels-for-an-issue"
570
}
571
+main:98> HTTP_STATUS=403 
572 …
```
> Wd: point to the correct directory even if installed with antibody

- plugins/debian/debian.plugin.zsh
There appears to be a definition issue for some functions/aliases which
result in the following errors when sourcing .zshrc:
```shell
/home/username/.oh-my-zsh/plugins/debian/debian.plugin.zsh:75: defining function based on alias `abd'
/home/username/.oh-my-zsh/plugins/debian/debian.plugin.zsh:75: parse error near `()'
```
Fixes #7986
> debian: fix bad function definitions

- plugins/gitfast/git-prompt.sh
An error was thrown ( `bash: [: =: unary operator expected` ) when using the `__git_ps1_colorize_gitstring` function outside of the one place it's called (line 512), because the `$detached` variable was not quoted, and was unset.
> Fixed error in git-prompt.sh

- plugins/kube-ps1/README.md
Found this while investigating why the prompt wouldn't show up in my Terminal.
The change in the contributor section wasn't intended; guess this is a Github issue.
> Add a note where to put the `PROMPT=...` line

- themes/robbyrussell.zsh-theme
This restores the original spacing of the prompt changed by https://github.com/robbyrussell/oh-my-zsh/pull/8131:
> Restore prompt spacing in robbyrussell theme

- plugins/gcloud/README.md
- plugins/gcloud/gcloud.plugin.zsh
This PR addresses issue #6205
This adds support for loading completion for the Google Cloud SDK
command line tools. It searches the known paths for an SDK and loads the
provided completion if it is found. Users can supply a custom location
for the SDK by setting `CLOUDSDK_HOME` in their `zshrc` before loading
oh-my-zsh plugins.
Fixes #6205
> Add gcloud plugin

- plugins/gcloud/gcloud.plugin.zsh
Hi @ianchesal, I have added the path for ArchLinux, the SDK is located on `/opt/google-cloud-sdk`.
Cheers.
> New Gcloud plugin search path for ArchLinux

- plugins/react-native/README.md
- plugins/react-native/react-native.plugin.zsh
Added aliases for `iPhone 11`, `11 Pro`, `11 Pro Max`
> react-native: add aliases for newer iPhones

- plugins/bundler/README.md
- plugins/bundler/bundler.plugin.zsh
Exactly what it says on the tin! Rubocop is a great addition to the `bundled_commands` list. This was already done in https://github.com/robbyrussell/oh-my-zsh/pull/3199 but that PR didn't get merged because of an issue with `berks`.
> Add rubocop to bundled_commands

- plugins/n98-magerun/README.md
This adds the README file for n98-magerun plugin as part of #7175.
> add README for n98-magerun

- plugins/rvm/README.md
This adds the README file for `rvm`, Ruby Version Manager, as part of #7175
> Adding README for rvm

- plugins/mysql-macports/README.md
Describes the aliases provided by the script for easy use of mysql on MacOS when installed using MacPorts
References issue #7175
> Added README describing mysql-macports plugin in oh-my-zsh

- plugins/pyenv/README.md
Partially addresses #7175 
Adds a README for the `pyenv` plugin. Plugin already has documentation on the wiki: https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#pyenv
> Add documentation for pyenv plugin

- plugins/git-escape-magic/README.md
I fixed a few typos I noticed in the readme of git-escape-magic
> docs: Fix a few minor typos in plugins/git-escape-magic/README.md

- lib/misc.zsh
fix 'sudo: [cmd]: command not found' error when executing commands like `_ ff somefile -print`
(see http://superuser.com/questions/605417/ddg#605460)
> Fix 'sudo: [cmd]: command not found' when using `_` alias

- plugins/bundler/bundler.plugin.zsh
When another function calls one of the bundler plugin's wrapper functions, the
command to run gets passed as an array instead of a space-separated string. That
works fine when the arguments are expanded alone, like `bundle exec $@`, but
something like `./bin/$@` will expand to something like `./bin/rake
./bin/--silent ./bin/--tasks`, which of course will explode. This was causing a
nasty interaction with the rake-fast plugin, and I'd be shocked if it wasn't
causing other problems.
The fix is to explicitly turn off the `RC_EXPAND_PARAM` option for that
expansion. See
http://zsh.sourceforge.net/Doc/Release/Expansion.html#Parameter-Expansion
for more details.
> Make bundler plugin play nice with functions that call wrapped commands

- plugins/bundler/bundler.plugin.zsh
As [Bundler](https://bundler.io) now allows using `gems.rb` and `gems.locked` filenames instead of `Gemfile` and `Gemfile.lock`, the bundler plugin should try searching not only for `Gemfile` but also for `gems.rb` when it is checking if we are inside a bundled project.
Currently the bundler plugin doesn't prepend bundled commands with `bundle exec` if the project uses `gems.rb` instead of a `Gemfile`.
> Support new naming convention in Bundler

- plugins/rails/rails.plugin.zsh
Apart from `Gemfile`/`Gemfile.lock`, Bundler supports `gems.rb`/`gems.locked` since [version 1.8.0.pre](https://github.com/bundler/bundler/blob/1-8-stable/CHANGELOG.md#180pre-2015-01-26)
This commit tweaks the `_rake_command` to pick up `gems.rb` as well.
> Detect gems.rb in _rake_command

- plugins/swiftpm/README.md
- plugins/swiftpm/_swift
This PR updates the SwiftPM plugin autocomplete information for Swift 5.1.
`_swift` was generated by running `swift package completion-tool generate-zsh-script` with Swift 5.1
> Update swiftpm plugin for Swift 5.1

- plugins/mvn/mvn.plugin.zsh
Add maven autocompletion for [openliberty](http://openliberty.io) web server. It has a maven [plugin](https://mvnrepository.com/artifact/io.openliberty.tools/liberty-maven-plugin). It would be good to have autocompletion for it. 
plugin goals are extracted by
``` 
mvn help:describe -Dplugin=liberty | grep "liberty:" | paste -sd " " - 
``` 
which provides the following result:
```                                                                                                                                                                                                                                          
liberty:clean-server liberty:compile-jsp liberty:configure-arquillian liberty:create-server liberty:debug liberty:debug-server liberty:deploy liberty:dev liberty:display-url …
```
> Add autocompletion for openliberty

- plugins/python/python.plugin.zsh
Deleting `.mypy_cache` did not work, because the directories were not empty.  They contain JSON files instead of compiled byte-code.  (ref PR robbyrussell/oh-my-zsh#7151)
This extends the cleanup by also getting rid of `.pytest_cache` directories.
`-O1` takes care of reordering expressions in order to perform the test based on `-name` first.
> python: Fix and extend pyclean

- plugins/emacs/emacsclient.sh
Piping stdin to emacs alias on MacOS was breaking (--tmpdir is not
supported in BSD flavored mktemp).
Tested in MacOS 10.14 and debian:buster to confirm it still works in
linux.
```
ls -al | e -
ls $TMPDIR/emacs-stdin*
```
@mcornella, I've read these guidelines which ask contributors to copy anyone relevant & found you as the most recent contributor to this script:
https://github.com/robbyrussell/oh-my-zsh/blob/master/CONTRIBUTING.md#you-have-a-solution
> Support BSD mktemp in emacsclient.sh

- plugins/emoji-clock/emoji-clock.plugin.zsh
- plugins/tmux/README.md
- themes/sunrise.zsh-theme
I found a few instances http urls and made them into https urls. Don't worry, I've *tried and tested* the new urls and they all work 😉.
In the obscure case that you go to one of these urls, I just want to let you know, rest assured, that someone spent *half an hour* tracking down http urls that should be https that aren't, and manually converting them to https, *for your protection* (psh, it's not like most browsers these days do it automatically).
> A Few Minor http to https Upgrades

- plugins/tmux/README.md
- plugins/tmux/tmux.extra.conf
- plugins/tmux/tmux.plugin.zsh
Hello,
Tmux developers do not want to comply with XDG standards ([see here](https://github.com/tmux/tmux/issues/142)). With this variable, those who wish to do so will be able to comply with this standard, without the agreement of these developers.
Thank you very much.
> [plugins/tmux] Allow to define a custom configuration path

- plugins/tmux/tmux.extra.conf
- plugins/tmux/tmux.plugin.zsh
1. The tmux command that allows you to include config file should be `source-file` not `source`.
2. since `$_ZSH_TMUX_FIXED_CONFIG` already includes the custom config with `source-file`, it is unnecessary to include the config manually with `tmux_cmd+=(-f "$ZSH_TMUX_CONFIG")`.
> Fix bad tmux config syntax and logical expression error in 86b39cf

- plugins/osx/spotify
When you run `spotify` with an unknown command, then the default case runs in the function, which exits with return code 1 (`exit 1`).
I think this is a not very nice behaviour as it closes my shell session when I mistype a command.
The trivial fix is to just `break`.
> fix(spotify): fix exit on unknown command

- plugins/tmux/tmux.plugin.zsh
#8374 introduced a bug in tmux autostart.
After those changes, `~/.tmux.conf` was not being loaded anymore when setting `ZSH_TMUX_FIXTERM="true"`.
This is due to tmux removing variables that are not present (exported) in the source environment.
> Tmux' man page states that update-environment will remove variables "that do not exist in the source environment [...] as if -r was given to the set-environment command".
>
> -- https://unix.stackexchange.com/a/76256/27284
This can be checked in the terminal with:
```bash
$ echo $ZSH_TMUX_CONFIG                          
/home/diovani/.tmux.conf
$ grep ZSH_TMUX_CONFIG
$ tmux show-environment -g | grep ZSH_TMUX_CONFIG
``` 
This pull request fixed that by exporting again `ZSH_TMUX_CONFIG` before sourcing `tmux.extra.conf` (which will source …
> Fix / Export ZSH_TMUX_CONFIG again to provide to tmux

- plugins/osx/README.md
- plugins/osx/osx.plugin.zsh
Change `itunes` to `music`, as iTunes was renamed to Music in _**macOS** Catalina 10.15_.
Pretty much all functionality is the same, except for changing the name and using AppleScript to communicate with `Music` instead of `iTunes`.
Perhaps both versions should be supported instead?
Fix #8373
> osx: modify itunes function to support Apple Music

- plugins/git-auto-fetch/git-auto-fetch.plugin.zsh
This takes care of not prompting for the ssh-key passphrase that can then not be entered.
This fixes #8381
PS: I also prefixed the git commands with `command` to not run into any issues with aliases or functions.
PPS: @slavaGanzin, it looks like you wrote most of this code, maybe you can take a look at it :smile:
> Stops git-auto-fetch plugin from asking for ssh-key passphrase

- plugins/rails/README.md
The pipe character in the md file was being interpreted by Github, breaking the rendering of the readme. I changed it to be escaped instead.
@mcornella
> Fix rendering issue in README of the rails plugin

- .gitignore
- lib/termsupport.zsh
- plugins/alias-finder/alias-finder.plugin.zsh
- plugins/dirhistory/dirhistory.plugin.zsh
- plugins/dirpersist/dirpersist.plugin.zsh
- plugins/git-prompt/git-prompt.plugin.zsh
- plugins/last-working-dir/last-working-dir.plugin.zsh
- plugins/pipenv/pipenv.plugin.zsh
- plugins/timer/timer.plugin.zsh
- plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
- themes/pygmalion-virtualenv.zsh-theme
- themes/pygmalion.zsh-theme
When zsh config and thus omz is reloaded `preexec_functions` can start to have duplicates. I noticed this first with alias-finder. There are three other places in the codebase where this is done. If this solution is acceptable I would like to encapsulate it in a function that could be used in any plugin and then update the existing places to use this function.
> Use safer append to hook function arrays

- plugins/jenv/jenv.plugin.zsh
This prevents the jenv plugin from messing up the PATH and putting `user/local/bin` back at the front of the PATH, undoing any careful setup done before enabling this plugin.
Fixes #8413
> Only add jenv to PATH if it is not already on it

- plugins/django/django.plugin.zsh
- plugins/jsontools/jsontools.plugin.zsh
- plugins/salt/_salt
- plugins/urltools/urltools.plugin.zsh
Fixes #8400.
Uses [this solution](https://bugs.python.org/issue33053#msg313966) for `python -c` invocations, and [the `-I` option](https://docs.python.org/3/using/cmdline.html#id2) (added in Python 3.4) for module loading.
> Remove current directory from sys.path in python invocations

- README.md
I couldn't make docker-compose completions to work. I wondered if I misconfigured something in ZSH. Turned out, I wasn't the only one with that problem: #4365
I thought that if this is a thing that happens with plugins, it should be mentioned in the README part dealing with enabling plugins, as it would be nice if it had all the info you need to get going.
> Mention FAQ in the README

- plugins/fzf/fzf.plugin.zsh
Debian package install completions file in /usr/share/doc/fzf/examples/completion.zsh.
> fzf: change debian completion file path

- plugins/keychain/keychain.plugin.zsh
Fixes issue #8380 .
What ```keychain``` creates will now match up with what the plugin sources.
> Added hostopt to keychain execution.

- plugins/fzf/fzf.plugin.zsh
Added the fzf base path for freebsd to fzf.plugin.zsh.
@maxbrunet 
@mcornella
> Added FZF base path for freebsd

- plugins/colorize/colorize.plugin.zsh
The option (`pygmentize -f terminal <...>`) lets pygments use terminal color
scheme. Otherwise, it would use its default colors, which might be
unbalanced with that of terminal (e.g. not harmonious with background color of terminal).
> edit colorize plugin: add `-f terminal` option

- plugins/colorize/README.md
- plugins/colorize/colorize.plugin.zsh
I improved the `colorize_via_pygmentize_less` methode to be able to use less options within `cless` and as an side effect, no temporary files have to be created.
> Update colorize to support less options

- plugins/osx/spotify
Running `spotify quit` will quit Spotify then exit the current session with `exit 0`. To fix this replace `exit 0` with `break`.
> osx: fix exit on quit command in spotify function

- plugins/extract/README.md
- plugins/extract/_extract
- plugins/extract/extract.plugin.zsh
Fixes #8383.
Allows decompression of `.tar.lrz` and `.lrz` files, with `lrzuntar` and `lrunzip` respectively.
> extract: add lrz support

- plugins/kubectl/kubectl.plugin.zsh
Add more get resources aliases with `--all-namespaces` option to kubectl.
> Add kubectl all-namespaces aliases for k8s objects

- plugins/extract/README.md
- plugins/extract/_extract
- plugins/extract/extract.plugin.zsh
Support decompression of `.tar.lz4` and `.lz4` files, with `lz4` command.
> extract: add lz4 support

- plugins/pyenv/pyenv.plugin.zsh
Wrapped pyenv plugin in condition, so it will only run if `pyenv` command is not already loaded.
Some software (Poetry for example), may spawn shell multiple times.
In this scenario `.zshrc` will be read again, running all plugins and changing $PATH again.
Seems like other plugins are aware of that, nvm for example.
May be it's not the best solution and plugin should create some environment variable that it has been already used.
> Run pyenv plugin only when necessary

- lib/clipboard.zsh
This pull request enables the clipboard features on the Cygwin-based [MSYS2](https://www.msys2.org/). MSYS2 has the same `/dev/clipboard` device as Cygwin but MSYS2 reports `msys` in `$OSTYPE`.
> Add MSYS2 support to system clipboard integration

- plugins/colored-man-pages/colored-man-pages.plugin.zsh
If `env` is aliased or there is a function with a name conflict, this may cause `man` to fail. Prepending `env` with `command` "bypasses" any aliases or functions. See the issue I ran into in this [StackOverflow answer](https://unix.stackexchange.com/a/562814/297140).
> fix(colored-man-pages): Suppress `env` shell lookup

- plugins/vscode/README.md
- plugins/vscode/vscode.plugin.zsh
The current [VS Code](https://github.com/microsoft/vscode) plugin (at `plugins/vscode`) only invokes the *Stable* release installation, unless the user make changes to `.zshrc` (which are already explained in the README.md of the plugin).
However, some enthusiastic users, including myself, just install the *Insiders* release to follow up on the upcoming features of VS Code. For those users to be able to use this great plugin out of the box, I've modified the script to use `code-insidiers` (instead of `code`), **if the Insiders release was the only available installation** on the host machine.
> Add calling VS Code Insiders

- plugins/tmux/README.md
- plugins/tmux/tmux.plugin.zsh
The standard terminfo for modern tmux is `tmux` or `tmux-256color`. Updating to reflect the change.
> fix: Update tmux plugin to use modern terminfo.

- themes/af-magic.zsh-theme
Fix issue related to #7615, #7747 and #6346
After the update, aws prompt (which should be visible out of the box) disappears when a user uses a theme af-magic, because of fact that plugins are loaded before themes.
This pull request fixes issue with not showing aws prompt in theme af-magic, by appending RPROMPT in theme af-magic instead overwriting.
> Fix showing aws prompt out of the box in af-magic

- plugins/tmux/README.md
- plugins/tmux/tmux.plugin.zsh
Reverts ohmyzsh/ohmyzsh#8582
`tmux-256color` and `tmux` may not be present in some systems, while the previous
`screen` and `screen-256color` values are still supported by tmux and seem to be
included in systems as of this moment.
See https://github.com/ohmyzsh/ohmyzsh/pull/8582#issuecomment-582034866
> Revert "fix: Update tmux plugin to use modern terminfo."

- plugins/systemd/systemd.plugin.zsh
Including the latest `systemctl` commands and making the systemd plugin easier to maintain.
> systemd: refactor and add latest commands

- plugins/systemadmin/systemadmin.plugin.zsh
Inside `pscpu` and `pscpu10` aliases, remove sorting of the head line
> systemadmin plugin: Fix head line sorting

- plugins/dotnet/README.md
- plugins/dotnet/dotnet.plugin.zsh
- Adds a sensible default alias for `dotnet watch` and `dotnet watch run`
I know this could easily go in my own .zshrc, but I think this is sensible to add to the dotnet plugin as a whole.
> [dotnet] Add dotnet watch and dotnet watch run aliases

- plugins/dotenv/dotenv.plugin.zsh
Hi all,
I have encountered an issue on the usage of .dotenv plugin.  Sourcing arbitrary .env files can lead a direct remote code execution on user machines. source doesn't soley read environment variables, it executes the code.
If I download a malicious repo, with a .env file. Then it would be executed with informing me about the execution of the source file.
```bash
$> cat .env             
touch /tmp/hacked
head -n 1 /etc/passwd
```
```bash
$> cd downloaded-dir
root:x:0:0:root:/root:/bin/bash
```
Fix: we can prompt the user before the execution.
```
$> cd x   
zsh: source .env file in the directory [Y/n]?: n
```
> [Security] Update dotenv plugin to prompt before executing env

- plugins/gradle/gradle.plugin.zsh
- Similarly to the mvn plugin
- Without this fix, the shell crashes in some cases
- fixes #8046
> Executing gradle literally, even if an alias exists (gradle plugin)

- plugins/dotenv/README.md
- plugins/dotenv/dotenv.plugin.zsh
Hello,
Now we have a confirmation prompt in dotenv plugins. See https://github.com/ohmyzsh/ohmyzsh/pull/8606 PR.
I find security issue really important, but in my case I don't want to answer the question every time.
I add `ZSH_DOTENV_PROMPT` var, you can set this variable to false in your zshrc if you don't want the confirmation message.
> dotenv: add ZSH_DOTENV_PROMPT config

- plugins/dotnet/README.md
- plugins/dotnet/dotnet.plugin.zsh
- Replaced the custom dotnet plugin with the official one
- Official autocomplete has several more features than the custom one, like autocompletion of nuget packages (try doing `dotnet add package MonoGame.~` and it will autocomplete possible nuget packages)
Link to the official plugin (the code base is MIT License): https://github.com/dotnet/toolset/blob/master/scripts/register-completions.zsh
> Use official dotnet zsh plugin

- themes/agnoster.zsh-theme
- Check if there is a `.bzr` folder in the current directory in parent directories, before attempting to call `bzr`.
- Optimize `bzr` calls: from 3 `bzr status` calls to 1.
- Use a more direct `bzr log` command to get the revision.
- Clean up `prompt_segments` calls.
Fixes #8237.
> agnoster: fix bzr prompt with breezy installed

- oh-my-zsh.sh
- plugins/themes/_theme
- plugins/themes/themes.plugin.zsh
- themes/random.zsh-theme
- Put the random theme logic in a theme of the name random, taking it out of the init script and the theme plugin (closes #2962, closes #3337).
- Change the logic such that themes in `$ZSH_CUSTOM` are also taken into account (fixes #7696, closes #7697).
- Add array variable to blacklist themes from the random pool (`$ZSH_THEME_RANDOM_BLACKLIST`) (fixes #3704, closes #3703).
- In the themes plugin, the `theme` function errors when it can't find the theme provided.
- In the themes plugin, the `lstheme` function uses wildcard expansion and looks in the `$ZSH_CUSTOM` folder as well. Also, the themes are printed in one line with spaces in between, instead of in a column separated by newlines.
- In the themes plugin, the completion function has been placed inside the `.plugin.zsh` file.
Closes …
> Add random theme and consolidate logic from init and themes plugin

- plugins/vscode/README.md
Found a quick solution but I figured it'd be useful in the plugin installation information. This adds a section to the bottom of the documentation for "debugging" and a solution I found. 
- [...]
...
> Adding #debugging section to the documentation for those who might get an error.

- tools/install.sh
- It can be further simplified by also removing the following `mv` command, 
but if `sed` is interrupted, it might exit with an incomplete .zshrc, so I decided
not to do so.
...
> Simplify installer by removing a `cp` command

- plugins/npm/npm.plugin.zsh
Fixes #8665
- Remove `npm_completion` cache file if it exists.
- Use native zsh version of the `_npm_completion` function, which bypasses the `bashcompinit` bug found in #8665.
Needs to be checked whether old versions of npm will broke with this function.
> npm: hardcode completion function and delete cached one

- plugins/zsh-interactive-cd/zsh-interactive-cd.plugin.zsh
- Add vi-mode support for interactive-cd
Used [sudo.plugin.zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/sudo/sudo.plugin.zsh) as a reference.  
However, decided to skip on `vicmd` since it's probably not the intentional use, nor intuitive for the user.
> Add vi-mode support for interactive-cd

- plugins/vagrant/vagrant.plugin.zsh
I found it strange these were missing.  I ran through them all to check that they weren't conflicting with any commands on my system and they were all good.
Almost made `vagrant init` alias to `vi` lol (used `vgi` instead).
Closes #3140
Closes #3312
> vagrant: add common aliases

- plugins/jhbuild/jhbuild.plugin.zsh
This adds "jhsh" as an alias for "jhbuild shell" to the JHBuild plugin.
> jhbuild: Add shell alias

- plugins/copybuffer/copybuffer.plugin.zsh
This PR fixes an issue of `copybuffer` about escape characters. And also fix the comment, since `clipcopy` is not a plugin anymore.
Issue description:
Typing `abc$'\0'def` on the command line, press Ctrl+O to copy the current line. We may get `abc$''def`(on macOS) or `abc$'`(on Ubuntu) in the clipboard.
> Fix an issue with escape characters

- plugins/fancy-ctrl-z/fancy-ctrl-z.plugin.zsh
According to [this helpful analysis](https://github.com/tarruda/zsh-autosuggestions/issues/82#issuecomment-181133379) in tarruda/zsh-autosuggestions#82 plugin fancy-ctrl-z could be made a better citizen when it calls potentially intercepted/overridden widgets. I do not understand the fix fully (scrutiny welcome), but it does fix the issue on my end.
> fancy-ctrl-z: ensure widgets are called with full context

- plugins/kitchen/_kitchen
The kitchen plugin was missing some commands, like login, because the regex was expecting brackets on all lines and yet the `kitchen help` command doesn't return that.
> Change sed regex to capture all possible kitchen commands

- plugins/composer/composer.plugin.zsh
`composer global *` and `composer *` should have the same autocompletion.
> Keep composer autocompletion when using global command

- lib/termsupport.zsh
Apple's Terminal doesn't open a new tab in your current directory if your hostname has UTF-8 characters in it. Percent encoding the host in addition to the path in update_terminalapp_cwd appears to solve this issue.
> Update update_terminalapp_cwd to urlencode the hostname

- plugins/fasd/fasd.plugin.zsh
Using `fasd —-init auto` will first detect terminal and then call fasd again to generate the final initialisation script. Caching that gives a more significant performance boost.
> Cache full fasd initialisation script

- plugins/pass/_pass
- see upstream:
https://git.zx2c4.com/password-store/tree/src/completion/pass.zsh-completion
this fix has been in the upstream zsh completion for a while now. Took my quite a while to find out why completion did not work for me anymore.
However - this is an easy one for you guys I guess.
Thanks,
Sven
> Fix plugins/pass completion to allow for multiple pass repos

- plugins/gradle/gradle.plugin.zsh
It should be `--rerun-tasks`, the original one miss a 's' at the end.
See also: https://docs.gradle.org/current/userguide/command_line_interface.html
> Fix gradle command option name

- plugins/mercurial/README.md
#4969 added `hga` alias to the mercurial plugin, readme should be updated as well
> mercurial plugin: add hga alias to README.md

- plugins/gitignore/gitignore.plugin.zsh
Using the `gi` command provided by the gitignore plugin was causing a `%` to be shown in the terminal at the end of output.
[I opened an issue](https://github.com/joeblau/gitignore.io/issues/442#issuecomment-461357115) on the gitignore.io repository and they suggested adding `-w '\n'` to the `curl` command in order to make `curl` add the new line character at the end. The linked issue explains what my problem was in more detail.
This PR applies the suggested fix.
Further, arguments expansion has been double-quoted for security reasons.
See https://unix.stackexchange.com/a/171347/222786.
> Minor improvements to the gitignore plugin

- plugins/zsh_reload/zsh_reload.plugin.zsh
Title says it all. Related to #7052, had originally planned on proposing this after that one is merged, but maybe this one doesn't need as much scrutiny.
> zsh_reload: Respect `$ZDOTDIR` when searching for `.zshrc`

- plugins/pip/_pip
It's often useful to `pip install` a package that is found locally on the filesystem (e.g. when testing a package before releasing on `pypi`). This allows such files to be options for completion for the `pip install` command.
It would be useful if https://github.com/robbyrussell/oh-my-zsh/pull/6986 is merged first.
> Add local Python package files to completion for pip install

- plugins/minikube/minikube.plugin.zsh
Add caching of completions for **minikube** plugin in the same manner as for **kubectl**.
> [minikube plugin] cache command completions

- plugins/shrink-path/README.md
- plugins/shrink-path/shrink-path.plugin.zsh
This PR adds two additional arguments to `shrink_path`, one to specify the (unconditional) minimum length of each truncated path element and the other to specify the symbol indicating truncation if one occurred. For example, here's the old behaviour:
```
$ shrink_path -t  -l ~/.oh-my-zsh/plugins/shrink-path
~/.o/p/shrink-path
```
Here's the new behaviour, with indication of whether an element was truncated:
```
$ shrink_path -t -3 -e '$' -l ~/.oh-my-zsh/plugins/shrink-path
~/.oh$/plu$/shrink-path
$ shrink_path -t -6 -e '$' -l ~/.oh-my-zsh/plugins/shrink-path
~/.oh-my$/plugins/shrink-path
```
This makes the path much more readable, while still saving a lot of space.
> Added minimum length and ellipsis symbol options for the shrink-path plugin.

- plugins/command-not-found/command-not-found.plugin.zsh
The command-not-found plugin is very slow. (Disabling it for me made my shell start-up time go from 0.75s to 0.15s.) After some searching I found a similar issue was reported and fixed in the prezto zsh framework: 
https://github.com/GuyHarwood/prezto/commit/46ef6091f63ddc052df1ec59cc3573ede0537103
https://github.com/sorin-ionescu/prezto/issues/1451
This PR includes this fix. The fix will source the specific files directly instead of calling the brew commands to get the code. 
The fix makes the plugin a little less robust since homebrew users could decide to install in a different location than suggested. But the speed difference is so big that I think it is worth it to use the method in this PR instead. 
The latter could be fixed by using `brew --repo homebrew/homebrew-command-not-found` …
> Speed up command-not-found plugin

- plugins/sdk/sdk.plugin.zsh
Added support for local versions (prefixed by '+'), so they are filtered out in __listInstallableVersions()_ and they are displayed correctly by __listAllVersion()_
@rahulsom
> sdk: add support for local versions and optimize sed calls

- lib/termsupport.zsh
Fix #7981 by using actual job title instead of `fg` in window title.  Based on part on [this superuser.com discussion](https://superuser.com/questions/497715/keep-tmux-title-from-fg-to-original-jobname).
I'm new to zsh scripting, so please let me know if this could be written any cleaner/shorter.  I found it particularly odd that I needed to check for the no-argument case separately; otherwise, `${${(z)1}[2]}` would return `g` (the second character of `fg`).
> Automatic title: Replace fg with description from jobs

- plugins/arcanist/README.md
- plugins/arcanist/arcanist.plugin.zsh
- adds the alias
- ardcp= 'arc diff --preview'
- adds the functions
- ardu: With this, both, `ardu https://arcanist-url.com/<REVISION>`, and `ardu <REVISION>` work.
- arpa: With this, both, `arpa https://arcanist-url/.com/<REVISION>`, and `arpa <REVISION>` work.
Both accept a parameter which can either be the revision id or the whole URL to the revision.
- updates the README
> [arcanist] Allow for easier copy pasting of URLS via functions and add arc diff --preview

- plugins/aws/aws.plugin.zsh
- Check if the autocompletion installed by AWS CLI v2 is present, and if so use that. Otherwise fall back to the original autocompletion code.
Version 2 of the AWS CLI was released on [February 10](https://aws.amazon.com/blogs/developer/aws-cli-v2-is-now-generally-available/) and comes with its own autocompletion built-in. Per [the README for the v2 branch](https://github.com/aws/aws-cli/blob/v2/README.rst#command-completion), this can be enabled with a wrapper in zsh, or with the `complete` command that ohmyzsh already supports. 
I realise I have a hardcoded path in the check, but both the [Linux](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html) and [macOS](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html) installation instructions …
> Add support for AWS CLI v2 autocompletion

- lib/termsupport.zsh
Currently, if TERM is set to `konsole-256color`, the `title` function doesn't do anything. I've tested locally and adding this in does fix the issue - `konsole` uses the same escape codes as `xterm` and the others.
Konsole defaults to `TERM=xterm-256color` because of issues like this, but using that creates other issues. Mainly, console applications like [kakoune](https://github.com/mawww/kakoune) assume incorrect terminal facts, and create inaccurate colors.
Since this is fairly small, and shouldn't have any adverse side affects, I hope it's a reasonable change. I'm not sure how widespread the use of `konsole-256term` is since konsole itself doesn't default to it, but I don't believe it would actively hurt anything but maintainability to include it.
Let me know if there's anything else I …
> Support konsole-256color TERM in title function

- plugins/aws/aws.plugin.zsh
- Add a new aws completer path which works on nixos
...
> fix aws completer path on nixos

- plugins/archlinux/README.md
- plugins/archlinux/archlinux.plugin.zsh
- Fix pacfiles alias not working
> archlinux: fix wrong parameters in pacfiles alias

- plugins/z/README.md
- Add markdown readme for the z plugin
- The new readme enables quick understanding of z and its installation in zsh
- I did not replace the original README file that contains the complete description from https://github.com/rupa/z. I'm only linking to it from the new readme. This way, we can continue to easily pull updates from https://github.com/rupa/z to the original README.
- I [verified](https://github.com/cbachhuber/ohmyzsh/tree/update-z-readme/plugins/z) that GitHub gives higher priority to rendering `README.md` over `README`.
> Add markdown Readme to z

- plugins/man/man.plugin.zsh
- Changed man plugin, so it removes all the arguments form the previous command and prepends man to the command itself without arguments
> man: Removed everything but the command itself before prepending man

- plugins/sublime/sublime.plugin.zsh
- Adds path to sublime binary installed when using `snap`:
- /snap/bin/subl
- /snap/bin/sublime-text.subl
Fixes #8686
> update path for snapd /snap/bin/* which is used by Linux systems

- plugins/direnv/direnv.plugin.zsh
- Change direnv plugin to not assume location of direnv, which is not portable across platforms (e.g. Ubuntu)
> Change direnv not assume /usr/local/bin

- plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
- On Debian 10 virtualenvwrapper script is installed in directory $HOME/.local/bin/virtualenvwrapper.sh, after installing oh-my-zsh and enabling virtualenvwrapper plugin I've got the following error:
"[oh-my-zsh] virtualenvwrapper plugin: Cannot find virtualenvwrapper.sh.
Please install with `pip install virtualenvwrapper`
[oh-my-zsh] virtualenvwrapper plugin: shell function 'workon' not defined.
Please check" 
I added the path  $HOME/.local/bin/virtualenvwrapper.sh on virtualenvwrapper.plugin.zsh  because it was not included in #8521
> [virtualenvwrapper plugin]: Adding $HOME/.local/bin/virtualenvwrapper.sh

- plugins/dotenv/README.md
- plugins/dotenv/dotenv.plugin.zsh
Hi! I must admit that I got really annoyed when dotenv plugin started asking me over and over whether I want to load .env files. On the other hand I understand that this is crucial to my security and I am really thankful to the one who introduced that prompt feature. To make it more convenient I made a small improvement that allows you to accept .env at given path once. I think it is a good compromise between convenience and security.
With oss love,
Jędrzej
- New feature for **dotenv** plugin: you can ask plugin to accept given .env file once
- When prompted if you want to load .env file, you can now type 'a' which will add absolute path to a list of accepted .env files
- Once path is added to the list, the plugin will not ask again if you want to load this particular .env
- The list is …
> dotenv plugin: agree once improvement

- plugins/systemd/systemd.plugin.zsh
- Fixes a bug where the prompt string has an unnecessary newline which caused issues in the prompt creation
...
> Fix systemd prompt appearance

- plugins/colored-man-pages/README.md
- plugins/colored-man-pages/colored-man-pages.plugin.zsh
- Adds hooks for `dman` and `debman` similar to existing hook of `man` to colorize its output using `less`
- README of the plugin also states that `dman` and `debman` are hooked.
`dman` and `debman` are tools from the package `debian-goodies` for
Debian systems (see https://packages.debian.org/stable/debian-goodies).
They can display man pages from manpages.debian.org or local debian
packages respectively.
I thought about adding a new plugin for these but then code would either
be duplicated or a dependency to this plugin would be there and as I
think non Debian users will not be disturbed by these additions this
solution should be fine. If you see it otherwise, please let me know.
> colorized-man-pages: Added hooks for commands dman and debman

- plugins/gnu-utils/gnu-utils.plugin.zsh
GNU "make" is installed as "gmake" by homebrew.
append make to cmds in gnu-utils plugin.
> gnu-utils: append make to cmds

- plugins/jsontools/README.md
- Update README - is_json usage for validation
- Issue #8858: Usage for is_json wrongly mentioned pretty print
> jsontools: correct usage for is_json

- plugins/aws/aws.plugin.zsh
After the upgrade to AWS CLI v2, if the default client side pager is set
the aws_change_access_key stopped working.
Fixes #8815
The default pager is set before any call to the aws cli:
```zsh
aws iam create-access-key
AWS_PAGER="" aws iam create-access-key
```
This prevents the aws cli to paginate any request, regardless of the default pager of the user.
> aws: fix aws_change_access_key function with awscli v2

- plugins/sdk/sdk.plugin.zsh
- Complete commands from `__sdk_` function names instead of from static array
- Don't display command aliases in command completion list
- Support `l` alias for `list`
- Only list installed candidates for `sdk upgrade`, `current`, `use`, `default` & `uninstall`
- Only list installed versions for `sdk use`
- Properly parse version completions
- Parse versions using zsh expansions instead of using sed
- Support `local_path` argument for `sdk install`
- Display context appropriate header above completions
- Added `version` completion for `sdk flush`
- Inlined helper methods
- Formatted code
- Added zsh shebang
@rahulsom
@mcornella
> Improve sdk completion

- oh-my-zsh.sh
The current algorithm is very simple:
- Get the OMZ revision and fpath
- Append it to the zcompdump cache file when creating it
- On subsequent loads, check if it revision and fpath are the same as last time
Fixes #7642 
Documentation: update [FAQ](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-have-enabled-a-completion-plugin-but-the-completion-doesnt-work) when this PR is merged.
> core: refresh zcompdump cache file in init script

- plugins/rustup/README.md
- plugins/rustup/_rustup
- Adds plugin/rustup/_rustup from the output of 'rustup completions zsh' with rustup 1.21.1 (7832b2ebe 2019-12-20) and also adds a simple README.md.
- Since the code was generated by rustup, I am not sure how the criteria about the code style and the MIT-compatible license apply. Please let me know.
- This PR is meant to answer #8072 
- This PR is similar to #5529, but has the output from the latest rustup version and has a nice and README.md. 
- In #5529, the idea of integrating the generation of the plugin with the standard oh-my-zsh update pipeline was brought up. The idea does sound interesting, but I propose it be done in a later PR once this initial one has been merged.
Closes #5529
Fixes #8072
> Add plugin for rustup completion

- tools/upgrade.sh
The bug was introduced in https://github.com/ohmyzsh/ohmyzsh/commit/27f4e079329dabf8e7008b98c8bddf443116eb54#diff-6d2fa595805de6f141a64f905f4db641. This commit has renamed `NORMAL` to `RESET` everywhere except one place.
> Fix a bug in upgrade.sh where it fails to reset terminal color

- plugins/frontend-search/README.md
- plugins/frontend-search/_frontend-search.sh
- plugins/frontend-search/frontend-search.plugin.zsh
- Adding `packagephobia` integration into `frontend-search` plugin.
More details in https://packagephobia.now.sh/
Example of search:
https://packagephobia.now.sh/result?p=perf-marks@1.8.0
cc/ @mcornella
> feat(frontend-search): adding packagephobia

- lib/cli.zsh
- lib/diagnostics.zsh
- oh-my-zsh.sh
builtin cd to override user alias and functions in system OMZ functions. Important when capturing output and writing to zcompdump
~/oh-my-zsh/oh-my-zsh.sh: 66 #omz revision: $(builtin cd -q "$ZSH"; git rev-parse HEAD 2>/dev/null)## Other comments:
tested
> builtin cd overrides user aliases and functions

- plugins/pipenv/pipenv.plugin.zsh
- `Pipfile` check from `-a` to `-f`.
This fixes a bug when `Pipfile` is a directory which cuases `pipenv` to
crash.
To reproduce it:
* Create a directory `Pipfile`.
* Enter the directory.
You are going to see an output similar to this:
```
Traceback (most recent call last):
File "/Users/rmax/.pyenv/versions/3.8.2/bin/pipenv", line 10, in <module>
sys.exit(cli())
...
File "/Users/rmax/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/project.py", line 677, in touch_pipfile
with open("Pipfile", "a"):
IsADirectoryError: [Errno 21] Is a directory: 'Pipfile'
```
The current code does a `-a` check which is true for any file type,
including directories. A better way is to use `-f` to ensure `Pipfile`
is a regular file.
> pipenv: fix error when Pipfile is not a file

- lib/history.zsh
The doc says it is useless to have both:
>This option both imports new commands from the history file, and also causes your typed commands to be appended to the history file (the latter is like specifying INC_APPEND_HISTORY, which should be turned off if this option is in effect)
http://zsh.sourceforge.net/Doc/Release/Options.html
> core: remove inc_append_history option

- plugins/git/README.md
- plugins/git/git.plugin.zsh
These are common operations when applying patches from mbox files on
mailing list based projects like U-Boot or the Linux
Kernel.
> git: add convenience aliases for `git apply` and `git am`

- plugins/direnv/direnv.plugin.zsh
Instead of printing that the direnv hook failed for every command
prompt, this fix changes the plugin to only load the hook if the
'direnv' command is available on the system.
- Extend the direnv plugin with a simple `if` statement to check if the `direnv` command is installed on the system.
- Testing performed: touch testing on two systems (w/ and w/o direnv)
> direnv: check if direnv is installed

- templates/zshrc.zsh-template
~The code follows the code style guide detailed in the wiki.~
~The code is efficient, to the best of my ability, and does not waste computer resources.~
~The code is stable and I have tested it myself, to the best of my abilities.~
Replace ` ~/.oh-my-zsh` with $ZSH and ` ~/.oh-my-zsh/custom` with $ZSH_CUSTOM
> Use oh-my-zsh path variables in zshrc.zsh-template

- plugins/vagrant/_vagrant
This fixes the `vagrant box` autocomplete
- Update regex to parse the correct list.
> vagrant: fix vagrant box autocomplete

- plugins/archlinux/archlinux.plugin.zsh
- Fix pacweb not working in non-English localized environment
Make sure the result returned by pacman is in English
> archlinux: fix pacweb with non-English locales

- plugins/git/README.md
- plugins/git/git.plugin.zsh
- added git alias / function that runs git diff, but doesn't show package-lock.json and *.lock files in diff view
Fixes #8923
> git: add alias for git diff excluding lock files

- plugins/asdf/asdf.plugin.zsh
Asdf completions are broken if the plugin is loaded after the `$ASDF_DIR/asdf.sh` application is loaded (asdf.sh exports ASDF_DIR) or if the ASDF_DIR variable is exported at all (manually for example) before the plugin is loaded.
> asdf: fix completions if ASDF_DIR is already exported

- plugins/terraform/_terraform
- Add `terraform fmt -recursive` flag autocompletion 
The flag description is taken verbatim from the `terraform fmt -help` command:
```
$ terraform fmt --help
Usage: terraform fmt [options] [DIR]
[…]
Options:
[…]
-recursive     Also process files in subdirectories. By default, only the
given directory (or current directory) is processed.
```
> terraform: add fmt -recursive flag autocompletion

- lib/history.zsh
- Only set `HISTSIZE` and `SAVEHIST` values if a bigger one is not already set
oh-my-zsh Changes the HISTSIZE and SAVEHIST values to fixed sizes,
however if a bigger value is set in ~/.zshrc, it will override it,
potentially causing the user history to be deleted.
So, only set these values if no other is set and if it is lower than the
default ones.
> lib: don't override bigger HISTSIZE and SAVEHIST values

- oh-my-zsh.sh
After #8939, the update process is definitely sure to be run just once, and a user cancellation is local to only the update process. This means that we can run it inside the current zsh session without fear of messing with it. This PR removes the external zsh call and just runs it inside the current one with a `source` call.
Fixes #5162
Fixes #6732
> init: run update check in the same zsh process

- plugins/osx/README.md
- plugins/osx/_security
- plugins/osx/music
- plugins/osx/osx.plugin.zsh
- osx: fix syntax and indentation
- osx: move music/itunes function to its own file
- osx: add completion for music function (#8578)
- osx: fix a few errors in music function
- osx: add completion for macOS security command (#2042)
- osx: add cdx function to cd to active Xcode project directory (#5807)
- osx: clarify README commands
- osx: add function to restart Bluetooth daemon (#6290)
- osx: fix pfd if frontmost Finder is not in the same desktop (#7398)
Fixes #8578
Closes #2042
Closes #5807
Closes #6290
Closes #7398
Remaining issues regarding the osx plugin: https://github.com/ohmyzsh/ohmyzsh/issues/8968 https://github.com/ohmyzsh/ohmyzsh/pull/8762
> osx: refactor plugin and add a few features

- plugins/archlinux/archlinux.plugin.zsh
…repos
- Fix so that `pacweb` doesn't produce an invalid URL when package is available in multiple repos.
Tested with rsync and works as intended.
Previously: <https://www.archlinux.org/packages/testing%0Aextra/x86_64%0Ax86_64/rsync/>
This PR: <https://www.archlinux.org/packages/testing/x86_64/rsync/>
> archlinux: fix pacweb breaking when multiple packages found

- tools/check_for_upgrade.sh
- When prompt to update ohmyzsh, the input accepted is: yY and enter to proceed and nN to deny, if an invalid input is given the user gets prompted again
It fixes #9057
> update: only update on a valid affirmative input

- lib/git.zsh
- lib/termsupport.zsh
DISABLE_UNTRACKED_FILES_DIRTY, DISABLE_AUTO_TITLE, GIT_STATUS_IGNORE_SUBMODULES are not set
Handle these variables not being set with conditional access.
If the user has set -u option to report attempts to use undeclared / unassigned variable, accessing the variables needs to be conditional.
> Handle unset variables in various parts of the codebase

- plugins/gradle/_gradle
Fixes #8730
- Adds `--console plain` to `gradle tasks` invocation to turn off colored output
> gradle: force `--console plain` for tasks cache generation

- tools/install.sh
Changing 'your' to 'you' in install.sh
- Changed the 'Before **your** scream Oh My Zsh!' in install.sh to 'Before **you** scream Oh My Zsh!'
😉
> install: fix typo

- themes/agnoster.zsh-theme
`git rev-parse --is-inside-work-tree` does not have a different exit
code when not within a work tree; the difference is in the output,
either "true" when in a work tree, or "false" when not.
The if was modified similarly to the check for the hide-status config,
which also parses command output rather than exit code.
> agnoster: fix git working tree check

- templates/zshrc.zsh-template
Other places in the template use `="true"` style, while solely this line uses `=true`.
Not much of a big deal, since both styles accomplish what we want.
But I felt consistency is better looking than non-consistency.
> Edit for better consistency in template

- plugins/sudo/sudo.plugin.zsh
- `[[ -z $BUFFER ]] && zle up-history` -> `[[ -z $BUFFER ]] && LBUFFER="$(fc -ln -1)"`
In the previous version, if you clear the buffer and press esc-esc again, you will get the history before last. And then the third to last, the fourth to last... It is fixed now.
- `[[ $BUFFER == sudo\ * ]]` -> `[[ -n $EDITOR && $BUFFER == $EDITOR\ * ]]`
In the previous version, if you accidentally add a space in the font of the buffer and you haven't specified `$EDITOR`, the `sudoedit` will be added. It is fixed now.
- `...`
In the previous version, if you put your cursor within `sudo` `sudoedit` `$EDITOR`, you will get a wrong result. It is fixed now.
Here is a more simple version:
```bash
sudo-command-line() {
[[ -z $BUFFER ]] && LBUFFER="$(fc -ln -1)"
if [[ -n $EDITOR && $BUFFER == $EDITOR\ * ]]; …
```
> Plugin: Sudo - Make the behavior more in line with expectations

- plugins/aws/aws.plugin.zsh
fixes #9060 by matching a `@` in the AWS profile name.
- fixed #9060 by matching a `@` in the AWS profile name.
> aws: allow @ in AWS profiles

- plugins/dotenv/README.md
- plugins/dotenv/dotenv.plugin.zsh
- change prompt from `Source it? ([Y]es/[n]o/[a]lways)` to  `Source it? ([Y]es/[n]o/[a]lways/n[e]ver)` (I couldn't find a synonym to never which doesn't start with **n**, suggestions welcome)
- add parallel to `ZSH_DOTENV_ALLOWED_LIST`: `ZSH_DOTENV_DISALLOWED_LIST`
- write disallowed dirs to that file and skip sourcing if directory is in that file
- update README
---
fixes #9101
> dotenv: add never option to confirmation prompt

- tools/check_for_upgrade.sh
The newly added trap, in systems where `rm` is aliased to `rm="rm -v"`,
shows a message stating that "update.lock" has been removed each time `zsh` is called.
- Suppressed the trap `rm` with directing the output to `/dev/null`. (prevents extra alerts in more verbose systems)
Fixes #9109
> Suppress the problematic trap output in check_for_upgrade.sh

- plugins/httpie/README.md
- plugins/httpie/httpie.plugin.zsh
Added an alias creating https, which uses httpie with https.
https://httpie.org/doc#custom-default-scheme
> httpie: add alias for https

- plugins/kubectl/README.md
- plugins/kubectl/kubectl.plugin.zsh
This PR adds new alias to list all pods within a namespace passed as parameter:
```
kgpn <namespace>
```
Examples:
```
kgpn kube-system
kpgn production -l tier=frontend
```
> kubectl: add alias to list pods by namespace

- plugins/battery/README.md
- Update read from battery plugin. Adds information for installing the acpi tool to display the battery percentage
> battery: add acpi requirement to README
