- plugins/django/django.plugin.zsh
activate django plugin on command "django-admin".
> activate django plugin on command "django-admin"

- plugins/vi-mode/vi-mode.plugin.zsh
Fixes https://github.com/robbyrussell/oh-my-zsh/issues/3537
> Added trapwinch to vi-mode plugin.

- tools/install.sh
> Save ZSH path in newly created .zshrc

- plugins/web-search/web-search.plugin.zsh
----
This pull request implements simpler logic that enables adding more search engines in the future, while mantaining ease-of-use to define aliases.
It also implements the following very solicited features:
- Silence nohup:
Fix #1970, fix #3097, fix #3183, fix #3218, fix #3302, fix #3441.
- Add Yandex support:
Fix #1845, fix #3119.
- Add Cygwin support to open command:
Fix #2831, fix #3103.
In total, **10 issues** can be closed with this PR.
Feedback is greatly appreciated.
> Refactor and improve web-search plugin

- plugins/ember-cli/README.md
- plugins/ember-cli/ember-cli.plugin.zsh
This PR adds plugin for ember-cli and adds required aliases for the commands respectively. 
Feedback would be appreciated. :shipit:
> Plugin for Ember-cli

- plugins/chucknorris/.gitignore
- plugins/chucknorris/LICENSE
- plugins/chucknorris/chucknorris.plugin.zsh
- plugins/chucknorris/fortunes/chucknorris
Adds Chuck Norris fortune file from http://www.k-lug.org/~kessler/projects.html. Depends on fortune (and cowsay if using `chuck_cow`) being installed (available via homebrew, apt, ...). Perfectly suitable as MOTD :)
```
Last login: Fri Jan 30 23:12:26 on ttys001
________________________________________
( Chuck Norris' pulse is measured on the )
( richter scale.                         )
----------------------------------------
o   ^__^
o  (oo)\_______
(__)\       )\/\
||----w |
||     ||
23:12:30 ~ 
$ chuck
Chuck Norris has a deep and abiding respect for human life... unless it gets in his way.
23:12:35 ~ 
$ chuck_cow
______________________________________
( When Chuck Norris plays Monopoly, it )
( affects the actual world economy.    )
--------------------------------------
o   ^__^
o …
```
> Chuck Norris fortune

- plugins/vi-mode/vi-mode.plugin.zsh
Vi-mode plugin now allow useful standard behaviors:
- ctrl-p, ctrl-n:  explore history
- ctrl-h, ctrl-?, ctrl-w: char, word deletion
> Plugins: vi-mode

- plugins/mix/_mix
Added the 'mix local.hex' command to plugin completions for mix
> Added the 'mix local.hex' command to plugin completions for mix

- plugins/grunt/grunt.plugin.zsh
https://github.com/gruntjs/grunt
courtesy of @yonchu: https://github.com/yonchu/grunt-zsh-completion
> grunt completion

- plugins/wd/README.md
- plugins/wd/_wd.sh
- plugins/wd/wd.sh
Added features:
* `list` now lists all warp points
* `ls` lists files in given warp point
* `path` given path of given warp point
> [wd] Update to v0.4.1

- plugins/symfony2/symfony2.plugin.zsh
Added alias for server:run command with verbose debug
> added server:run alias

- lib/grep.zsh
> Test if --color=auto is a valid option for grep

- plugins/git/git.plugin.zsh
> Fix gmt compdef

- plugins/carton/carton.plugin.zsh
- plugins/cask/cask.plugin.zsh
https://github.com/rejeep/cask.el
(formerly carton)
> cask completion plugin

- plugins/rails/rails.plugin.zsh
This adds `rdms` alias to Rails plugin.
> Add rdms alias to rails plugin

- plugins/golang/golang.plugin.zsh
go 1.4 added new tool command called `generate`
> go plugin upgrade for version 1.4

- plugins/httpie/httpie.plugin.zsh
HTTPie is a command line HTTP client, a user-friendly cURL replacement. 
http://httpie.org
> Add completion for httpie

- plugins/nmap/README.md
- plugins/nmap/nmap.plugin.zsh
Just some aliases that could be useful for people frequently scanning with nmap.
Most of these are easy to type while autocompleting with TAB.
I'm not sure if this is the proper way to contribute this to the repo.
If you have any suggestions do let me know.
> Add nmap plugin with some aliases for scan modes

- plugins/sublime/README.md
Added a _README.md_ file for the __Sublime__ plugin.
> Add README.md file

- plugins/django/django.plugin.zsh
Update Django plugin for Django 1.7.6 according to its new subcommands and refactor.
> Update django.plugin.zsh for Django 1.7.6

- plugins/cakephp3/cakephp3.plugin.zsh
This adds auto-completion for the [CakePHP 3](http://cakephp.org) framework. Once merged, I will update the plugins wiki page to reflect the changes.
Thanks for considering (and hopefully merging)!
/cc @markstory @lorenzo
> Add CakePHP3 plugin

- plugins/zeus/README.md
> Add installation instructions to README

- plugins/brew/brew.plugin.zsh
Add two new aliases for:
* update and list outdated packages
* upgrade the outdated packages and cleanup homebrew
> Create new aliases for homebrew plugin

- plugins/gitfast/_git
- plugins/gitfast/git-completion.bash
- plugins/gitfast/git-prompt.sh
Lots of changes from upstream.
> gitfast: update to upstream v1.9.2

- plugins/docker/_docker
Remove Docker insert, more run options, and add create.
> Docker run and create options

- plugins/docker-compose/README.md
- plugins/docker-compose/docker-compose.plugin.zsh
Using docker compose daily, and this is a feature that is needed.
Feature https://github.com/robbyrussell/oh-my-zsh/issues/3557  was not prorgressing.
> Added aliases for docker compose

- lib/completion.zsh
- templates/zshrc.zsh-template
Replaces #3826
What kind of testing is needed?
> Add hyphen insensitivity

- plugins/common-aliases/common-aliases.plugin.zsh
As not every user will use the vim.
>Q: How to generate a random string in vi?
>A: Put a user in front of it and ask them to exit
> Use $EDITOR

- plugins/bundler/bundler.plugin.zsh
Added alias of bundle clean.
I want to use this alias.
> Add alias of bundle clean

- plugins/jira/jira.plugin.zsh
Fixes a syntax error due to an apparent badly-resolved merge conflict between #2898 and #2955.
Fixes #4027 
Closes #4089
> Fix jira plugin syntax error due to merge conflict

- plugins/n98-magerun/n98-magerun.plugin.zsh
This is a new completion plugin for the n98-magerun tool for Magento.  https://github.com/netz98/n98-magerun
> New plugin for the n98-magerun Magento command line tool

- themes/candy-kingdom.zsh-theme
- themes/fino-time.zsh-theme
- themes/fino.zsh-theme
> Fix little typo that makes the statement useless.

- plugins/terraform/README.md
- plugins/terraform/_terraform
Recreating https://github.com/robbyrussell/oh-my-zsh/pull/3499
CC @pmoust @robbyrussell @dlsniper
> Add terraform completion

- plugins/frontend-search/README.md
- plugins/frontend-search/_frontend-search.sh
- plugins/frontend-search/frontend-search.plugin.zsh
Add new website in search: npmjs
> Frontend-search: add search in npm website

- plugins/git-flow/git-flow.plugin.zsh
> improved alias conflict between git flow & git fetch

- tools/upgrade.sh
The Twitter link didn't use https
> Use https instead of http

- plugins/rvm/rvm.plugin.zsh
Repeating the `-E` flag won't work with GNU sed.
> rvm plugin: Fix `gems` to work on Linux machine

- plugins/emoji/emoji-char-definitions.zsh
- plugins/emoji/update_emoji.pl
`==` in Perl if for numeric comparison, using it make the update failed to generate data.
> Emoji plugin - Fix wrong string comparison

- plugins/man/man.zsh
Inspired by sudo. But we have man-preview!
> Add 'man' plugin.

- plugins/spring/README.md
- plugins/spring/_spring
oh-my-zsh plugin for Spring Boot plugin. http://projects.spring.io/spring-boot/
> Spring Boot Plugin

- plugins/ubuntu/ubuntu.plugin.zsh
Since #3902 lacks the auto-completion I made a PR for this as well.
Also fixes some typos.
> Adds agar = apt-get autoremove

- plugins/thefuck/thefuck.plugin.zsh
> thefuck-alias -> thefuck --alias

- plugins/vundle/vundle.plugin.zsh
> Plugin vundle: update link

- plugins/git-extras/git-extras.plugin.zsh
The git-extras plugin has not been updated for long, so I do it to catch up with the development of git-extras
> update git-extras plugin

- plugins/rails/rails.plugin.zsh
http://guides.rubyonrails.org/testing.html#running-tests
> rails rake test

- themes/dogenpunk.zsh-theme
I removed the incorrect Devanagari conjunct symbol at the end of Om. The dash below the letter indicates that it should join the previous letter, which is not needed in spelling Om.
> Devanagari Om fixed in dogenpunk theme

- plugins/taskwarrior/README.md
- plugins/taskwarrior/_task
- plugins/taskwarrior/taskwarrior.plugin.zsh
- Updates to latest version of completion ([July 26th, 2015](https://git.tasktools.org/projects/TM/repos/task/commits/3158883dc4d251))
- Moves documentation into separate README file.
Closes #3796.
> Fix taskwarrior plugin

- themes/emotty.zsh-theme
:warning: **This commit requires the changes from #4370** :warning:
> Add emotty theme

- themes/amuse.zsh-theme
This pull request integrate rvm to the amuse theme.
> Display rvm ruby version

- plugins/stack/stack.plugin.zsh
Hey @robbyrussell,
This one is based on `cabal` plugin. 
Used the default list of available [stack](https://github.com/commercialhaskell/stack) commands:
```
Available commands:
build                    Build the project(s) in this directory/configuration
install                  Build executables and install to a user path
test                     Build and test the project(s) in this
directory/configuration
bench                    Build and benchmark the project(s) in this
directory/configuration
haddock                  Generate haddocks for the project(s) in this
directory/configuration
new                      Create a brand new project
init                     Initialize a stack project based on one or more cabal
packages
solver                   Use a dependency solver to try and …
```
> Add Haskell Stack commands list

- tools/install.sh
- tools/upgrade.sh
> Do not fail if tput is not available

- plugins/sublime/sublime.plugin.zsh
Though there may be additional common paths, this is a good start.
> Adds Cygwin support to Sublime

- plugins/osx/osx.plugin.zsh
Added function to display the song you're currently listening to in iTunes
- itunes playing
osx.plugin.zsh
> Display song currently playing in iTunes

- plugins/sublime/sublime.plugin.zsh
@maxd is right! Copy/paste error initially.
https://github.com/robbyrussell/oh-my-zsh/pull/4396#commitcomment-13458853
Fixes #4414
> Fixes Sublime Cygwin support

- plugins/git-hubflow/git-hubflow.plugin.zsh
Add some aliases to match what the git and git-flow projects do.
> Add Git Hubflow aliases

- README.markdown
Change http://ohmyz.sh link to use proper markdown syntax
> Fix ohmyz.sh link

- plugins/systemd/systemd.plugin.zsh
I've heard many people requesting systemd to add this functionality. It's very handy under Arch.
> Added --now systemd aliases

- plugins/git/git.plugin.zsh
Added an alias for upstream.
git plugin does not have that so far, so I'd like to use it.
> Add an alias for upstream

- lib/diagnostics.zsh
Fixes #4436
Reference:
https://github.com/zsh-users/zsh/blob/zsh-5.1.1/NEWS#L20-L32
> diagnostics: fix for reserved-word changes in zsh 5.1

- plugins/gradle/gradle.plugin.zsh
Minor upgrade for switch commands to Gradle 2.7.
> Gradle Plugin: Update Gradle Commands

- plugins/pyenv/pyenv.plugin.zsh
Check pyenv-virtualenv can eval before use it
> Fixd bug for pyenv plugin

- plugins/chucknorris/fortunes/chucknorris
few quotes were missing the '%' line delimiters,
so some of the quotes were appearing at once merged together
> chucknorris: add missing line/quote delimiters

- tools/check_for_upgrade.sh
Hi,
Noticed #4504 and thought I'd throw together a quick PR for it.
Fixes #4504
Closes #4506
> Check for git before trying to upgrade OMZ

- plugins/wp-cli/README.md
- plugins/wp-cli/wp-cli.plugin.zsh
Two similar aliases which were causing issues.
> Removed Similar Aliases

- plugins/wd/wd.sh
Some fixes and minor changes. See [release](https://github.com/mfaerevaag/wd/releases/tag/v0.4.2).
> [wd] update minor version (v0.4.2)

- plugins/z/README
- plugins/z/z.1
- plugins/z/z.sh
There is an old PR at #3248
That's why I'm creating a new one
Version: https://github.com/rupa/z/commit/5dc2a863ccdcefb28aaf87cc99c31c6619158ed4
Closes #3248.
> Update z version to 5dc2a86

- plugins/zsh-navigation-tools/.config/znt/README.txt
- plugins/zsh-navigation-tools/.config/znt/n-aliases.conf
- plugins/zsh-navigation-tools/.config/znt/n-cd.conf
- plugins/zsh-navigation-tools/.config/znt/n-env.conf
- plugins/zsh-navigation-tools/.config/znt/n-functions.conf
- plugins/zsh-navigation-tools/.config/znt/n-history.conf
- plugins/zsh-navigation-tools/.config/znt/n-kill.conf
- plugins/zsh-navigation-tools/.config/znt/n-list.conf
- plugins/zsh-navigation-tools/.config/znt/n-options.conf
- plugins/zsh-navigation-tools/.config/znt/n-panelize.conf
- plugins/zsh-navigation-tools/LICENSE
- plugins/zsh-navigation-tools/README.txt
- plugins/zsh-navigation-tools/n-aliases
- plugins/zsh-navigation-tools/n-cd
- plugins/zsh-navigation-tools/n-env
- plugins/zsh-navigation-tools/n-functions
- plugins/zsh-navigation-tools/n-history
- plugins/zsh-navigation-tools/n-kill
- plugins/zsh-navigation-tools/n-list
- plugins/zsh-navigation-tools/n-list-draw
- plugins/zsh-navigation-tools/n-list-input
- plugins/zsh-navigation-tools/n-options
- plugins/zsh-navigation-tools/n-panelize
- plugins/zsh-navigation-tools/znt-cd-widget
- plugins/zsh-navigation-tools/znt-history-widget
- plugins/zsh-navigation-tools/znt-kill-widget
- plugins/zsh-navigation-tools/znt-usetty-wrapper
- plugins/zsh-navigation-tools/zsh-navigation-tools.plugin.zsh
Hello,
I've written these:
https://github.com/psprint/zsh-navigation-tools
There are screenshots and videos about the tools on the page. They can work as OMZ plugin, can you please include them. They are very thoroughly tested and optimized.
Best regards,
Sebastian Gniazdowski
> Zsh Navigation Tools plugin

- plugins/zsh-navigation-tools/README.md
- plugins/zsh-navigation-tools/n-list
Small problem with vim modeline
> znt: updated README.md, twice as fast searching

- plugins/extract/extract.plugin.zsh
Add suport for `.xpi` and `.apk` files in extract plugin.
> Recognize Firefox addon and Android packages.

- plugins/branch/README.md
- plugins/branch/branch.plugin.zsh
This simply displays current Git or Mercurial branch.
The idea came when I first installed Mercurial plugin and it was a little slow on my Mac Air. 
Now it's simple and fast (it was annoying me).
I'm creating branch plugin because this one simply displays repository branch and **nothing else**.
> Add branch plugin

- plugins/gulp/gulp.plugin.zsh
Fetch Gulp tasks lists in a better way through 
```bash
gulp --tasks-simple
```
> Fetch Gulp tasks list in a better way

- plugins/github/_hub
This uses the version at commit 35c76bf (2015-12-08)
https://github.com/github/hub/commit/35c76bf91dc3d699173599464b9b41cb877ee440
Fixes #4670
> Add hub's completion file

- MIT-LICENSE.txt
> A Happy New Year!

- plugins/vault/README.md
- plugins/vault/_vault
> Vault basic autocompletion

- plugins/brew/_brew
Updated _brew to match latest in https://github.com/Homebrew/homebrew/blob/master/Library/Contributions/brew_zsh_completion.zsh
> Update _brew to match latest

- plugins/mvn/mvn.plugin.zsh
> fix terminal color pollution

- plugins/npm/npm.plugin.zsh
- add alias for "npm outdated" to check outdated npm modules
> Add alias for "npm outdated"

- themes/bureau.zsh-theme
The checkmark in clean repo wasn’t dispalyed. Now it fixed.
> Fix checkmark for clean repo in bureau theme

- themes/candy.zsh-theme
Now uses 12-hour clock or 24-hour clock depending
on user locale
> localization support for clock in candy theme

- plugins/zsh-navigation-tools/zsh-navigation-tools.plugin.zsh
> [znt] Don't leave positional parameters being set

- plugins/vagrant/_vagrant
> [TASK] Vagrant plugin: Add missing vagrant snapshot command

- plugins/fossil/README.md
- plugins/fossil/fossil.plugin.zsh
This plugin adds completion support and prompt for fossil repositories.
The prompt will display the current branch and status been dirty or clean.
For those that don't know what fossil is: http://fossil-scm.org/
> Added fossil plugin.

- plugins/gitfast/_git
- plugins/gitfast/git-completion.bash
- plugins/gitfast/git-prompt.sh
Basically what the title says (gitfast plugin).
> gitfast: update to the latest upstream Git and a couple of fixes

- plugins/vagrant/_vagrant
> vagrant snapshot

- plugins/react-native/_react-native
> add plugin react-native

- plugins/react-native/README.md
- plugins/react-native/react-native.plugin.zsh
I've added some of my aliases for ReactNative to save keystrokes for everyone.
> Plugin for React Native

- plugins/taskwarrior/_task
> Update taskwarrior completion to 2.5.1

- plugins/emacs/emacsclient.sh
[inspired by this](https://github.com/davidshepherd7/emacs-read-stdin/blob/master/emacs-read-stdin.sh)
> emacs plugin tweak to open buffer from stdin

- plugins/emacs/emacsclient.sh
* `function` keyword removed
* Fixup the `if` statement and operators
> Fix issue with `dash` as the default `/bin/sh` script executing program.

- plugins/emacs/emacs.plugin.zsh
- plugins/emacs/emacsclient.sh
1. updated minimal version from 23 to 24
2. added new aliase that fix unexpected close with -nw option (fixes #4221)
3. removed some old aliases
4. fixed line that detects open frames, now it works
> Updated emacs plugin

- plugins/docker-compose/README.md
- plugins/docker-compose/_docker-compose
I've updated _docker-compose to the latest version (from 0.1.0 to  1.5.0).
I've also fixed the readme file to redirect to the official page. The url in the file was good however the generated markdown link was not working.
Closes #4311
Closes #4659
> Updated _docker-compose plugin to 1.5.0. (current version is 0.1.0)

- plugins/npm/npm.plugin.zsh
Added a couple of aliases for common npm commands.
> add npm aliases

- themes/muse.zsh-theme
see this effect in figure below:
> muse theme: Remove extra spaces for none git/virtualenv prompt

- plugins/sudo/sudo.plugin.zsh
If $EDITOR is the first word of the line, change it to sudoedit when Esc-Esc
> Plugin : Sudo - Add support of sudoedit

- plugins/osx/README.md
- plugins/osx/osx.plugin.zsh
This commit adds two very commonly used aliases for showing and hiding hidden files in OSX.
> Enhancement: Show/Hide OSX hidden files 💯

- plugins/archlinux/README.md
- plugins/archlinux/archlinux.plugin.zsh
- Format and reorder plugin.zsh
- Reword and simplify README
- Fix wrong URL in `pacmanallkeys` (fixes #5333)
> Clean up Archlinux plugin

- plugins/osx/README.md
Hey man, huge fan of your work. I was just digging through the source of the OSX plugin and found a few super helpful commands that were undocumented. Hope this helps.
Thanks again, I'd love to help out more if I can.
-- Ivan
> Added documentation for undocumented OSX plugin commands

- plugins/rake-fast/README.md
- plugins/rake-fast/rake-fast.plugin.zsh
- Fix `_tasks_changed` function (repost of #5319).
- Fix formatting and syntax of plugin.
- Reword and reorganisation of README.
Close #5319
> Repost of #5319 and refactor of rake-fast plugin

- plugins/coffee/README.md
> Fixed typo

- plugins/firewalld/firewalld.plugin.zsh
- plugins/firewalld/readme.md
Could be too opinionated but this is what I use for firewalld.
> Add FirewallD plugin

- plugins/brew/_brew
Added the ability to autocomplete services based on the list of services installed via brew.
> Add ability to autocomplete services for brew-services.

- plugins/docker/README.md
- plugins/docker/_docker
Updated the docker zsh completion script with the latest version from the official docker repo.
Fixes #5411.
> Update docker completion

- plugins/osx/README.md
- plugins/osx/osx.plugin.zsh
control Spotify by applescripts hooks and has search options with Spotify api for tracks, artists, albums and playlists.
also get information, share link and status about song that is playing.
> Spotify Controller

- plugins/npm/npm.plugin.zsh
versions is missing list is missing
> missing listing and versions

- plugins/docker/_docker
See
https://github.com/docker/docker/blob/master/contrib/completion/zsh/_docker
> Update docker completion to match docker upstream

- lib/completion.zsh
Fixes #1398.
Fixes #4063.
Fixes #4599.
Thanks to @Gravemind for his code.
> Fix completion of files with hyphens and underscores

- plugins/copybuffer.zsh
- plugins/copybuffer/README.md
- plugins/copybuffer/copybuffer.plugin.zsh
binds ctrl-o to copy the command line buffer to the system clipboard
> Add copybuffer function and keybinding

- plugins/extract/README.md
- plugins/extract/_extract
- plugins/extract/extract.plugin.zsh
Fixes #4946
Also fixes styling to use tabs, as well as help message.
> Fix extract of deb packages with data.tar.xz

- plugins/nomad/README.md
- plugins/nomad/_nomad
Add a simple autocompletion plugin for nomad
> WIP add nomad plugin

- plugins/react-native/react-native.plugin.zsh
Context: https://github.com/facebook/react-native/commit/1f9b765f8159216ca7696a0d818acfef7d1e4aff
> Add an alias for React Native Link command

- plugins/mvn/mvn.plugin.zsh
JGit-Flow project page: http://jgitflow.bitbucket.org
> Add jgitflow maven goals to mvn plugin

- plugins/per-directory-history/README.md
- plugins/per-directory-history/per-directory-history.zsh
Latest version: February 17, 2016 - dd81201
Fixes #5492
Related: #4883
Related: https://github.com/jimhester/per-directory-history/issues/11
> Update per-directory-history plugin to latest version

- plugins/globalias/README.md
- plugins/globalias/globalias.plugin.zsh
Expand your aliases 
Explained:
http://blog.patshead.com/2012/11/automatically-expaning-zsh-global-aliases---simplified.html
Closes #4834
> globalias fix #4834

- README.md
Change OS X to macOS in the read me file in line with apples rebranding
of the operating system.
> Readme.md update OS X to macOS

- oh-my-zsh.sh
It isn't OS X anymore, its macOS.
> OS X --> macOS

- lib/theme-and-appearance.zsh
> Fix #5604: No DIR ( directory ) colors

- plugins/gradle/gradle.plugin.zsh
Currently, only tasks with complete subproject specifier are added to
.gradletasknamecache. Gradle commands can be called for all (sub-)projects
they are defined for, using their name as defined in the subproject, here
called "simple" task names. One example is "gradle clean".
This patch adds support for parsing out those "simple" task names from the list
of fully specified task names. The .gradletasknamecache file will contain
both the fully specified names, and the "simple" names for your autocompletion
pleasure.
> Gradle: Extract simple task names from subproject tasks

- plugins/heroku/_heroku
> Add heroku `features` command to completion

- plugins/react-native/_react-native
Updated react-native autocomplete plugin to include all of the current commands for react-native.
@designorant @BilalBudhani @debbbbie
> Updated react-native autocomplete arguments

- plugins/mvn/mvn.plugin.zsh
Added the four commands the [Maven Asciidoctor plugin](https://github.com/asciidoctor/asciidoctor-maven-plugin) offers:
* process-asciidoc 
* auto-refresh
* http 
* zip
> Added mvn asciidoctor commands

- plugins/battery/battery.plugin.zsh
> Fixing battery prompt formatting issue

- plugins/archlinux/README.md
- plugins/archlinux/archlinux.plugin.zsh
Added ```pacfileupg``` for syncing pacman's file database
Added ```pacfiles``` for searching pacman's file database
> Added pacman file aliases

- plugins/osx/osx.plugin.zsh
Added playlist feature for the itunes command: 
if a variable is passed and is valid - will play the playlist
if a variable is passed and is invalid(no such playlist) - will stop all playing
if no variable is passed will print all playlists available on the host
> itunes playlist first commit

- themes/rkj-repos.zsh-theme
> Fix RKJ theme coloring and make it slightly more readable

- plugins/mvn/mvn.plugin.zsh
added some apache maven plugin completions see https://maven.apache.org/plugins/index.html
added arguments for maven see `mvn -h`
added long version of arguments for maven
improved script with use of shellcheck see https://github.com/koalaman/shellcheck
> improved maven plugin

- themes/gallifrey.zsh-theme
The old preview on Skitch is no longer available (closed account?). The new preview is on a free Flickr which might last longer. ?
> Replace preview link.

- plugins/wd/README.md
- plugins/wd/_wd.sh
- plugins/wd/wd.sh
Add support for warp paths containing colons (Mac OS X)
Bug fixes regarding zsh regex and auto-completion
> [wd] Update wd plugin to latest version

- plugins/autojump/autojump.plugin.zsh
> Add nixos support for autojump plugin

- plugins/git-flow/git-flow.plugin.zsh
It is possible to pull and push branches to/from origin.
> Update git-flow aliases

- plugins/npm/npm.plugin.zsh
Added alias for:
npm run
npm publish
npm ls --depth=0
> Improved npm aliases: run, publish

- plugins/yarn/yarn.plugin.zsh
With this PR we will have alias for major commands in Yarn plugin
> Update Yarn plugin alias

- plugins/debian/debian.plugin.zsh
ag is a famous command just like grep.
> fix conflict with command ag

- plugins/helm/helm.plugin.zsh
> Added: Helm plugins

- plugins/wd/_wd.sh
- plugins/wd/wd.sh
Fixes overwriting of `PATH` env variable
> [wd] Update wd plugin to latest

- plugins/terraform/README.md
- plugins/terraform/terraform.plugin.zsh
Expanded Terraform plugin with function that can be used to show workspace name in the zsh prompt
> Plugins: Terraform

- plugins/colored-man-pages/colored-man-pages.plugin.zsh
> Prepend function keyword in colored-man-pages plugin

- plugins/oc/oc.plugin.zsh
Add autocomplete for `oc` for OpenShift.
> Add OpenShift autocompletion

- plugins/docker-machine/README.md
- plugins/docker-machine/docker-machine.plugin.zsh
Hey,
As described i add docker-machine plugin for zsh. You may want to merge it.
> Add docker-machine plugin

- plugins/ubuntu/ubuntu.plugin.zsh
Added 'agli' to list all installed packages.
Added 'aglu' to list available updates only.
> Added aliases for listing packages

- plugins/wd/_wd.sh
Really sorry for the sudden amounts of PRs lately. 
As pointed out in the last PR #6383, I forgot to include some changes.
- Variable conflict of `PATH`
> [wd] Fix update of wd plugin to v0.4.6

- plugins/docker/README.md
- plugins/docker/_docker
This just updates the README file with the new location and is a copy paste from the file found there.
> Update Docker completion plugin

- plugins/adb/README.md
- plugins/adb/_adb
send commands to a specific device
> add autocomplete for adb -s option

- plugins/docker/_docker
Docker completion updated to the version of completion provided by docker team
> Update of docker completion

- plugins/docker-compose/_docker-compose
Pulls in the latest docker-compose completion script from the [docker-compose](https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose) git repo.
> Update docker-compose plugin completion script

- plugins/kubectl/kubectl.plugin.zsh
I added a new kubectl alias for `kubectl apply -f $YML_FILE`
> Add kubectl alias for apply -f

- plugins/kube-ps1/README.md
- plugins/kube-ps1/kube-ps1.zsh
Prompt helper to use with kubectl.  Assists when using multiple clusters and namespaces.
> kube-ps1 zsh prompt helper

- plugins/archlinux/archlinux.plugin.zsh
EDIT: accidentally closed and reopened
> hotfix for archlinux.plugin.zsh

- themes/emotty.zsh-theme
see http://www.zsh.org/mla/workers/2015/msg03259.html
> Fix emotty theme when using zsh 5.2

- plugins/emotty/emotty.plugin.zsh
* The display_emotty function show the name of the displayed emotty set
* Unless an emotty set was given show the emotty set configured
in $emotty_set
> Improve emotty plugin

- themes/rkj-repos.zsh-theme
Doesn't "fix" it per se, but tells the user how to fix.
Might be impacted by PR #2068
Solves #6036.
> [rkj-repos] Check for 'hg prompt' and exit if not found

- plugins/npm/npm.plugin.zsh
> Add npm init to npm plugin

- plugins/rails/_rails
Before
$ rails runner [TAB]
nothing...
After
$ rails runner [TAB]
path complete. happy!
Fixes #5772
> $ rails runner [TAB] *complete*

- plugins/mix-fast/mix-fast.plugin.zsh
The mix command for listing all available actions has been changed from `mix --help` to `mix help`. The mix-fast plugin was using the old command and did not return any results, which prevented the plugin to work.
For the record, invoking the old `mix --help` returns the following output:
```
$ mix --help
Mix is a build tool for Elixir
Usage: mix [task]
Examples:
mix             - Invokes the default task (mix run) in a project
mix new PATH    - Creates a new Elixir project at the given path
mix help        - Lists all available tasks
mix help TASK   - Prints documentation for a given task
The --help and --version flags can be given instead of a task for usage and versioning information.
```
While invoking `mix help` returns:
```
$ mix help
mix                           # Runs the default …
```
> Fix mix-fast plugin

- plugins/kubectl/kubectl.plugin.zsh
Adds get/edit/describe/delete for kubectl ingress
> Add aliases for kubectl ingress

- tools/install.sh
It miss ! for check zsh exist.
> fix bug for check zsh

- plugins/docker/_docker
This is using the current latest version, from:
https://github.com/docker/cli/blob/ec412bdbb47b0cd84d85a0212c7160cec0ee9f02/contrib/completion/zsh/_docker
Fixes #6198
This is an update on PR: https://github.com/robbyrussell/oh-my-zsh/pull/6199
(keeping @troyfontaine 's contribution)
> Updated docker autocomplete

- plugins/heroku/_heroku
This pull request adds basic support for pipelines in the Heroku plugin.
> Add Heroku pipelines support

- plugins/terraform/README.md
- plugins/terraform/_terraform
Terraform has been rapidly developed, so the plugin was way out of date. I've updated it to reflect all the new and removed functionality.
> [plugins/terraform]Update terraform plugin with v0.11.7 commands and help

- plugins/docker/_docker
Adds enable/disable and install/remove to docker completion
> Docker completion updated to current version from the Docker-devs

- plugins/emacs/emacs.plugin.zsh
> Fix 6840 Check emacsclient version instead of emacs's

- plugins/transfer/README.md
- plugins/transfer/transfer.plugin.zsh
Created a single function to easily upload files to transfer.sh file sharing site
Usage : $ transfer file.txt
@slavaGanzin
> added a transfer.sh plugin

- plugins/kubectl/kubectl.plugin.zsh
> Cache kubectl completion script to file to speed up sourcing

- plugins/npx/README.md
Adds some notes on usage https://github.com/robbyrussell/oh-my-zsh/pull/6152#issuecomment-390767752. (@zkat)
> [plugin] update NPX docs

- plugins/shrink-path/shrink-path.plugin.zsh
> shrink-path: match only the beginning of the directory

- plugins/xcode/README.md
- plugins/xcode/xcode.plugin.zsh
I am very frequently opening files in Xcode, and have been hoping to have a very fast way of doing that, and this plugin seems like the perfect place to do that. Very simple addition.
> add xx command to Xcode plugin. Allows quick opening of files in Xcode.

- plugins/gitignore/gitignore.plugin.zsh
Uses silence mode of curl for better autocomplete.
> [plugins/gitignore] silence mode of curl

- plugins/golang/golang.plugin.zsh
> fix path completion issue with go run subcommand

- plugins/debian/debian.plugin.zsh
> 6098 add support apt

- plugins/zeus/_zeus
> Added more levels of zeus compeletion

- themes/mortalscumbag.zsh-theme
theme mortalscumbag add downward arrow icon showing that the local branch is behind the origin one
> mortalscumbag add icon showing local branch behind

- plugins/percol/README.md
- plugins/percol/percol.plugin.zsh
See [README](https://github.com/CodeFalling/oh-my-zsh/blob/percol/plugins/percol/README.md)
> add plugin:percol

- plugins/nvm/_nvm
update completions with the lastest version of nvm
> update nvm completions with v0.29.0

- themes/mortalscumbag.zsh-theme
> Change mortalscumbag theme to use core git_current_branch

- plugins/kubectl/kubectl.plugin.zsh
The original refers to the fictional beast the [Alot](http://hyperboleandahalf.blogspot.com/2010/04/alot-is-better-than-you-at-everything.html).
> Spelling fix

- plugins/perms/README.md
- plugins/perms/perms.plugin.zsh
This can avoid big mistakes as this I just made.
I thought I could give it an argument. So, now, it is possible.
> Add argument to set644 and set755 perms alias.

- plugins/kube-ps1/README.md
- plugins/kube-ps1/kube-ps1.plugin.zsh
Add changes from upstream to plugin.  README updated.
Fixes #6993 and #6512 
Also addresses issue from upstream project: https://github.com/jonmosco/kube-ps1/issues/57
> updating kube-ps1 to align with upstream changes

- plugins/z/z.1
- plugins/z/z.sh
I imported the new version of z.sh to the plugin. This fixes this to error on my machine
_z:101: parse error near `done'
_z:99: parse error in command substitution
> Update z to latest version

- plugins/dash/dash.plugin.zsh
- plugins/rake/rake.plugin.zsh
> Add function to search Dash.app

- plugins/docker/_docker
Update `docker` plugin from [docker/cli master](https://github.com/tommilligan/cli/blob/master/contrib/completion/zsh/_docker)
- bugfix for `docker update` autocompletion: https://github.com/docker/cli/pull/1232
- added `scope` subcommand: https://github.com/docker/cli/pull/1227/files
> Update docker plugin from upstream docker/cli

- plugins/swiftpm/_swift
This was generated by the Swift compiler 4.1.2 using the following
command:
swift package completion-tool generate-zsh-script
> Add shell completion for Swift Package Manager

- themes/agnoster.zsh-theme
This pull request allows a light variant of agnoster theme, to be used with Solarized light theme.
> Agnoster: solarized light variant

- themes/trapd00r.zsh-theme
The biggest change is that it converts the perl script to zsh and it improves its logic.
I've done this step by step so that any change can be reverted if needed.
Also cleans up the rest of the script.
Please check it out @smk291 @miia @memoselyk @trapd00r
> Refactor trapd00r theme

- templates/zshrc.zsh-template
Clarify random theme setting, in particular how to know
which theme was loaded if picked at random.
> Clarify random theme setting

- plugins/kubectl/kubectl.plugin.zsh
I saw there was a couple older PRs opened for various parts of node management but I don't think they all follow the established format and cover the entire get/edit/describe/delete convention.
> Add aliases for kubectl nodes

- plugins/salt/README.md
- plugins/salt/_salt
Add plugin for completion of [Salt](https://github.com/saltstack/salt/) commands.
> Feat: add Salt completion plugin

- plugins/git/git.plugin.zsh
This is quite a nice feature from git. I'm not sure if it's better adding it to gup / gupv, or if it should be added to a new alias :)
> git: add pull rebase --autostash aliases

- plugins/git/git.plugin.zsh
`gstall` = stash ignored, untracked, and tracked files.
> Git plugin - add alias for `git stash --all`

- plugins/git-flow/README.md
- plugins/git-flow/git-flow.plugin.zsh
- Add `gflfp` as an alias for `git flow feature publish`
- Update README.md documentation
> Add "gflfp" as an alias for git flow feature publish

- plugins/react-native/README.md
Added documentation of the new aliases added to the 'plugins/react-native'
> update react-native readme to document new aliases

- plugins/python/python.plugin.zsh
Remove Optional Static Type Checker's (mypy) Cache Files on `pyclean`
> Remove Optional Static Type Checker's (mypy) Cache Files on `pyclean`

- plugins/react-native/README.md
Fixes the broken bottom "Logging" section of the table
> Fix table in README

- plugins/git-auto-fetch/README.md
- plugins/git-auto-fetch/git-auto-fetch.plugin.zsh
Automatically fetch changes from all remotes on cwd
Use case: I maintain a few projects as reviewer and often forget to update all repos before writing reviews.
Besides it awesomely works with git-prompt
> git auto fetch

- plugins/iwhois/README.md
- plugins/iwhois/iwhois.plugin.zsh
The plugins owner however seems to have discontinued the project.
> Added iwhois readme

- plugins/brew/README.md
> Add README to brew plugin

- plugins/django/README.md
Hi, this is my first PR.
If there's something worng in the way I did it, please let me know.
Regards.
> Added README for Django plugin (#7175)

- plugins/brew/README.md
Fix a small typo in `plugins/brew/README.md`.
> Fix a typo in the README.md for the brew plugin

- plugins/dircycle/dircycle.plugin.zsh
Fixes #7149
EDIT: now improved to also call chpwd hooks if a real cd was made
> dircycle: trigger appropriate hooks after directory change

- plugins/python/README.md
Added readme for python plugin  under #7175
> added python plugin Readme

- plugins/grunt/README.md
> Add README.md for grunt plugin

- plugins/gulp/README.md
> Add README.md to gulp plugin

- plugins/node/README.md
> Add README.md to node plugin

- plugins/nvm/README.md
> Add README.md to nvm plugin

- plugins/web-search/README.md
> Add README.md to web-search plugin. Issue #7175

- plugins/macports/README.md
- plugins/macports/macports.plugin.zsh
> Add README for macports plugin

- plugins/golang/README.md
Adds golang plugin README, per #7175
> issue: #7175 adding README for golang plugin

- plugins/emoji-clock/README.md
Adds readme to emoji clock plugin #7175
> Added Readme to emoji-clock plugin

- plugins/ruby/README.md
This is a README.md file for the Ruby plugin, as requested in #7175.
> Add README.md for Ruby plugin

- plugins/vagrant/README.md
Didn't see any aliases in the file, is there anything else to add to the README?
> issue: #7175 adding README for vagrant plugin

- plugins/bower/README.md
Adds README file to Bower plugin
> Adds Bower plugin Readme (#7175)

- plugins/postgres/README.md
> #7175 Add readme to postgres plugin

- plugins/laravel4/README.md
Let me know if I've missed something 👍
Contributes to #7175
> Add README.md to laravel4 plugin. Issue #7175

- plugins/laravel5/README.md
Let me know if I've missed something 😉
Contributes to #7175
> Add README.md to laravel5 plugin. Issue #7175

- plugins/gradle/README.md
> Add Gradle Plugin README

- plugins/gem/README.md
> Add Gem README file

- plugins/mosh/README.md
- plugins/themes/README.md
- plugins/yum/README.md
Issue: #7175 
Adds README.md file for following plugins:
- Yum Plugin
- Mosh Plugin
- Themes Plugin
> Adds Docs for plugins (yum, mosh, themes)

- plugins/iterm2/README.md
Added a README.md for the iterm2 plugin as asked for in #7175 .
> Added iTerm2 plugin README.md

- plugins/lol/README.md
I have no idea why I made this readme. I also have no idea why this plugin exists. But anyway, this PR adds the readme for the `lol` plugin, complete with steps to enable the plugin and has a table containing all the available aliases with usage examples.
> Added readme for `lol` plugin

- plugins/emacs/README.md
> Added Emacs plugin documentation

- plugins/dirhistory/README.md
This adds a readme file for the dirhistory plugin as requested in #7175.
> Add README.md for dirhistory plugin

- plugins/mercurial/mercurial.plugin.zsh
Add an alias for additing files in the mercurial plugin.
> Add "hga" alias for command "hg add"

- plugins/gitfast/README.md
Add README.md file to the gitfast plugin.
This contributes to #7175.
> Add README.md to the gitfast plugin

- plugins/vundle/README.md
> Add README for vundle plugin

- plugins/autopep8/README.md
> #7175 - added README.md to autopep8 plugin

- plugins/pep8/README.md
> #7175 - added README.md to pep8 plugin

- plugins/swiftpm/_swift
Script generated by swift 4.2
Fixes bug described [here](https://bugs.swift.org/browse/SR-7053)
> Update swift completion script

- plugins/colorize/colorize.plugin.zsh
> colorize: fix check for pygmentize

- plugins/nanoc/README.md
> Add readme file for nanoc plugin #7175

- plugins/autoenv/README.md
> Add README for the autojump plugin

- plugins/kubectl/README.md
- plugins/kubectl/kubectl.plugin.zsh
This adds a readme file for the kubectl plugin as requested in #7175.
> Add README for Kubectl in #7175

- plugins/command-not-found/README.md
this should go along with #7175
> adding README for the command-not-found plugin

- plugins/virtualenv/README.md
Added readme file for virtualenv plugin #7175
> README for virtualenv plugin added

- plugins/kitchen/README.md
> add simple README.md for kitchen plugin

- plugins/dirpersist/README.md
Updated the dirpersist README file for #7175
> Added README file to the dirpersist plugin

- plugins/systemadmin/README.md
Added a list of Aliases and Functions in the README for the systemadmin plugin
> Added a README file for the systemadmin plugin

- plugins/scala/README.md
Readme for the Scala plugin #7175
> Added Readme for Scala plugin

- plugins/pylint/README.md
> added README for pylint plugin

- plugins/man/README.md
Added a README file for the man plugin for #7175
> Add README file for the man plugin

- plugins/textmate/README.md
> Add README for textmate plugin

- plugins/systemadmin/README.md
- plugins/systemadmin/systemadmin.plugin.zsh
It's nothing big, but still worth the fix
> systemadmin: fix typos in README

- plugins/sbt/README.md
This adds a readme file for the sbt plugin as requested in #7175
> Add Readme for sbt

- plugins/tmux/README.md
> Added Tmux readme

- plugins/composer/README.md
Added readme to composer plugin #7175
> Added: Composer plugin README

- plugins/battery/README.md
Adds a README.md file for issue #7175
> Create README.md for battery plugin

- plugins/gitignore/README.md
Add a readme for gitignore plugin.
> Adding gitignore plugin README #7175

- plugins/helm/README.md
Adds a simple description for a simple plugin.
> Helm README.md

- plugins/symfony2/README.md
Add README.md to Symfony2 plugin
> Create README.md for symfony2 plugin

- plugins/symfony/README.md
Created the symfony plugin README.md
> Adding symfony plugin README.md

- plugins/heroku/README.md
Create Heroku's plugin README.md
> Adding heroku plugin README.md

- plugins/doctl/README.md
Create doctl's plugin README.md
> Adding doctl plugin README.md

- plugins/celery/README.md
Create celery's plugin README.md
> Adding celery plugin README.md

- plugins/homestead/README.md
Create homestead's plugin README.md
> Adding homestead plugin README.md

- plugins/jake-node/README.md
Create jake's plugin README.md
> Add jake-node plugin README.md

- themes/avit.zsh-theme
> Fix wrong handling of time since last commit

- plugins/aws/README.md
Readme for the aws plugin #7175
> aws: add README.md

- plugins/grails/README.md
This adds a readme file for the grails plugin as requested in #7175
> Add readme for grails plugin

- plugins/stack/README.md
Create stack's plugin README.md
> Adding stack plugin README.md

- plugins/bwana/README.md
Add the bwana's plugin README.md
> Adding bwana plugin README.md

- plugins/ant/README.md
> Adding ant plugin README.md

- plugins/capistrano/README.md
- plugins/capistrano/capistrano.plugin.zsh
Add capistrano's plugin README.md
> Adding capistrano plugin README.md

- plugins/cpanm/README.md
- plugins/cpanm/_cpanm
> Adding cpanm plugin README.md

- plugins/golang/golang.plugin.zsh
Add support to "go help environment" autocompletion
Closes #7403 
Signed-off-by: Ricardo Seriani <ricardo.seriani@gmail.com>
> Add support to "go help environment" autocompletion

- plugins/debian/README.md
Created readme for debian #7175
> debian: README created

- plugins/keychain/README.md
- plugins/keychain/keychain.plugin.zsh
This plugin integrates the Keychain tool[1] in to the project.
[1] [keychain](https://www.funtoo.org/Keychain)
> Add keychain plugin

- plugins/ansible/README.md
- plugins/ansible/ansible.plugin.zsh
`Ansible Plugin` provides custom [ansible](https://docs.ansible.com/ansible/latest/index.html) commands and aliases.
> ansible plugin added

- plugins/ssh-agent/ssh-agent.plugin.zsh
With this PR the ssh-agent plugin checks the `ssh-add -l` output for the identities added, and adds all those specified by the user that haven't been added yet.
We also decouple the logic of starting ssh-agent from the logic of adding identities, meaning that even if ssh-agent has been started by some other means (like [launchd](https://github.com/robbyrussell/oh-my-zsh/issues/6979#issuecomment-411088832)) we can still ssh-add the user's identities.
Fixes #3019
Fixes #6979
> ssh-agent: autoload identities not already loaded

- plugins/extract/README.md
- plugins/extract/_extract
- plugins/extract/extract.plugin.zsh
It's like JAR, but with Android resources and other stuff
> Extract AAR Android archive support

- plugins/ssh-agent/ssh-agent.plugin.zsh
Also, fixed an if syntax error
Fixes https://github.com/robbyrussell/oh-my-zsh/pull/7174#issuecomment-454741290
> ssh-agent: add default keys if no zstyle identities were set

- plugins/emacs/emacs.plugin.zsh
This is my simple solution to fix #3305 
With this small change 'e' command always open new emacsclient in terminal
> Fix emacs client terminal

- plugins/ros/README.mkd
- plugins/ros/_ros
[Roswell](https://github.com/roswell/roswell) is a Common Lisp environment setup utility
this plugin added simple completions for roswell's options and commands
> Added Plugin for Roswell

- plugins/osx/spotify
This change updates the code for the spotify plugin from Dec 14, 2017 to today's, which looks to have been updated on Nov 14, 2018.  The plugin code contains fixes for functionality which is broken in the current version [full list](https://github.com/hnarayanan/shpotify/issues?q=is%3Aissue+closed%3A%3E2017-12-14+is%3Aclosed).
> Plugin: Updates spotify plugin to current master (as of 2019-01-31)

- plugins/emacs/emacs.plugin.zsh
Reverts robbyrussell/oh-my-zsh#5714
> Revert "Fix emacs client terminal"

- plugins/fancy-ctrl-z/README.md
Just found this typo while browsing through the `plugins` folder ... and it "hurt sme" :hurtrealbad:
> Fix "hurt sme" typo

- plugins/kubectl/README.md
- plugins/kubectl/kubectl.plugin.zsh
hi,
found this snippet in the internet and i use it all the time. i think it would be useful for the `kubectl` plugin
> allow kubectl commands against all namespaces

- oh-my-zsh.sh
fix: #7685 bug introduced in #7679
Fixes #7687 
Fixes #7688
> init: fix erroneous plugin not found warning

- plugins/web-search/README.md
- plugins/web-search/web-search.plugin.zsh
Apply proposed fix in #7659 
@iamantu93
> web-search: fix #7659, update alias for stackoverflow

- plugins/aws/aws.plugin.zsh
Clean up Homebrew detection and add comments.
Also changed some if flags.
Incorporated the main changes of #7264 
Closes #7264 
Fixes #6424
> aws: refactor completion sourcing logic

- themes/pygmalion-virtualenv.zsh-theme
since pygmalion has no virualenv prompt info, so I added it.
> add virualenv prompt info into pygmalion

- plugins/cargo/_cargo
1. Complete `--target` names based on cargo configurations
0. Add a simple description for `--color`
0. Complete `--message-format`
> Improve cargo completion

- plugins/gradle/gradle.plugin.zsh
You can change the location of the buildscript in the settings file, thus it should also be checked for.
> Gradle Plugin: Also support settings files

- plugins/drush/README.md
- plugins/drush/drush.complete.sh
- plugins/drush/drush.plugin.zsh
Aliases and function for drush to help the drupal workflow.
> Added drush compatibility

- themes/refined.zsh-theme
> refined: reset command exec time

- plugins/nvm/nvm.plugin.zsh
> nvm plugin only load nvm script if command doesn't already exist

- plugins/gitfast/_git
- plugins/gitfast/git-completion.bash
- plugins/gitfast/git-prompt.sh
- plugins/gitfast/gitfast.plugin.zsh
- Updates git completion and git-prompt to v2.10 (partially fixes #6137)
- Stops loading the git plugin (fixes #6206)
@felipec can you check out if I didn't break anything, and also if we could update the completions to a newer version?
> Update gitfast plugin

- plugins/pip/pip.plugin.zsh
> pip: fix indexes URL

- plugins/archlinux/README.md
> fix minor typo

- plugins/kube-ps1/README.md
- plugins/kube-ps1/kube-ps1.plugin.zsh
changes:
- easily customize the colors via variables
- command to switch on/off the custom prompt
- Improved documentation with example on how to append on the prompt.
Fixes #7261
> plugin: kube_ps1: colors and dynamically enable / disable

- plugins/bwana/README.md
- plugins/bwana/bwana.plugin.zsh
Fix #5732
Change name function from `man` to `bwana`.
> bwana: change function name to bwana

- plugins/sublime/README.md
- plugins/sublime/sublime.plugin.zsh
Fixes #7570
Fixes #7595 
Fixes #6734 
The changes are documented in each separate commit.
> sublime: refactor plugin and fix documentation

- plugins/rails/README.md
Just made readme file.
Could be used as a cheat sheet.
> rails: create README

- plugins/sfdx/README.md
- plugins/sfdx/_sfdx
This is a completion for the Salesforce CLI. I'm on the prod engineering team and it's quite useful.
Fixes #7645
> Added plugin and completion for sfdx

- plugins/aws/aws.plugin.zsh
> aws: fix path resolution of aws_zsh_completer.sh for Ubuntu

- plugins/kubectl/README.md
- plugins/kubectl/kubectl.plugin.zsh
Reverts robbyrussell/oh-my-zsh#7749
See https://github.com/robbyrussell/oh-my-zsh/issues/6408#issuecomment-485718042 and later comments.
> Revert "kubectl: rename k alias"

- plugins/github/_hub
Simple PR to update hub completions as provided by [hub](https://github.com/github/hub).
> Updated hub completions

- plugins/vscode/README.md
- plugins/vscode/vscode.plugin.zsh
> vscode: add code-insiders support

- plugins/osx/README.md
- plugins/osx/spotify
Updates the spotify() function to match shpotify latest release (v2.1):
- updates the copyright years
- fixes typos
- adds broken out status
- *brings back `spotify play list <query>` ability*
- cleans up code (exit status and break)
Fixes #6170 
Fixes #6232
Fixes #6345
> Update spotify v2.1

- plugins/emotty/emotty.plugin.zsh
See https://github.com/robbyrussell/oh-my-zsh/pull/6731#issuecomment-449653115
cc @dubbadubbadubbacha
> emotty: fix for undefined $TTY (FreeBSD)

- plugins/gitfast/_git
- plugins/gitfast/git-completion.bash
- plugins/gitfast/git-prompt.sh
- plugins/gitfast/gitfast.plugin.zsh
- plugins/gitfast/update
- plugins/gitfast/updates.patch
I've added a script to automatically update to the latest upstream, and while at it, I updated to the latest upstream:
> gitfast: update to upstream v2.21

- plugins/kubectl/README.md
- plugins/kubectl/kubectl.plugin.zsh
Add pvc aliases to the kubectl plugin.
> Add PersistentVolumeClaim support to kubectl plugin

- plugins/kubectl/README.md
- plugins/kubectl/kubectl.plugin.zsh
Adds aliases for managing statefulsets
> Add statefulset aliases to kubectl

- themes/af-magic.zsh-theme
As asked for in #5249.
cc @leoheck
> af-magic: make separator window-size-aware

- plugins/common-aliases/README.md
Added README for common-aliases plugin (#7175 )
> Added README for common-aliases plugin 

- themes/agnoster.zsh-theme
This PR fixes the logic bug here: https://github.com/robbyrussell/oh-my-zsh/issues/7985
> Bug fix for schrodingers VIRTUAL_ENV_DISABLE_PROMPT (7985)

- themes/agnoster.zsh-theme
Reverts robbyrussell/oh-my-zsh#8050
> Revert "Bug fix for schrodingers VIRTUAL_ENV_DISABLE_PROMPT (7985)"

- plugins/sudo/sudo.plugin.zsh
- plugins/thefuck/thefuck.plugin.zsh
- plugins/vi-mode/vi-mode.plugin.zsh
> Allow sudo and thefuck plugins to be loaded before vi-mode

- plugins/homestead/homestead.plugin.zsh
It's fix problem with empty list of commands
Fixes #8091
> homestead: change key string for getting command list

- plugins/homestead/homestead.plugin.zsh
I'm so sorry. i broke the plugin but now it' work correct
> homestead: repair sed regex

- plugins/ripgrep/README.md
- plugins/ripgrep/_ripgrep
As before, just the official completion.
> Updated ripgrep completion to latest version

- themes/evan.zsh-theme
We don't need to sexualize a shell prompt :) 
(Will update the wiki accordingly, too, if this is merged)
> Change description for Evan's prompt to something neutral

- themes/robbyrussell.zsh-theme
Now it can be sourced in a function, like zplug.
> Remove local variable in robbyrussell theme

- plugins/gitfast/_git
- plugins/gitfast/git-completion.bash
Includes completions for `git branch`.
Tested on `git version 2.23.0`.
Fixes: #8105
> plugins/gitfast: update completions

- plugins/autoenv/README.md
PR for https://github.com/robbyrussell/oh-my-zsh/issues/7175#issue-365263634
Add READMEs to undocumented plugins
- README.md added to the autoenv plugin
> Add README for the autoenv plugin

- plugins/oc/README.md
Hopefully this is okay, there's really not much to their autocompletion, but it works great!
Thanks guys, happy to discuss.
Updates #7175.
> Add README.md for oc plugin.

- plugins/fzf/fzf.plugin.zsh
Added function to setup fzf from deb package. Separated everything into functions, for clarity
> fzf: Adding support for debian packages

- plugins/lein/README.md
Adds Leiningen plugin README file as part of #7175
> Adding Leiningen Plugin README

- plugins/jruby/README.md
This adds a README for the `jruby` plugin as part of #7175
> Add jruby readme

- plugins/yii/README.md
Add README to yii plugin
- Create a README file in the `yii` plugin directory.
- Add documentation on how to use the `yii` plugin
- View `README` file in `yii` plugin directory.
This contributes to #7175
> Add README to yii plugin

- plugins/cakephp3/README.md
**What does this PR do?**
Add README to cakephp3 plugin
This contributes to #7175
> Add Readme to cakephp3 plugin

- plugins/rebar/README.md
This adds the README file for the `rebar` plugin as part of #7175
> Adding README for rebar plugin

- plugins/terminitor/README.md
Added README for terminitor plugin.
Reference issue : #7175
> terminitor: add README

- plugins/dash/README.md
addresses part of https://github.com/robbyrussell/oh-my-zsh/issues/7175
> docs: add README.md for Dash plugin

- plugins/redis-cli/README.md
Add redis-cli plugin's README.md
> Adding Redis-CLI plugin README.md

- plugins/perl/README.md
> Adding Perl plugin README.md

- plugins/virtualenvwrapper/README.md
fixes part of https://github.com/robbyrussell/oh-my-zsh/issues/7175
> docs: add README.md for virtualenvwrapper

- plugins/colemak/README.md
- plugins/tugboat/README.md
See https://github.com/robbyrussell/oh-my-zsh/issues/7175 for more info.
> Adds READMEs for Tugboat and Colemak plugins

- plugins/cloudapp/README.md
> Add README.md for CloudApp plugin

- plugins/terminalapp/README.md
- plugins/terminalapp/terminalapp.plugin.zsh
#7175 add README.md for Terminalapp plugin
> #7175 add README.md for Terminalapp plugin

- plugins/singlechar/README.md
- plugins/singlechar/singlechar.plugin.zsh
> #7175 Create README.md for Singlechar plugin

- plugins/compleat/README.md
> Create README.md for compleat plugin

- plugins/chruby/README.md
https://github.com/robbyrussell/oh-my-zsh/issues/7175
> Adds chruby plugin README.md

- plugins/python/python.plugin.zsh
> Add -r flag to pygrep

- plugins/battery/battery.plugin.zsh
this is just copy paste and move from acpi to sysctl for FreeBSD
> added support for sysctl

- plugins/rust/README.md
I added a readme for the rust plugin, hope it helps!
> add readme for the rust plugin

- plugins/rake/README.md
#7175 add README.md for rake plugin
> #7175 add README.md for rake plugin

- plugins/git-remote-branch/README.md
This PR adds `git-remote-branch` plugin's README.md
> Add README file for git-remote-branch plugin

- plugins/eecms/README.md
Added a readme for this simple plugin contributing to #7175
> added eecms plugin readme

- plugins/phing/README.md
Added a readme for the phing plugin, issue #7175
> Simple phing auto complete plugin

- plugins/pass/README.md
> added README.md

- plugins/docker/README.md
> Format docker Readme like the other plugins.

- plugins/supervisor/README.md
- plugins/supervisor/_supervisorctl
Sync completion with original source.
see #7175
> Add Readme.md for supervisor.

- plugins/magic-enter/Readme.md
This PR updates `magic-enter` plugin's README.md
see #7175
> Update Readme for Magic Enter plugin

- plugins/safe-paste/README.md
I've add a readme for safe-paste plugin with a description of this plugin
Refer #7175
> add readme for safe paste plugin

- plugins/rbenv/README.md
#7175 add README.md for rbenv plugin
> #7175 add README.md for rbenv plugin

- plugins/fasd/README.md
#7175 Adding Documentation for fasd plugin.
> Add fasd documentation

- plugins/terraform/_terraform
*  Add 0.12upgrade commands
* Add state commands
* Add state completion to -target option in commands
* Add state completion where used as argument
@mcornella
> Update terraform completion

- CONTRIBUTING.md
- LICENSE.txt
- README.md
- plugins/bundler/README.md
- plugins/emotty/README.md
- plugins/fedora/README.md
- plugins/gitfast/README.md
- plugins/go/README.md
- plugins/history-substring-search/README.md
- plugins/meteor/README.md
- plugins/mvn/README.md
- plugins/ng/README.md
- plugins/percol/README.md
- plugins/rake/README.md
- plugins/thefuck/README.md
- plugins/urltools/README.md
- plugins/wd/README.md
- templates/zshrc.zsh-template
- themes/gallifrey.zsh-theme
- tools/install.sh
- tools/upgrade.sh
This PR does the following items from the [list of tasks to be made when migrating the repository](https://github.com/robbyrussell/oh-my-zsh/issues/8388#issue-523100317) to the @ohmyzsh org:
I'm creating it as a draft PR because it shouldn't be merged until the repo transfer is done.
> Actions to take after repository migration is complete

- tools/uninstall.sh
> Fix change to old shell on uninstall

- plugins/extract/README.md
- plugins/extract/_extract
- plugins/extract/extract.plugin.zsh
Adds support for the [Zstandard](https://github.com/facebook/zstd) compression algorithm and updates the README accordingly.
> add zstd support for the extract plugin

- plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
Fixes issue described in #4603
> Change order of automatic virtualenv activation/deactivation

- plugins/git-prompt/gitstatus.py
Fix the finicky parsing logic and just ask git the necessary information directly.
Fixes: https://github.com/robbyrussell/oh-my-zsh/issues/5747, Fixes https://github.com/robbyrussell/oh-my-zsh/pull/4991, Fixes https://github.com/robbyrussell/oh-my-zsh/issues/6341
> Rewrite gitstatus tag and hash collection to be more robust

- plugins/microk8s/README.md
- plugins/microk8s/microk8s.plugin.zsh
Plugin (completion and aliases) for MicroK8s
> Added MicroK8s plugin for ZSH

- plugins/kubectl/kubectl.plugin.zsh
Add kubectl log since aliases
```
--since 1h
--since 1m
--since 1s
```
> Add kubectl log since aliases

- plugins/laravel/README.md
- plugins/laravel/laravel.plugin.zsh
I added few more frequently used artisan commands for laravel.
I also updated it's readme accordingly.
> Laravel artisan commands extension

- .github/workflows/check-suite.yml
- README.md
In order to maintain a cleaner commit history, I made a new branch and will be closing the other PR. This is the only way I see of giving this work a cleaner commit history.
@larson-carter
> Create Github Action to run tests

- plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
Rewrote the init script location code to remove duplication. Also added the default debian location for the file.
Fixes #8513
> virtualenvwrapper: rewrite init script location code

- plugins/kube-ps1/README.md
I ran into this issue, looks like maybe a few other people did as well.
https://github.com/jonmosco/kube-ps1/issues/28#issuecomment-359761463
A simple clarification seems helpful.
> kube-ps1: Add example for common pitfall

- plugins/vagrant/_vagrant
Fixes #6673 
Ran a few tests and seems good :crossed_fingers:
> vagrant: obey VAGRANT_CWD when completing vagrant commands

- plugins/kubectl/kubectl.plugin.zsh
> [kubectl] Avoid conflicts with existing `f` aliases

- plugins/fzf/fzf.plugin.zsh
EDITED by @mcornella:
This PR also works for Void Linux, so I modified it to mention that as well.
Closes #8548
Fixes #8585
Closes #8623
> Support getting fzf for NixOS and Void Linux

- plugins/cloudapp/README.md
- Just a small type fix in the readme
NA
> Fixes typo on plugin's name from dash to cloudapp

- plugins/web-search/README.md
- plugins/web-search/web-search.plugin.zsh
> Adding wolframalpha search engine

- plugins/jfrog/README.md
- plugins/jfrog/jfrog.plugin.zsh
This plugin adds autocompletion for JFrog CLI.
> Add JFrog CLI plugin

- themes/norm.zsh-theme
I added the hg_prompt_info to the norm theme.
> added hg prompt to norm theme

- lib/functions.zsh
- Don't fail upgrade if lock file does not exist
> lib: use `command` to run rm in upgrade function

- plugins/nvm/_nvm
Missing completion to nvm feature.
> nvm: add `install-latest-npm` to completion

- plugins/sdk/sdk.plugin.zsh
Fixes #8724
@rahulsom
@mcornella
- removed invalid value "candidates" from sdk flush completion
> remove invalid value "candidates" from sdk flush completion

- plugins/tig/README.md
For more convenient plugin exploring.
- [...]
...
> Readme: Adds more info.

- plugins/sdk/sdk.plugin.zsh
- support completion for the new `env` & `home` commands in 5.8.0
> sdk plugin: support completion for new commands in 5.8.0

- tools/upgrade.sh
Displays the logo in rainbow colors when updating, similar to the [rainbow sticker sold on the website](https://shop.planetargon.com/products/ohmyzsh-ascii-art-stickers-set-of-3).
> update: display logo in rainbow colors

- plugins/jira/README.md
- plugins/jira/_jira
- plugins/jira/jira.plugin.zsh
- added `tempo` command to access Tempo page
> jira: add tempo command

- plugins/man/man.plugin.zsh
Example: git rebase ...
- Execute man beforehand, to determine if command manual for "git rebase"
- If exists: write "man git rebase" into buffer
- Else: write "man git" into buffer
> man: look for man page for subcommands

- plugins/forklift/forklift.plugin.zsh
- The Setapp platform distributes a version of Forklift which has a different CFBundleIndentifier that which is supported by this plugin. These changes simply add this identifier to that the plugin will work.
...
> forklift: add support for Forklift distributed via the Setapp

- plugins/git/README.md
- Changed readme of git plugin
...
> Clarify what glp alias does

- plugins/docker/_docker
Updating the file `plugins/docker/_docker` according to the source
https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker
> docker: update to latest upstream completion (92dc906)

- plugins/python/python.plugin.zsh
- adds line-numbering to pygrep alias
> python: add line-number to pygrep

- plugins/bazel/README.md
- plugins/bazel/_bazel
Hi, I have created a new plugin to add bazel zsh completion copied from their repo.
> Add plugin for bazel completion

- plugins/web-search/README.md
- plugins/web-search/web-search.plugin.zsh
- Add Reddit and The Internet Archive Wayback Machine to the list of search engines.
> web-search: add Wayback Archive

- plugins/chucknorris/fortunes/chucknorris
- fix typos in `plugins/chucknorris/fortunes/chucknorris`
someone has a problem spelling "doesn't"
> chucknorris: fix typos

- plugins/chucknorris/fortunes/chucknorris
- normalize apostrophes in `plugins/chucknorris/fortunes/chucknorris`
> chucknorris: normalize apostrophes

- oh-my-zsh.sh
- tools/check_for_upgrade.sh
```
update: refactor check_for_upgrade file
- Move .zsh-update file migration inside check_for_upgrade
- Use a trap to remove the lock folder
- Simplify upgrade script call
- Rename functions
update: remove lock directory if older than one day
update: fix trap for SIGINT and read prompt on non-newline characters
```
Fixes #4992
Fixes #5286
Closes #6646
Fixes #7042
Fixes #8332
These are not solved by this PR:
- https://github.com/ohmyzsh/ohmyzsh/issues/2971
- https://github.com/ohmyzsh/ohmyzsh/issues/4361
- https://github.com/ohmyzsh/ohmyzsh/issues/6732
- https://github.com/ohmyzsh/ohmyzsh/issues/6989
- https://github.com/ohmyzsh/ohmyzsh/pull/7539
- https://github.com/ohmyzsh/ohmyzsh/issues/8003
- https://github.com/ohmyzsh/ohmyzsh/issues/8387
- https://github.com/ohmyzsh/ohmyzsh/pull/8788
> update: refactor and fix logic in check_for_upgrade.sh

- plugins/web-search/README.md
- plugins/web-search/web-search.plugin.zsh
- Google Scholar search added to web-search plugin, README modified accordingly
- Usefulness for developers in not obvious, but can be usefull for data scientists
> web-search: add Google Scholar

- oh-my-zsh.sh
Fixes #9039 
Related to #9019 
- skip the update check at initialization if DISABLE_AUTO_UPDATE is set to true
Please refer to the issue #9039
> init: don't run update check if DISABLE_AUTO_UPDATE

- tools/install.sh
- tools/upgrade.sh
- I added a few touches to the install script.
- I made the shameless twitter plug seem more concise and clear about what we are wanting
- I added a another note for our swag link.
- Then, the most important update, the discord server. I added the discord vanity url for our Official verified server.
- We should get a few more people to join the discord server now!
> Modernize install and update banners

- lib/theme-and-appearance.zsh
enable diff color if possible.
> lib: enable diff color

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
- themes/mlh.zsh-theme
- Bug Template
I added a simple self check to help cut down on issues/bugs that have already been reported. This will also hopefully get the discord server just a bit more active. I also added a field for WSL1/2 that way we can easily categorize rather it is a Windows bug or a Oh My Zsh issue.
- Feature Request Template
I added a field that is consisted with aliases and themes that way they are consisted throughout that entire file. I also added a field for related issues that this feature request could be related too. This can help us make a PR that would close issues and PRs at the same time.
- Added MLH Theme
Since we are involved in the MLH-Fellowship fellows created a MLH theme! This theme is to be used a Hackathons and by other Fellows that are involved in the fellowship. This will …
> Bug and Feature Request Templates + MLH Theme + Readme

- plugins/mix-fast/mix-fast.plugin.zsh
**Is your feature request related to a particular plugin or theme? If so, specify it.**
mix-fast
**Is your feature request related to a problem? Please describe.**
currently completions don't have descriptions
**Describe the solution you'd like**
use `_decribe` instead of `compadd` so descriptions from `mix help` are included
> mix-fast: add decriptions to mix-fast completions

- plugins/extract/README.md
- plugins/extract/_extract
- plugins/extract/extract.plugin.zsh
- plugin extract: Add IPA to extractable filetypes. IPA files are also ZIP files.
> extract: Add IPA to extractable filetypes

- lib/cli.zsh
- lib/functions.zsh
Extend `omz` CLI (https://github.com/ohmyzsh/ohmyzsh/pull/8876) with `update` command that invokes `lib/upgrade.sh`.
Fixes #8003
> cli: add update command

- README.md
- tools/install.sh
- Updated the readme and install.sh header to include the `fetch` install option per issue #8016 
Unable to personally test the `fetch` command myself, but pulled it from the issue #8106 comment and updated it per the most recent url in `wget` and `curl` commands.
Fixes #8016
> docs: add fetch install command for FreeBSD

- README.md
Update presents a following info message
```Note: `upgrade_oh_my_zsh` is deprecated. Use `omz update` instead.```
so this PR is to update that piece of info
- Readme update
> Update README with new update command

- plugins/chucknorris/fortunes/chucknorris
> chuck-norris: remove some CN quotes and fix formatting

- plugins/wd/README.md
- plugins/wd/wd.sh
Update wd to latest commit on master branch of repository. We have recently had a new major release (v0.5.0), so this update brings this to ohmyzsh along with the updated README
See [release notes](https://github.com/mfaerevaag/wd/releases/tag/v0.5.0)
Is there anyway this can be automated for future or will there always need to be manual PRs?
I'm a maintainer of [wd](https://github.com/mfaerevaag/wd) so am happy to work with yourselves to make this happen
> Update wd to latest

- plugins/terraform/README.md
- plugins/terraform/terraform.plugin.zsh
> terraform: add tf Alias

- plugins/bundler/README.md
- Formatted Aliases and added description
...
> bundler: format aliases table and clean up README

- plugins/nvm/README.md
- plugins/nvm/nvm.plugin.zsh
Homebrew has a slightly different nvm setup, and this change checks for it and sources the right files.
Fix #8307 
@saschabratton
> nvm: add Homebrew's nvm setup

- .github/CODEOWNERS
- plugins/git-lfs/README.md
- plugins/git-lfs/git-lfs.plugin.zsh
- Add git lfs plugin, which is requested in #8598
- Add a few more aliases git the current git plugin as suggested in #8598
> Add git-lfs plugin

- plugins/mvn/mvn.plugin.zsh
mvn plugin:
1. list modules (dir with pom.xml in it)
2. convert spaces to tabs
> mvn: list modules (directories with pom.xml)

- themes/agnoster.zsh-theme
- Fixed icon for unstaged git status in agnoster theme.
Fixes #8520
> agnoster: fix icon for unstaged git status

- plugins/kube-ps1/README.md
Removes missing screenshots from README for kube-ps1 plugin.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
...
> Remove missing screenshots from kube-ps1 README

- plugins/fzf/README.md
- plugins/fzf/fzf.plugin.zsh
- Added check for OpenBSD package based on https://github.com/ohmyzsh/ohmyzsh/issues/9023
- Added check for OpenSUSE package based on https://github.com/ohmyzsh/ohmyzsh/issues/9290
- Simplified and cleaned up logic
- Redid the README to clarify it
Fixes #9023 
Fixes #9290
> fzf: add check for OpenSUSE and OpenBSD packages

- plugins/kubectl/README.md
- plugins/kubectl/kubectl.plugin.zsh
* Add aliases for
* Service Accounts
* DaemonSets
* CronJob
* Minor fixes on formatting and typo in README.md
N.A.
> kubectl: add aliases for serviceaccount, daemonsets and cronjob

- plugins/gitfast/_git
- plugins/gitfast/git-completion.bash
Signed-off-by: Felipe Contreras <felipe.contreras@gmail.com>
- Fixed backwards compatibility with older versions of Git
- Fixed loading error messages (macOS pkg-config)
- Fixed issue completing remote branches
- Fixed loading upstream bash script
> gitfast: fetch latest fixes from git-completion

- plugins/thefuck/README.md
Add a description about adding thefuck to the plugins list
- update thefuck README.md
> docs(thefuck): add description for enabling the plugin

- plugins/aws/README.md
Example for AWS profile set up
> docs(aws): add config examples

- plugins/colored-man-pages/README.md
- plugins/colored-man-pages/colored-man-pages.plugin.zsh
- plugins/colored-man-pages/nroff
1. Convert tabs to spaces
2. Extract Solaris hack
Also refactors and documents existing behavior.
3. Move PAGER to the env array
4. Use named colors and associative arrays
@mcornella, please, take a look.
Closes #9436
> refactor(colored-man-pages): move nroff wrapper and refactor logic in `colored` function

- plugins/aws/aws.plugin.zsh
If there are `duration_seconds` and/or `role_session_name` parameters in the AWS CLI config file then use them.
...
> feat(aws): respect optional parameters from the AWS CLI config file

- plugins/gitfast/_git
- plugins/gitfast/git-completion.bash
- plugins/gitfast/update
- Improved auto suffix removal
- Support for recursive aliases
- Support for git parseopt completions
- Support for -C and -c options
- Couple of bug fixes
There's now a testing framework and [all the tests pass](https://travis-ci.org/github/felipec/git-completion).
> feat(gitfast): update to git-completion 1.2

- plugins/shell-proxy/proxy.py
- plugins/shell-proxy/ssh-agent.py
- change environment variable name
...
> fix(shell-proxy): change NAME env variable for WSL clash

- plugins/ansible/ansible.plugin.zsh
Fix minor, but annoying, spacing bug in `ansible-role-init`.
> style(ansible): minor style change

- plugins/archlinux/archlinux.plugin.zsh
- prevent leaking local variables
None
> refactor(archlinux): prevent leaking local variables

- plugins/common-aliases/README.md
- plugins/common-aliases/common-aliases.plugin.zsh
> aliases: Don't overshadow fd

- plugins/docker/_docker
> feat(docker): update completion to upstream version

- themes/essembeh.zsh-theme
- single line
- quite simple by default: user@host:$PWD
- green for local shell as non root
- red for ssh shell as non root
- magenta for root sessions
- prefix with remote address for ssh shells
- prefix to detect docker containers or chroot
- git plugin to display current branch and status
- [...]
...
> feat(essembeh): update theme with new features

- plugins/mongocli/README.md
- plugins/mongocli/mongocli.plugin.zsh
- Adds a plugin for mongocli to have a couple of handy short aliases to common commands
> feat: add mongocli plugin

- themes/adben.zsh-theme
- Fix style
- Use curl if wget is not available
- Don't error on missing `fortune` command
- Don't use offensive quotes on fortune
Fixes #9698
> refactor(adben): refactor theme and degrade gracefully on missing dependencies

- tools/theme_chooser.sh
> feat(theme_chooser): display non-zero exit code

- plugins/archlinux/README.md
- plugins/archlinux/archlinux.plugin.zsh
Arch Linux plugin: add support for aura AUR helper.
~This is draft PR. We are yet to settle on some aliases.~
Related issue in aura repository: https://github.com/fosskers/aura/issues/675
> feat(archlinux): add support for aura AUR helper

- plugins/react-native/react-native.plugin.zsh
- I added new alias for 12th Gen iPhones in order to decrease writing time while testing on multiple devices.
> feat(react-native): add aliases for iPhone 12

- themes/ys.zsh-theme
Now this theme will show if you are in a virtualenv, and if so, what the name of the virtualenv is.
> feat(ys): add virtualenv prompt info

- plugins/npm/README.md
- plugins/npm/npm.plugin.zsh
Adds two new aliases: `npm info` and `npm search`
The realize the aliases themselves may not be ideal in differentiating them from others. I attempted to find a balance between easy/memorable, while also trying to avoid collisions with other aliases. I'm definitely open to feedback if others feel strongly for better-named aliases. Thanks!
> feat(npm): add aliases for `npm search` and `npm info`

- README.md
Fix "FaceBook" typo in README.md.
> chore: fix "Facebook" typo in README.md

- plugins/deno/deno.plugin.zsh
Adding the two lines remaining to solve completion problem on Deno plugin.
Thanks @mcornella for your code!
Closes #9862
> fix(deno): actually load deno completion

- plugins/chucknorris/fortunes/chucknorris
> chore(chucknorris): fix typo

- plugins/extract/README.md
- plugins/extract/_extract
- plugins/extract/extract.plugin.zsh
- Adds ability for extract to work with .ear files
- Adds autocomplete functionality for extract with .ear files
> feat(extract): add support for .ear files

- plugins/aliases/aliases.plugin.zsh
- plugins/aliases/cheatsheet.py
- plugins/aliases/termcolor.py
with lots of 3rd-party amazing aliases installed, just need something to explore it quickly.
**acs: alias cheatsheet**
1. `acs`: group all alias
2. `acs $keyword`quickly filter alias & highlight
> add alias plugin: cheatsheat your alias.

- tools/upgrade.sh
- fix(update): correct description of how changelog is displayed
Piping the changeling to less was removed in 4b2431e8b1c08a2dc14fe31bf07a5e5f08eaa87e
> fix(update): correct description of how changelog is displayed

- lib/functions.zsh
Download, extract, and cd into the resulting directory.
> add support to `take' for taking remote urls

- plugins/git/README.md
- plugins/git/git.plugin.zsh
- all checked
- add a new alias for "git pull --rebase"
- NA
> feat(git): add gpr alias for "git pull -rebase" which is easier to remember (#9951)

- plugins/ubuntu/ubuntu.plugin.zsh
Add an alias for `showpkg` to get the reverse and recursive dependencies on a package
> Add a new alias

- plugins/bedtools/README.md
- plugins/bedtools/_bedtools
- plugins/samtools/README.md
- plugins/samtools/_samtools
The patches create some initial support for bedtools & samtools autocompletion.
> Complete samtools bedtools

- plugins/ag/README.md
- plugins/ag/_ag
A replacement for ack/grep https://github.com/ggreer/the_silver_searcher
> Add Ag completion

- themes/mlh.zsh-theme
* allow for customization of RPROMPT (exit code and timestamp)
* improve code and comments
* adjust code style to conform to [code style guide](https://github.com/ohmyzsh/ohmyzsh/wiki/Code-Style-Guide)
> update the official theme of Major League Hacking

- plugins/pip/README.md
- plugins/pip/pip.plugin.zsh
Created alias for pip commands to create `requirements.txt` file, install packages from `requirements.txt` file, update and uninstall all packages.
> feat(plugins): add alias for pip

- .github/CODEOWNERS
- plugins/zoxide/README.md
- plugins/zoxide/zoxide.plugin.zsh
- Adds a plugin for [zoxide](https://github.com/ajeetdsouza/zoxide) - a smart, fast, and configurable alternative to your `cd` command.
> feat(plugins): add zoxide

- plugins/mercurial/mercurial.plugin.zsh
Mercurial plug-in is slow when working with big repository. Modified it a bit so it is usable again. The changes are:
- changed functions not to call other functions which lead to multiple mercurial command executions
- replaced hg summary with hg branch which is faster
- replaced hg status with hg status -mar
> speed up mercurial plugin

- plugins/pm2/README.md
- plugins/pm2/_pm2
- plugins/pm2/pm2.plugin.zsh
The plugin adds several aliases and completions for common [pm2](http://pm2.keymetrics.io/) commands.
> pm2 plugin

- plugins/github/README.md
> chore(github): add links to supported tools

- plugins/pyenv/pyenv.plugin.zsh
- PyEnv expects you to update your PATH in your .zshenv or .zprofile.
> fix(pyenv): fix pyenv PATH settings with a warning

- plugins/ag/README.md
> Fix ag readme

- plugins/git-auto-fetch/git-auto-fetch.plugin.zsh
- Add a date to the git-auto-fetch log to know when was the last fetch
@mcornella
> feat(git-auto-fetch): add date to git-auto-fetch log file

- plugins/archlinux/README.md
- plugins/archlinux/archlinux.plugin.zsh
> feat(archlinux): add cleanup aliases to `yaourt` and `yay`

- plugins/jsontools/README.md
- plugins/jsontools/jsontools.plugin.zsh
- refactor(jsontools): restructure and simplify logic
- refactor(jsontools): move to functions, align `is_json` tool to return exit code
- feat(jsontools): add tools to pretty print json-lines (ndjson) (#10176)
Closes #10176
> refactor(jsontools): refactor and add NDJSON support

- plugins/python/README.md
> docs(python): update README to include new `py` alias

- plugins/chucknorris/fortunes/chucknorris
> chore(chucknorris): add a few more Chuck Norris quotes

- plugins/z/z.sh
Updates the z plugin to use https://github.com/rupa/z/commit/b82ac78a2d4457d2ca09973332638f123f065fd1
Which includes a fix for https://github.com/rupa/z/issues/92 + some other fixes 🙂 
- Updates z to latest commit 
...
> feat(z): update z to latest version

- plugins/sublime/sublime.plugin.zsh
add Sublime Text 4 path for Windows 10
> feat(sublime): add support for Sublime Text 4 on Windows

- CONTRIBUTING.md
Fixes a minor typo in `CONTRIBUTING.md`
> chore: fix grammar mistake in `CONTRIBUTING.md`

- plugins/kn/README.md
- plugins/kn/kn.plugin.zsh
- adding a plugin to add `kn` command line completion
> feat(kn): add plugin for `kn` completion

- plugins/volta/README.md
- plugins/volta/_volta
- Add [Volta](https://volta.sh/) autocompletion.
> feat(volta): add volta plugin

- plugins/istioctl/README.md
- plugins/istioctl/istioctl.plugin.zsh
> feat(istioctl): add plugin for istioctl

- plugins/jfrog/jfrog.plugin.zsh
- Add auto completion support to jfrog's `jf` executable name.
> feat(jfrog): Support jf executable auto completion

- plugins/operator-sdk/README.md
- plugins/operator-sdk/operator-sdk.plugin.zsh
> feat(operator-sdk): add plugin for operator-sdk

- README.md
- [X ] The PR title is descriptive.
- [ X] The PR doesn't replicate another PR which is already open.
- [ X] I have read the contribution guide and followed all the instructions.
- [ X] The code follows the code style guide detailed in the wiki.
- [ X] The code is mine or it's from somewhere with an MIT-compatible license.
- [ X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ X] The code is stable and I have tested it myself, to the best of my abilities.
- Add a note explaining that the current `.zshrc` will be moved immediately after instructions on executing script.
My attempt at #9658
> docs(README): Document .pre-oh-my-zsh

- plugins/rvm/README.md
- plugins/rvm/rvm.plugin.zsh
- add alias `rvms` to `rvm gemset`
> feat(rvm): add alias `rvms`

- plugins/yarn/_yarn
Upgrade `yarn` completions to latest version, found [here](https://github.com/zsh-users/zsh-completions/blob/master/src/_yarn)
> feat(yarn): upgrade completion to latest version

- plugins/pip/pip.plugin.zsh
The title is absolutely clear :)
This PR closes #10421
> feat(pip): alias `pip` to `pip3` if pip is missing

- plugins/oc/README.md
- Update outdated link to point to the latest documentation in the oc README
Paging @kevinkirkup as you're the plugin author... Super tiny minor change.
I hope a tiny PR like this isn't frowned upon 😃
> docs(oc): update link to openshift CLI reference

- plugins/aliases/README.md
- docs(aliases): clarify usage
I've re-used image from [original comment](https://github.com/ohmyzsh/ohmyzsh/pull/4662#issuecomment-161872641), because "an image is worth 1.000 words" ;-)
Should I include it in the repo instead of linking it?
> docs(aliases): clarify usage

- plugins/fossil/_fossil
- plugins/fossil/fossil.plugin.zsh
For fossil it only makes sense to 'add' files which aren't currently
tracked in the repo.
http://fossil-scm.org/home/help?cmd=add
> feat(fossil): add completion for `fossil add`

- plugins/gcloud/gcloud.plugin.zsh
- Include newer Homebrew path to Google Cloud SDK
Hey @ianchesal, I've added the path for newer Homebrew instalations.
> feat(gcloud): support Homebrew Google Cloud SDK path

- plugins/repo/_repo
Done with repo 2.8
Add stage subcommand
Add arguments for start subcommand
- [...]
...
> feat(repo): add command completion for repo 2.8

- plugins/ipfs/_ipfs
- Updates completion script for IPFS version 0.8.0
Tested with:
```
$ ipfs version --all
go-ipfs version: 0.8.0-ce693d7
Repo version: 11
System version: amd64/darwin
Golang version: go1.14.15
```
> Update completion script for IPFS version 0.8.0

- plugins/common-aliases/README.md
- plugins/common-aliases/common-aliases.plugin.zsh
This commit add two aliases in `common-aliases` plugin
@ohmyzsh
- [...]
...
> feat(common-aliases): add single-column and recursive `ls` aliases

- plugins/vi-mode/README.md
> docs(vi-mode): fix link typo in readme

- plugins/yarn/_yarn
Updating `yarn` completion to latest version, found [here](https://github.com/zsh-users/zsh-completions/blob/master/src/_yarn).
Closes #10578
> fix(yarn): update completion

- plugins/fig/README.md
- plugins/fig/fig.plugin.zsh
Adds autocomplete for [Fig](https://fig.io)
- Add [Fig](https://fig.io) autocompletion plugin
> feat(fig): add plugin for Fig

- plugins/poetry/README.md
- plugins/poetry/poetry.plugin.zsh
- Adds a `poetry` plugin that provides tab completion for the [poetry](https://python-poetry.org/) CLI. 
Based on PR #7353.
@mcornella
> feat(poetry): add plugin to provide completion for Poetry

- themes/ys.zsh-theme
- feat(ys): show svn repo info
@ysmood
> feat(ys): show `svn` repository information

- plugins/1password/1password.plugin.zsh
- plugins/1password/README.md
- adds a [1password](https://1password.com/) plugin
> feat(1password): add plugin for 1password

- plugins/ripgrep/README.md
- plugins/ripgrep/_ripgrep
> feat(ripgrep): update `rg` completion to v13.0.0

- plugins/fd/README.md
- plugins/fd/_fd
> feat(fd): update `fd` completion to v8.3.2

- plugins/kubectl/kubectl.plugin.zsh
> fix(kubectl): support completion for snap installs

- plugins/dash/dash.plugin.zsh
- fix(dash): fix "no application knows how to open URL" error (#10767)
- perf(dash): improve dash completion performance
Fixes #10767
> fix(dash): fix "no application knows how to open URL" error

- plugins/cargo/cargo.plugin.zsh
- plugins/deno/deno.plugin.zsh
- plugins/fnm/fnm.plugin.zsh
- plugins/gh/gh.plugin.zsh
- plugins/helm/helm.plugin.zsh
- plugins/kubectl/kubectl.plugin.zsh
- plugins/rbw/rbw.plugin.zsh
- plugins/rust/rust.plugin.zsh
- plugins/rustup/rustup.plugin.zsh
- plugins/volta/volta.plugin.zsh
> chore: removing old completion code

- plugins/charm/README.md
- plugins/charm/charm.plugin.zsh
- Add completions from `charm completion zsh`
N/A
> feat(charm): add plugin for `charm`

- plugins/bazel/README.md
- Update bazel completion link
> docs(bazel): improve plugin README

- plugins/aliases/aliases.plugin.zsh
- plugins/aliases/cheatsheet.py
- plugins/git-prompt/README.md
- plugins/git-prompt/git-prompt.plugin.zsh
- plugins/git-prompt/gitstatus.py
- plugins/jsontools/jsontools.plugin.zsh
- plugins/pyenv/pyenv.plugin.zsh
- plugins/python/README.md
- plugins/python/python.plugin.zsh
The title is descriptive.
Closes #10469
Closes #10681 
Closes #10775
Closes #10777 
Closes #10796 
(and probably many others)
> fix: use `python3` for all `python` invocations

- CONTRIBUTING.md
- README.md
- Updated the rename target; it's `.zshrc.pre-oh-my-zsh` now, not just `.pre-oh-my-zsh`
- Listed Nerd Fonts in the note previously saying that many themes require a powerline font; while true, there's many that require more symbols. Purely meta
- A couple additional, minor sentence changes
> chore: minor documentation tweaks

- lib/git.zsh
> Revert "fix(lib): don't return clean with `hide-dirty=1` in `parse_git_dirty`"

- plugins/kube-ps1/README.md
- plugins/kube-ps1/kube-ps1.plugin.zsh
To view the list of updates, please visit https://github.com/jonmosco/kube-ps1/commits/master
- To view the full list of updates, please visit https://github.com/jonmosco/kube-ps1/commits/master
> chore(kube-ps1): update to most recent version

- plugins/brew/README.md
- plugins/brew/brew.plugin.zsh
Title is quite descriptive 👍🏻 
Closes #10389
> feat(brew): add `brew shellenv` command at plugin load

- plugins/aws/aws.plugin.zsh
> feat(aws): only disallow spaces for profile names

- plugins/copybuffer/README.md
> docs(copybuffer): format shortcut and lighten text

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- Document alias changes in CONTRIBUTING file
- Add checkbox in new PR template
cc @carlosala @robbyrussell @larson-carter
> docs: document new aliases policy

- plugins/gitfast/git-completion.bash
- plugins/gitfast/git-prompt.sh
- plugins/gitfast/update
Just a minor update to sync it with upstream git.
> feat(gitfast): update to git-completion 1.3.7

- plugins/emoji/update_emoji.py
- plugins/lpass/_lpass
- plugins/ng/_ng
- plugins/pm2/_pm2
- plugins/salt/_salt
- plugins/swiftpm/_swift
- plugins/systemadmin/README.md
- plugins/terraform/_terraform
- tools/require_tool.sh
> chore(docs): fix some typos

- plugins/dnote/README.md
- Link to project website was wrong
- Improved plugin description
> Fix incorrect link

- plugins/web-search/README.md
- plugins/web-search/web-search.plugin.zsh
Added brave browser to the web search list, as well as my own alias.
- [...]
...
> feat(web-search): add support for Brave search engine

- CONTRIBUTING.md
> word replacement line #236

- plugins/asdf/README.md
- Fix outdated links in asdf plugin
- Reorder installation instructions to match the document
- Add some usage commands
> Update asdf plugin outdated links and description

- CONTRIBUTING.md
Corrected grammatically incorrect sentences, punctuations and typos for better readability.
- [Corrected grammatically incorrect sentences, punctuations and typos for better readability.]
...
> Corrected grammatically incorrect sentences, punctuations and typos for better readability. 

- plugins/brew/brew.plugin.zsh
- fix(brew): suppress error message of brew cask on Linux
> fix(brew): suppress error message of brew cask on Linux

- plugins/web-search/README.md
- plugins/web-search/web-search.plugin.zsh
`Ask.com` search added to web-search plugin, README modified accordingly
Useful for students and is among top 5 search engines based on performance
> feat(web-search): add ask.com

- plugins/wd/README.md
- plugins/wd/wd.sh
https://github.com/mfaerevaag/wd/releases/tag/v0.5.2
> feat(wd): update to latest upstream release

- plugins/hasura/README.md
- plugins/hasura/hasura.plugin.zsh
- Adds a plugin for [the Hasura CLI](https://hasura.io/docs/latest/hasura-cli/index/) that adds shell completions.
> feat(hasura): add completion plugin

- plugins/colorize/colorize.plugin.zsh
- fix the dead conditional code in requirements check.
> fix(colorize): check if $ZSH_COLORIZE_TOOL exists

- plugins/bgnotify/bgnotify.plugin.zsh
- perf(bgnotify): cache terminal app ID computation
- refactor(bgnotify): clean up and reorganize code
- Standardize code style
- Organize code sections
- Optimize calls for window ID
Fixes #10971
> Refactor and optimize performance of bgnotify plugin

- plugins/git/README.md
- plugins/git/git.plugin.zsh
- add `gcn` alias for `git commit -v --no-edit`
Fixes #10835
cc @mcornella
> feat(git): add `gcn` alias

- plugins/aliases/README.md
> docs(aliases): fix typos

- plugins/pre-commit/README.md
- plugins/pre-commit/pre-commit.plugin.zsh
- Adding a new plugin with common aliases for [pre-commit](https://pre-commit.com/) 
Maintainers: @hofbi @cbachhuber 
...
> feat(pre-commit) add aliases

- plugins/mvn/mvn.plugin.zsh
- Adds completion for Vaadin maven plugin goals
> feat(mvn): add completion for Vaadin

- plugins/helm/README.md
- plugins/helm/helm.plugin.zsh
- [ X] If the code introduces new aliases, I provide a valid use case for all plugin users below.
I already checked aliases haven't conflict with other aliases or commands.
> feat(helm): add aliases

- plugins/pip/README.md
- plugins/pip/pip.plugin.zsh
> feat(pip): add several aliases

- plugins/heroku-alias/README.md
- plugins/heroku-alias/heroku.alias.sh
<details>
<summary>Click to expand!</summary>
| Alias  | Command |
| ------------- | ------------- |
| h | heroku |
| hauto | heroku autocomplete $(echo $SHELL) |
| hl | heroku local |
| Alias  | Command |
| ------------- | ------------- |
| hc | heroku config |
| hca | heroku config -a |
| hcr | heroku config -r |
| hcs | heroku config:set |
| hcu | heroku config:unset |
| hcfile | function hcfile bellow |
```sh
hcfile() {
echo " Which platform [-r/a name] ? "
read platform
echo " Which file ? "
read file
while read line;
do heroku config:set "$platform" "$line";
done < "$file"
}
```
| Alias  | Command |
| ------------- | ------------- |
| ha | heroku apps |
| hpop | heroku create |
| hkill | heroku apps:destroy |
| hlog | heroku apps:errors |
| hfav | heroku apps:favorites |
| hfava | …
> heroku cli alias

- plugins/jira/README.md
- plugins/jira/jira.plugin.zsh
- [jira plugin] Added new environment variable JIRA_TEMPO_PATH to allow change the path for **tempo** url
> feat: add optional jira plugin "tempo" path

- plugins/qrcode/README.md
- plugins/qrcode/qrcode.plugin.zsh
- adds commands `qrcode` and `qrsvg`
...
> feat(qrcode): new plugin to generate qrcode via https://qrcode.show

- plugins/qrcode/README.md
> docs(qrsvg): fix command example

- plugins/extract/extract.plugin.zsh
> feat(extract): add `pbzip2` and `pixz`

- plugins/fasd/README.md
While both are now basically unmaintained, whjvenyl's fork is a touch more recent.
Changed one link in a readme to a more recently maintained fork
> docs(fasd): recommend fork over original fasd

- plugins/extract/README.md
- plugins/extract/_extract
- plugins/extract/extract.plugin.zsh
- feat(extract): add zpack support
...
> feat(extract): add zpack support

- plugins/gradle/_gradle
- I updates the plugin code from upstream at [gradle/gradle-completion](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/gradle/_gradle).
PS What's the recommended practice for keeping `ohymzsh`'s plugin in sync with upstreams?
> feat(gradle): update completion from upstream

- plugins/lando/README.md
- Added docs for php support
PHP support was added in https://github.com/ohmyzsh/ohmyzsh/pull/10146, but this is not reflected in the readme. This PR fixes that.
> docs(lando): document php support

- plugins/terraform/README.md
- plugins/terraform/terraform.plugin.zsh
- add alias `tfc` for terraform console
N/A
> feat(terraform): add `tfc` alias

- plugins/azure/azure.plugin.zsh
> fix(azure): load completion properly for brew

- plugins/nodenv/README.md
- plugins/nodenv/nodenv.plugin.zsh
- Adds the "nodenv" plugin, similar to the ones for rbenv and pyenv
> feat(nodenv): add plugin for `nodenv`

- plugins/gnu-utils/gnu-utils.plugin.zsh
- Add [indent](https://www.gnu.org/software/indent/), a GNU program, to the list of programs to check for.  
The indent program changes the appearance of a C program by inserting or deleting whitespace.
> feat(gnu-utils): add `gindent`

- plugins/macos/spotify
- Just updating a URL in Spotify's plugin
> Fix Spotify for Developers URL in plugin docs

- plugins/archlinux/archlinux.plugin.zsh
- Fixed Arch Linux upgrade's keyring update function.
...
> feat(archlinux): fix keyring update function

- plugins/archlinux/archlinux.plugin.zsh
- Blend appearance of `upgrade` function with Pacman and other Pacman helpers
...
> feat(archlinux): blend keyring update function

- plugins/aws/README.md
- plugins/aws/aws.plugin.zsh
Add improvements to aws_change_access_key to catch more error conditions
and give more useful feedback.
Offer to deactivate the old access key after the new one is
generated and in place.
> feat(aws)!: improve `aws_change_access_key`

- .github/CODEOWNERS
- plugins/starship/README.md
- plugins/starship/starship.plugin.zsh
- Add starship prompt as a zsh plugin
...
> feat(starship): create plugin

- themes/robbyrussell.zsh-theme
- [] bugfix for multiline command mess up on editing for robbyrussell theme
> fix(robbyrussell) multiline command editing

- plugins/archlinux/archlinux.plugin.zsh
Improve the performance of `paclist` by using `xargs` to execute it in parallel.
This is actually a follow-up to the previous PR #11398.
> perf(archlinux): improve `paclist` performance

- plugins/git-extras/README.md
Inform user this plugin requires an external repo needs to be installed to use this.
- [x ] The PR title is descriptive.
- [x ] The PR doesn't replicate another PR which is already open.
- [x ] The code is mine or it's from somewhere with an MIT-compatible license.
- [x ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x ] The code is stable and I have tested it myself, to the best of my abilities.
- [...]
...
> docs(git-extras): clarify readme

- themes/fino-time.zsh-theme
> feat(fino-time): add conda environment

- themes/agnoster.zsh-theme
> feat(agnoster): add git tag to prompt

- plugins/qodana/README.md
- plugins/qodana/qodana.plugin.zsh
- Add shell completion for `qodana` CLI
Based this one on the `gh` plugin, just updated the README.md based on the changes in that plugin
> feat(qodana): add completion plugin

- plugins/git-commit/README.md
- plugins/git-commit/git-commit.plugin.zsh
- Add a plugin that adds git aliases for conventional commits
https://www.conventionalcommits.org/en/v1.0.0/#summary
> feat(git-commit): create plugin

- themes/gallois.zsh-theme
- Simple update to a theme
Should be fairly innocuous, as it's just changing a theme. I've been using this for a few years now without any issue
> feat(gallois): big rewrite to `gallois` theme

- plugins/git-commit/git-commit.plugin.zsh
- fix(git-commit): fix non-posix condition and array in alias
Closes #11882
> fix(git-commit): fix compatibility of alias functions

- plugins/poetry-env/README.md
- plugins/poetry-env/poetry-env.plugin.zsh
- Automatically change poetry environment when you cd into and out of a directory.
PR #10028 was created for this but author didn't reply/update for a long time and changes are not merged as well (pending review). Hence creating this PR again to add poetry-env feature.
> feat(poetry-env): create plugin

- README.md
Edited 2 Headings to title case
- [...]
...
> chore: change headings in README to Title Case

- plugins/hitchhiker/fortunes/hitchhiker
- [x ] The PR title is descriptive.
- [ x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
Typos fixed:
decribing -> describing
attendent -> attendant
Foreward -> Foreword
addded -> added
- [...]
...
> chore(hitchhiker): fix typos

- plugins/bazel/_bazel
> feat(bazel): use completion also for bazelisk

- plugins/history/README.md
- plugins/history/history.plugin.zsh
- Pipe history output to less to search and navigate it easily.
The large result of the history command often scrolls the screen. Running it through the less command makes it much easier: reading, searching, and navigating.
> feat(history): add `hl` alias

- plugins/vi-mode/vi-mode.plugin.zsh
- [ x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
- Using `p` to paste clipboard in visual mode.
...
> feat(vi-mode): allow replacing on visual mode

- plugins/bgnotify/bgnotify.plugin.zsh
- Minor cleanup by using named parameter variables instead of numbered parameter variables
- If using Wayland but not Sway, it will no longer fetch app_id from [xprop](https://man.archlinux.org/man/xprop.1.en), which gives the wrong result.
- Added an icon parameter to the `bgnotify` function. While this is unused currently, it allows the user to put something like this in their ~/.zshrc to set the icon depending on the command's exit status:
```
function bgnotify_formatted {
[ $1 -eq 0 ] && title="Great success" || title="Command failed"
[ $1 -eq 0 ] && icon="$HOME/icons/success.png" || icon="$HOME/icons/fail.png"
bgnotify "$title - took ${3}s" "$2" "$icon"
}
plugins=(git bgnotify sudo)  # for example
```
> feat(bgnotify): add icon parameter

- plugins/bgnotify/README.md
- Updating Readme to the bgnotify plugin:
* Showcasing how the icon parameter (that was introduced in #12055) can be used
* The text now talks about Linux in general rather than specifically Ubuntu.
* Minor Markdown cleanup
> docs(bgnotify): match README with current features

- plugins/dotnet/dotnet.plugin.zsh
- Copied the newest changes from the .NET team
> feat(dotnet): update completion script

- plugins/react-native/README.md
- plugins/react-native/react-native.plugin.zsh
- add aliases for iPhone:
- iPhone 15
- iPhone 15 Plus
- iPhone 15 Pro
- iPhone 15 Pro Max
> feat(react-native): add aliases for iPhone 15

- plugins/rails/_rails
Source: https://github.com/zsh-users/zsh-completions/blob/f7c3173886f4f56bf97d622677c6d46ab005831f/src/_rails
Includes the typo fix from #11293
> feat(rails): update completion script

- plugins/git/README.md
> docs(git): align `gpristine` alias

- plugins/python/python.plugin.zsh
Added command line args support to ipython alias, fixes: #12153
n/a
> fix(python): add support for cli args

- plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
- Add the following hook: `add-zsh-hook precmd workon_cwd` enabling the plugin to run when new windows, panels or tabs are created on the same directory. Otherwise you will need to cd out, then cd in.
...
> feat(virtualenvwrapper): run function on startup

- plugins/ssh/ssh.plugin.zsh
- This is an updated version of #2707, applying a commit which addresses review feedback on top of the commits from the original author @elias5000
- Regarding the second and third checkboxes, obviously this does duplicate an open PR, and while I've READ the contributors guide, this PR doesn't follow all instructions. The commits lack Conventional Commits style titles.
- Regarding the seventh checkbox, I haven't tested all of this code myself, as I don't use most of these features.
cc: @carlosala
> feat(ssh): add plugin

- plugins/stripe/README.md
- plugins/stripe/stripe.plugin.zsh
- Adds a plugin for the Stripe CLI autocompletion
> feat(stripe): add completion plugin

- lib/completion.zsh
> style(completion): remove extra space

- README.md
No need to test
add star history and contributor list to README.
- Increases project transparency: This can help other developers understand the popularity and activity level of the project.
- Recognizes contributors: Listing contributors can recognize those who have contributed to the project, which may also motivate more people to participate in the project.
- Provides more information: The star history chart and contributor list provide more information for potential users or contributors, helping them make decisions about whether to use or participate in the project.
Enhances the project's professionalism: A detailed README file can enhance the professionalism of the
> docs(readme): add contributor list

- plugins/pyenv/README.md
> docs(pyenv): fix typo

- lib/cli.zsh
- plugins/catimg/README.md
- plugins/emacs/README.md
- plugins/emacs/emacs.plugin.zsh
- plugins/ipfs/_ipfs
- plugins/nomad/_nomad
- plugins/per-directory-history/per-directory-history.zsh
- plugins/ssh-agent/README.md
> docs: fix typos

- plugins/git-prompt/README.md
- Add clarification to README about need to modify/customise theme in order to use the git-prompt plugin
Basically summarises the comments on the issue https://github.com/ohmyzsh/ohmyzsh/issues/9395
> Update README for git-prompt to clarify how to use

- lib/termsupport.zsh
- feat(termsupport): Support alacritty* $TERM in title() function (ohmyzsh#12391)
> feat(termsupport): support `alacritty*` TERM

- plugins/procs/README.md
- plugins/procs/procs.plugin.zsh
- Plugin with completions for [procs](https://github.com/dalance/procs) has been added
> feat(procs): add completions plugin

- plugins/stripe/README.md
> docs(stripe): fix typo

- custom/example.zsh
- plugins/eza/README.md
- plugins/eza/eza.plugin.zsh
- Give the possibility to display icons with eza command
> feat(eza): add icons option

- plugins/forklift/forklift.plugin.zsh
This adds support for ForkLift 4.  Fixes #12490.
Setting the value of text field does not work anymore, so I used keystroke with small delay afterwards (very low value is enough, otherwise the new path is not passed correctly).
> feat(forklift): add support for ForkLift 4 (#12490)

- plugins/symfony6/README.md
- plugins/symfony6/symfony6.plugin.zsh
Don't mind me...I'm on a plane hitting merge too quickly and needed to fix the commit message format so that Carlo and Marc don't yell at me this week in Berlin. ;-)
Reverts ohmyzsh/ohmyzsh#12493
> feat(symfony6): Add plugin for native autocompletion from Symfony 6

- README.md
- tools/upgrade.sh
- Rename Twitter to X (I guess time has come already, X is recognizable compared to 2023)
- fix  URL in README
...
> docs: rename twitter to X, fix link

- plugins/battery/README.md
- plugins/battery/battery.plugin.zsh
- added a simple customizable variable
> feat(battery): support custom AC indicator

- plugins/eza/README.md
- plugins/eza/eza.plugin.zsh
- Add `--hyperlink` as an option to *eza* using zstyle configuration
Note: the *eza* `--hyperlink` option is not fully compatible with *ls* as it does not have the `[=WHEN]` setting.
> feat(eza): add hyperlink option

- plugins/git/README.md
- plugins/git/git.plugin.zsh
- fetch all tags from remote when using `gfa`
Alternative would be to introduce a `gfat` git fetch all tags alias?
> feat(git): fetch tags in `gfa` alias

- plugins/brew/README.md
See-also: #7536
- Removes reference to bubc
This was accidentally missed. `¯\_(ツ)_/¯`. Code-related boxes unchecked because this isn't... code :smile:.
> docs(brew): remove reference to bubc

- plugins/brew/brew.plugin.zsh
- Remove duplicate **alias bup='brew upgrade'**
> duplicate(brew): alias bup='brew upgrade'

- plugins/git/README.md
- plugins/git/git.plugin.zsh
- Turn `gpf` alias into a function that shows a yes/no prompt
- Rename `git push --force-with-lease` to `gpff`
Fixes #10168
> feat(git)!: ask for confirmation in `gpf` alias

- plugins/mix/README.md
- plugins/mix/_mix
This allows autocompletion of the command `mix test.watch` itself but more important for following files too. So `mix test.watch TAB TAB` does show files finally instead of just nothing.
> feat(mix): add mix plugin test.watch

- plugins/tailscale/README.md
- plugins/tailscale/tailscale.plugin.zsh
- [ x ] The PR title is descriptive.
- [ x ] The PR doesn't replicate another PR which is already open.
- [ x ] I have read the contribution guide and followed all the instructions.
- [ x ] The code follows the code style guide detailed in the wiki.
- [ x ] The code is mine or it's from somewhere with an MIT-compatible license.
- [ x ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ x ] The code is stable and I have tested it myself, to the best of my abilities.
- Created tasko function
- Created README.md file
There is another closed PR #11540 / Issue #11539
- which only added an alias for mac support, we could consider including that too.
> feat(tailscale): new tailscale plugin

- plugins/ssh-agent/ssh-agent.plugin.zsh
Add id_ed25519_sk to the keys supported by the ssh-agent plugin
> feat(ssh-agent): support `id_ed25519_sk`

- lib/functions.zsh
Fixes #12669
- Adds a `takezip` function to the `functions.zsh` file to handle ZIP downloads with `take`
- Adds a conditional to the `take` function to call `takezip` if the URL is a ZIP file.
...
> feat(functions): add `takezip`

- plugins/web-search/README.md
- plugins/web-search/web-search.plugin.zsh
- add `reddit` alias options to a web search plugins
[recording_20240911-233622.webm](https://github.com/user-attachments/assets/a085a827-8ebb-40c3-ab66-679d2468dd50)
...
> feat(web-search): add `reddit`

- plugins/k9s/README.md
- plugins/k9s/k9s.plugin.zsh
This adds k9s command completions as plugin
> feat(k9s): add completion plugin for `k9s`

- plugins/buf/README.md
- plugins/buf/buf.plugin.zsh
Introduce [buf](https://github.com/bufbuild/buf) plugin.
A better implementation of #12752 
...
> feat(buf): add completion plugin

- plugins/rclone/README.md
- plugins/rclone/rclone.plugin.zsh
Introduce [Rclone](https://rclone.org/) plugin.
Largely inspired by the deno plugin ;)
> feat(rclone): create completion plugin

- .devcontainer/devcontainer.json
- .editorconfig
- templates/minimal.zshrc
- templates/zshrc.zsh-template
- Added baseline devcontainers configuration
- Added minimal zshrc file
- Needs fixing error messages on startup
Fixes #12730
Fixes #12731
> feat: add `devcontainers` configuration

- plugins/vault/README.md
- plugins/vault/vault.plugin.zsh
Re-introduce [Vault](https://www.vaultproject.io/) plugin.
Previous vault plugin have been deprecated, then removed, because there is now an official completion. This new version exactly use this one :)
> feat(vault): re-introduce vault plugin

- plugins/timoni/README.md
- plugins/timoni/timoni.plugin.zsh
Fixes #12801
- Add plugin for Timoni
> feat(timoni): add completion plugin

- lib/misc.zsh
- plugins/macports/README.md
- plugins/opentofu/README.md
> chore: fix some typos

- plugins/ngrok/README.md
- plugins/ngrok/ngrok.plugin.zsh
> feat(ngrok): add completion plugin

- .github/dependencies.yml
- Update dependencies.yml to the new layout of git-completion
> ci(deps): update `gitfast` to its new structure

- plugins/jira/README.md
- plugins/jira/jira.plugin.zsh
> feat(jira): allow branch name customization

- plugins/git-auto-fetch/README.md
> Fixing function name in README.md

- plugins/ember-cli/README.md
> docs(ember-cli): fix typo

- plugins/rand-quote/rand-quote.plugin.zsh
- Update the url from http to https
> fix(rand-qoute): Fix url for plugin (now uses strict https)

- plugins/mix/_mix
> Completions for mix format

- plugins/jira/README.md
- plugins/jira/_jira
- plugins/jira/jira.plugin.zsh
> Add option to open jira project

- README.md
- [] The code follows the code style guide detailed in the wiki.
- Fixed some small typos
I really enjoyed using this project, nice work! Caught a couple of typos in the README though 😛
> docs(typo): Update README.md, fix typos

- plugins/asdf/README.md
Update asdf usage examples for versions >= 0.16.0 (Go binary release)
- Added another commonly used uninstall command
- Clarified flag meanings for `asdf set` instead of writing shorthand directly
- Referred to `asdf help` and official docs for discovering more commands
N/A
> doc(asdf): update usage example

- plugins/pip/README.md
…tation table
- Updated the pip plugin README.md to improve readability and clarity.
- Added a clean table listing all existing plugin aliases with their respective commands and descriptions.
- No functional or code changes to the plugin itself — documentation only.
The updated documentation makes it easier for users to quickly understand and use the available pip aliases without having to look through the plugin file.
Should be a helpful quality-of-life improvement for anyone using this plugin.
> docs(pip): improve plugin README with clearer alias descriptions

- plugins/rsync/README.md
improved the documentation of the rsync plugin
> docs(rsync): improved the documentation of the rsync plugin

- plugins/laravel/README.md
- plugins/laravel/laravel.plugin.zsh
add alias for php artisan db:wipe
- [X ] The PR title is descriptive.
- [X ] The code follows the code style guide detailed in the wiki.
- [ X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X ] The code is stable and I have tested it myself, to the best of my abilities.
- [X ] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
- [...]
...
> Update laravel.plugin.zsh Adds db:wipe alias

- .github/INCIDENT_RESPONSE_PLAN.md
> Document Incident Response Plan

- .github/workflows/dependencies.yml
- Adds strict permissions to the dependencies workflow:
- ~~`contents:write`: create commits and branches (not to main).~~
- ~~`issues:write`: create issues (for manual dependency update).~~
- ~~`pull-requests:write`: create pull requests (for automatic dependency update).~~
- `contents:read`: just the necessary for GitHub repo checkout.
> ci: add strict permissions to `dependencies.yml` workflow

- plugins/spackenv/README.md
- plugins/spackenv/spackenv.plugin.zsh
- Plugin displays Spack environment and allows background theming.
- Based on the `virtualenv` plugin.
- Provides the function `spackenv_prompt_info`
[Spack](https://spack.io) is a software/package management system commonly used in high performance computing environments.
> Spackenv plugin

- plugins/repo/_repo
- Added auto completion for update-refs
> feat(git): auto-complete docs rebase update-refs

- plugins/task/README.md
- plugins/task/task.plugin.zsh
> feat(task): support task completion plugin

- .github/workflows/project.yml
There is no inherent security vulnerability in the workflow, but there were certain practices that increased latent risk. In this commit, we:
- Explicitly bind app token for each step that needs it, instead of setting it for all steps after "Store app token"
- Refactor "classify" step, to not rely on files passed around, and instead uses only awk script.
- Remove all instances of template injection within `run` scripts. There was nothing dangerous, but the practice is unsafe.
- Sanitize all unwanted characters from PR plugin and theme names.
References: W2M1-06 W2M1-07
> ci: improve security in project.yml workflow
