ohmyzsh/ohmyzsh

plugins/aws/aws.plugin.zsh
Closes #9122
The current check is assuming that the aws_completer is installed
globally, it then runs the command without that path
I have aws_completer in ~/.local/bin/aws_completer
This changes the check to see if the command exists instead of
concerning itself with where it in installed. This test matches the
behavior of just running the command.
- use `command` to check for aws_completer instead of hardcoded path
=> aws: improve check for aws_completer - unhardcode path

plugins/colorize/README.md, plugins/colorize/colorize.plugin.zsh
In order to get colorize to work with my setup I needed to change the formatter chroma was using to `terminal256`. This updates colorize to look for a new $ZSH_COLORIZE_CHROMA_FORMATTER env var to set this value.
- Check for the existence of `$ZSH_COLORIZE_CHROMA_FORMATTER` and if present add a `--format` flag to the `chroma` call
Super simple low risk change.
=> colorize: add $ZSH_COLORIZE_CHROMA_FORMATTER config env var

plugins/sudo/sudo.plugin.zsh
- Just the main file of the 'sudo' plugin
...
=> sudo: keep space before the command to ignore it in the history

themes/pygmalion-virtualenv.zsh-theme, themes/pygmalion.zsh-theme
My system doesn't have `perl` in $PATH, so using this theme clutters the
shell output quite a bit.
Given these are simple regexp substitutions, these can be done by `sed`,
which is more likely to be available.
- use `sed` instead of `perl` to do the regexp substitution.
I'm not sure if this works with the `sed` coming with MacOS, so probably should be tested there as well.
=> pygmalion: use pure zsh instead of perl

plugins/fzf/README.md, plugins/fzf/fzf.plugin.zsh
Setting the FZF_DEFAULT_COMMAND allow fzf to use a faster searcher
- Set `$FZF_DEFAULT_COMMAND` on `fzf` plugin
This PR is based on a personal necessity, since I was having to do this on my config, and I found an issue related to it (#8187), that was close because there was no PR
=> fzf: setup FZF_DEFAULT_COMMAND based on installed tools

tools/upgrade.sh
Add `exit 1` to return an error status if `omz update` fails. This replaces an implicit `0`.
=> update: return git error code on failure

plugins/pyenv/pyenv.plugin.zsh
Add --no-rehash to the pyenv init command, which was removed in [#4492].
The rehash was likely disabled because it can affect shell startup times.
It should only be necessary when installing or removing Python versions.
See [pyenv/pyenv#784] and [sorin-ionescu/prezto#1603] for more detail.
[#4492]: https://github.com/ohmyzsh/ohmyzsh/pull/4492
[pyenv/pyenv#784]: https://github.com/pyenv/pyenv/issues/784
[sorin-ionescu/prezto#1603]: https://github.com/sorin-ionescu/prezto/pull/1603
=> Run pyenv init with --no-rehash

plugins/minikube/minikube.plugin.zsh
- Replace "minicube" by correct spelling, "minikube" (cf https://minikube.sigs.k8s.io)
=> minikube: fix spelling

plugins/pip/pip.plugin.zsh
- Move pip plugin's cache file to $XDG_CACHE_HOME/pip which is ~/.cache/pip by default  #9213
...
=> pip: move plugin cache to XDG folder

plugins/sublime-merge/README.md, plugins/sublime-merge/sublime-merge.plugin.zsh
I've tried to put together a plugin similar to [`sublime`](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/sublime) but for [Sublime Merge](https://www.sublimemerge.com). I've used the `sublime` as the base and adjusted it with Sublime Merge. In the process, I've changed the `$*` to `"@*"` as I read that it's more robust. It shouldn't be very relevant in the case of Sublime Merge, but I thought why not?
P.S. I'm not a `zsh` expert! Please let me know if I'm missing something, or in any way I can improve this :-)
=> Add sublime-merge plugin

plugins/git/git.plugin.zsh
This PR changes `gfa` to run with up to 10 jobs in parallel using `--jobs=10`. This speeds up fetching from many remotes significantly. I arbitrarily chose 10 jobs; I'm using up to 7 remotes on the projects I work with.
I can't think of any reason not to fetch remotes in parallel besides limiting bandwidth or CPU load. In my opinion the speedup is very much worth it.
I'm happy to add a separate alias (e.g. `gfaj` or `gfap`) for parallel fetching if there's opposition to my PR.
=> git: run gfa with --jobs=10 (fetch remotes in parallel)

themes/fino.zsh-theme
Fix dangling "using" word. Add support for python virtualenv.
Currently fino theme has some problems:
1. dangling "using". It should appear only when using ruby or python virtual env, but it is always shown
2. wrong color of the prompt
This PR removes these problems are adds support for python virtualenv:
Most of the code changes are borrowed from fino-time theme.
=> fino: fix dangling "using" and clean up

plugins/z/README, plugins/z/z.1, plugins/z/z.sh
This PR updates the z plugin to the latest available version in the upstream repository:
Commit-id: 125f4dc47e15891739dd8262d5b23077fe8fb9ab
https://github.com/rupa/z/commit/125f4dc47e15891739dd8262d5b23077fe8fb9ab
Before this PR, the z plugin is updated to:
https://github.com/rupa/z/commit/e77e9384937bd43eb6ca8f1ba036924f4006df07
With this PR, the z plugin is updated to:
https://github.com/rupa/z/commit/125f4dc47e15891739dd8262d5b23077fe8fb9ab
Upstream diff commits:
https://github.com/rupa/z/compare/e77e9384937bd43eb6ca8f1ba036924f4006df07...125f4dc47e15891739dd8262d5b23077fe8fb9ab
=> z: upgrade plugin to the latest version

plugins/kubectl/README.md, plugins/kubectl/kubectl.plugin.zsh
- Add two wrapper functions to the kubectl plugin for colorized output
=> kubectl: add wrappers for colorized output in JSON and YAML

lib/termsupport.zsh
In Ubuntu and Debian, in scp, and in rsync the prompt is by default specified as in `user@hostname:/path/to/directory`
Before this patch, ohmyzsh set the title of the window to `user@hostname: /path/to/directory` (notice the space)
This PR unifies makes the window title to be set accordingly to the standards above.
- See above
=> lib: follow standards in window title

plugins/safe-paste/safe-paste.plugin.zsh
* Prefer built-in bracketed paste goodness if zsh version >= 5.1
* Save/restore active keymap before/after paste (resolves #7883)
* Attempt to not clobber `zle_line_{init,finish}`
* Partially addresses [Plugins breaks if `zle -N zle-line-init` is called #70](https://github.com/zsh-users/zsh-history-substring-search/issues/70)
* Clear paste content queue before first use
* [Style guide](https://github.com/robbyrussell/oh-my-zsh/wiki/Coding-style-guide)
* Wrap lines at 80 columns
* Remove `function` before function definitions
* Make paste keymap range more readable
* Simplify `$TERM` tests
* Ensure all functions have comments
* Prefix all globals with `bracketed`
* Improve punctuation in comments
Fixes #5237
Fixes #7883
Fixes #8749
Fixes #8886
=> safe-paste: refresh plugin (update for zsh 5.1 and vi keymaps)

lib/nvm.zsh, plugins/nvm/README.md, plugins/nvm/nvm.plugin.zsh
- nvm: use `nvm current` in nvm_prompt_info and look in alternate install locations
This makes it work regardless of where nvm is loaded from. And it uses nvm's version strings, which distinguish the "system" and "none" NVM environments, instead of reporting the specific version of the system node.js or erroring, respectively.
Fixes #4336
Closes #4338
- nvm: simplify nvm.sh and bash completion loading
- nvm: check $XDG_CONFIG_HOME/nvm for an nvm installation
Closes #7807
- nvm: speed-up nvm loading with `--no-use`
Closes #7138
- nvm: only lazy-load nvm if the NVM_LAZY setting is set
- nvm: exit the plugin if the nvm loading script wasn't found
- nvm: add autoloading of nvm version in .nvmrc
Closes #5782
Fixes #8959
Closes #8976
=> nvm: consolidate many changes

plugins/wd/wd.sh
See [here](https://github.com/mfaerevaag/wd/releases/tag/v0.5.1)
=> wd: update to v0.5.1

plugins/mvn/README.md, plugins/mvn/mvn.plugin.zsh
* Add alias `mvnqdev` tu run [Quarkus](https://quarkus.io) in dev mode
* Add Quarkus plugin support in completion
- Fixes #9036
=> mvn: add Quarkus support in mvn completion

plugins/emacs/emacs.plugin.zsh
I used the prompt into emacs, with the commands M-x term, or others, when I began to use zsh, the commands as C-x C-f to find files in emacs  doesn't followed the path to file directory of the prompt, but with this change doesn't matter in which directory I stay, always the commands will follow the path of the directory.
...
=> emacs: add ansi-term directory tracking

plugins/globalias/README.md, plugins/globalias/globalias.plugin.zsh
- Added a really simple array based check to globalias to filter out values that should not be expanded 
- Inspired by multiple unwanted alias expands and closed issue #7550
=> globalias: allow filtering values not to be expanded

plugins/git-prompt/README.md
- Updated the README file to add `python` as a prerequisite
I've installed a new OS (PopOS), based on Ubuntu 20.04, and the `gti-prompt` plugin was not working and no error was shown. After digging, I've found that `python` is a requirement for this plugin and it is not statted anywhere (not even on oh my zsh docs) so I though in saving someone else time, by statting more clearlly this prerequisites
=> git-prompt: document Python prerequisite in README

plugins/globalias/globalias.plugin.zsh
I loved the new feature in #9331 but it had a small problem for me - it only worked when the entirety of LBUFFER matched, meaning that it only prevented expansion when the alias was the first word on the line. This uses parameter expansion to perform a word split on LBUFFER and then match on the last entry in the array, so it will filter expansion regardless of where the alias occurs in the line.
Currently, given:
```
alias grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
GLOBALIAS_FILTER_VALUES=(grep)
```
An initial grep won't be expanded (because LBUFFER="grep" and that matches an item in GLOBALIAS_FILTER_VALUES):
```
> grep forthis file.txt
```
But a piped grep would (because LBUFFER='curl mywebsite.com | grep' which doesn't match):
```
> curl mywebsite.com | …
```
=> globalias: expand filtering to anywhere in the command

plugins/kubectl/kubectl.plugin.zsh
=> kubectl: verify kubectl is installed before running compdef

plugins/cargo/_cargo, plugins/golang/golang.plugin.zsh
- replace instances of “up‑to‑date” with “up to date” when it’s a predicate adjective that follows what it describes[¹](https://english.stackexchange.com/a/180617)&#8239;[²](https://web.archive.org/web/20190728053012id_/grammarist.com/usage/up-to-date/#text-60)
- retain “up‑to‑date”, with hyphens, otherwise, such as at https://github.com/ohmyzsh/ohmyzsh/blob/5b717ab3e4bfb627a936d7c04367a39867734d63/plugins/golang/golang.plugin.zsh#L135
=> Grammar: remove hyphens from predicate adjective “up to date”

plugins/gitfast/_git
So that compdefs with dashes work as well as underscores:
`  compdef _git gc=git_commit`
Or:
`  compdef _git gc=git-commit`
The official Zsh Git completion uses dashes, and this way people don't
have to change their existing definitions.
There's also the benefit that the compdefs in the standard 'git' plugin work out-of-the-box.
Fixes #9018 (possibly).
...
=> gitfast: improve command aliases

plugins/colorize/colorize.plugin.zsh
The direct assignment of a local array is not possible in older ZSH version, as used by RHEL/CentOS 7.
- minor change in assignment of local array
Fixes #9389
=> colorize: add compatibility for zsh < 5.1

plugins/aws/aws.plugin.zsh
Get and set session token if available and already configured when `role_arn` is not set.
Changes from https://github.com/ohmyzsh/ohmyzsh/pull/8419/ stopped setting the value for `AWS_SESSION_TOKEN` for me. Traced it back to this line of change.
=> aws: get and set session token if available

plugins/aws/README.md, plugins/aws/aws.plugin.zsh
- Fixes #9394 by splitting the `asp` function into two: `asp` behaving like the original one, and `acp`, which actually changes the profile by assuming the associated role.
Addresses #9394
=> AWS plugin: split out changing profile from asp into a separate function (acp)

plugins/aws/README.md, plugins/aws/aws.plugin.zsh
- Previously, the plugin only supported MFA for profiles that had a role to assume, specified in role_arn. Now, the plugin supports MFA for profiles without a role to assume. Closes #9408 
Closes #9408
...
=> AWS plugin: support MFA for profiles without role to assume

plugins/fzf/fzf.plugin.zsh
Be consistent and ignore contents of `.git` directory no matter how FZF_DEFAULT_COMMAND is set.
- Be consistent and ignore contents of `.git` directory no matter how FZF_DEFAULT_COMMAND is set.
Currently `FZF_DEFAULT_COMMAND` is configured to ignore `.git` directory contents when `fd` command is used. Make this consistent and also ignore `.git` when setting `FZF_DEFAULT_COMMAND` with `rg` and `ag`
=> fix(fzf): consistently ignore .git directory in `FZF_DEFAULT_COMMAND`

plugins/battery/battery.plugin.zsh
returns the battery charge consistent with the system battery manager
- [...]
...
=> fix(battery): use `pmset` for battery percentage in macOS

plugins/aws/aws.plugin.zsh
- fix(aws): don't duplicate aws_prompt_info function in RPROMPT
- refactor(aws): clean up logic in acp function and fix session duration input
Fixes #9409
=> aws: refactor acp function and various fixes

plugins/sudo/sudo.plugin.zsh
If you use some alias for your $EDITOR, say `e`. You type `e /to/file`.
But that file needs sudo permission. You naturally do `<Esc><Esc><Enter>`.
But, to your dismay, it errors out `command not found`, because it
didn't detect your alias to $EDITOR, thereby failing to convert it to
`sudoedit`.
This commit tries to detect your alias and convert it to sudoedit.
- Removed a trailing whitespace
- Added vim modeline
- Added my name and GitHub user URL under Authors
- Added the actual functionality this PR is intended for
NONE
=> feat(sudo): support aliases to $EDITOR

plugins/git/git.plugin.zsh
It adds `trunk` branch name as option in case the repository uses it as default branch.
- [...]
...
=> feat(git): support trunk branches in `git_main_branch`

plugins/terraform/_terraform
As of Terraform ~0.12.29~ 0.13.3
- Add autocompletion for login/logout and force-unlock
- Add completion for 0.13upgrade
- Remove legacy push command
- Add -json flag to version command
=> feat(terraform): add autocompletion for Terraform 0.13

plugins/magic-enter/magic-enter.plugin.zsh
This solution makes the magic-enter function a wrapper for the accept-line zle widget, meaning that magic-enter will be run instead of accept-line (this is usually done when pressing Enter or running `zle accept-line`).
The zsh-autosuggestions plugin will automatically notice this is a wrapper and properly assign it the "clear suggestions" action when run.
Also: refactored and changed code style of the plugin.
Related: https://github.com/marlonrichert/zsh-autocomplete/issues/131
Checks the [`$CONTEXT` variable](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#User_002dDefined-Widgets) to see whether we're in the start of the prompt. This solves the bug where, for example, the user would have typed `echo '` and <kbd>Enter</kbd>, then zsh would be in PS2 waiting for the user to …
=> fix(magic-enter): fix various bugs in the plugin

plugins/git-auto-fetch/README.md, plugins/git-auto-fetch/git-auto-fetch.plugin.zsh
- Background the whole `git-fetch-all` function.
- Fix the `zle-line-init` widget creation so as to not overwrite previous defined widgets.
- Remove dependency on `date` (use `EPOCHSECONDS` and `zstat`).
- Code and README clean-up and style changes.
- Document caveat with regards to `git push --force-with-lease`.
Fixes #9416
=> fix(git-auto-fetch): background `git-fetch-all` and other fixes

lib/cli.zsh, lib/functions.zsh, tools/changelog.sh, tools/check_for_upgrade.sh, tools/upgrade.sh
- refactor(updater): switch to Zsh execution and fix git remote detection logic
- fix(updater): correctly restart the zsh session when the update pulled changes
- feat(updater): add changelog display by parsing the commit list
- feat(CLI): add `omz changelog` command
**NOTE:** after updating, the changelog is displayed briefly with `less` if available, or directly `cat`-ed to the console if `less` isn't available. This might not be the best UI, so I'll appreciate any feedback on this.
The changelog functionality is dependent on commits following the [Conventional Commits spec](https://www.conventionalcommits.org/).
Sample screenshot (works with new and old commit formats):
In this screenshot, the call to `omz changelog` expects a commit-ish (branch, hash or tag work). In the future, this …
=> feat(updater): add changelog and restart session on successful update

plugins/git-prompt/gitstatus.py
check_output() in get_tagname_or_hash() returns bytes instead of str in
python3.  Decode the return value to utf-8, this works in both python2
and python3.
- Make plugins/git-prompt/gitstats.py python3 compatible.
...
=> fix(git-prompt): make `gitstatus.py` python3-compatible

plugins/command-not-found/command-not-found.plugin.zsh, plugins/gcc/gcc.plugin.zsh
It won't show anything when there is no match for a not-found command.  
So I changed the plugin from
to
"未找到命令" means "command not found", It depends on your language package.
Fixes #9491
=> fix(command-not-found): show error in Ubuntu when no package is found

plugins/wp-cli/README.md, plugins/wp-cli/wp-cli.plugin.zsh
- Added aliases for some frequently used 'wp db' commands
...
=> feat(wp-cli): add aliases for DB management

plugins/git/git.plugin.zsh
- `git_main_branch` silently returns when executed outside of a git repo. 
Mimics the same behaviour as `git_current_branch`
...
=> fix(git): silently fail in `git_main_branch` if not in a git repo

plugins/grc/README.md, plugins/grc/grc.plugin.zsh
- No changes, adds a new plugin (grc)
```zsh
❯ grep ^plugins ~/.zshrc
plugins=(direnv fzf git kubectl pipenv ssh-agent tmux pyenv grc)
❯ whence ping
grc --colour=auto /sbin/ping
```
=> feat(plugins): add grc plugin for Generic Colouriser

.github/CODEOWNERS, plugins/genpass/README.md, plugins/genpass/genpass.plugin.zsh
- 
Add genpass plugin providing `gen-apple-pass`, `gen-monkey-pass`, and `gen-xkcd-pass` password generators
These password generators help minimize the mistake people make thinking they can "design" good passwords in the shell. Instead, each password generator provided by this plugin generates passwords with at least a 128-bit security margin, suitable even for cryptographic keys. The user can provide a numerical argument to generate more passwords if needed. No external 3rd party software is required.
...
=> feat(plugins): add genpass plugin with 3 distinct password generators

plugins/genpass/genpass.plugin.zsh
=> Plugin genpass. Force grep(1) to use only ASCII characters in gennpass-xkcd.

plugins/genpass/genpass.plugin.zsh
- there was a minor typo in the regular expression sent to `grep` in `genpass-xkcd`, such that `dict` was always empty. I have fixed it by adding a lower bound to the regex range. Fixes #9513.
oh my zsh rocks!
=> fix(genpass): fix grep regex in `genpass-xkcd` for FreeBSD version

lib/git.zsh
- modify a status mapping in function `git_prompt_status`.
The 'MM ' prefix means some file modified after added, so the right status should be `'MODIFIED'`.
Like this:
```shell
$ echo 'foo' >> README.md
$ git add README.md
$ echo 'bar' >> README.md
$ git status --short
MM README.md
```
=> fix(lib): mark changes as MODIFIED on 'MM' in `git_prompt_status`

plugins/nvm/README.md
It wasn’t clear where I should set the `NVM_AUTOLOAD` variable. The clue was to be found in [the docs for another plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/fzf). It seems setting values need to come before Oh My Zsh is sourced.
Updated read me to reflect this, and the fact that one of the settings mentioned is specific to nvm, not this plugin.
- Update README.md for nvm plugin
Replaces #9541
=> docs(nvm): clarify how to enable settings

plugins/vi-mode/vi-mode.plugin.zsh
This fixes all issues I'm aware of for vi-mode. Tested on zsh-5.7.1 on macOS, and I've been using it extensively for a quite a while.
In summary:
* Fix: Fixes consistency issues with tracking mode changes
* Fix: Restores zsh's very good built-in visual mode, rather than launching a full editor…
* Fix: Restores up-arrow etc. keybindings.
* Enhancement: Speeds up mode changes by avoiding unnecessary prompt "full resets" which can trigger `git` work. (See also—not dependent, but helps— _[#7804 - Safety fix and speed-ups for lib/git.zsh prompt functions](https://github.com/robbyrussell/oh-my-zsh/pull/7804)_)
* Feature: Draws the cursor style based on the current mode.
* Feature: Copying and pasting in vi-mode uses `clipcopy`/`clippaste`, to integrate with your clipboard. (See also—not …
=> fix(vi-mode): control cursor, restore and use visual mode and speed up mode changes

plugins/archlinux/archlinux.plugin.zsh
Error and investigation:
```
❯ pacmanallkeys                                                                                                                                 ─╯
[sudo] password for lagbrie: 
==> ERROR: No targets specified
❯ which pacmanallkeys                                                                                                                           ─╯
pacmanallkeys () {
curl -s https://www.archlinux.org/people/{developers,trustedusers}/ | awk -F\" '(/pgp.mit.edu/) { sub(/.*search=0x/,""); print $1}' | xargs sudo pacman-key --recv-keys
}
❯ curl -s https://www.archlinux.org/people/{developers,trustedusers}/ | awk -F\" '(/pgp.mit.edu/) { sub(/.*search=0x/,""); print $1}'
❯ curl -svo /dev/null https://www.archlinux.org/people/\{developers,trustedusers\}/ |& grep …
```
=> fix(archlinux): update URL and key server in `pacmanallkeys`

plugins/vi-mode/README.md, plugins/vi-mode/vi-mode.plugin.zsh
- docs(vi-mode): revamp README and document settings
- fix(vi-mode): hide cursor-change logic behind `VI_MODE_SET_CURSOR` setting
Fixes #9570
=> fix(vi-mode): hide cursor-change logic behind opt-in setting

lib/termsupport.zsh
Emacs replaced the environment variable that it sets in interactive subshells from `EMACS`  to `INSIDE_EMACS`. See https://www.gnu.org/software/emacs/manual/html_node/emacs/Interactive-Shell.html for details.
I couldn't find exactly when Emacs made this change, but [this post from 2015](https://lists.gnu.org/archive/html/bug-gnu-emacs/2015-03/msg01008.html) shows that `EMACS` was deprecated for 8 years at that point.
Closes #6411.
=> fix(lib): update Emacs terminal detection in `title` function

plugins/jake-node/jake-node.plugin.zsh
- Extend checks filenames for Jakefiles.
- Add Jakefile, Jakefile.js, jakefile and jakefile.js
https://jakejs.com/docs-page.html#item-advanced-usage-modularizing
↓
When you run Jake, it will look for a Jakefile in the current diretory. Jake will recognize Jakefile, Jakefile.js, jakefile, or jakefile.js as a vaild name for a Jakefile.
=> fix(jake-node): support all Jakefile filenames in `jake` completion

plugins/macports/_port
The sub-command `reclaim` is quite useful for freeing up disk space.
`reclaim` is missing from the list of completions in the `macports` plugin.
The description for the `reclaim` sub-command is:
"port reclaim will find files that can be removed to reclaim disk space by uninstalling inactive ports on your system as well as unnecessary unrequested ports, and removing unneeded or unused installation files. The user is then provided interactive options for files to remove. No files are removed initially, until the user selects them from the provided list."
For all the details use this command on a system with Macports installed:
`port help reclaim`
- Add `reclaim` to subcmds list
=> feat(macports): add 'reclaim' to completion list for Macports

plugins/last-working-dir/README.md, plugins/last-working-dir/last-working-dir.plugin.zsh
- Modified condition at ```chpwd_last_workind_dir``` and ```lwd```.
=> feat(last-working-dir): log separate `lwd`s for different SSH keys on the same user account

plugins/colorize/colorize.plugin.zsh
I want to set `alias less="colorize_less"` to have fancy `less`.
But in current state it will expand alias recursively basically in infinite loop causing the whole terminal to crash. Prevent this by prepending it with `command` which will use default `less` instead.
=> fix(colorize): bypass less aliases in `colorize_less`

templates/zshrc.zsh-template
Enabling this setting causes issues for multiline prompts when tab
completion is triggered. Add a caution in template warning against the
same.
See https://github.com/robbyrussell/oh-my-zsh/issues/5765
=> chore: caution against `COMPLETION_WAITING_DOTS` in template

plugins/term_tab/README, plugins/term_tab/term_tab.plugin.zsh
This plugin allows the user to complete other zsh session pathes by hitting 'CTRL+v'.
=> feat(plugins): add `term_tab` plugin to complete other zsh sessions' directories

plugins/git-prompt/README.md
Stashed icon is added in #4880
- The `stashed` icon is added in #4880 PR. This PR updates the README file to explain the icon.
=> docs(git-prompt): explain stashed icon (⚑)

lib/cli.zsh, tools/check_for_upgrade.sh, tools/upgrade.sh
No error code is required for a non failure scenario.
- Removes the `ret=80` when no upgrade has been performed. If no actions is/was required when performing an upgrade then an error scenario hasn't occurred.
=> fix(update): don't error on upgrade no-op

lib/prompt_info_functions.zsh, plugins/terraform/terraform.plugin.zsh
The purpose of this change is to speed up tf_prompt_info() function.   This function relies on 'terraform workspace show' which could be very slow operation.   To speed up I made the following changes
- Check for .terraform/environment directory.  If it doesn't exist we are probably not in the terraform stack or the stack doesn't have custom workspace
- To get the workspace one just needs to look into .terraform/environment file.  It contains the workspace name.  No need to launch the terraform command because it is very slow
- Also, added tf_prompt_info to the list of prompt_info functions in lib/prompt_info.  So that theme writers are aware of it
=> fix(terraform): use faster method to get workspace

themes/gentoo.zsh-theme
- Use `vcs_info` which supports svn and bzr and CVS
- Add vsc_info hook to show when there are untracked files
Repost of #1855 with a fix for showing untracked files.
**BEFORE**
**AFTER**
=> feat(gentoo)!: use `vcs_info` to support other VCSs

plugins/emotty/emotty.plugin.zsh
Removed redundant spaces to prevent:
```
$ emotty
emotty:7: bad assignment
```
=> fix(emotty): fix `bad assignment` error

plugins/fzf/fzf.plugin.zsh
- Added support for Termux debian package
=> feat(fzf): add support for Termux package

plugins/fossil/fossil.plugin.zsh
=> fix(fossil): PROMPT, and RPROMPT are not meant to be exported

plugins/vi-mode/vi-mode.plugin.zsh
In some cases, the prompt was not always being redrawn properly after running a command from vi-mode.  If a command is executed with zle in 'normal' mode, after command completion, the next prompt drawn still indicates 'normal' mode, even though it is a new zle line and is back in 'insert' mode.  This was because the `VI_KEYMAP` var (on which the prompt selection is based) was being updated on zle init, which isn't called until after the prompt draw.  This PR fixes this by setting `VI_KEYMAP` back to 'main' on `zle-line-finish` to mirror what is already being done on `zle-line-init`.
- In `vi-mode` plugin, reset `VI_KEYMAP` to 'main' after zle finishes editing line.
=> Update VI_KEYMAP on zle-line-finish.  Fixes next prompt draw after running command from 'normal' mode.

tools/install.sh
Clear all warnings and errors raised by https://shellcheck.net static analysis.
- Replace non-POSIX shell use of `$OSTYPE` by POSIX compliant check on `uname -o`.
- Move variables out of `printf` format string.
- Refactor/simplify string formatters for error and underline.
- Fix expansion of arguments to a single string `$*` rather than individual elements `$@` within the error and underline formatters.
none
=> refactor(install.sh): fix static analysis warnings

plugins/dirhistory/dirhistory.plugin.zsh
- Make sure built-in widgets are used for `kill-buffer` and `accept-line`
Fixes https://github.com/ohmyzsh/ohmyzsh/issues/9770
=> fix(dirhistory): make sure to call built-in zle widgets

plugins/archlinux/README.md, plugins/archlinux/archlinux.plugin.zsh
* Fix naming.
* Pacman goes first. AUR helpers, sorted alphabetically, follow it.
* Add footnote to explain identically named *upg aliases.
* Convert upgrade function to aliases, put them alongside other aliases.
* Rewrite paclist function: it was unreliable and over-complicated.
* Add --help to pacweb function instead of silently failing.
This refactoring is a prerequisite for #9467
=> refactor(archlinux): fix name & scripts; reorder aliases

plugins/shell-proxy/proxy.py, plugins/shell-proxy/shell-proxy.plugin.zsh
- improve ux
```bash
export DEFAULT_PROXY="your proxy server"
source "$ZSH/oh-my-zsh.sh"
DEFAULT_PROXY="your proxy server"
source "$ZSH/oh-my-zsh.sh"
```
...
=> feat(shell-proxy): enable unexported `DEFAULT_PROXY` setting

plugins/archlinux/README.md, plugins/archlinux/archlinux.plugin.zsh
- Remove calls to aur and abs commands
See #8591
=> feat(archlinux)!: remove deprecated commands `aur` and `abs`

plugins/rails/README.md
#9662 Fixed the deprecated `rake routes`. However, the documentation in the README was not reflective of this change. This PR corrects the documentation to reflect this change. 
BTW. Thank you for a great product.
=> Fix Rails plugin documentation to reflect #9662

themes/gentoo.zsh-theme
This commit fixes an issue in the gentoo theme introduced in 3bb5e977.
Due to incorrect line width calculations, colors are incorrectly applied
when using tab.
Fixes #9778
Signed-off-by: Thomas De Backer <mosterdt@debacker.me>
The last %{$reset_color%} part of the theme messes up the line width calculation (`%{...%}` tells zsh that the characters inside have zero width.) Replacing this somewhat opaque variable with `%k%b%f` fixes the line width calculation and the tab completion color bleed. (stop background color, stop boldface mode, stop foreground color, see zshmisc(1))
I've ran this version of the theme for a week or 2, and I didn't see the problem reoccur except once. It might have been a specific vcs state that combined the other snippets into a broken prompt line. I was not able to …
=> fix(gentoo): fix tab completion color bleed

themes/ys.zsh-theme
On large mercurial projects, using `hg status` to show dirty prompt causes significant delay.
This commit checks a local hg config value of `oh-my-zsh.hide-dirty` to skip dirty check.
Users who wish to skip dirty check can add this to their `.hg/hgrc` file.
```
[oh-my-zsh]
hide-dirty = 1
```
This config value uses the same naming as ones found for git, in file [lib/git.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/1546e12/lib/git.zsh).
@ysmood
=> feat(ys): add setting to hide dirty info in hg repositories

plugins/systemadmin/systemadmin.plugin.zsh
- modified the first curl command to get the dedicated external ipv6 address
- added a curl command to get the dedicated external ipv4 address
This is needed for dual stack setups. Feedback is wanted on how to test it for resiliency.
=> feat(systemadmin): add IPv6 info to `geteip` command

plugins/fzf/fzf.plugin.zsh
Please see [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).
- Added an additional location to search for a preexisting installation of FZF via the `XDG_DATA_HOME` environment variable as specified in the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).
...
=> feat(fzf): look in XDG compliant location

plugins/npm/README.md, plugins/npm/npm.plugin.zsh
- Add alias for `npm i -f`
It's an useful alias that forces npm to fetch remote resources even if a local copy exists on disk.
=> feat(npm): add alias for `npm i -f`

plugins/kubectl/README.md, plugins/kubectl/kubectl.plugin.zsh
This option is stable, since it was added in Kubernetes v1.12.0 (Sep 2018). The previous `$(kubectl config current-context)` command may cause bugs after switching contexts.
=> fix(kubectl): use `--current` flag in `kcn` alias

plugins/command-not-found/command-not-found.plugin.zsh
- Removes `--` argument to PackageKit command-not-found that was inadvertently added
`pk-command-not-found` doesn't accept `--` as an argument. This is what happens when `--` is the first argument:
```
foo@bar ~  gem 
zsh: --: command not found...
```
...
=> fix(command-not-found): remove invalid argument for PackageKit

plugins/cargo/_cargo
By default, cargo provides alias for some commonly used functions. This patch
makes it that those alias will complete the same as their full commands.
Default alias:
b -> build
c -> check
t -> test
r -> run
Since cargo allows users to define custom alias it would be nice if
oh-my-zsh automatically detected those and preformed completions as such
but that would be a much more complex patch.
Reference documentation: https://doc.rust-lang.org/cargo/reference/config.html#alias
- The case statement matching the cargo sub-command now also the commands default aliases as described above.
=> fix(cargo): complete flags for default cargo aliases

plugins/shrink-path/README.md, plugins/shrink-path/shrink-path.plugin.zsh
- Add `-x`/`--expand` option to `shrink_path` function.
- Document new usage.
- Document keyboard shortcut widget for toggling path shrinking on and off.
Fixes #9227
=> feat(shrink-path): add ability to toggle off path shrinking

plugins/dirhistory/dirhistory.plugin.zsh
* Add the missing key bindings for ALT+UP and ALT+DOWN (note: they work in iTerm2 but not in Terminal.app)
* Add support for iTerm2
=> feat(dirhistory): add ALT+UP/DOWN key bindings for iTerm2

plugins/dirhistory/dirhistory.plugin.zsh
Fixes #9938
Separates <kbd>ALT+Left</kbd> / <kbd>ALT+Right</kbd> key bindings for iTerm2 and Terminal.app and fixes key binding sequences for iTerm2.
=> fix(dirhistory): fix ALT+Left/Right key bindings for iTerm2

themes/gentoo.zsh-theme
This commit fixes an issue where the prompt symbol is white when vcs_info is displayed in the gentoo theme.
before:
after:
=> fix(gentoo): fix the color of the prompt symbol

plugins/rails/rails.plugin.zsh
This adds `rdmd` (`rake db:migrate:down`) and `rdmu` (`rake db:migrate:up`) aliases to Rails plugin to be able to run specific migrations.
=> Add `rdmd` and `rdmu` aliases to Rails plugin

plugins/kubectl/README.md, plugins/kubectl/kubectl.plugin.zsh
A fix to https://github.com/ohmyzsh/ohmyzsh/issues/9842.
Remove alias `kgsa` from kubectl plugin, because it is conflicting with another alias. To get service accounts, command `k get sa` is short enough. Therefore, surrender this alias for a longer command.
N.A.
=> remove duplicated alias for kubectl plugin `kgsa`

plugins/bower/bower.plugin.zsh
Add the following frequently used bower command aliases:
bis: installs a package and adds it to package.json under dependencies (bower install)
bisd: installs a package and adds it to package.json under devDependencies (bower list)
original pr https://github.com/robbyrussell/oh-my-zsh/pull/1614
=> add bower commands aliases

plugins/mercurial/mercurial.plugin.zsh
Add a new function to get the current mercurial bookmark which can be
used in the theme prompts for example.
=> Add helper function to get the mercurial bookmark.

plugins/debian/README.md, plugins/debian/debian.plugin.zsh
`apt` is installed by default at Debian (maybe Ubuntu too),
while `aptitude` does not seem to be installed by default.
For that, it may be better for most users to prefer `aptitude` if installed.
=> Plugin "debian": Switch order of "apt" and "aptitude" for detection

plugins/nvm/README.md, plugins/nvm/nvm.plugin.zsh
Add `$NVM_LAZY_CMD` such to customize a list of command that triggers lazy loading.
-  add parameter `NVM_LAZY_CMD` and expand it in lazy loading 
-  add instruction in `README.md`
...
=> feat(nvm): customizable list of command that triggers lazy loading

plugins/git/git.plugin.zsh
I thought it would be useful to add these aliases. 
There are already aliases for `git commit -S` and `git commit -s` but there is none for both simultaneously =)
@ncanceill could you please take a look?
=> Add aliases for 'git commit -S -s [-m]'

plugins/git-flow/git-flow.plugin.zsh
Changed commands in git-flow plugin:
gcd: uses gitflow.branch.develop to get user-set development branch
gch: uses gitflow.prefix.hotfix to get user-set hotfix prefix
gcr: uses gitflow.prefix.release to get user-set release prefix
=> Add config interpolation for git-flow messages

plugins/gnu-utils/gnu-utils.plugin.zsh
- Include `ggrep` in `gcmds` array for gnu-utils plugin. This allows ggrep to be aliased if you have GNU grep installed.
...
=> feat(gnu-utils): include ggrep in gcmds

plugins/aws/aws.plugin.zsh
- Close if statement after checking for mfa_serial in `acp()`
- Remove extraneous `fi` before profile switching
- Fix indentation
I think scope of one of the if statements was accidentally expanded in #9426 to include code that was supposed to do profile switching. This fix attempts to correct the scope of if statemnts.
Fixes #9843
=> fix(aws): allow for profile switch w/o MFA configured

plugins/git/README.md, plugins/git/git.plugin.zsh
Some repositories use branch names other than `develop` for the development branch. This PR adds a `develop` branch name detection inspired by the `main` branch name detection.
Closes #10088
=> feat(git): add `develop` branch name detection

plugins/invoke/README.md, plugins/invoke/invoke.plugin.zsh
This gives completion for the `inv` / `invoke` commands.
https://github.com/pyinvoke/invoke
There already is a PR for invoke (https://github.com/robbyrussell/oh-my-zsh/pull/3471) but it is outdated. Invoke since added a command to generate a completion script.
This PR  simply uses this command.
http://docs.pyinvoke.org/en/latest/invoke.html#tab-completion
Note: [pyinvoke](https://pypi.org/project/pyinvoke/) is a python package that has nothing to do with invoke, but the website for invoke is http://www.pyinvoke.org/.
Closes #3471
=> feat(plugins): add completion plugin for `invoke`

plugins/octozen/README.md, plugins/octozen/octozen.plugin.zsh
Added a plugin which `curls` `https://api.github.com/octocat` on startup and displays the returned message.
=> feat(plugins): `octozen` shows an Octocat zen quote on startup

lib/cli.zsh
- extends omz cli (#8876, #9087) with a plugin load <plugin> subcommand to support loading plugins manually
- Fixes #9672
Lines 51-52 are repeated in 58-59 to provide completions for multiple plugin entries and there may be a less redundant way to store the added completions.
Reopened since last one (#9753) was polluted with other commits.
=> feat(cli): add `plugin load` subcommand

plugins/kubectx/kubectx.plugin.zsh
- If the associative array is declared but the desired key is not there the plugin will now fall back to the default value.
Previously this situation would result in the empty string, meaning that if you want to remap some value you would have
to remap all.
=> fix(kubectx): show plain context if not mapped

themes/mlh.zsh-theme
- let users configure MLH theme using environmental variables. User can set
them conveniently, for example, in their `~/.zshrc` file, instead of being
forced to override the whole theme.
- make the theme 2 line. Currently, when the user is working on a branch with a long name, it looks
really awkward:
Now, it looks just cool.
=> feat(mlh): let users configure the official MLH theme

plugins/git/git.plugin.zsh
- When guessing the git main branch name consider remote branches from origin or upstream remotes that weren't checked out locally, this allows shortcuts like `gcm`, `glum`, and `gmom` to work even before the main branch is checked out locally.
=> feat(git): guess main branch name also from remotes

plugins/git/README.md, plugins/git/git.plugin.zsh
- Change glol, glols and glola to use author date like glod and glods.  The committer date is rewritten by rebases and is generally less useful.
=> feat(git): change from commiter to author in `git log` aliases

plugins/gcloud/gcloud.plugin.zsh
Homebrew on Mac M1 is moved to the /opt/Homebrew location. This change adds updates the search locations with this path.
- [...]
...
=> feat(gcloud): add Mac M1 Homebrew path

plugins/autojump/autojump.plugin.zsh
On M1-Macs homebrew uses /opt/homebrew as default location for ARM
packages. This results in the autojump plugin not being able to find
autojump after a clean default installation.
This commit adds the new default location to the autojump plugin.
- Add autojump path for new homebrew default location
=> feat(autojump): add new Homebrew default path on M1 Macs

plugins/chruby/chruby.plugin.zsh
- a missing $ made finding homebrew's chruby in an alternate path fail.
homebrew for OSX on ARM is installed in /opt/homebrew by default, so we might want to add a check for that path the same way we check /usr/local instead of having to shell out to homebrew on every M1 mac.
=> fix(chruby): fix typo in test for Homebrew path

plugins/git-auto-fetch/git-auto-fetch.plugin.zsh
Check directory and file permissions before fetching the Git remotes.
The zsh prompt will display an error message if the user don't own the git directory.
...
=> fix(git-auto-fetch): cancel fetch if we don't have permission over git folder

plugins/git/README.md, plugins/git/git.plugin.zsh
- Adds the `gdu` alias in the git plugin to `diff` against the tracked upstream branch (`@{u}`)
(None.)
=> feat(git): add `gdu` alias to diff against upstream

plugins/vim-interaction/vim-interaction.plugin.zsh
Instead of relying on a hardcoded instance-name existing for the default-value, let's look up the latest instance by getting the latest line from `gvim --serverlist`. This also resolves my problem where MacVim uses a servername of "VIM" instead of "GVIM".
=> fix(vim-interaction): look up the newest GVim instance

plugins/cp/README.md, plugins/cp/cp.plugin.zsh
Add a unique suffix (the user name) to `rsync` backup directory for each user.
If the path to the backup directory is a fixed location, this may cause permission issues on a multi-user operating system (e.g., on a Linux server).
Suppose USERALICE uses the command `cpv` and that creates the backup folder `/tmp/rsync`. Then this backup folder is owned by USERALICE and anyone else on the system does not have permission to write this folder (to use `cpv` command).
=> fix(cp): add unique suffix to rsync backup directory for each user

plugins/kubectx/README.md
Remove spaces that cause a syntax error
=> docs(kubectx): fix README sample code syntax

plugins/lando/lando.plugin.zsh
- Added php command alias support for lando
Running `php` in a lando repo's cli (a repo with a .lando.yml in it) will run `lando php` instead.
=> feat(lando): add support for `php` command

plugins/vim-interaction/vim-interaction.plugin.zsh
- Simplified `$before` and `$after` command building.
- Open a gvim instance if none found.
- Clean up syntax to be more idiomatic zsh.
=> refactor(vim-interaction): clean up code and open gvim instance if none open

tools/install.sh
- The logo is now displayed in rainbow colors as is done in the update script.
- The success message has improved colors and links are rendered as hyperlinks where it's possible.
- installer success screen with hyperlink support:
- installer success screen without hyperlink support:
- installer success screen without tty:
=> style(installer): use rainbow logo and polish success message

plugins/osx/osx.plugin.zsh
- The current `man-preview` function switches to Preview.app from your terminal if you attempt to open a man page with `man-preview` and the man page doesn't exist. This adds a check to see if the man page exists before piping it into Preview, and, if not, passes the errors through.
=> fix(osx): only run Preview.app in `man-preview` if man page exists

plugins/emacs/emacs.plugin.zsh, plugins/emacs/emacsclient.sh
- Remove dependency on `require_tool.sh` and use `is-at-least` instead.
- Fix code style in `emacsclient.sh`.
- Fix test for open frames in `emacsclient` wrapper: supports testing for tty and graphical frames.
- Fix passing stdin as arguments to `emacsclient` wrapper.
Fixes #5405
Fixes #5779
=> Refactor and fix various issues in emacs plugin

lib/correction.zsh
- no correct alias `su` command
...
=> feat(lib): don't correct `su` command arguments

plugins/pyenv/pyenv.plugin.zsh
- Fix pyenv-virtualenv detection under macOS when pyenv-virtualenv is installed by Homebrew
When pyenv-virtualenv is installed by Homebrew, it does not present under `"$(pyenv root)/plugins/pyenv-virtualenv"`.
=> fix(pyenv): Fix brew installed pyenv-virtualenv.

oh-my-zsh.sh
- Removes formatting when output is non-tty
- Adds `ptree` function that gathers information about the process tree of the caller shell
- Correctly gets shell name from `$$` process command
Related: #10213
=> feat(init): show error and process tree if OMZ is loaded from non-zsh shells

plugins/docker-compose/docker-compose.plugin.zsh
- Tests if `docker compose` runs successfully and uses that to decide whether to use `docker-compose` or `docker compose` in the aliases.
Fixes #10231 #10241
=> fix(docker-compose): support Compose V2 `docker compose` command

plugins/git/README.md, plugins/git/git.plugin.zsh
Switching the git alias `gdu` to `gduu`, to avoid conflicts with [gdu](https://github.com/dundee/gdu) following `git diff` alias syntax.
This PR closes #10201.
Thanks!
=> fix(git)!: rename `gdu` alias to `gdup`

lib/directories.zsh
alias for 1 needs to specify 1.  '-' is the previous directory, which may not be the same as the 1 directory on the stack if the previous location was just popd.
- [...]
...
=> fix(lib): fix `1` alias to `cd` to directory 1 in stack

themes/ys.zsh-theme
- White color changed to lightgrey to work better in both light and dark color schemes
- Fixes #10278
Before:
After:
=> feat(ys): increase color contrast with light color schemes

plugins/command-not-found/command-not-found.plugin.zsh
- Fix passing arguments to command-not-found in NixOS
The [command-not-found script](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/command-not-found/command-not-found.pl) in NixOS uses the first argument to find programs.
Thus there should be no '--' when passing arguments.
=> fix(command-not-found): pass arguments correctly in NixOS

lib/diagnostics.zsh, lib/directories.zsh, lib/functions.zsh, lib/git.zsh, plugins/scd/scd, plugins/systemadmin/README.md, plugins/systemadmin/systemadmin.plugin.zsh, tools/install.sh
The `tail` manpage says:
> For compatibility tail also supports an obsolete usage ‘tail
> -[num][bcl][f] [file]’, which is recognized only if it does not
> conflict with the usage described above. This obsolete form uses
> exactly one option and at most one file. In the option, num is
> an optional decimal number optionally followed by a size letter
> (‘b’, ‘c’, ‘l’) to mean count by 512-byte blocks, bytes,
> or lines, optionally followed by ‘f’ which has the same meaning
> as -f.
This usage is not supported with newer coreutils implementations
(for example github.com/uutils/coreutils), so let's just use the
non-deprecated flag option.
=> style: use `-n` flag in `head` and `tail` commands

themes/refined.zsh-theme
Change the VCS name - branch name separator in PS1 prompt from `/` to `:` to allow selecting and copying the branch name with a double click.
Fixes #10379
=> feat(refined): allow selecting git branch by changing prefix to `:`

plugins/command-not-found/command-not-found.plugin.zsh
- Fix passing arguments to command-not-found in Termux
[command-not-found in Termux](https://github.com/termux/command-not-found/blob/master/command-not-found.cpp#L188) uses the first arg.
<details><summary>screenshot of the problem with fix</summary>
</details>
latest Termux 0.117
refs: https://github.com/ohmyzsh/ohmyzsh/pull/10381
=> fix(command-not-found): pass arguments correctly in Termux

plugins/docker-compose/docker-compose.plugin.zsh
- Look for `docker-compose` command instead of trying `docker compose` to decide whether to use `docker compose` or `docker-compose` in aliases.
Fixes #10409
=> fix(docker-compose)!: check for old command instead of calling `docker`

plugins/bgnotify/bgnotify.plugin.zsh
- Replaced the applescript to get the pid of the frontmost app instead of the window id of the active window.
On recent macOS versions, getting the window id of the active window of the frontmost app using `osascript` and `tell` requires granting permission for controlling said app. This means that if `bgnotify` is active and one puts the terminal in the background, after the terminal process completes it will spawn a permission request window relating to the app currently in the foreground. Obviously this gets annoying really quickly as each new foreground app has to be approved separately. Getting the pid of the frontmost app only requires this permission to be granted once, for the "System Events" app.
=> fix(bgnotify): avoid permission prompts by checking frontmost app ID

plugins/bundler/bundler.plugin.zsh
When calling `bundle install` with `--jobs=<n>`, bundle persists this argument in `.bundle/config`. If we run `BUNDLE_JOBS=<n> bundle install` instead, this is not persisted.
Fixes #10425
Reference: https://bundler.io/v1.14/man/bundle-config.1.html#LIST-OF-AVAILABLE-KEYS
=> fix(bundler): use BUNDLE_JOBS in `bi` to avoid config file change

lib/termsupport.zsh
- in lib/termsupport.zsh's title function: Use a parameter substitution to avoid erroring if INSIDE_EMACS is not set
After updating ohmyzsh this morning, I was getting the following error:
```
title:4: INSIDE_EMACS: parameter not set                                        
zsh: vcs_info_msg_0_: parameter not set
~
```
where the final `~` is the start of my prompt, but not the whole thing. I tracked the `title:4` error to this `-n "$INSIDE_EMACS"` condition and have changed it to `-n "${INSIDE_EMACS:-}"`. The problem appears to have been introduced in a263cdac9:
```diff
diff --git a/lib/termsupport.zsh b/lib/termsupport.zsh
index ef0d7889..49f64400 100644
--- a/lib/termsupport.zsh
+++ b/lib/termsupport.zsh
@@ -7,8 +7,7 @@
function title {
-  emulate -L zsh
-  setopt prompt_subst
+  setopt …
```
=> fix(lib): don't error if `INSIDE_EMACS` is not defined

plugins/xcode/README.md, plugins/xcode/xcode.plugin.zsh
- Allows to open the Swift Playgrounds App introduced by Xcode 13.2 directly with xc.
N/A
=> feat(xcode): support `.swiftpm` as project file in `xc`

tools/check_for_upgrade.sh
It's great that oh-my-zsh supports a "reminder" mode for updating.  I personally prefer the (default) prompting behavior.  However, I occasionally inadvertently dismiss it (usually as part of a "new tab -> start typing first command" workflow).  When I do so, I usually want to do the update as soon as possible afterwards.  I have a terrible memory, so it's a nice QOL change to emit the command to manually update, so that I can know what to run right away to trigger the update (rather than waiting for the next time I open a new shell).  This is kind of the best of both worlds of the prompt + reminder behavior.
- as far as I can tell (it's hard to search for "update" and get any relevant results 😃  )
- I didn't see anything in the code style guide covering case statements 😬 
- Echo the …
=> feat(updater): show command to update when update skipped

plugins/branch/README.md, plugins/branch/branch.plugin.zsh
- if a bookmark is used, it will be shown via slash. Like {branch}/{bookmark}
...
=> feat(branch): show mercurial bookmarks if used

.github/actions/spelling/expect.txt, .github/workflows/spelling.yml
- `expect.txt` shrinks a bit as items that are defined as aliases are automatically included in the dictionary
Addresses https://github.com/ohmyzsh/ohmyzsh/pull/10349#issuecomment-985725019
=> ci(spelling): automatically accept aliased commands

themes/ys.zsh-theme
Changes part of the prompt which were changed from white to grey to the terminal default color, providing a better experience across more terminal themes.
On my normal Konsole Breeze:
On Konsole Solarized Light:
Replaces this PR: https://github.com/ohmyzsh/ohmyzsh/pull/10295
=> fix(ys): use default color instead of gray for improved readability

plugins/fzf/fzf.plugin.zsh
- Fixes `setup_using_openbsd_package` function from fzf plugin from leaking into user environment by unset-ing like its counter-parts.
- #9463 includes this change, but not in isolation.
=> refactor(fzf): adopt code style and simplify function naming

plugins/heroku/heroku.plugin.zsh
- Fix name used to reference XDG_CACHE_HOME
@jdxcode
=> fix(heroku): fix XDG cache directory name and code style

plugins/brew/brew.plugin.zsh
This is an improvement (in my opinion) to the `brews` command that prints each leaf formula (in white), followed by its dependencies (in blue), on each line. Compared to the existing flat list of formulae, the new layout is both more compact and more informative, by differentiating leaves from dependencies at a glance.
Screenshot:
=> feat(brew): improve `brews` list layout

plugins/symfony2/symfony2.plugin.zsh
The "php bin/console" command can write "info/warn" logs and breaks the "sed/awk" command. it makes the Deprecated code visible
````
$ php $(find . -maxdepth 2 -mindepth 1 -name 'console' -type f | head -n 1) --no-ansi | sed "1,/Available commands/d" | awk '/^  ?[^ ]+ / { print $1 }'
[....]
2021-12-23T13:51:13+00:00 [info] User Deprecated: Method "Countable::count()" might add "int" as a native return type declaration in the future. Do the same in implementation "Aws\HandlerList" now to avoid errors or add an explicit @return annotation
security:encode-password 
security:hash-password
workflow:dump
````
Adding the option "--no-debug" in the "php bin/console" command deactivates debug mode
````
$ php $(find . -maxdepth 2 -mindepth 1 -name 'console' -type f | head -n 1) --no-ansi --no-debug …
```
=> fix(symfony2): silence debug lines in command completion

plugins/lpass/README.md, plugins/lpass/_lpass
- Adding zsh completion for the LastPass CLI (`lpass`)
```zsh
❯ grep plugins= ~/.zshrc
plugins=(direnv fzf git kubectl pipenv ssh-agent tmux pyenv grc lpass)
❯ lpass <tab>
--help     -h  -- show help
--version  -v  -- show version
add        -- Add a new entry
duplicate  -- Create a duplicate entry of the one specified
edit       -- Edit the selected field
...
```
=> feat(lpass): add plugin for LastPass CLI completion

.github/actions/spelling/expect.txt, plugins/rbw/README.md, plugins/rbw/rbw.plugin.zsh
- Adding [`rbw`](https://github.com/doy/rbw) plugin
[`rbw`](https://github.com/doy/rbw) is nowadays the most used CLI for [Bitwarden](https://bitwarden.com), an Open Source password manager.
=> feat(rbw): add completion for `rbw` Bitwarden client

plugins/autojump/autojump.plugin.zsh
NetBSD's default path structure is a bit different - everything is put
in /usr/pkg by default. This is tested and working on NetBSD 9.1 for
amd64.
- Make the autojump plugin work on NetBSD.
...
=> feat(autojump): add support for NetBSD

plugins/bundler/_bundler
Bundler 2.2.5 shows deprecation warning using "show":
```
[DEPRECATED] use `bundle info gem_name` instead of `bundle show gem_name`
```
=> feat(bundler): add completion for `info` argument

plugins/helm/helm.plugin.zsh
This PR updates the way of using `helm completion  zsh` command by creating a file that will be used as a cache to speed things up.
=> feat(helm): cache completion file in the background

plugins/macports/README.md, plugins/macports/macports.plugin.zsh
- Commands are provided to search with the following criteria:
* `pli`: check for updates of installed ports
* `plm`: check for updates of ports maintained by the specified list ids.
...
=> feat(macports): add commands to get list of updated ports

plugins/pass/_pass
Quote $@ in completion.
I started using zsh yesterday, and my command completion broke. 
It happens at least with filenames containing colons. The details of the breakage are: "the completion suggestions are all weird so they are useless". (I haven't looked at further details.)
The completion command contains a $@, and I my first guess was maybe trying to quote it would help. Lo and behold, it did! So I stopped trying to understand much about zsh completion after that.
=> fix(pass): update `pass` completion to ff5ac38

plugins/rvm/README.md, plugins/rvm/rvm.plugin.zsh
It's been a while and Ruby grew up to 3.0.1 version, but rvm plugin does not have any up-to-date aliases. I've took current stable minor versions from [this](https://www.ruby-lang.org/en/downloads/releases) link and add those version to rvm too. Most of gems currently support 2.5 and above versions, up to 3.x.
Hope it fits well!
=> feat(rvm): add latest `rb*` utility functions

plugins/shell-proxy/ssh-proxy.py
- Identify the proxy protocol passed to netcat based on URI schemes
- No longer pass proxy protocol options uniformly as `connect`
=> feat(shell-proxy): support SOCKS protocol based on URI scheme

plugins/systemd/README.md, plugins/systemd/systemd.plugin.zsh
All systemd power commands I've used so far (e. g. `suspend`, `hibernate`, ...) do work without root access (as in I can call `systemctl suspend` instead of `sudo systemctl suspend`).
This PR would alias those commands to not use sudo.
Also there is no user variant of the power commands so I removed that as well.
- I changed the systemd module to include a list of subcommands that are power-relevant (suspend, hibernate, hybrid-sleep, poweroff, reboot, restart, suspend)
- I changed the systemd module to remove the aliases from `scu-(any power-relevant command)` to `systemctl --user (any power-relevant command)` and changed the aliases from `sc-(power-relevant command)` which orginally was aliased to `sudo systemctl (prc)` to `systemctl (prc)` as the sudo is not needed. 
- hibernate …
=> fix(systemd): remove `sudo` from power-related aliases

plugins/vi-mode/README.md, plugins/vi-mode/vi-mode.plugin.zsh
feat(vi-mode): add INSERT_MODE_INDICATOR
* use `INSERT_MODE_INDICATOR` configure how insert mode is displayed
=> feat(vi-mode): add `INSERT_MODE_INDICATOR`

plugins/zbell/README.md, plugins/zbell/zbell.plugin.zsh
When using a workstation remotely with something like SSH, we might not want to send pop-up's on the screen.
In my case, when I connect to the UI session, I can see heaps of missed notifications. All I want with this zbell plugin is the 'bell' sent in the terminal and displayed in Tmux.
Now we have a simple option not to use 'notify-send' even if it is available.
Please note that the code follows in priority the design that was already applied in the modified file.
=> feat(zbell): add option not to use notify-send

plugins/pip/_pip
If only `pip3` is present in the shell environment,
pip uninstall tab returns an error like:
_pip_installed:2: command not found: pip
This change makes it possible to alias `pip` to `pip3` and keep the completions
working as intended.
Whatever command that the `pip` command aliases is used for generating
the uninstall completions.
Fixes #8977
n.a
=> fix(pip): use `pip3` in `pip3 uninstall` completion

plugins/pip/pip.plugin.zsh
1. Change to a long style parameter.
2. Use pipeline processing to replace temporary files. 
The original way of using "requirements.txt" as a temporary file name risked overwriting the original file.
And if the action of deleting a file is not performed correctly, the temporary files left behind can easily mislead the user.
...
=> fix(pip): don't overwrite `requirements.txt` in internal commands

plugins/ubuntu/README.md
- Documented the `acsp` alias
I noticed documentation was missing for this alias, so I decided to add it for any missing aliases in this plugin and it ended up that it was only this alias.
=> chore(ubuntu): add documentation for `acsp` alias

plugins/nvm/README.md
`$(brew --prefix nvm)` gets the definitive directory where Homebrew has installed nvm.
- Updates the README to provide a helpful hint about how to get the directory Homebrew has installed nvm in.
Having upgraded to an Apple Silicon-based Mac, I was completely stumped as to why I couldn’t get the autoloading feature to work. Oh My Zsh was working. NVM was working, it didn’t make sense. Only once I discovered that Homebrew installs in a different directory on Apple Silicon-based Macs, was I able to realise what the problem was.
Not sure if this is the best place for this information, but it’s where I came looking for help as I tried to understand why auto loading wasn’t working. I’ve also linked to the relevant page on the Homebrew site.
=> docs(nvm): clarify how to get Homebrew directory

plugins/systemd/systemd.plugin.zsh
`restart` is a unit-related command, not power-related, so it should appear as `sc-restart=sudo systemctl restart` and `scu-restart=systemctl --user restart`
- In #9441 I introduced a bad commit which falsely deleted the `scu-restart=systemctl --user restart` command. I moved away from oh my zsh soon after that PR so never found the issue myself. However, after it was merged, someone else notified us about the mistake. This intends PR intends to fix the issue.
=> fix(systemd): fix the restart command

plugins/svn/svn.plugin.zsh
svn_dirty_choose had the "return" mixed up, echoing the first input (which is basically svn info) for dirty repositories and $ZSH_THEME_SVN_PROMPT_DIRTY for clean repositories ($1 and $2). The correct behaviour is rechoing $2 and $3, respectively.
- [x ] The PR title is descriptive.
- [x ] The PR doesn't replicate another PR which is already open.
- [x ] I have read the contribution guide and followed all the instructions.
- x[ ] The code follows the code style guide detailed in the wiki.
- [x ] The code is mine or it's from somewhere with an MIT-compatible license.
- [x ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x ] The code is stable and I have tested it myself, to the best of my abilities.
- 
...
=> Fix svn_dirtry_choose echoing wrong input parameters

plugins/rust/rust.plugin.zsh
- The Rust plugin does not escape spaces in the Rust sysroot (obtained with `rustc +${${(z)$(rustup default)}[1]} --print sysroot`) when generating the completion script for Cargo, so Cargo completions fail when the sysroot contains spaces. Added double quotes around the invocation of rustc to escape spaces.
I'm not sure who maintains the Rust plugin to mention, but this change is simple enough anyways that I don't think the maintainer(s) of the Rust plugin specifically need to look at this.
=> fix(rust): Fix cargo completion when Rust sysroot contains spaces

themes/avit.zsh-theme
Fixes avit's _git_time_since_commit does not work when git log was configured to show signature by default.
=> fix(avit): disable `log.showSignatures` in `_git_time_since_commit`

plugins/mvn/mvn.plugin.zsh
- Remove usage of `find` and use glob expansion instead.
Fixes #10580
=> fix(mvn): fix listing modules in completion

plugins/helm/helm.plugin.zsh, plugins/kubectl/kubectl.plugin.zsh
- Change kubectl and helm plugins to `source`-ing their completion functions, instead of relying on `compinit` and `autoload`.
Fixes #10581
=> Fix completion loading mechanism in helm and kubectl plugins

plugins/sudo/README.md, plugins/sudo/sudo.plugin.zsh
- Switches from `sudoedit` to `sudo -e` when editing files, to give compatibility with MacOS (closes #10509). In `sudo`'s manpage is told that `sudoedit` is just an alias for `sudo -e`, so there's no problem with that :)
- Now the plugin respects the `$SUDO_EDITOR` and `$VISUAL` variables, instead of always using `$EDITOR`, with the priorities stated in `sudo`'s manpage.
=> feat(sudo): respect `$SUDO_EDITOR` and `$VISUAL`, switch to `sudo -e`

plugins/aws/README.md, plugins/aws/aws.plugin.zsh
- Accept AWS MFA token code on `acp` command line instead of having to wait for the prompt
...
=> feat(aws): accept aws mfa tokencode on `acp` cli call

plugins/poetry/poetry.plugin.zsh
- Removes an `unset` that became stale after the latest plugin refactor.
See #10595 
@mcornella
=> chore(poetry): remove unnecessary unset

plugins/1password/README.md
- Fix typo in `plugins/1password/README.md`
=> chore(1password): fix typo in `opswd`

plugins/postgres/postgres.plugin.zsh
Supporting apple silicon devices for `postgres` plugin.
Closes #10612
=> feat(postgres): support Homebrew for Apple Silicon

tools/install.sh
- Avoid's using [`git clone -c`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt--cltkeygtltvaluegt) (which specifies git-config options when cloning) to support git versions older than v1.7.7. This parameter was introduced in https://github.com/git/git/commit/84054f79de35015fc92f73ec4780102dd820e452, so using an older git (as in centos 6) will break the installer.
Fixes #8533
=> fix(installer): avoid `git clone -c` to support git v1.7.1

themes/ys.zsh-theme
- ys theme: Don't fail if `$VIRTUAL_ENV` is not set in shell with `-o nounset`
Issue was introduced in 0e5fed193edf0073fab5adaac61f7b912ea86060.
=> fix(ys): fix `$VIRTUAL_ENV` check if `nounset` is enabled

themes/rkj-repos.zsh-theme
Fix color for solarized light users. I will see the filesystem path. Works also with solarized dark.
=> style(rkj-repos): change `white` to `default` to support light color schemes

plugins/gitfast/_git, plugins/gitfast/git-completion.bash, plugins/gitfast/git-prompt.sh, plugins/gitfast/update
It's been a while since I synchronized gitfast with git-completion, that's why the changes are big, but they have been thoroughly tested.
- Fix to make it loadable through zinit
- Better handling of completion sufixxes
- More completions for `git send-email`
- Update to standardized upstream `__git_complete`
- Many small fixes
This corresponds with upstream's 2.35.0 release.
=> fix(gitfast): update to git-completion 1.3.6

plugins/1password/1password.plugin.zsh
- Originally intended to be a code change to follow the comments, I then noticed the README and the code were the same; I decided to update the comments instead, so someone reading the code wouldn't be surprised as I was when I tried to understand it.
- As I said, it's purely for people reading the code, feel free to refuse my PR if you don't find it that useful on its own!
=> chore(1password): fix comments to follow code

oh-my-zsh.sh
Reviewing the `oh-my-zsh.sh` file I noticed that wasn't really consistent. Sometimes quotes for variables, sometimes not, sometimes `[ ]`, others `[[ ]]`, so I tried to unify a little bit the style. By the way, this could also be done for other parts of the repo.
I will open this as a draft PR as this is kinda _breaking_ so we can discuss a little bit about it before deciding whether or not merging it.
I also modified a little bit the plugins loading and theme loading. Just a refactor to have a consistent code in every plugin or theme loading.
=> style(init): use consistent code style in init script

lib/cli.zsh
The commands `omz plugin {enable,disable}` and `omz theme set`
automatically reload the zsh session on success. With this
change, the CLI checks whether the commands are run in an
interactive session before reloading the zsh session.
This change also conditionally sets the completion function
for `omz` so that it's not done in a non-interactive session.
Fixes #10643
=> fix(cli): allow `omz` commands to be used in a script

plugins/yarn/README.md, plugins/yarn/yarn.plugin.zsh
Setting `ZSH_YARN_GLOBAL_DISABLE=true` prevents adding `yarn global bin` to the `$PATH`.
Fixes #10641
=> feat(yarn): add setting to disable adding global dir to `$PATH`

plugins/kubectl/kubectl.plugin.zsh
`keti` is the only `kubectl` command alias that doesn't autocomplete with the pod names when you `TAB` complete. This is because I failed to properly separate the arguments to the source command when I wrote the original aliases for `kubectl` these back in 2017.  This has been occasionally bothering me ever since like a small paper cut thats not important enough to dig into. I finally broke down and dove into the cause this morning. 
This should do NOTHING except fix a very small and subtle bug with no other potential side effects to users. Safe to merge. 
- [x ] I have read the contribution guide and followed all the instructions.
- [x ] The code follows the code style guide detailed in …
=> fix(kubectl): fix arguments in `keti` alias to allow completion

plugins/rbw/README.md, plugins/rbw/rbw.plugin.zsh
Adding `rbwpw` function, very similar to `opwsd` (or something like that 😅) in `1password` plugin. It copies the password for a service and clears the clipboard after 20s.
=> feat(rbw): add `rbwpw` function to copy passwords to the clipboard

lib/cli.zsh
When using `omz pr test #sth` I'm being prompted to enter my GPG key password, and it's really annoying because them are not important commits. I think would be nice to just don't sign it.
=> fix(cli): disable GPG signing in `omz pr test` to avoid key prompt

plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
- Only call `deactivate` if `$VIRTUAL_ENV` is set
- Unset `$CD_VIRTUAL_ENV` regardless
- Only call `deactivate` if `$VIRTUAL_ENV` is set
- Unset `$CD_VIRTUAL_ENV` regardless
Closes #10670
=> fix(virtualenvwrapper): only deactivate if virtual env is still present

plugins/kubectx/kubectx.plugin.zsh
Previously if there isn't a current kubectl context every time the plugin runs (e.g. if in a prompt) it would display `error: current-context is not set`.
- Add `$KUBECTX_UNSET` variable to configure what's displayed when no kubectl context is set
- Removes previous behaviour of displaying the error.
=> fix(kubectx): don't error on missing k8s context

tools/install.sh
- Defines `$HOME` if the variable is unset, which ended up creating a directory named `~` instead of using the user's home directory. See https://github.com/ohmyzsh/ohmyzsh/issues/10680#issuecomment-1047148767 for explanation.
- Unrelated: add `--quiet` to `git init` call since new git versions have a big prompt about the default branch when called without parameters.
Fixes #10680
=> fix(installer): set `$HOME` if not defined

tools/check_for_upgrade.sh
- Add a timeout of 2 seconds on latest commit check. This helps when not having a stable connection, in which case the update check will assume no updates are available.
- Properly check whether the latest commit is present in the local repository. Previously, only the local HEAD was compared to the remote HEAD, and if it didn't match it was assumed that the remote HEAD was newer, so there were updates. This is not true if the local repository has newer commits on top of the remote HEAD, so this change checks for that using `git merge-base`.
If merged, this PR should use the rebase strategy as both commits should appear separately in the changelog.
=> fix(updater): various update check fixes

themes/michelebologna.zsh-theme
Fixes #10715.
I think that this theme has a really low code quality for `omz` standards. It's not a priority, but maybe we should reorganize its logic.
=> fix(michelebologna): use `$HOST` variable instead of running `hostname`

plugins/helm/helm.plugin.zsh
Redirecting output from `helm` CLI caused `--classic` snap installs to throw an error if the file where it was trying to redirect its output was in a hidden folder. This workaround fixes this.
Fixes #10722
=> fix(helm): support completion for snap installs

lib/termsupport.zsh
- Add `|foot` to the terms getting title set via ANSI escape codes
Fixes #10734
=> feat(lib): support auto title in foot terminal

.gitignore, plugins/autoenv/autoenv.plugin.zsh
Based the path on my local testing and from Homebrew's own installation page [here](https://docs.brew.sh/Installation)
```
This script installs Homebrew to its preferred prefix 
(/usr/local for macOS Intel, 
/opt/homebrew for Apple Silicon and 
/home/linuxbrew/.linuxbrew for Linux)
```
=> feat(autoenv): add path for Apple Silicon Homebrew

tools/check_for_upgrade.sh
- Modified check_for_upgrade.sh in order to use builtin cd.
I'm using zoxide and I've aliased cd to z. This broke check_for_upgrade.sh because zoxide desn't understand the -q flag.
This PR force check_for_upgrade.sh to use builtin cd.
=> fix(updater): prefix `cd` with `builtin` when it is aliased

plugins/fzf/README.md, plugins/fzf/fzf.plugin.zsh
As `fd` is faster than `rg` when searching files, it should have priority when defining `$FZF_DEFAULT_COMMAND`. In my `hyperfine` tests, it's a 10-25% faster (not much, but something).
=> feat(fzf)!: default to using `fd` before `rg`

plugins/kubectl/README.md, plugins/kubectl/kubectl.plugin.zsh
- Add `kdrs` alias for describing replicasets
- Update `kgrs` to allow grepping for `replicaset` more easily
=> feat(kubectl): add aliases for replicasets

plugins/rvm/README.md, plugins/rvm/rvm.plugin.zsh
- Added ruby3.1.1 to rvm plugin
...
=> feat(rvm): add `rb31` shortcut to use ruby 3.1

tools/upgrade.sh
=> fix(updater): change remote using deprecated `git:` protocol

plugins/gpg-agent/gpg-agent.plugin.zsh
From the latest update to gpg-suite 2022.1 (MacGPG 2.2.34) I get the following errors every time I open a new session with enable-ssh-support enabled
This fix suppresses the annoying errors without affecting operation.
```bash
Note: no default option file '/usr/local/MacGPG2/etc/gnupg/gpg-agent.conf'
reading options from '/Users/wayne/.gnupg/gpg-agent.conf'
```
cc @fwalch
Fixes #10783
=> fix(gpg-agent): suppress errors from `gpgconf`

plugins/toolbox/README.md, plugins/toolbox/kubectx.plugin.zsh
Adds `toolbox_prompt_info` function.
Closes #10446
=> feat(toolbox): add plugin to show `toolbox` prompt info

plugins/fzf/fzf.plugin.zsh
- This adds support for using fzf installed by macports
I've been using this patch for since at least January without problems
=> feat(fzf): support `fzf` installed with MacPorts

tools/install.sh
- Exit the install directory with `cd -` on successful repository setup.
Fixes #10798
NOTE: can't use `pushd` and `popd` because some systems (Alpine, busybox) don't have them.
=> fix(installer): exit install directory on setup

lib/cli.zsh
I don't know how we should do this, is how I do it great, or other options are preferred?
=> fix(cli): turn of `commit.gpgsign` compatibly with git v1.7.1

plugins/vi-mode/vi-mode.plugin.zsh
- This causes vicmd 'x' to copy the deleted char into the CUTBUFFER
Based off a [user complaint on Discord](https://discord.com/channels/642496866407284746/809850042575093760/960253802571759676).
To test this PR, run `omz pr test 10820`.
=> fix(vi-mode): use system clipboard also for `vi-delete-char`

themes/frisk.zsh-theme
Fix typo in frisk theme.
Fixes #10838.
=> fix(frisk): fix color typo in `PS2`

tools/check_for_upgrade.sh
- Move check for `reminder` mode and typed user input together.
- Clear line and move cursor to the first column when displaying the reminder.
- Move check for `auto` mode after the check for typed user input. This aborts the automatic update if the user has started typing, meaning that they have stuff to do.
=> feat(updater): check for typed input before automatically updating

plugins/shell-proxy/.editorconfig, plugins/shell-proxy/ssh-proxy.py
- Allow customize netcat program
macOS built-in netcat program not supported `-X` parameter
=> fix(shell-proxy): make ssh-proxy compatible with macOS

plugins/httpie/README.md, plugins/httpie/httpie.plugin.zsh
This change reverts https://github.com/ohmyzsh/ohmyzsh/commit/93e9b80d3ff160c7d7f5be4c2c1862da97b273dc as httpie already has an https command which obviates the need for an https alias.
fixes https://github.com/ohmyzsh/ohmyzsh/issues/10855
Relevant httpie issue/commit:
https://github.com/httpie/httpie/issues/608
https://github.com/httpie/httpie/commit/8e04a24b90475608d65ad13ce66d59a41ed8b457
=> fix(httpie): remove unnecessary `https` alias

plugins/gnu-utils/gnu-utils.plugin.zsh
Signed-off-by: Robbie Lankford <robert.lankford@grafana.com>
...
=> feat(gnu-utils): include `ghostname` if present

oh-my-zsh.sh
Actual `compinit`'s approach was loading completion functions from _insecure_ directories (those categorized as insecure by `compaudit`) even though not having `$ZSH_DISABLE_COMPFIX` set to `true`. This PR's approach should take into account those insecure directories.
Without the `-C` flag in `compinit` call, `.zcompdump` file could potentially change if there are changes in completion functions, so I also added a test to see if this happened and append `omz` metadata to `.zcompdump` file.
Now the function `handle_completion_insecurities` will run in background to speed up a little bit the init time.
=> fix(init): check for unsafe directories in `fpath`

plugins/nvm/nvm.plugin.zsh
=> fix(nvm): `brew` prefix changed for Apple M1 users

plugins/git/README.md, plugins/git/git.plugin.zsh
Alias `gupom` to `git pull --rebase origin $(git_main_branch)`.
It is a very common practice for me to rebase off latest remote origin/main once I am finished with a PR, so that the commit history is clean.
- Alias `gupom` to `git pull --rebase origin $(git_main_branch)`
- Update README to reflect the new alias
*Note in this section that I am using `master`/`main`/`$(git_main_branch)` interchangibly in some places, as the PR I am referencing was created before using `git_main_branch` was common practice.*
Also see @hikaru-shindo's PR https://github.com/ohmyzsh/ohmyzsh/pull/8988, which introduces `alias grbom='git rebase origin/master'`.
This is a good suggestion, but it does not cover the full scope of my desires, mainly because it rebases off local origin/master (the version last …
=> feat(git): add `gupom` and `gupomi` aliases

plugins/oc/oc.plugin.zsh
See kubernetes / kubectl issue [106968](https://github.com/kubernetes/kubernetes/issues/106968) for more information about this breaking issue.
Alternative fix vs PR #10939 — this proposed change used `compdef` instead of directly modifying the completions generated by the `oc` utility.
- adds a single `compdef` statement to the `oc` plugin:
```sh
if [ $commands[oc] ]; then
source <(oc completion zsh)
compdef _oc oc
fi
```
=> fix(oc): fix completion for oc 4.9 and 4.10

plugins/github/README.md, plugins/github/github.plugin.zsh
- Deprecating the `git.io` command.
GitHub no longer accepts the new URL: https://github.blog/changelog/2022-01-11-git-io-no-longer-accepts-new-urls/
=> fix(github): deprecate the `git.io` command

plugins/emacs/emacsclient.sh
Fixes #10991
This is only necessitated by some plugin or emacs itself writing to
stdout when it shouldn't. But that is out of our control - so being
tolerant becomes necessary.
Since the output in question always ends in \0x07 (ASCII BELL), we just
sed it away.
Signed-off-by: Marcus Müller <marcus@hostalia.de>
- Strip the "noise" emacs starting can output, depending on emacs plugins out of our control
See discussion at the end of the report in #10991 why this is necessary, and to my best ability.
=> fix(emacs): fix check for open frames w/ extra output

plugins/git/README.md
- Updates the git plugin README so that all the LaTeX is removed
This has been a recent addition to GitHub's markdown standard (see here: https://github.blog/2022-05-19-math-support-in-markdown/) so adding the span tags removes the latex and leaves the dollar signs alone. This resolves #10993 however I suspect there will be more README files with this issue.
=> chore(git): fix unintentional latex in documentation

lib/misc.zsh
> idk if ack is supposed to exist on every distro if not then thats fine but this keeps the alias command a bit cleaner :/## Standards checklist:
added new if block to change alias ;/
https://patch-diff.githubusercontent.com/raw/ohmyzsh/ohmyzsh/pull/11017.diff
this could probably be added withsome elses bigger merge because its really small
=> chore(lib): only create `afind` alias if `ack` is installed

themes/frontcube.zsh-theme
- Addition of closing curly brace to color reset field in prompt line for the **frontcube** theme.
- Files changed: ohmyzsh/themes/frontcube.zsh-theme
- This is my first open source PR so I would appreciate any feedback in the verbosity of the PR title, branch naming or anything else. Thank you!
=> fix(frontcube): fix escape of reset color sequence

tools/check_for_upgrade.sh
omz will not auto-update on some systems using `curl`, failing at the modified line
- `--conect-timeout 2` changed to `--connect-timeout 2`
This bug (not auto-updating on console start) occurs on a WSL2 Ubuntu distribution where `tools/upgrade.sh` is modified and `git update-index --assume-unchanged tools/upgrade.sh` has executed. Tracing the script, `curl` exits unexpectedly. The script functions as expected after the change in the PR.
=> fix(updater): correct spelling of `curl` flag

plugins/git-auto-fetch/git-auto-fetch.plugin.zsh
- Only load zstat builtin command from zsh/stat module
According to man page `zshbuiltins` are the builtins `stat` and `zstat` synonymous, but because the builtin `stat` will shadow any `stat` executable in the path, it is recommended to only load `zstat`.
The plugin already used `zstat`.
~~I will fix the commit message ASAP to respect the Commit Guidelines.~~ **EDIT:** Changed commit message.
=> fix(git-auto-fetch): don't override native `stat` command

lib/cli.zsh
For people that version control their dotfiles, ~/.zshrc may be a
symlink. The omz tool was breaking symlinks when updating ~/.zshrc for
theme and plugin operations, thus not making the changes in a way that
are easily preserved and managed.
To fix this, rely on a few globbing tricks when finding the file to
resolve the target for ~/.zshrc when backing it up and when
overwriting it.
This will not work on systems lacking a realpath(3) call, but should
be no worse the current behaviour.
Fixes #10885
- [...]
...
=> fix(cli): make `omz` honour symlinks when changing `.zshrc`

plugins/git/README.md, plugins/git/git.plugin.zsh
`glum` works great in most cases when you develop based on `master` or `main` branch, however, it's also common to work against a particular feature or release branch. In this case, it'd be efficient to have an alias to sync with that particular branch in upstream.
- Introduce alias `gluc` to `git pull upstream $(git_current_branch)`
- Update README to reflect the new alias
Fixes #11087.
=> feat(git): alias `gluc` to sync with current branch in upstream

oh-my-zsh.sh
=> chore(init): ignore any aliases when running `rm`

plugins/react-native/README.md, plugins/react-native/react-native.plugin.zsh
- Introduces aliases for the iPhone 13 and iPhone 14 families and also adds the 12 Mini device.
- Add usage instructions on README
...
=> feat(react-native): add aliases for 2021 and 2022 iOS devices

lib/grep.zsh
Updating grep aliases:
- egrep to use grep -E instead of egrep
- fgrep to use grep -F instead of fgrep
Fixes #11160
=> chore(lib): update deprecated grep aliases

plugins/nvm/README.md, plugins/nvm/nvm.plugin.zsh
Source `nvm` in an async way. This `nvm.sh` takes 50ms even if using `NVM_LAZY` so let's load it only when needs to be used the first time
closes #11042
=> fix(nvm): source nvm script only when used

.github/workflows/main.yml, .github/workflows/project.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

.gitignore
There are workspace settings for vscode plugins that make contributing to ohmyzsh easier. However, these would be noisy for users, especially for those that don't use vscode.
Simply adds `.vscode` workspace settings to the `.gitignore`.
This way, myself and others that have VS Code settings specifically for contributing to this repo don't have to keep ignoring the `.vscode` folder manually on every commit (or a different `.gitignore` that ignores the `.vscode` folder 🙃 )
I had considered committing the `.vscode` settings, since there is already a precedent of adding editor settings to the repo in `.editorconfig`. However, I thought committing settings that would only work for one specific vendor's editor would only help users of vscode, and be noisy for the rest of folks. It also seemed …
=> chore: add vscode workspace settings to gitignore

lib/cli.zsh
- Change `\s` with `[ \t]` in awk script for CLI zshrc change operations.
In BSD awk, \s is not a valid sequence interchangeable with "space or tab characters"
as it is in GNU awk. This fix uses [ \t] instead, which is all the possibilities that
we need to contemplate when reading the .zshrc file.
Fixes #11146
=> fix(cli): change unrecognized `\s` in BSD awk (#11146)

plugins/git-auto-fetch/git-auto-fetch.plugin.zsh
If the remote is using HTTP authentication (and does not use a credential helper) it triggers writes to the terminal that cannot be responded to. This happens every time the repository is fetched by git-auto-fetch.
`GIT_TERMINAL_PROMPT=0` prevents prompts to the terminal. The man page explicitly names HTTP authentication as an example: https://git-scm.com/docs/git#Documentation/git.txt-codeGITTERMINALPROMPTcode
Adds environment variable to `git fetch` command in the git-auto-fetch plugin
Actually I am not 100% on if the indentation is correct. I believe it is though.
Also would be great if the PR would count for the Hacktoberfest even tough it is just one line :)
=> fix(git-auto-fetch): avoid password prompt with `GIT_TERMINAL_PROMPT=0`

plugins/brew/README.md, plugins/brew/brew.plugin.zsh
This changes the brew plugin to only source `brew shellenv` if brew cannot be found in `PATH`. This aligns with the brew installer.sh post install steps, and will prevent duplicate entries for `/usr/local/bin` in PATH on MacOS Intel.
The plugin will continue to export `HOMEBREW_PREFIX` for custom user config which previously relied on the behavior.
Fixes #11166
=> fix(brew): do not source `brew shellenv` if already on path

plugins/debian/README.md, plugins/debian/debian.plugin.zsh
- Remove `ar` alias
This alias was shadowing `ar` archiver. Closes #9304
=> fix(debian)!: remove ar alias

lib/cli.zsh
only use `column` if installed
=> fix(cli): avoid using `column`

plugins/pip/pip.plugin.zsh
=> fix(pip): fix `pipupall` error with `freeze` format

plugins/npm/npm.plugin.zsh
- npm plugin: disregard `rm` alias if set.
See also: #11156.
=> fix(npm): ignore `rm` alias

.github/workflows/project.yml
This is the GitHub blog post announcing the API changes: https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/
And this is the updated example from the GitHub documentation: https://docs.github.com/en/enterprise-cloud@latest/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions
=> Migrate to the new ProjectV2 GraphQL API

plugins/swiftpm/README.md, plugins/swiftpm/_swift
This PR updates the SwiftPM plugin autocomplete information for Swift 5.7.
`_swift` file was generated by running `swift package completion-tool generate-zsh-script` with Swift [5.7](https://github.com/apple/swift-package-manager/releases/tag/swift-5.7-RELEASE) (with small modification to include and a [manual fix approved by Apple](https://github.com/apple/swift-package-manager/pull/5852) as otherwise the autocompletion would not work)
Result autocompletion
- feat(swiftpm): update completion for Swift 5.7
- chore(docs): fix typo
=> feat(swiftpm): update completion for Swift 5.7

plugins/fzf/fzf.plugin.zsh
In function fzf_setup_using_macports, changed MacPorts fzf auto-completion file location.
MacPorts changed fzf auto-completion file location from /opt/local/share/zsh/site-functions/fzf to /opt/local/share/fzf/shell/completion.zsh .
You can check this macports fzf commit : 
https://github.com/macports/macports-ports/commit/b90c2574a1b62cabc202848d2b8684d771cdbd24
=> feat(fzf): fix MacPorts auto-completion file location.

plugins/coffee/_coffee, plugins/docker-machine/_docker-machine, plugins/frontend-search/_frontend, plugins/httpie/_httpie, plugins/kitchen/_kitchen, plugins/pod/_pod, plugins/rails/_rails, plugins/ripgrep/_ripgrep, plugins/scala/_scala, plugins/xcode/xcode.plugin.zsh, themes/refined.zsh-theme
Just a few minor capitalization fixes, e.g. `Github` -> `GitHub`.
=> docs: fix some capitalization typos

plugins/lol/README.md, plugins/lol/lol.plugin.zsh
The http URL used by the `yolo` alias of the `lol` plugin is now returning a default http redirect response:
```
➜   yolo
[master 6de2761d] <html> <head><title>301 Moved Permanently</title></head> <body> <center><h1>301 Moved Permanently</h1></center> </body> </html>
1 file changed, 0 insertions(+), 0 deletions(-)
```
Using https seems to solve the issue:
With http:
```
➜   curl -s http://whatthecommit.com/index.txt  
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
</body>
</html>
```
With https:
```
➜   curl -s https://whatthecommit.com/index.txt
Revert "fuckup".
```
=> fix(lol): use https for `yolo` calls

plugins/1password/README.md, plugins/1password/opswd
- This commit updates the `opswd` command to also copy the username of a
service into the clipboard
- The README was updated to take those changes into account
This only works for v2 of the 1password CLI, and I closed my previous PR doing this for v1 of the CLI (#10637 )
=> feat(1password): add username copy to `opswd`

lib/git.zsh
- [] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
- Add tag infromation to git prompt
...
=> feat(git): display tag in git-prompt when possible

plugins/debian/README.md, plugins/debian/debian.plugin.zsh, plugins/ubuntu/README.md, plugins/ubuntu/ubuntu.plugin.zsh
See #11331 for details about this PR.
Closes #11331
Poke @carlosala for their suggestion on how to fix it. 
- Rename alias `acs` in `debian` plugin to `acse` and update documentation accordingly;
- Rename alias `acs` in `ubuntu` plugin to `acse` and update documentation accordingly.
=> fix(ubuntu)!: rename `acs` alias to `acse

plugins/fzf/fzf.plugin.zsh
- this change allows the `fzf` plugin to find `fzf` when installed with homebrew on an Apple Silicon mac (homebrew's directory changes to `/opt/homebrew` on AS)
none?
=> feat(fzf): support macOS ARM brew install dir

plugins/cakephp3/cakephp3.plugin.zsh
- `orm_cache` command has been replaced with `schema_cache` command (to make it compatible with CakePHP 3.7+)
- Also fixed the case in "completion" command
PR #6262 has fixed the case issue, but somehow the latest revision still has this issue. Oh, well. Here's the fix.
=> feat(cakephp3): add compatibility with CakePHP 3.7+

plugins/systemadmin/systemadmin.plugin.zsh
- This makes `ip` use colored output, when not piping the output
=> feat(systemadmin): color `ip` if shell is interactive

plugins/nvm/README.md, plugins/nvm/nvm.plugin.zsh
Move plugin customization to `zstyle` and soft-deprecate old options.
=> feat(nvm)!: settings now are zstyle-based

oh-my-zsh.sh
- Compile compdump only if there's no lockfile
Closes #11341
=> fix(init): prevent multiple compdump compilations

plugins/last-working-dir/last-working-dir.plugin.zsh
Use system 'pwd' instead of possible user's alias or function.
- [...]
...
=> fix(last-working-dir): use builtin `pwd`

themes/avit.zsh-theme
- fix(avit): Replace deprecated GREP_COLOR
Fixes a warning in grep:
```
grep: warning: GREP_COLOR='1;33' is deprecated; use GREP_COLORS='mt=1;33'
```
GREP_COLOR was deprecated in grep 3.8.  https://git.savannah.gnu.org/cgit/grep.git/commit/?id=4ac5fa8959c6366f64815de3dd94e1327242af4a
=> fix(avit): replace deprecated GREP_COLOR

tools/changelog.sh
Currently `tools/changelog.sh` would generate same link of `https://github.com/ohmyzsh/ohmyzsh/commit/` for each commit in markdown mode, without the commit hash properly included in the link
* Currently: ``[`my-commit-hash`](https://github.com/ohmyzsh/ohmyzsh/commit/)``
* Expected: ``[`my-commit-hash`](https://github.com/ohmyzsh/ohmyzsh/commit/my-commit-hash)``
=> fix(changelog): generate correct commit link in markdown

plugins/nvm/nvm.plugin.zsh
Ran into an issue where the nvm autoload would always try to install and use node. Turns out newline characters in my .nvmrc files caused issues with the `nvm version` check. This PR trims non-printable characters from the .nvmrc file before passing it to nvm.
=> fix(nvm): trim non-printable chars from .nvmrc

plugins/tmux/tmux.plugin.zsh
```zsh
if [[ -n "$ZSH_TMUX_DEFAULT_SESSION_NAME" ]]; then
[[ "$ZSH_TMUX_AUTOCONNECT" == "true" ]] && $tmux_cmd attach -t $ZSH_TMUX_DEFAULT_SESSION_NAME
else
[[ "$ZSH_TMUX_AUTOCONNECT" == "true" ]] && $tmux_cmd attach
fi
```
instead of 
```zsh
[[ "$ZSH_TMUX_AUTOCONNECT" == "true" ]] && $tmux_cmd attach
```
Also fixed indentation, to be consistent inside the file.
`$ZSH_TMUX_DEFAULT_SESSION_NAME` was not used when attaching to existing session. Now it is used.
=> fix(tmux): use `$...SESSION_NAME` while attaching

plugins/term_tab/README.md
This plugin only works for OSTYPE solaris* and linux* - let users know in the readme
- [X ] The PR doesn't replicate another PR which is already open.
- [X ] I have read the contribution guide and followed all the instructions.
- [X ] The code follows the code style guide detailed in the wiki.
- [X ] The code is mine or it's from somewhere with an MIT-compatible license.
- [X ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X ] The code is stable and I have tested it myself, to the best of my abilities.
- [X ] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
...
=> docs(term_tab): plugin can only be used with linux and solaris

plugins/watson/README.md, plugins/watson/_watson
Add completion for watson time tracker https://tailordev.github.io/Watson/
With #8847 there was a PR for watson. It was closed because of a missing Readme.
I'm a first time contributor. It'd be great if there were  links to the stuff I need to read in the PR template.
=> feat(watson): add completion

plugins/doctl/doctl.plugin.zsh
- fix(doctl): add compdef line
Reported to upstream doctl at: https://github.com/digitalocean/doctl/issues/1329
=> fix(doctl): standardize plugin completion

plugins/mvn/mvn.plugin.zsh
Add `quarkus:remove-exitension` and `quarkus:remove-extensions` command support in `maven` plugin with `-Dextensions=` option
- add `quarkus:remove-extension` and `quarkus:remove-extensions`
- add `-Dextensions=` option
N/A
=> feat(maven): add `quarkus` command support

plugins/systemd/systemd.plugin.zsh
- test if systemd unit is active in user space if it is not active in on the system level.
...
=> feat(systemd): add support for user units in prompt

plugins/autojump/autojump.plugin.zsh
This commit fixes an apparent bug when sourcing autojump when it is installed through nix-darwin in MacOS. Instead of sourcing a shell script (like the other entries), the changes line tries to source the binary (which is a python script), which fails as expected with the following message.
```
...
/etc/profiles/per-user/username/bin/autojump:21: command not found: from
...
```
I am not sure if/how the old PR (#11291) worked, as it should have failed then aswell. 
Let me know if you need anything changed.
=> fix(autojump): fix autojump sourcing in nix (-darwin)

plugins/autojump/autojump.plugin.zsh
- I was unfortunately a bit too fast in my second commit in #11422, missed that the .zsh file is missing from the repo. Sorry about that.
@mcornella
=> fix(autojump): use sh file instead of zsh

plugins/pipenv/pipenv.plugin.zsh
- Remove existing _pipenv function, replace with recommended completion generation
...
=> feat(pipenv): standarize completion generation

plugins/git/git.plugin.zsh
- Update git plugin: accept "mainline" and "default" as main branch name
The [Git documentation branch management page](https://git-scm.com/book/en/v2/Git-Branching-Branch-Management) mentioned `master/main/mainline/default` in a side note as common main branch names:
> Changing the name of a branch like **master/main/mainline/default ** will break the integrations, services, helper utilities and build/release scripts that your repository uses.
> ...
I also personally encountered companies using `mainline` and `default` as their main branches' naming convention. The plugin would partially broken in such environments.
Having this change not only aligns with what Git's branch management documentation, but also making many folks who work in corporate environments a bit easier.
=> feat(git): accept `default` and `mainline` as main branches

.github/CODEOWNERS
@mcornella I'm afraid I no longer use `ohmyzsh` or even `zsh` in favour of `fish`. Hence, it doesn't make sense for me to continue being the code owner for the plugin. Good luck with supporting a fantastic tool!
=> Update CODEOWNERS to remove maksyms

plugins/jira/README.md, plugins/jira/jira.plugin.zsh
- Converts both `issue_arg` and `JIRA_PREFIX` to lower case before checking if the prefix is already present. 
- Teammates randomly deciding whether they want capital letters in their branch name
=> Make prefix check on "jira branch" command case-insensitive

plugins/jira/README.md, plugins/jira/_jira, plugins/jira/jira.plugin.zsh
- [...]
Hi! I saw that there was missing an auto-completion for `myissues` so I added one. 
I also feel that `jira mine` feels more UX-y. If this is undesired I can revert the naming.
=> refactor(jira)!: rename myissues to mine and add completion

plugins/macos/macos.plugin.zsh
- Preview.app on macOS Ventura drops support for PostScript on which the current `man-preview` function with `man -t` (basically `mandoc -Tps`) relies. This commit switches to `mandoc -Tpdf` and keeps it simple.
=> fix(macos): fix `man-preview` for macOS Ventura

lib/termsupport.zsh
- Add a `print -Pn "\r"` after setting window/tab titles to force the cursor back to the start of the line
Window and tab titles are changed by emitting unprintable escape sequences to the terminal. These escape sequences do not play nicely with the TAB character on multiple terminal emulators—they create un-deletable characters on the first line after command execution. Sending "\r" after changing the window and tab titles allows all characters on the first line to be deleted.
Fixes #11314
=> fix(lib/termsupport): Add carriage return after changing window/tab titles (#11314)

plugins/aws/aws.plugin.zsh
- Use `aws configure list-profiles` to list the available profiles instead of manually parsing the config files.
Using `aws configure list-profiles` makes sure we parse both config and credentials files.
Doing so will also make the function not prone to future changes of file format or creating / removing configurations files by AWS CLI.
Fixes #8472
=> feat(aws): load profiles from credentials file

lib/clipboard.zsh
Closes #8827
Avoid the usage of `uname` in clipboard detection.
=> fix(clipboard): `uname` seems to be slow in wsl2

.prettierrc, oh-my-zsh.sh, tools/check_for_upgrade.sh
Fixes #11390
We are only using `check_for_upgrade.sh` on init file. I'd disable whole omz upgrade (no matter which mode is enabled by the user) to prevent auto updates that might introduce breaking changes and user would not notice about that.
=> fix(init): only check for upgrade if shell is interactive

lib/functions.zsh
- The `take` now also accepts files ending with the extension `.tgz`.
The `take` command only accepts files ending with the extensions `.tar.gz`, `.tar.bz2`, or `.tar.xz`. This also allows also for files ending in `.tgz`. This extension is quite used. An example of this usage is the python source code files (https://www.python.org/ftp/python/3.11.1/Python-3.11.1.tgz)
=> feat(functions/take): make `.tgz` behave as `.tar.gz`

plugins/fzf/fzf.plugin.zsh
The code calls the external command `dpkg -s fzf` to check fzf installation and is therefore inefficient. 
I use `time zsh -i -c exit` to measure start up time. With this if condition, my startup time is 0.16-0.19s. Without this if condition, my startup time is 0.09-0.12s. This check almost doubles my start up time.
Replace it by checking the fzf binary exists at the right place.
- [...]
...
=> perf(fzf): speed up startup on debian

themes/mlh.zsh-theme
The `mlh` theme lacks this config option.
- if `MLH_SHELL_SYMBOL_ROOT` env var is defined, `mlh` theme will use it. If it's not defined, it defaults to `# `.
`MLH_SHELL_SYMBOL_ROOT` is used when `$UID` is `0` (root user).
=> feat(mlh): add separate prompt symbol for root user

lib/theme-and-appearance.zsh
Fix `diff` completion for macOS
=> fix(theme-and-appearance): fix `diff` completion in macOS

plugins/systemadmin/systemadmin.plugin.zsh
- Swallows curl error for IPv6 request to icanhazip.com and checks for return code 7 which indicates no route was accessible using IPv6 external IP.
This has been verified by checking https://test-ipv6.com/. See https://github.com/ohmyzsh/ohmyzsh/issues/11457#issuecomment-1405475594.
Fixes #11457
=> fix(systemadmin): handle error for no IPv6 route in `geteip`

plugins/git/README.md, plugins/git/git.plugin.zsh
```gpsupf``` works great in most cases when want to sync force upstream branch with the current local branch for the first time.
* Introduce alias gpsupf to 'git push --set-upstream origin $(git_current_branch) --force'
* Update README to reflect the new alias
=> feat(git): add `gpsupf` alias

tools/install.sh
- feat(installer): respect and install in `$ZDOTDIR` if set (#9376)
Fixes #9001, fixes #10479
=> Respect `$ZDOTDIR` in installer and uninstaller

tools/install.sh
=> fix(installer): don't use `$ZDOTDIR` in zshrc file if same as `$HOME`

plugins/git/README.md, plugins/git/git.plugin.zsh
- As per the issue #11388 adds a new safer flag in git plugin `--force-if-includes`
=> feat(git)!: add `force-if-includes` flag

themes/amuse.zsh-theme
- The prompt shows currently active python virtualenv (in green)
- A python unicode icon next to the env name
- Requires virtualenv plugin
- Demo:
Fixes #7766. There is another PR #8814  for the same purpose but I believe my design is better since it fits in better with the overall theme of amuse. Implementation inspired from the one in [bira theme](https://github.com/ohmyzsh/ohmyzsh/blob/master/themes/bira.zsh-theme)
=> feat(amuse): add virtualenv support

plugins/gradle/_gradle
- Fixed `gradle` plugin completion not working. Apparently the line `compdef gradle gradlew gw` must be the first line of the `_gradle` file. I broke this in #11485 – sorry about this.
=> Fix `gradle` plugin completion not working

plugins/fzf/fzf.plugin.zsh
- fix the default directory searched by fzf plugin when installed with brew on an Apple Silicon mac, which should be the `opt` not the `bin` directory.
@SConaway added this directory in #10944, but the `opt` directory should be used here instead of the `bin` directory.
=> fix(fzf): fix default fzf_base dir installed by macOS ARM brew.

lib/directories.zsh
Recent change allows disabling aliases for common directory commands, document directly in the file instead of requiring the user to parse a markdown file. (file has extremely long lines making it ugly to read with a simple pager.)
- [...]
...
=> document how to disable aliases

themes/af-magic.zsh-theme
In some cases, such as command decorations in vscode's integrated terminal, PS1 doesn't start with `(` when venv is displayed. Therefore, it should check whether `($python_env)` exits in PS1 somewhere.
- In some cases, such as command decorations in vscode's integrated terminal, PS1 doesn't start with `(` when venv is displayed. Therefore, it should check whether `($python_env)` exits in PS1 somewhere. `\(*`->`*\(${python_env}\)*`
=> fix(af-magic): fix python venv checking logic

lib/correction.zsh
These aliases were for non-standard (installed by default) unix/linux commands and should not be included here.   They should be put into their appropriate plugin to be optionally added by users using those commands.
- [...]
...
=> Remove aliases for non-standard commands

plugins/gcloud/gcloud.plugin.zsh
Latest snap installs gcloud at /snap/google-cloud-cli, so add that to the list of possible locations.
- Adds `/snap/google-cloud-cli/current` to the list of possible locations for gcloud installation
...
=> fix(gcloud): add location of latest snap install

plugins/extract/README.md, plugins/extract/_extract, plugins/extract/extract.plugin.zsh
- Add support for [obscpio](https://github.com/openSUSE/obs-service-tar_scm#obscpio) archive format
For extraction purposes an `obscpio` archive is a `cpio` archive.
=> feat(extract): support `obscpio` format

themes/af-magic.zsh-theme
- fix number of dashes in af-magic theme. 
The latest release of `af-magic` theme seems to have a problem on my zsh, I found #11495.
https://github.com/ohmyzsh/ohmyzsh/blob/8c50d1fa4a87b159080f8f3c70294669807fc7e2/themes/af-magic.zsh-theme#L9-L17
`python_env` is the **path** of Python venv like `/path/of/venv` and `PS1` contains the **name** of Python venv folder like `(venv)`. 
So line 13 is always false, therefore dashes will exceeds one line. Besides, line 14 minus too much and  dashes cannot fill one line.
=> fix(af-magic): fix number of dashes caused by python_venv checking logic

plugins/iterm2/README.md, plugins/iterm2/iterm2.plugin.zsh, plugins/iterm2/iterm2_shell_integration.zsh, plugins/iterm2/update
Mirror the official script and source it with the iterm2 plugin.
The integration script brings features like automatic marks on each prompt, drag and drop scp support, or automatic profile switching.
- adds script from https://iterm2.com/documentation-shell-integration.html
- sources that script
=> feat(iterm2): add shell integration script

plugins/gnu-utils/gnu-utils.plugin.zsh
- Checks whether `ls` alias looks like `ls -G` or `gls --color=tty` and resets it to `ls --color=tty`.
Fixes #11503
=> fix(gnu-utils): reset ls alias to use GNU-based --color argument

lib/completion.zsh
- Use character classes instead of ranges in zstyle matcher-list pattern to circumvent off-by-one error mentioned in https://www.zsh.org/mla/workers/2022/msg00652.html.
Fixes: #10972
=> fix(lib): fix case-insensitive completion for zsh 5.9

plugins/aliases/README.md, plugins/aliases/cheatsheet.py
The plugin `aliases` offers a `filter` argument to filter all available aliases, but it does not work. 
For example, `acs filter a` should only list all aliases containing `a`, but this command produces no output before this PR.
=> fix(aliases): clarify how to pass in keywords to `acs`

plugins/rvm/README.md, plugins/rvm/rvm.plugin.zsh
- Ruby 3.2 added to RVM plugin
=> feat(rvm): add `rb32` alias

plugins/brew/README.md
- Remove twice written alias from documentation
=> docs(brew): remove twice written alias from documentation

lib/functions.zsh
- If a URL is passed to `open_command`, use `$BROWSER` when set. This will fix the case when the user is in a SSH session and `$BROWSER` is set to a local browser.
Fixes #11098
=> fix(lib): use `$BROWSER` in `open_command` if set

lib/theme-and-appearance.zsh
- Reorganize sections
- Add and clarify comments
- Clean up logic for dealing with ls color flags
- Set both $LSCOLORS and $LS_COLORS defaults
- Set zsh completion coloring before first prompt (so that `$LS_COLORS` has been set to the final value)
Closes #3743
Closes #6353
Closes #8315
Closes #11091
Note: missing from #3743 is the logic to load and reset settings made by themes. The logic is pretty straightforward (capture state before and after theme setting), and it should be done on a separate PR.
=> refactor(theme-and-appearance): reorganize and clean up logic

plugins/aliases/cheatsheet.py
- The itertools.groupby function operates by grouping together *contiguous* items that have the same key. Since the `exps` list is unordered with respect to the 3rd element (i.e., they key for the group), this results in chunking together of items with the same key only if it is fortunate enough to be immediately before or immediately after another expression with the same key. Without sorting the list of `exps`, numerous expressions get put into a bin of one when they should be included in a larger group, which results in erroneously putting these expressions into the "_default" group.
- Aliases that previously showed up in the "_default" group when invoking `acs`, even though other aliases existed with the same base command, are now categorized correctly. The "_default" group now only …
=> fix(aliases): correct grouping of aliases by `acs`

plugins/vi-mode/README.md
Added Vi-mode documentation for adding mode info to prompts.
=> docs(vi-mode): document how to add vi-mode info on the prompt

plugins/rails/README.md, plugins/rails/rails.plugin.zsh
- Add alias `rta` for `rails test:all`, following the `rt` 'convention' 
`rails test` only run a subset of all tests, running the whole suite tests are a common task
=> feat(rails): add `rta` alias

plugins/aws/README.md, plugins/aws/aws.plugin.zsh
- display region from `$AWS_DEFAULT_REGION` if `$AWS_REGION` is not set
- display region from selected profile returned from `aws configure get region`
- cache `aws configure get region` within `$AWS_PROFILE_REGION`
...
=> feat(aws): set region when AWS_REGION is not set

tools/uninstall.sh
Fixes https://github.com/ohmyzsh/ohmyzsh/issues/6581: when the system is unable to revert back to the previous shell, the uninstaller aborts the uninstall process.
=> Fix: abort uninstall when unable to change shell

tools/install.sh
Using "sudo -k chsh" in termux will cause an error "env: exec -k: No such file or directory", so it needs to judge
- Add a link to determine whether sudo is tsu in install.sh
...
=> fix(installer): don't use `sudo` when user is in Termux

tools/changelog.sh
For terminals that support it, links are now provided for commit hash and issue references.
- For terminals which support it, references to issues/prs and commit hashes are now hyperlinks.
I started this work before #11545 was opened - there's a comment in there that implies that a change like this might already be in the works but I figured I may as well finish it up and offer it anyway.
This is my first contribution here, so it's possible I've missed some step - please let me know if there's anything I can do to improve both in terms of the process and code.
~~The logic for the condition used to set `supports_uris` is [taken from symfony/console](https://github.com/symfony/console/blob/75d4749d9620a8fa21a2d2847800a84b5c4e7682/Formatter/OutputFormatterStyle.php#L85-L90), which has to …
=> feat(changelog): provide links in changelog

plugins/vi-mode/vi-mode.plugin.zsh
The previous logic checked $VI_MODE_RESET_PROMPT_ON_MODE_CHANGE, which was changed on the  `vi_mode_prompt_info` function to make sure that we redisplay the prompt on vi mode change only if the vi-mode indicator is shown on the prompt.
This failed because the variable context inside a prompt function did not propagate to the regular variable environment, so the `VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true` code did not actually change anything and the prompt was never forcibly redisplayed.
This change dynamically checks whether the vi_mode_prompt_info function is added to the prompt segments to figure out whether we must redisplay the prompt.
Fixes #10915
=> fix(vi-mode): fix check for prompt redisplay on mode change

plugins/extract/extract.plugin.zsh
- Creates a folder based on file name and extracts the contents from within this folder
- Remove the folder if there was an error
- If the only content in the extraction folder is one folder, move the folder up and remove the created extraction folder
Fixes #11537
=> feat(extract): always extract files into its own folder

lib/termsupport.zsh
Contour Terminal is is supporting OSC 1 and OSC 2 as well as host programmable statusline, which can be controlled via terminfo entries `tsl` / `fsl` / `dsl`. OMZ seems to use `tsl`/`fsl` to fallback-set the window title, and that is heavily confusing. So this change ensures OSC 1 + OSC 2 logic is used, to streamline this change with most TEs.
I personally think that the host programmable statusline is a bad start to simply show that string is probably not the best choice to begin with. Despired having rare support for it. :)
=> Add support for detecting Contour terminal in title() function

plugins/term_tab/term_tab.plugin.zsh
This can probably be improved with better lsof and zsh zen, but it works reasonably well on my system.
...
=> feat(term_tab): add support for macOS

plugins/toolbox/README.md, plugins/toolbox/toolbox.plugin.zsh
- Add `tbr` to allow run `toolbox run`.
- Change `te` to `tbe` to have them in sync.
I'm thinking of adding more commands, but I'm still new to Toolbox.
=> Add toolbox run (tbr) to Toolbox plugin

plugins/jump/jump.plugin.zsh
Previously in 3c3766fdf5f64daa4a4e96bee56487314ebcd642, the applied patch did not account for the characters that would be consumed by colour coding.
Fix this by using `printf` on the inner mark name, which does not yet have colour coding.
=> fix(jump): even spacing between marks

plugins/archlinux/archlinux.plugin.zsh
- Arch Linux PLugin: Unifies the Upgrade aliases into a single function which is capable of cleanly handling an out of date Arch Linux PGP Keyring to prevent failure before handing off the system upgrade to pacman or an AUR helper.
...
=> feat(archlinux): unify `upgrade` function

plugins/aws/README.md, plugins/aws/aws.plugin.zsh
resolves #11618
tl;dr : `$(aws_prompt_info)` now can be `admin|us-east-1`
- feature 1: allow empty string for variables
- e.g., `ZSH_THEME_AWS_PROFILE_PREFIX` can be an empty string (`""`)
- feature 2: add a divider variable instead of a single space
Slight worry for the second feature: Before this commit, the divider (a single space) i visible only when AWS_PROFILE and AWS_REGION were set. But this PR, for straightforward usage, makes it always visible.
=> feat(aws): allow more customisation in prompt function

plugins/dirhistory/dirhistory.plugin.zsh
- dirhistory plugin: Don’t fail with “parameter not set” errors on navigation in shells with -o ksh_arrays
=> fix(dirhistory): run properly if `ksh_arrays` is set

lib/cli.zsh
- omz cli: Don’t fail with “bad output format specification” in shells with -o ksh_arrays
=> fix(cli): execute as expected if `ksh_arrays` is set

plugins/npm/README.md, plugins/npm/npm.plugin.zsh
- Add an npmRD alias in the npm plugin to use `npm run dev`
Many developers use `npm run dev` to test their code. If an alias for `npm test` exists, then `npm run dev` should also exist.
=> feat(npm): add `npmrd` alias

plugins/azure/azure.plugin.zsh
Closes #11644
Recognize properly linuxbrew
=> fix(azure): recognize properly linuxbrew

oh-my-zsh.sh
Fix regression introduced in #11550. If an existing alias was present in the moment of sourcing, and oh-my-zsh aliases were disabled for that file, it'd be overwritten aswell. See #11658.
Fix regression introduced in #11550. If an existing alias was present in the moment of sourcing, and oh-my-zsh aliases were disabled for that file, it'd be overwritten aswell. See #11658.
=> fix(init): avoid overwriting existing aliases

plugins/rake-fast/rake-fast.plugin.zsh
- Added rake task descriptions in the autocomplete list
- Added version control to the .rake_tasks file. If the `_rake_tasks_version` changes, it will force .rake_tasks to regenerate. This is necessary because the file format has changed
- The list of completions now shows all tasks, not just …
=> feat(rake-fast): show task descriptions in autocomplete

plugins/deno/README.md, plugins/deno/deno.plugin.zsh
- Add a `dru` alias in the Deno plugin to use `deno run --unstable`
When you use unstable API in Deno (especially [Deno KV](https://deno.com/manual@v1.33.1/runtime/kv)), this can be very useful.
=> feat(deno): add `dru` alias for `--unstable`

README.md, lib/theme-and-appearance.zsh
Closes #11647 
To disable gnu-ls (`gls`) even if it's installed in freeBSD and macOS you can set it up with:
```zsh
zstyle ':omz:lib:theme-and-appearance' gnu-ls no
```
=> feat(theme-and-appearance): allow disabling gnu-ls in bsd

plugins/aws/aws.plugin.zsh
- use local `$region` to assert whether region is set
- use local `$_aws_to_show` to check whether a divider is needed
...
=> fix(aws): use the correct variable to assert region is defined

plugins/pyenv/README.md
- [ x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
- Add a warning/instruction to the Pyenv plugin README.md in order to help deal with the confusing issue when using the plugin. Solution based on: …
=> docs(pyenv): warn about pyenv init

README.md
- Fix docs on forcing use of GNU `ls`
Needed after https://github.com/ohmyzsh/ohmyzsh/commit/dcff7a7f0854591ee1b4f25266f292ec1b1904eb as far as I can tell, for mac users who want to nudge OMZ to use GNU ls aliases
=> docs(theme-and-appearance): fix docs on forcing GNU ls

plugins/extract/README.md, plugins/extract/extract.plugin.zsh
- Extract files to random directory to minimize chance of name conflicts
- Only move single extracted directory if current directory does not contain a file or directory of the same name, i.e. to prevent:
```sh
touch file
gzip file
extract file.gz # error here
```
- Add support for `.whl` (already there), `.zlib` and `.exe` files.
Fixes #11642
Fixes #11085
=> extract: fixes and other improvements

themes/bureau.zsh-theme
The git_prompt_info() function in lib/git.zsh ignores git repos which contains a specific config key, allowing to effectively "hide" them from the prompt. Unfortunately, the bureau theme doesn't use the library function to build its prompt.
This commit modifies the specific prompt generation function in the bureau theme in order to achieve the same behaviour.
Fixes #11706
- Add support for hiding git repos with oh-my-zsh.hidden-info set to 1 as in lib/git.zsh
=> feat(bureau): ignore hidden git repos

themes/half-life.zsh-theme
- Added virtualenv prompt info to half-life theme
=> feat(half-life): add virtualenv prompt

themes/bureau.zsh-theme
Added a character to display stashed content in a git repo when using bureau theme.
...
=> fix(bureau): properly display git stash info

plugins/archlinux/README.md, plugins/archlinux/archlinux.plugin.zsh
- Use `mktemp` to create the temporary directory.
In the Archlinux environment, **`mktemp` is part of the base installation**, so there is no need to worry about its existence.
- Remove search path `/bin`, `/sbin` and `/lib`
In the Archlinux environment, `/bin`, `/sbin`, `/lib` and `/lib64` (which even not mentioned in the current version) are just **soft links** to the folders under /usr.
```bash
$ ls -ld /bin /sbin /lib /lib64
lrwxrwxrwx 1 root root 7 Dec  7 10:41 /bin -> usr/bin
lrwxrwxrwx 1 root root 7 Dec  7 10:41 /lib -> usr/lib
lrwxrwxrwx 1 root root 7 Dec  7 10:41 /lib64 -> usr/lib
lrwxrwxrwx 1 root root 7 Dec  7 10:41 /sbin -> usr/bin
```
- The command string passed to the `trap` command should use **double quotes** to ensure that parameter expansion inside is done immediately …
=> feat(archlinux): optimize `paclist` and `pacdisowned`

plugins/git/README.md, plugins/git/git.plugin.zsh
In order to get better performance, we only query the subject (first line of the commit message), using a plumbing command, `git rev-list`.
The `-c` flag of `grep` was useless, as `-q` disables output, so it was removed.
=> perf(git): improve `gunwip` alias

plugins/gcloud/gcloud.plugin.zsh
- Adds `/opt/google-cloud-cli` to the list of possible locations for gcloud installation
The recommended Arch package for gcloud is now https://aur.archlinux.org/packages/google-cloud-cli which means the path has changed for that distro to `/opt/google-cloud-cli`
=> fix(gcloud): add location of latest AUR install

plugins/autoenv/autoenv.plugin.zsh
- Create a support for `venv`, `env`, `.venv` and `.env` folder.
- Support for `activate.sh` or `activate` files.
I have come across repositories that document that to create virtual environments they use variations of folders like "env" or "venv", using for example:
```bash
python3 -m venv .venv
```
To support these, add some variations to `$install_locations`.
In mac M1 (I have not checked if it happens in other OS or if it happens by the venv library) the files that are generated do not end in .sh, so I added compatibility by doing `-e $d/activate || -e $d/activate.sh`
=> feat(autoenv): macOS compatibility, add more dirs

plugins/git/README.md, plugins/git/git.plugin.zsh
Same as `gunwip` but recursive
fix: #11721
-  add `gunwipall` function, which is same as `gunwip` but recursive
=> feat(git): add `gunwipall` function

lib/termsupport.zsh
- Skip initializing `omz_termsupport_cwd` if [in a SSH session](https://unix.stackexchange.com/a/9607/487474).
Fixes #11696
=> fix(termsupport): don't report current working directory in SSH sessions

plugins/git/README.md, plugins/git/git.plugin.zsh
fix: #11750
-  improve `gunwipall` function to produce 1 reflog record instead of many.
Solution was provided by @anastygnome in #11750. I've tested it and it seems to work as expected
=> fix(git): `gunwipall` now only resets once

plugins/docker/docker.plugin.zsh
Use `command docker` to avoid aliases and functions that may be overriding the `docker` command.
Since most docker commands require `sudo` privileges, I added an `alias docker='sudo docker'` to my `.zshrc`. I noticed that if I put the alias before `source $ZSH/oh-my-zsh.sh`, the [docker plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/docker) uses the user-defined alias instead of the actual `docker` command.
By invoking docker with `command docker` instead, aliases and functions are ignored, and the correct behaviour is always observed.
- Replaces invocations of docker with `command docker` (not a breaking change) in the plugin
...
=> Fix (docker plugin): use `command docker` to bypass aliases

plugins/gcloud/gcloud.plugin.zsh
Update gcloud search locations to homebrew handle locations
- Added `/usr/local/share/google-cloud-sdk` to the search locations for gcloud binaries
...
=> fix(gcloud): add support for `brew` installations

plugins/jira/jira.plugin.zsh
Our git uses branch names like feature/PROJECT-1234-some-description-of-the-branch. Using "jira branch" does not work here, since it does not detect the PROJECT-1234 tag, but uses the full branch name.
This fix first checks if there is more than one part, then splits it with "-" if there is only one part (that contains a "-").
When using "jira branch", the code splitted the branch name on underscore delimiter. The PR now adds support for branch names delimited with a hyphen
=> fix(jira): support identifiers delimited with a hyphen

themes/michelebologna.zsh-theme
- change white to blue
Fixes issue #11809
=> fix(michelebologna): use blue instead of white

plugins/per-directory-history/per-directory-history.zsh
- [] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
- Add ^G keybind for vimcd mode.
Fixes issue #11807
Roping in original plugin developer -- @jimhester
=> fix(per-directory-history): ^G also in vi mode

plugins/terraform/README.md, plugins/terraform/terraform.plugin.zsh
- resolves #11811 
-  I added a function called `tf_version_prompt_info` to the zsh file to specify the terraform version and also added an introduction to that function in the `Prompt function` section to the README file.
@roeniss He taught me shell script grammar while also giving me a very valuable opportunity to contribute to ohmyzsh. He is a very thoughtful software engineer and a man full of love. I am very grateful that he gave me this precious opportunity. ♥︎
=> feat(terraform): add terraform version prompt

plugins/colored-man-pages/colored-man-pages.plugin.zsh
The `colored-man-pages` plugin stopped working after this bug see
[this](https://unix.stackexchange.com/questions/746094/why-dont-these-less-termcap-variables-work-on-oracle-linux)
and [this](https://bugzilla.redhat.com/show_bug.cgi?id=1028764)
the fix was just to add
`export GROFF_NO_SGR=1` to the plugin
=> fix(colored-man-pages): add env GROFF_NO_SGR=1

oh-my-zsh.sh
The variable `custom_config_file` is no longer exist, so `unset` it does nothing. Instead, this patch rename the variable from `config_file` to `lib_file`, and unset it immediately.
- Rename the variable from `config_file` to `lib_file`
- This increased readability by distinguish between the variable for Oh My Zsh lib file and the variable for custom configuration.
- This solved the problem of `unset` a variable that no longer exist.
...
=> refactor(init): rename variable

plugins/extract/extract.plugin.zsh
- Changes `pigz` and `gunzip` commands to extract single-file `.gz` archives
- Makes sure to also move single-file extract outputs
Fixes #11642
=> fix(extract): extraction to directory for single-file .gz

plugins/alias-finder/.zunit.yml, plugins/alias-finder/README.md, plugins/alias-finder/alias-finder.plugin.zsh, plugins/alias-finder/tests/_support/bootstrap, plugins/alias-finder/tests/test_run.sh
- resolves https://github.com/ohmyzsh/ohmyzsh/issues/11624
> Before starting, I want to clarify the norms I will use.
> On `alias a=abc`, 'abc' is the source of the alias, and 'a' is the destination of the alias.
> If this naming seems inappropriate, please let me know. I couldn't find better names... 
> (This is important because the same namings are also written in [readme](https://github.com/roeniss/ohmyzsh/commit/6eb647d5a5b9f8dad3c5ab5b8d8060c65af546a5#diff-7a6e14abfc821561312a2d3217f3d66c89bb4237460daa7fb0c03ceaaffe84a6R17)) 
- Add `--cheaper/-c` option: Shows only the aliases where the destination is shorter than the current input (command). This option could filter out the following example:
```sh
> alias g=git
> alias longerCmd=git
> alias-finder -c git
g=git
>
```
- You might …
=> feat(alias-finder): add cheaper option and apply zstyle options

tools/upgrade.sh
=> fix(updater): disable `nounset` to avoid warnings

plugins/bun/README.md, plugins/bun/bun.plugin.zsh
- Adds `bun` completions. the autocompletion file is autogenerated using `bun completions`
=> feat(bun): add plugin

plugins/web-search/web-search.plugin.zsh
- added `alias` for `youtube` instead of the duckduckgo `!bang` search
!bang search for youtube using duckduckgo takes some time due to the `redirection` from duckduckgo to youtube also this makes  use of duckduckgo without the user concern which does not affect anything but still people might not like it.
with this change people can search youtube results using their primary search engine without any redirection or delay
also allowing user to use duckduckgo !bang search by using
=> feat(web-search): add `youtube` alias

lib/termsupport.zsh
- [N/A] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
- fix(termsupport): match foot* extra shipped terminfo files
- `foot` terminal ships `foot-extra` and/or `foot-extra-direct` terminfo files on many distros.
- `TERM` is set accordingly (e.g. `TERM=foot-extra`),
and would not otherwise match simply "`foot`",
therefore disabling OMZ's features when in fact they are supported.
- Reference:
- https://codeberg.org/dnkl/foot/wiki\#foot-s-terminfo-vs-ncurses-terminfo
=> fix(termsupport): match foot* extra shipped terminfo files

plugins/battery/battery.plugin.zsh
Fixes #11857 
- Uses the built-in `apm` ([OpenBSD manual](https://man.openbsd.org/apm.8)) command to fetch the battery status and details and adds OpenBSD support.
I am a bit confused about the `battery_level_gauge` function. It seems like the main function doing most work but the [README](https://github.com/ohmyzsh/ohmyzsh/tree/ccce2e1cfdf5b9680f691a402e288d9cf6ce272a/plugins/battery) just recommends the usage of `battery_pct_prompt` function which only shows the percentage.
Other than that, this is a very useful plugin.
=> fix(battery-plugin): add support for OpenBSD

plugins/extract/extract.plugin.zsh
Currently, when extracting files with extensions .tar.* (such as xxx.tar.gz or xxx.tar.bz2), the output directory name incorrectly becomes xxx.tar. This patch corrects this issue by removing the .tar extension from the directory name, ensuring the output directory accurately reflects the original file's name.
=> fix(extract): remove extraction file extension for tar

plugins/tmux/README.md, plugins/tmux/tmux.plugin.zsh
=> feat(tmux): allow all standard config files

oh-my-zsh.sh
- Skips loading Oh My Zsh if current zsh is in non-zsh emulation mode
Fixes #11686
=> fix(init): exit gracefully if on non-zsh emulation mode

plugins/podman/README.md, plugins/podman/podman.plugin.zsh
- Adding aliases for `podman` based on the aliases of the `docker` puglin
- Added an automated loading mechanism for the auto completion script, inspired by the `argocd` and `fluxcd` plugin.
This is the third try to add a plugin for podman, to provide automatic code completion and a set of useful aliases. The prior PRs were:
* #9275
* #11438
It is based on the aliases of docker that are available for docker, as podman is often promoted with its cli compatibility, so that in 95% `alias docker=podman` would also do the trick.
It should fix #9721 and #7489 by 50%.
=> feat(podman): add plugin

plugins/git/README.md
Correct whitespace to align table borders following change in #11864. This hasn't affected rendering on GitHub, but might on other markdown viewers.
n/a
=> docs(git): align markdown table borders

themes/mortalscumbag.zsh-theme
- Show the Toolbox icon in mortalscumbag if relevant. This brings the theme in line with the default Fedora Silverblue bash prompt.
I tested this with and without `toolbox` enabled.
/cc @carlosala
=> feat(mortalscumbag): show toolbox info

plugins/macos/spotify
This script is a copy/paste from https://github.com/hnarayanan/shpotify (the plugin's acknowledgements list it as such). The upstream script has been updated since this plugin was created, this PR pulls in those changes to this plugin.
I noticed the version bundled in this plugin does not work with the latest version of Spotify, however the upstream does. Hopefully this will resolve that discrepancy.
I can't tell who (if anyone) is an active maintainer of this plugin so I'm not sure who to `@`, apologies for that.
=> feat(macos): update spotify plugin to upstream

plugins/systemd/README.md, plugins/systemd/systemd.plugin.zsh
Adds `alias sc-failed=systemctl --failed` to list failed systemd units
=> feat(systemd): add alias for --failed commands

plugins/gcloud/gcloud.plugin.zsh
This PR removes the condition that checks if `gcloud` command is already available before sourcing the path file.
If gcloud SDK was installed with brew, the binary is already symlinked in the folder `/opt/homebrew/bin` which is by default in the PATH. This means that the condition is never verified and therefore, the file never sourced. This causes an issue when you need to connect on GKE clusters for instance. You would need to use the `gke-gcloud-auth-plugin` binary which won't be available because not in the PATH.
=> fix(gcloud): source `path.zsh.inc` always

plugins/hitchhiker/fortunes/hitchhiker
Replace instances of QUOTEHERESTRINGMAGIC1234 with a space. Looks like someone was doing some string processing and failed to substitute these 13 instances back out.
Tagging @luizpericolo who submitted this fortune database in the first place and perhaps can remember why.
- [n/a] The code is efficient, to the best of my ability, and does not waste computer resources.
- [n/a] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
- Replace instances of QUOTEHERESTRINGMAGIC1234 with a space 
None :)
=> feat(hitchhiker): clean up refs to magic string

plugins/dnf/README.md, plugins/dnf/dnf.plugin.zsh
- Fedora 39 or 40 moves from classic dnf to dnf5, which makes dependency
solving, package cache updates etc. faster. It's desirable to use it now
if available.
No new aliases were added.
=> feat(dnf): use `dnf5` if available

plugins/git/README.md
- [-] The code is efficient, to the best of my ability, and does not waste computer resources.
- [-] The code is stable and I have tested it myself, to the best of my abilities.
- [-] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
1. Use backticks to place all aliases in monospaced font.
2. Change table syntax to use non-aligned `|` column markers, with just one space on either side of each cell’s contents. This avoids lines being wide except where needed. It also makes it easier to edit the table without introducing broken alignment, like I did before as fixed in #11878.
3. Fix the display of some aliases. For example, `gbgd` and `gbgD` weren't showing the whole aliased command due to unescaped `|` characters (interpreted by Markdown as a …
=> docs(git): improve tables and language

plugins/git/README.md, plugins/git/git.plugin.zsh
⚠️ This PR builds on top of #11895, which should be merged first
Remove the [`--text` diff option](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt--a) from the `gsts` alias for `git stash show`. `--text` forces treating binary files as text, causing their contents to be output and potentially breaking terminal rendering.
For example, here's what `git stash show` outputs with and without `--text` for a PNG file.
First, without:
```
$ git stash show
donut.png | Bin 0 -> 238137 bytes
1 file changed, 0 insertions(+), 0 deletions(-)
```
Plain stat details, and no attempt to represent the binary file. (Representation can be added by setting up a textconv filter.)
Second, with `--text`:
```
$ git stash show --text
diff --git donut.png donut.png
new file mode 100644
index …
```
=> fix(git): remove `--text` from `gsts`

plugins/gradle/gradle.plugin.zsh
Now `gradle` alias works properly with composite builds inside project
- removed lookup of `settings.gradle` and `settings.gradle.kts` files to work with composite builds inside project
Fixes #11916
=> fix(gradle): exclude lookup for settings.gradle* files for `gradle` function

plugins/gas/README.md
- Changed the link for the `gas` plugin to the current URL
The previous url was a GitHub page hosted at http://walle.github.com/gas. The error message that appears says that github.com links no longer work for GitHub pages and to use github.io instead. After changing the URL to github.io, it redirected to this new link.
=> docs(gas): update gas plugin URL

plugins/vi-mode/README.md, plugins/vi-mode/vi-mode.plugin.zsh
This makes it possible to kill/yank to the clipboard  using `c{motion}`, `C`, `dd`, `d`, `x` and `X` when editing a line and put it back using `p` or `P`.
This was already partially supported, although some of the `vi-yank`, `vi-change` and `vi-delete` widgets were missing.
=> feat(vi-mode): copy to clipboard when using `vi-change*` and `vi-yank*` widgets

plugins/ruby/ruby.plugin.zsh
=> fix(ruby): add missing `-run` in `rserver` alias

plugins/rtx/README.md, plugins/rtx/rtx.plugin.zsh
Added a plugin for rtx, which is faster asdf as it is written in rust. Solves #11700.
- [...]
I would like to add aliases to both rtx and asdf based on use cases of users. An example would be
```alias install = "rtx install"```
...
=> Added rtx plugin (asdf replacement)

plugins/git/README.md, plugins/git/git.plugin.zsh
- change `gbda` in git plugin to delete squash-merged branches
Fixes #11613
=> feat(git): delete squash-merged branches in `gbda`

plugins/kind/README.md, plugins/kind/kind.plugin.zsh
This plugin adds completion for the [Kind](https://kind.sigs.k8s.io/) tool.
Signed-off-by: Adam Henley <adam.henley@shuttlerock.com>
- Adds autocompletion for `kind`
- Uses the zsh command completion generated by Kind itself like as kubectl does.
- Fixes #9826
Closes #10413 
Closes #11560
=> feat(kind): add plugin for Kind k8s tool

plugins/git/README.md, plugins/git/git.plugin.zsh
Follow up to #11897 after discussion. The removed `--text` option was forcing showing the patch, this PR adds the `--patch` option ([from `git diff`](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt--p)) to show the patch, without forcing binary files to be shown. Although `stash.showPatch` can be configured to enable this by default, the alias showed the patch previously and folks may not be aware of the option.
Thanks @MarijnS95 for reporting.
=> fix(git): restore showing patch in `gsts`

plugins/yarn/_yarn
- Fixes `yarn run ...` completions with UTF-8 chars in scripts. This is especially useful if there are emojis in the scripts.
Before the fix:
After the fix:
=> fix(yarn): output completion entries in UTF-8

plugins/systemadmin/systemadmin.plugin.zsh
- Fix code style
- Use `ss` equivalent commands and fall back to `netstat` if not available
Fixes #10330
=> refactor(systemadmin): use `ss` instead of `netstat` when available

plugins/zsh-navigation-tools/n-list
- [x ] The PR title is descriptive.
- [x ] The PR doesn't replicate another PR which is already open.
- [x ] I have read the contribution guide and followed all the instructions.
- [x ] The code follows the code style guide detailed in the wiki.
- [x ] The code is mine or it's from somewhere with an MIT-compatible license.
- [x ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x ] The code is stable and I have tested it myself, to the best of my abilities.
- [x ] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
Corrected a typo in plugins/zsh-navigation-tools/n-list in line number 470. fixed 'Inproper' to 'Improper'
- [...]
...
=> chore(zsh-navigation-tools): fix typo

themes/avit.zsh-theme
- Fixed how the theme set `RPROMPT`. The theme was causing plugins that would decorate the prompt to not load properly.  See Issue #10307 
...
=> fix(avit): `RPROMPT` Fix for #10307.  Allows for Plugin Prompt customization

plugins/git/git.plugin.zsh
- Return error code if no main or develop branch were found
- Fall back to `git_develop_branch` if `git_main_branch` was not found in `gbda` function
Fixes #11964
=> fix(git): fix fallback to develop branch if `master` not found

plugins/kubectl/kubectl.plugin.zsh
Add an alias to list all daemonset
Only adding one alias to get all DS
...
=> feat(kubectl): add `kgdsa` alias

plugins/git/README.md, plugins/git/git.plugin.zsh
- Move deletion of squash-merged branches into its own function
- This is a slow operation (#11985) and can't be fixed apparently
See https://github.com/ohmyzsh/ohmyzsh/issues/11985#issuecomment-1769049733
Fixes #11985
=> fix(git): move squash-merged branch deletion from `gbda` to `gbds` function

plugins/ssh-agent/ssh-agent.plugin.zsh
solves:  #11829
Added the code for ssh-agent plugin to fail gracefully and better handle edge cases.
Before this PR: If the ssh-agent plugin was enabled and the required ~/.ssh directory was not found , the plugin used to respond with an error message which was hard to understand.
Now if the ~/.ssh directory doesn't exist, plugin will respond with understandable error and will automatically create ~/.ssh directory as mentioned in the issue.
Message will be:
You have enabled the ssh-agent which requires ~/.ssh directory to store a cache file. 
Created ~/.ssh directory to store cache file.
This will only be displayed for first time if the directory doesn't existed before.
Included Code after line 22 in ssh-agent.plugin.zsh file
if [[ $? -ne 0 ]]; then
mkdir ~/.ssh
chmod 700 ~/.ssh
echo "You …
=> fix(ssh-agent): add error message if `~/.ssh` is not found

plugins/tmux/README.md, plugins/tmux/tmux.plugin.zsh
The `td` alias will create or attach to a tmux session named for the current working directory.
- Created the `td` alias, and the associated `_tmux_directory_session` function that handles the fiddly bits.
- Added documentation to the plugin README
The use case is when I'm working across several sessions. My tmux sessions are almost always scoped to whatever directory / repo I'm working out of, and doing the `tmux ls` and `tmux -a` dance to determine if I already have a session set up for a project is cumbersome and repetitive. Now I just go into a directory and `td` and it just works.
=> feat(tmux): add `tds` alias for directory sessions

plugins/direnv/direnv.plugin.zsh
Based on here:
https://github.com/direnv/direnv/blob/master/docs/hook.md#zsh
- Fix `direnv` plugin hook installation
=> fix: Use "hook" instead of "export" in `direnv` plugin

plugins/firewalld/firewalld.plugin.zsh
- fix `Error: INVALID_ZONE: public (default)` when using `fwl` with `firewall-cmd` version `2.0.1`
In `firewall-cmd` version `2.0.1`, command `firewall-cmd --get-active-zones` output like this.
```
public (default)
interfaces: wlp0s20f3
trusted
sources: 127.0.0.1
```
Just remove ` (default)` from the end of zone string. This fix won't affect any zone string without ` (default)`.
=> fix(firewalld): remove ` (default)` from the end of zone string

plugins/git-auto-fetch/git-auto-fetch.plugin.zsh
This PR enhances the git-auto-fetch plugin to support recursive fetching of submodules in a monorepo setup, without affecting its behavior in regular repositories.
- [] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
- Enabled recursive submodule fetching in git-auto-fetch script.
=> feat(git-auto-fetch): fetch also submodules

plugins/npm/README.md, plugins/npm/npm.plugin.zsh
This is my first ever attempt at open source contribution, and it is intended for the HacktoberFest. (although I only added 2 lines, I'm not sure if it qualifies) Anyway, enjoy your alias!
- added requested alias for `npm run build` as `npmrb`
I did not test this. (I am not sure how to test a different branch of zsh)
=> feat(npm): add alias for `npm run build`

plugins/wd/wd.sh
zsh versions prior to 5.0.6 mark `[[ <num> ]]` as invalid syntax
Closes #12017
=> fix(wd): use `(( ))` instead of `[[ ]]`

plugins/grc/grc.plugin.zsh
Closes #12048
- Added file `/usr/share/grc/grc.zsh` to the list of files that (could) get sourced - which is provided by Gentoo Linux package app-misc/grc.
=> fix(grc): source grc.zsh on gentoo

plugins/vi-mode/README.md, plugins/vi-mode/vi-mode.plugin.zsh
- Adds a flag to disable clipboard functionality on yank/paste, thus restoring workflow as before.
PR #11861 enabled clipboard integration when utilizing yank/paste in vi-mode, but that broke by workflow.  This change adds a flag to disable the newly added functionality, thus restoring workflow as before.
If the environment variable `VI_MODE_DISABLE_CLIPBOARD` is set the newly added functionality is not run.
=> feat(vi-mode): add option to disable clipboard

plugins/juju/juju.plugin.zsh
- The helper function `jaddr` is not working correctly. This might be because of the newer Juju versions (I'm using 3.3, for example). As I checked, the `address` field is now missing in the JSON data returned by `juju status` command. I've added a second fallback that reads the `public-address` field, as well.
- In jq, `//` is called *Alternative* operator. The jq's man page explains:
> A filter of the form a // b produces the same results as a, if a produces results other than false and null. Otherwise, a // b produces the same results as b.
=> fix(juju): add `public-address` fallback to `jaddr`

plugins/bgnotify/bgnotify.plugin.zsh
`bgnotify_appid` only checked for the presence of `xprop`, which might be available when using wayland, but will not work. Checking for `DISPLAY` is enough to prevent calling `xprop` and failing.
The other case is for wayland + sway and requires jq
- now works properly on wayland
- explicit support for sway
- explicit support for Alacritty (adds alacritty icon to notification)
=> feat(bgnotify): add support to wayland

plugins/per-directory-history/per-directory-history.zsh
- fixed per-directory-history plugin toggle message
PR is open since February at https://github.com/jimhester/per-directory-history/pull/42. However, it seems @jimhester is not active in that repo, so I'm opening a PR here now with the fix. This fixes https://github.com/jimhester/per-directory-history/issues/2. More info at https://github.com/romkatv/powerlevel10k/issues/1779.
=> fix(per-directory-history): print toggle message properly

themes/robbyrussell.zsh-theme
My system ([MIT Supercloud](https://supercloud.mit.edu/)) somehow doesn't recognize `➜` and `✗`. 
This PR fixes line wrapping in my environment.
=> fix(robbyrussell): line wrapping for some systems

lib/misc.zsh
Simple detection of `less` or `more`, and set PAGER to whatever is available.
Fixes #12049 
I did not touch the line in https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/cli.zsh#L392 as I can't be certain that the pager is already set when hitting the code. Seemed over-engineering to have the same detection there again.
=> fix(misc): only set PAGER if `less` or `more` are available

README.md
#11467 never documented the alternate installation URL. This PR fixes that, at least for the GitHub README, by including it as an alternative in key places where the GitHub raw URL is mentioned. The website needs to be updated as well, but that's a separate task for later, as it isn't covered by this repo anyway.
=> docs: document the off-github installation URL

plugins/bgnotify/README.md, plugins/bgnotify/bgnotify.plugin.zsh
- Add `bgnotify_bell` option to disable the terminal bell to just show a silent notification.
=> feat(bgnotify): add option to disable terminal bell

lib/functions.zsh
- Termux only has a single UTF-8 locale, so byte-by-byte encoding is not possible. This PR effectively bypasses that so that the resulting URL has the UTF-8 characters directly, which is [already possible in URLs](https://stackoverflow.com/a/913653).
Fixes #12061
=> fix(lib): patch `omz_urlencode` to not encode UTF-8 chars in Termux

plugins/frontend-search/README.md, plugins/frontend-search/frontend-search.plugin.zsh
Adding in nextjs search functionality. Also added in lucky feature the top result from DDO automatically added for things tha the fallback search provider..
- Add nextjs search option for frontend-search plugin.
- Add FRONTEND_SEARCH_FALLBACK_LUCKY env variable which allows the plugin to automatically open the top DuckDuckGo search result for context's that use the fallback search url.
I can break this up into two separate PRs if that makes more sense. But since the lucky ("ducky") feature is completely opt-in, and doesn't change the default behavior of the plugin, I thought it might be okay to do it in one.
=> Adding in nextjs search functionality. And add in DDG lucky feature.

.github/dependencies.yml, .github/workflows/dependencies.yml, .github/workflows/dependencies/updater.py, .github/workflows/external.yml
- Add `dependencies.yml` which tracks which dependencies we have in the repository and the path they are included in.
- Add `updater.py` script which:
- Checks upstream repositories for updates, tracking newer SHAs and tags (algorithm for tags is quite simple, might have issues in the future)
- Includes changes into the right path, with ability to run `precopy` and `postcopy` scripts (`precopy` runs on cloned upstream repository, `postcopy` runs on the dependency path within our repo)
- Creates a Pull Request if everything went well, otherwise opens an issue notifying of the available update
Currently there is a workflow included that is only manually runnable. In the future, a cron script should be included (currently commented out), and also:
- The GitHub App "ohmyzsh" should be used to …
=> ci(dependencies): add automation for updating external dependencies

plugins/rake-fast/rake-fast.plugin.zsh
- The sequence of steps when generating `.rake_tasks` file has been changed
- a variable with the contents of this file is created
- the variable is written to a temporary file
- the temporary file is moved to the location of the final `.rake_tasks` file.
This ensures that the `.rake_tasks` file is not corrupted if a process terminates prematurely or if multiple processes run in parallel. This is useful in particular when used in conjunction with the [marlonrichert/zsh-autocomplete](https://github.com/marlonrichert/zsh-autocomplete) plugin, which, while typing, runs an autocomplete command every time a key is pressed, causing the file to become corrupted.
=> fix(rake-fast): make `.rake_tasks` write atomic

tools/changelog.sh
Fixed 404 for changelog commit URLs. `omz changelog` was using 7 letter short sha for GitHub commit URLs. Since the repo has grown bigger in number of commits, we may need to update it to use 12 letter short sha instead. This is a good number for the future as well.
Following is the changelog from running `omz changelog` for the the recent update:
```
master
Features:
- 48ccc7b [dotnet]          Update completion script (#12028)
- 346bd1c [frontend-search] Add `I am lucky` option
- c37df3e [frontend-search] Add nextjs
Bug fixes:
- 1ae0515 [lib]             Patch `omz_urlencode` to not encode UTF-8 chars in Termux (#12076)
```
The output above links to 346bd1c for `[frontend-search] Add I am lucky option` the URL generated is https://github.com/ohmyzsh/ohmyzsh/commit/346bd1c …
=> fix(changelog): use longer hashes for commits

plugins/bgnotify/bgnotify.plugin.zsh
fixes: #12097 When running with bgnotify plugin, set -e will terminate zsh immediately 
- Added return 0 instead of return
- Attributed the code change to the original author @ipChrisLee on the commit
=> fix(bgnotify): make it work with `set -e`

plugins/aws/README.md, plugins/aws/aws.plugin.zsh
The aws plugin gives the user the possibility to login into the sso session when using the AWS profile selection. Unfortunately, it is not possible to also logout this way. Naturally, one would think that when one is typing "asp <aws_profile> login" it is also possible to type "asp <aws_profile> logout" but this is currently not the case. This commit adds this possibility and therefore enables the user to login and logout with the plugin without having to use awscli directly.
- [] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
- Add aws sso logout possibility for aws plugin
...
=> feat(aws): add sso logout capabilities

plugins/aws/README.md, plugins/aws/aws.plugin.zsh
- Resolves https://github.com/ohmyzsh/ohmyzsh/issues/11482, simply add `<sso_session>` to login with SSO session after `asp <profile> login`
...
=> feat(aws): add support for sso sessions login

.github/workflows/dependencies.yml, .github/workflows/dependencies/requirements.txt, .github/workflows/dependencies/updater.py, .github/workflows/project.yml
Bugfixes of #12109:
- Pass `GH_TOKEN` properly.
- Author commits as the bot (displayed correctly on Github UI)
- Use bot token as well for `project.yml` workflow
- Fix `tmp` dir
=> ci(dependencies): pass app token properly

lib/clipboard.zsh
The function `clippaste` wont emit an additional new line on Wayland anymore.
`clippaste` Now behaves similarly between Wayland and X11.
Here are my tests, on X11:
```console
$ echo foobar | xsel --clipboard --input; xsel --clipboard --output; echo END
foobar
END
$ echo -n foobar | xsel --clipboard --input; xsel --clipboard --output; echo END
foobarEND
```
```console
$ echo foobar | xclip -selection clipboard -in &>/dev/null; xclip -out -selection clipboard; echo END
foobar
END
$ echo -n foobar | xclip -selection clipboard -in &>/dev/null; xclip -out -selection clipboard; echo END
foobarEND
```
on Wayland (sway), without and with `wl-paste`'s `--no-newline` option:
```console
$ echo foobar | wl-copy; wl-paste; echo END
foobar
END
$ echo -n foobar | wl-copy; wl-paste; echo END
foobar
END …
```
=> fix(clipboard): remove clippaste additional newline on wayland

plugins/gcloud/gcloud.plugin.zsh
I have added the path `"$HOME/.asdf/installs/gcloud/*/"` to the `search_locations` array. This is specifically for cases where the **Google Cloud SDK** is installed using the **ASDF Version Manager**.
- Added `$HOME/.asdf/installs/gcloud/*/` to the `search_locations` array.
=> feat(gcloud): add asdf installation dir

plugins/macos/macos.plugin.zsh
Instead of just running `man` with no argument, which leads to it printing the question `What manual page do you want?`, we now print a usage statement if no arguments are provided.
**Before this change**
```
> man-preview
What manual page do you want?
```
The command then hangs and you need to use Ctrl-C to abort it.
**After this change**
```
> man-preview
Usage: man-preview command1 [command2 ...]
>
```
=> fix(macos): print usage for `man-preview` with no args

themes/rkj-repos.zsh-theme
If the `hg` command is available but `~/.hgrc` does not exist, the theme would print `grep: ~/.hgrc: No such file or directory` before every prompt line.
Could be also achieved by redirecting grep's stderr to `/dev/null` or adding the `-s` flag. Not sure which approach is best, please comment.
=> fix(rkj-repos): check if `~/.hgrc` exists

plugins/web-search/README.md, plugins/web-search/web-search.plugin.zsh
- added alias for DeepL URL: `https://www.deepl.com/translator#auto/auto/`
I discovered that when I input a specific string into the URLs of DeepL, they automatically translate it for me.
I often use web-search.plugin and frequently use DeepL as well. Therefore, thinking it would be convenient to be able to translate from web-search.plugin to DeepL, I sent a request.
DeepL automatically translates text when you add a string after `https://www.deepl.com/translator#auto/auto/`.
For example, like this:
[https://www.deepl.com/translator#auto/auto/こんにちは世界](https://www.deepl.com/translator#auto/auto/こんにちは世界)
=> feat(web-search): add `deepL`

plugins/history-substring-search/README.md, plugins/history-substring-search/history-substring-search.plugin.zsh, plugins/history-substring-search/history-substring-search.zsh
Updates OMZ's copy to commit 8dd05bfcc12b0cd1ee9ea64be725b3d9f713cf64 from zsh-users/zsh-history-substring-search
- ran `ohmyzsh/plugins/history-substring-search/update-from-upstream.zsh` and created PR from changes
- Fixed #11925
=> feat(history-substring-search): update to upstream

plugins/vscode/README.md, plugins/vscode/vscode.plugin.zsh
- Added a vscode plugin alias that allows you to open it with a particular profile.
This functionality is available in the newer VS Code versions and documented [here](https://code.visualstudio.com/docs/editor/profiles). The particular commandline option is given [here](https://code.visualstudio.com/docs/editor/profiles#_command-line).
=> feat(vscode): add `vscp` alias

plugins/autojump/autojump.plugin.zsh
NixOS configuration can have user-scoped packages, e.g.:
{
users.users.example.packages = [ pkgs.autojump ];
}
There was an entry to try and support this but I think autojump must have changed in nixpkgs to break it.
- [...]
...
=> feat(autojump): add path for nix per-user

lib/spectrum.zsh
- add the "dim" formatting option that has been missing in the FX helper in `lib/spectrum.zsh`
The _dim_ option is listed for example [here](https://misc.flogisoft.com/bash/tip_colors_and_formatting).
=> feat(lib/spectrum): add `FX[dim]` and `FX[no-dim]` formats

plugins/jump/jump.plugin.zsh
BREAKING CHANGE
jumping previously took you to the absolute path of the marked
directory. If you create a mark to a symlinked path, then when you jump
you'll end up at the absolute version of that path:
```
$ mkdir /real-path
$ ln -s /real-path /link-path
$ cd /link-path
$ mark
Mark /link-path as link-path? (y/n) y
$ jump link-path
$ pwd
/real-path
```
this seems unintuitive to me, so this commit changes the jump function
to take you to the actual path of the mark (`/link-path` in the example
above) rather than the absolute path.
although this is a breaking change, I felt conflicted about the value of adding an environment variable to preserve the old functionality, since this seems more intuitive and is such a small change. But I can totally imagine how this could inconvenience people, …
=> fix(jump)!: only resolve mark symlink

plugins/aws/aws.plugin.zsh
- Sets a default region for the `aws ec2 describe-regions` call in `aws_regions` to avoid this situation:
```
You must specify a region. You can also configure your region by running "aws configure".
You must specify a region. You can also configure your region by running "aws configure".
Available regions:
```
I've used `$AWS_DEFAULT_REGION` and `$AWS_REGION` as regions for the call in case they are set.
I think we could always use any region like `us-west-1` but I can't test if the list is different when using an "exotic" source region.
=> fix(aws): pass default region to fetch regions

plugins/git-commit/README.md, plugins/git-commit/git-commit.plugin.zsh
- Added new type for commit
- I noticed that you are following the ["Conventional Commits"](https://www.conventionalcommits.org) exactly but this new implementation might be interesting.
=> feat(git-commit): add `wip` kind

plugins/aws/README.md, plugins/aws/aws.plugin.zsh
- [?] The code is efficient, to the best of my ability, and does not waste computer resources.
- [n/a] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
- Introduced a mechanism to store the AWS Profile in a file in order to survive shell sessions 
~This implementation will affect the shell startup time noticeably because of the file read operation and call to asp/asr on each new shell. If you clear the profile (meaning state file is empty) it will have no measurable impact.~
EDIT: We fixed the performance issue by avoiding validation when loading profile from state.
=> feat(aws): implement permanent state

plugins/kubectx/kubectx.plugin.zsh
- Fix the problem: When Kubernetes context contains spaces, custom names are not working.
=> fix(kubectx): k8s contexts with spaces

plugins/brew/brew.plugin.zsh
Using the tool proposed in https://github.com/ohmyzsh/ohmyzsh/pull/10859, I could find this duplicate which is easy to fix
- [...]
...
=> chore(brew): remove duplicated alias

lib/prompt_info_functions.zsh
- quotes the call in the `ruby_prompt_info` to preserve leading spaces
=> fix: Quote ruby prompt

plugins/sublime/sublime.plugin.zsh
- Changed the alias `sst` from `sudo subl` to `sudo -EH subl`
On some (all ?) wayland environnements, like Hyprland,  `sudo subl` is not able to open a new window (although it can open files in an already open window). This fix allow it to work.
=> fix(sublime): pass user's env to `sst`

plugins/web-search/README.md, plugins/web-search/web-search.plugin.zsh
- Add search engine `dockerhub` --> "https://hub.docker.com/search?q=";
- Add search engine `npmpkg` --> "https://www.npmjs.com/search?q=";
- Add search engine `packagist` --> "https://packagist.org/?query=";
- Add search engine `gopkg` --> "https://pkg.go.dev/search?m=package&q=".
- Add new aliases in README.md `ohmyzsh/plugins/web-search/README.md`
The aliases `npmpkg` and `gopkg` had to have "pkg" added to the name as they would conflict with other commands.
The aliases `dockerhub` and `packagist` got this way due to the name of the container registry itself and the Composer package repository being this way.
I already use them on my PC and I also did some research to see if they would conflict with any commands.
=> feat(web-search): add programming packages search

.github/workflows/installer.yml, .github/workflows/main.yml
- Resolve deprecation warnings in workflows, see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> ci: bump `actions/checkout` version

plugins/kubectx/README.md
After merging #12191, keys in the associative array of available contexts now need to be quoted.
Not sure if this change is to be considered a bug or if just fixing the documentation is enough.
=> docs(kubectx): add quoting to array keys

plugins/zoxide/README.md, plugins/zoxide/zoxide.plugin.zsh
Updating `zoxide.plugin.zsh` to set the `--cmd` argument to the `ZOXIDE_CMD_OVERRIDE` variable with a default of `z`.
=> feat(zoxide): add option to override cmd

plugins/docker/docker.plugin.zsh
- This is a replication of #10723 for the same problem showing around snap installs of docker
- @mcornella I didn't open an issue as to not add overhead for something I took off @strowk 's PR (#10723 ) following issue #10722 . LMK if an issue is indeed needed. I'd be happy to comply.
- The bug here exhibited the same behavior for docker plugin as described in #10722. Namely: `write /dev/stdout: permission denied` on each new shell when docker plugin is enabled. Debugging showed the error stems from the redirection.
- Untested yet. Not sure how to test without `omz pr test ...`
=> fix(docker): support completion on snap installs

plugins/tmux/README.md, plugins/tmux/tmux.plugin.zsh
- I honestly don't know why this wasn't added earlier. It's a feature I use frequently because it compels me to keep only one section active and adjust the screen size accordingly.
- I also took the liberty of defining the README.md list of features and aliases in alphabetical order, improving the pattern and organization.
=> feat(tmux): add option for detached mode

plugins/tmux/README.md, plugins/tmux/tmux.plugin.zsh
- The default value for `ZSH_TMUX_FIXTERM_WITHOUT_256COLOR` and `ZSH_TMUX_FIXTERM_WITH_256COLOR` now will use `tmux-(256color)?` if exist. This is in accordance to the important note specified in the [tmux FAQ page](https://github.com/tmux/tmux/wiki/FAQ)
It seems `tmux-256color` provides support for some text formatting that `xterm-256color` doesn't. For instance, [the former supports italics while the latter doesn't](https://github.com/gpakosz/.tmux/issues/382).
=> feat(tmux): prioritize `tmux` terminfo

.github/CODEOWNERS, plugins/eza/README.md, plugins/eza/eza.plugin.zsh
The `eza` plugin provides some configurable aliases to simplify usage of the [`eza`](https://github.com/eza-community/eza) tool.
* Creates 5 aliases that are very common to invoke when using the `ls` command, but implemented using `eza` instead
* Allows limited configuration for `eza` defaults through usage of `zstyle` (see `README.md` for info)
=> feat(eza): create plugin

plugins/tmux/tmux.plugin.zsh
- Removes the -t flag from the aliases. (Fixes #12230)
If passing -t does something important, this may not be ideal. AFAICT `tmux attach-session` and `tmux attach-session -t` are identical.
=> fix(tmux): do not pass empty flags to aliases

plugins/ssh/ssh.plugin.zsh
With the small changes in this commit we split all the host values in lines, sort them out and make a unique array of them.
- Update SSH plugin.
The current completion doesn't work correctly when there are multiple hosts per line, e.g.:
```
Host foo bar baz
```
SSH config also allows to have repeated hosts, e.g.:
```
Host foo bar
...
Host foo
...
```
=> fix(ssh): allow multiple definitions per host

plugins/kube-ps1/README.md, plugins/kube-ps1/kube-ps1.plugin.zsh
Add `KUBE_PS1_KUBECONFIG_SYMLINK` variable that defaults to `false`. This varialble will control the behaviour of `stat` and `zstat` commands. Users will be able to set the var to `true` and thus force the plugin to evaluate the mtime of the symlink instead of the real file. This will be …
=> feat(kube-ps1): add symlink support

plugins/tmux/tmux.plugin.zsh
- Use the offset as 0 to extract the first letter when checking whether the parameter is a flag like `-t`.
My zsh version is v5.8.1 and tmux version is 3.2a. After the change in [fix(tmux): do not pass empty flags to aliases](https://github.com/ohmyzsh/ohmyzsh/pull/12232), I found the alias command `ta server` can not work to attach the session. The error is `ta:1: closing brace expected`. This is caused by the omitted offset parameter. Add 0 as offset can fix it.
=> fix(tmux):  use the offset parameter when extracting the first letter

plugins/terraform/_terraform
Up-to-date Terraform completion as of v1.7:
- Update all usage strings
- Remove removed arguments in Terraform v1
- Add completion for all new commands and flags
- Add value completion on many flags (mostly boolean and enums, some files and directories)
- Add completion of global options
- Fix completion of resource addresses
- Add completion of workspace names
- Ensure all function are prefixed by `_terraform` to avoid collision with other functions in the global scope
- Ensure functions are defined on once
- Make code formatting consistent
- Make loading completion flexible (I find `source`'ing convenient for development for example)
...
=> feat(terraform): update completion to `v1.7`

plugins/python/README.md, plugins/python/python.plugin.zsh
- Adds and runs a function that listens for directory changes. When cd'ing into a directory
containing `venv/bin/activate`, it automatically activates the virtual environment.
When cd'ing out of the directory, it automatically deactivates the virtual environment.
- It supports two global environment variables,
- `VENV_NAME`  where a name different from `venv` can be specified. (For example,
`.venv` is also suggested by the Python docs.)
- Also, if anyone doesn't want this, they can simply set `DISABLE_AUTO_VRUN` and the listener
will always exit without making any changes.
Auto-activating the environment is a feature of the Ruby Version Manager (rvm). I really like that feature,
and researched till I could add it to my Python environments. I've been running this on my computer for
about …
=> feat(python): add auto venv activation

plugins/terraform/_terraform
- pass -chdir to completion commands
- stabilize sub-sub-commands completion
Thank you @carlosala for the quick merge on #12252 :bow:
=> fix(terraform): pass -chdir to completion commands

plugins/terraform/_terraform
- Ensure all flags with a value (`-flag=`) have a message, otherwise the completion suggests them again and again as if they were repeatable flags (`*-flag=`)
...
=> fix(terraform): fix completion repeating flags with value

.github/dependencies.yml, plugins/gitfast/README.md, plugins/gitfast/gitfast.plugin.zsh, plugins/gitfast/update
- General update
I've removed the `update` script since it seems a GitHub action is already taking care of the updating. I also updated the plug-in standard code to match upstream. And I removed the aliases section in the readme, since it only applies to ancient versions of oh-my-zsh.
=> chore(gitfast): remove update script

tools/changelog.sh, tools/install.sh, tools/upgrade.sh
zkat/supports-hyperlinks has updated the list of terminals that support
hyperlink escape codes.
=> feat(tools): update `supports_hyperlinks`

lib/async_prompt.zsh, lib/git.zsh
- Implement generic async prompt feature
- Apply to git prompt by default
BREAKING CHANGE: the `git_prompt_info` prompt function has been reworked by default to use the new async prompt feature. If you're experiencing issues, you can set the following zstyle setting in your `.zshrc` file before Oh My Zsh is sourced:
```sh
zstyle ':omz:alpha:lib:git' async-prompt no
```
Fixes #10869
=> feat(async)!: implement async prompt API and apply to git prompt

plugins/fzf/fzf.plugin.zsh
- Add default fzf base path on [MSYS2](https://www.msys2.org/) system on Windows
=> fix(fzf):  add default fzf_base dir when on Windows MSYS2 System

plugins/extract/extract.plugin.zsh
- Try to use `pbzip2` when extracting `.bz2` archive.
=> feat(extract): prefer using `pbzip2` instead of `bunzip2`

plugins/docker-compose/_docker-compose
Remove unnecessary backslash causing error in `docker-compose config`  completions.
=> fix(docker-compose): completion regression

plugins/mise/mise.plugin.zsh
Now mise installs can be found by any following OMZ plugins.
- Run `mise hook-env` automatically
...
=> fix(mise): update environment when loading the plugin

plugins/ssh-agent/ssh-agent.plugin.zsh
The ssh-agent plugin provides a symlink of SSH_AUTH_SOCK with a stable name, so that tmux/screen users can reference this name in their configs, e.g. in .tmux.conf:
```
set -g update-environment "DISPLAY SSH_ASKPASS SSH_AGENT_PID \
SSH_CONNECTION WINDOWID XAUTHORITY"
setenv -g SSH_AUTH_SOCK /tmp/ssh-agent-$USER-screen
```
However, up to now, the if conditions in the plugin were formulated such that, if the symlink already exists, a new ssh-agent would be started, thereby overwriting the SSH_AUTH_SOCK from the symlink. This defeats the whole purpose of the symlink mechanism.
Steps to reproduce issue:
1. Enable agent forwarding on client and enable ssh-agent plugin + forwarding on server, add lines above to .tmux.conf
2. Start ssh agent on client, add a key
3. Connect to server with …
=> fix(ssh-agent): don't start new agent if screen/tmux symlink exists

plugins/jira/README.md, plugins/jira/_jira, plugins/jira/jira.plugin.zsh
```
❯ jira help
jira                            Performs the default action
jira new                        Opens a new Jira issue dialogue
jira ABC-123                    Opens an existing issue
jira ABC-123 m                  Opens an existing issue for adding a comment
jira dashboard [rapid_view]     Opens your JIRA dashboard
jira mine                       Queries for your own issues
jira tempo                      Opens your JIRA Tempo
jira reported [username]        Queries for issues reported by a user
jira assigned [username]        Queries for issues assigned to a user
jira branch                     Opens an existing issue matching the current branch name
```
=> feat(jira): add help/usage cmd

plugins/starship/starship.plugin.zsh
BREAKING CHANGE: starship plugin will keep ZSH_THEME as a fallback if Starship is not found. You can put ZSH_THEME="" before running oh-my-zsh.sh to keep the previous behavior where starship plugin always unset the Zsh theme.
While I usually use Starship to configure the prompt style, some of my environments don't have Starship installed (by default). I want to use one of Oh My Zsh themes as the fallback instead of the default Zsh prompt if Starship is not (or cannot be) installed. 
CC @axieax as the author of the great plugin
=> fix(starship)!: keep `ZSH_THEME` when Starship is not found

plugins/gcloud/gcloud.plugin.zsh
- Add `/opt/homebrew/share` to glcoud installation search paths
I don't know enough about to internals of homebrew to understand why this path is different than existing options. But I have new mac and just installed google-cloud-sdk:
```
==> Caveats
for zsh users
source "$(brew --prefix)/share/google-cloud-sdk/path.zsh.inc"
source "$(brew --prefix)/share/google-cloud-sdk/completion.zsh.inc"
➜  brew --prefix
/opt/homebrew
```
=> fix: add gcloud homebrew installation path

plugins/httpie/_httpie
- httpie completion now also works on its `https` command that previously wasn't completed.
=> Added https httpie command to completion sources

lib/async_prompt.zsh
- Make sure `_omz_async_callback` is only called when the handler writes data (at the end), instead of just after the fork : it blocked the shell until the end of the async prompt handler
- Do not use a subshell to set the status
- Fixes #12290 (cc @mcornella)
This is draft for now, as I cannot explain why the subshell could sometimes block for several seconds (which blocked the shell in `_omz_async_callback`).
Even when it didn't block, the subshell was 10-20ms slower anyway.
=> fix(async): avoid blocking the shell while waiting

lib/async_prompt.zsh
- Do not run `command true` (fork + exec) in `_omz_async_request` with zsh >= 5.8
=> perf(async): avoid executing true

plugins/autojump/autojump.plugin.zsh
The added path is currently default for Apple Silicon installations with 'pkgsrc' - https://pkgsrc.smartos.org/
- [...]
This is really a simple fix...
```
❯ pwd
/opt/pkg/share/autojump
❯ tree
.
├── autojump.bash
├── autojump.fish
├── autojump.sh
├── autojump.tcsh
├── autojump.zsh
└── icon.png
0 directories, 6 files
```
=> autojump plugin: fix for 'pkgsrc' installation path on macOS

plugins/laravel/README.md, plugins/laravel/laravel.plugin.zsh
- Added `pat` alias for `php artisan test` into Laravel plugin.
Since running tests is one of the most repetitive tasks in TDD flow, I think it would be nice to have this alias.
=> feat(laravel): add `artisan test` alias (`pats`)

plugins/git/README.md, plugins/git/git.plugin.zsh
- Added `gmc` alias for `git merge --continue` in git plugin
=> feat(git): add alias `gmc` for `git merge --continue`

lib/history.zsh
fixes #12334 by not forcing the `1` argument and giving the user more control.
=> fix(history)!: fix arg passing to `fc` for `history` command

lib/history.zsh
Handles:
https://github.com/ohmyzsh/ohmyzsh/pull/12338#issuecomment-2045281096
https://github.com/ohmyzsh/ohmyzsh/pull/12338#issuecomment-2045304370
Running `history` prints the whole history starting from 1.
=> Reverting to old behaviour when running just `history`

plugins/shell-proxy/ssh-proxy.py
The ssh-proxy.py generates `nc` commands to connect the proxy. However, in cygwin, it does not set the protocol type, leading to `nc` using wrong default protocol (socks5) if we actually use an http proxy.
- add a check ("cygwin") for sys.platform
=> fix(shell-proxy): support ssh-proxy using http proxy in cygwin

plugins/yarn/_yarn
This simply replaces 3 instances of `cd` in the `_yarn` completion script with `builtin cd` to avoid issues in the case that `cd` has been aliased or redefined. While this may sound like an unusual situation, consider the example below.
Example: `cd` is 'enhanced' to list contents of the new directory, e.g.
```shell
function cd () {
builtin cd "$1"
ls -laFhGT
}
```
Chaos ensues on invoking completion, `yarn ⇥` <kbd>tab</kbd>
<a href="https://asciinema.org/a/ejagW9I1NnnSpciUanxshhx0r" target="_blank"><img src="https://asciinema.org/a/ejagW9I1NnnSpciUanxshhx0r.svg" alt="asciinema of yarn completion bug" style="max-width:500px;"  width="500" /></a>
Here is a video screen recording if asciinema link goes away:
<video controls muted src="https://github.com/ohmyzsh/ohmyzsh/assets/8978069/82cd8f1 …
=> fix(yarn): use `builtin cd` in completion

plugins/poetry-env/poetry-env.plugin.zsh
Support moving from one poetry directory to another poetry directory instead of only from a non-managed poetry directory into and out of poetry managed ones.
This version of the script includes several improvements:
- **Deactivation Logic**: It checks if you're moving out of a Poetry directory or into a different Poetry directory. This ensures the current environment is deactivated when needed.
- **Reactivation Logic**: After potentially deactivating an environment, it checks if the new directory is a Poetry directory. If so, it activates the environment for the new directory.
- **Robustness Enhancements**: The script now properly checks for the existence of pyproject.toml and validates it contains Poetry configuration before attempting to activate an environment. It also handles …
=> feat(poetry-env): support changing between two venv dirs

plugins/tmux/README.md, plugins/tmux/tmux.plugin.zsh
When `$ZSH_TMUX_AUTONAME_SESSION=true`, name the tmux session after the working directory.
If you are in `~/foo/bar`, the name will be `bar`. If you are in `~/`, the name will be `home`.
=> feat(tmux): sessions named as current dir

lib/history.zsh
Introduce local stamp and catch options -f, -E and -i to it.
- Add a local stamp variable and use `zparesopts` to catch option `-f`, `-E` or `-i'
...
=> fix(history): fix edge cases introduced in #12341

lib/history.zsh
The `t` option takes a strftime format specification as argument. This fixes cases in which $HIST_STAMPS is set to a value outrange `"mm/dd/yyyy|dd.mm.yyyy|yyyy-mm-dd"`.
- Add `t` option to the zparseoptions to fix #12364 
...
=> Add `t` option to omz_history function

lib/async_prompt.zsh, lib/git.zsh
- Use `zle .reset-prompt` in `_omz_async_callback` to bypass crash reported in #12331 (test)
~~This is only a test based on a hunch related to [[1]] and [[2]] fixed in 5.0.6.~~ Confirmed to solve the issue in [[3]].
[1]: https://www.zsh.org/mla/workers/2014/msg00237.html
[2]: https://github.com/zsh-users/zsh/commit/97115e0e7f33378390aabd3c15d0cd69bf8d191c
[3]: https://github.com/ohmyzsh/ohmyzsh/issues/12331#issuecomment-2065941645
=> fix(async): bypass zsh 5.0.2 crash on `zle reset-prompt`

plugins/ssh-agent/ssh-agent.plugin.zsh
=> fix(ssh-agent): add identity only if identity exists

themes/fishy.zsh-theme
Modifies the prompt in fishy.zsh-theme to display the hostname in a different color (yellow) when the user is connected via SSH. Additionally, the username is now displayed in a separate color block, improving readability and making it easier to distinguish different components of the prompt.
- Modified the fishy theme prompt to add color to the username. This is consistent with the current version of fish-shell.
- Modified the fishy theme prompt to display the hostname in a different color (yellow) when the user is connected via SSH. This is consistent with the current version of fish-shell.
=> feat(fishy): add color to username

plugins/autojump/autojump.plugin.zsh
=> feat(autojump): add `nix-darwin` install path

plugins/extract/extract.plugin.zsh
- Fix extraction for single-file .zst
Currently it returns an error:
```
$ extract archive.zst 
extract: extracting to archive
zstd: /tmp/archive: Is a directory
```
The code replicates the same logic as with .gz file, i.e.
```
gunzip -ck "$full_path" > "${file:t:r}" ;;
```
=> fix(extract): `zst` now extracts as expected

plugins/python/README.md, plugins/python/python.plugin.zsh
1. `auto_vrun` function uses `PYTHON_VENV_NAME` as pattern rather than full name.
2. `auto_vrun` function searches for venv not only in current directory but also in parent directories.
1. Allows auto-activation of  venvs with descriptive names that follow naming convention: (e.g. venv_name, venv-description, venvsomething).
2. Does not deactivate venv when entering a subdirectory of a project but only when cd'ing up the directory tree. That is more natural behavior in most use cases.
=> feat(python): autovenv keeps activated on subdirs

lib/cli.zsh, lib/tests/cli.test.zsh
- Adds word-boundary regexes in awk script to be more accurate in regex replace.
Fixes #12400
=> fix(cli): fix disabling plugins by accident in `omz plugin disable`

.github/dependencies.yml
- https://github.com/mfaerevaag/wd/releases/tag/v0.6.0
Are the changes made in 2d32e9be668672c110405aa2952ab8adaf374856 still required? They were never contributed upstream so my simple copy-paste from the wd repo has overwritten them
=> feat(dependencies): add `wd`

plugins/nvm/nvm.plugin.zsh
- Fixes missing changes of https://github.com/ohmyzsh/ohmyzsh/commit/fd01fd66ce27c669e5ffaea94460a37423d1e134. Seems like `$node_version` was removed in that commit but not replaced in every usage.
- Related code snippet seems to be coming from [nvm-sh#zsh](https://github.com/nvm-sh/nvm?tab=readme-ov-file#zsh)
- Similar/related `nvm-sh` change: https://github.com/nvm-sh/nvm/pull/2874/
=> fix(nvm): use `nvm version` when needed

plugins/nvm/nvm.plugin.zsh
- When `cat` is aliased to something like `bat --style=number` ([bat](https://github.com/sharkdp/bat)), `$(cat "$nvmrc_path" | tr -dc '[:print:]')` fails because of additional information that these helpful tools display. This change fixes this behavior by using non-aliased version of `cat` command, which I think is a safer option to use within zsh plugins.
**Reasoning / Steps to reproduce**
=> fix(nvm): use `command cat` to avoid alias

plugins/git/README.md, plugins/git/git.plugin.zsh
If a branch is checked-out, `git branch` will show `*` (or `+` if it's checked-out in a worktree) as first character. This change will skip the first 2 characters that can be `*\s`, `+\s`, or `\s\s`.
=> fix(git): add checked-out branch support to `gbg*`

.editorconfig, .github/workflows/dependencies.yml, .github/workflows/dependencies/requirements.txt, .github/workflows/dependencies/updater.py
Closes #12178
- Use semver-based tag verification
- Enable cron-based action run
- Avoid creating PR if it was created previously.
Other stuff:
- Update requirements
- Use `actions/setup-python` to ensure Python version consistency
- Run `ruff` formatter
=> feat(dependencies): improve and enable cron-based checks

plugins/fzf/fzf.plugin.zsh
Fixes fzf plugin on Fedora. Plugin didn't previously find the completion script in `/usr/share/zsh/site-functions/fzf`.
Used the above `fzf_setup_using_opensuse` as a base. Just fixed to use the correct paths on Fedora.
```
$ rpm -ql fzf | grep zsh
/usr/share/fzf/shell/key-bindings.zsh
/usr/share/zsh/site-functions
/usr/share/zsh/site-functions/fzf
```
=> feat(fzf): add support for Fedora package

templates/zshrc.zsh-template
- fix(zshrc): added `~/.local/bin/` to PATH, as required by systemd, so user specific binaries can be found
The vast majority of modern Linux distributions are systemd based. User specific binaries can be now placed inside `~/.local/bin/` ([SPEC](https://www.freedesktop.org/software/systemd/man/latest/file-hierarchy.html#~/.local/bin/)).
For this reason, `~/.bashrc` already adds that location to PATH. E.g. (code from a Fedora 40 brand new installation)
```
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH
```
=> chore(template): propose add `.local/bin` to PATH

themes/agnoster.zsh-theme
- [ x ] The PR title is descriptive.
- [ x ] The PR doesn't replicate another PR which is already open.
- [ x ] I have read the contribution guide and followed all the instructions.
- [ x ] The code follows the code style guide detailed in the wiki.
- [ x ] The code is mine or it's from somewhere with an MIT-compatible license.
- [ x ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ x ] The code is stable and I have tested it myself, to the best of my abilities.
- [ x ] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
- [...]
...
=> feat(agnoster): add `anaconda` env information

themes/agnoster.zsh-theme
- Fix typo: promp_conda_virtualenv
`promp_conda_virtualenv` --> `prompt_conda_virtualenv`
...
=> chore(agnoster): typo

plugins/laravel/README.md, plugins/laravel/laravel.plugin.zsh
- Added `pamcl` alias for `php artisan make:class`
- Added `pamen` alias for `php artisan make:enum`
- Added `pami` alias for `php artisan make:interface`
- Added `pamtr` alias for `php artisan make:trait`
Laravel version 11 introduced new artisan commands, see https://laravel.com/docs/11.x/releases#new-artisan-commands. I think it would be nice to have this aliases for laravel plugin makers alias.
=> feat(laravel): add aliases laravel 11

plugins/git/git.plugin.zsh
This commits adds the option `stable` to the available list of options used by the `git_main_branch` function, which returns the main used by the git repository.
- Introduces a new option `stable` to the list of options handled by the `git_main_branch` function, which detects and returns the name of the repository's main branch.
=> feat(git): support `stable` in `git_main_branch`

plugins/macos/README.md, plugins/macos/macos.plugin.zsh
- Added Support for Tabby Terminal for MacOS-Plugin
Please tell me, if I should change anything :-)
=> Add Support for Tabby Terminal in Macos Plugin

plugins/kitty/README.md, plugins/kitty/kitty.plugin.zsh
- [ ✅ ] The PR title is descriptive.
- [ ✅ ] The PR doesn't replicate another PR which is already open.
- [ ✅ ] I have read the contribution guide and followed all the instructions.
- [ ✅ ] The code follows the code style guide detailed in the wiki.
- [ ✅ ] The code is mine or it's from somewhere with an MIT-compatible license.
- [ ✅ ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ ✅ ] The code is stable and I have tested it myself, to the best of my abilities.
- Adds a `kitty` plugin.
- Only loads if the terminal identifies as xterm-kitty
- Provides a very useful `kssh` alias that one can use to ssh and correct terminfo issues on remote hosts.
- There's also a `kssh-slow` which does a slower form of the special ssh should `kssh` not work.
- …
=> A plugin for the Kitty terminal

plugins/pass/_pass
- changed pass plugin according to https://lists.zx2c4.com/pipermail/password-store/2019-January/003502.html I don't know why this wasn't merged upstream, but this fixes the completion if you use multiple repositories
without the fix `workpass secre[tab]` works but `workpass edit secre[tab]` would search the default pass directory for that secret
=> fix(pass): completion for multiple repositories

plugins/yarn/README.md, plugins/yarn/yarn.plugin.zsh
- This updates the yarn plugin to better support Yarn berry (aka Yarn v2 and beyond) because some commands are no longer available or changed in modern Yarn.
- A new pair of aliases `yii` and `yifl` are added. These are to install dependencies while locking versions down to the `yarn.lock` file. The reason `yifl` is an alias for `yii` is to respect that for v1 it's **y**arn **i**nstall --**f**rozen-**l**ockfile, whereas for berry it's **y**arn **i**nstall --**i**mmutable, so `yii`.
- The aliases `ydlx` and `yn` are added to cover [`yarn dlx`](https://yarnpkg.com/cli/dlx) and [`yarn node`](https://yarnpkg.com/cli/node)
Version checking inspired by the git plugin
=> feat(yarn)!: add optional support for yarn berry

plugins/tmux/tmux.plugin.zsh
Fixes #12282
Closes #12278 
- Fixes completion for aliased functions (`ta`, `tad`, and `tkss`) introduced in [fix(tmux): do not pass empty flags to aliases #12232](https://github.com/ohmyzsh/ohmyzsh/pull/12232).
Inspired by https://github.com/ohmyzsh/ohmyzsh/blob/e0c6cb147030350c8e27dbdeda6e8a4d367d1e66/plugins/debian/debian.plugin.zsh#L120-L133
=> fix(tmux): add completion for alias functions

plugins/bgnotify/bgnotify.plugin.zsh
- N/A If the code introduces new aliases, I provide a valid use case for all plugin users down below.
`bgnotify` notifications don't work in macOS when using latest version of `terminal-notifier`
After trying out the command calling `terminal-notifier` used to send notifications manually, could reproduce the issue. Removing `-sender` arg seems fixed the issue.
After reading [`terminal-notifier`'s README](https://github.com/julienXX/terminal-notifier/blob/2.0.0/README.markdown) seems this is actually expected:
> _`-sender ID`_
> [...]
> _Because of this it is important to note that **you cannot combine this with options like -execute and -activate** which depend on the sender of the notification to be ‘terminal-notifier’ to perform its work._
Using therefore only `-activate` argument so …
=> fix(bgnotify): use terminal-notifier args properly

README.md
- Reword the alternative mirror install line (as it currently implies that Indian users for all ISPs need to use the other method, while this isn't true as `raw.githubusercontent.com` is only blocked in Jio and their affiliated ISPs so I have added a note about it).
- Fix minor typos in the page.
...
=> docs: reword alternative installer mirror

plugins/eza/eza.plugin.zsh
Explicitly pass the default `automatic` argument to `--icons` flag, if icons are configured to display. Without this argument, it causes tab-completion not to work.
See issue on Eza's tracker here: https://github.com/eza-community/eza/issues/964#issuecomment-2143417856
Also occurred to me on zsh 5.9 in Arch Linux.
Follow up to PR #12469 merged 3 days ago from this PR, adding support for this option
=> fix(eza): icons tab completion

plugins/extract/extract.plugin.zsh
Added a pattern to match filename.7z.[digit]
ex. a.7z.001, a.7z.002, a.7z.003
```bash
> x a.7z.001
```
=> feat(extract): add support for multi-part 7z

plugins/swiftpm/README.md, plugins/swiftpm/_swift
This PR updates the SwiftPM plugin autocomplete information for Swift 5.9.
Result autocompletion
- `_swift` file was generated by running swift package completion-tool generate-zsh-script with Swift [5.9](https://github.com/apple/swift-package-manager/releases/tag/swift-5.9-RELEASE)
=> feat(swiftpm): update completion for Swift 5.9

plugins/symfony6/README.md, plugins/symfony6/symfony6.plugin.zsh
- Add plugin for native autocompletion from Symfony 6
Native auto-completion was introduced in Symfony 5.4, but only for bash.
As of Symfony 6.2, zsh is also supported, so I wanted to add it as a new plugin.
The code is generated by the Symfony command `php bin/console completion zsh'.
https://symfony.com/doc/current/console.html#console-completion
https://symfony.com/blog/new-in-symfony-6-2-console-improvements#zsh-shell-autocompletion
=> Add plugin for native autocompletion from Symfony 6

plugins/screen/screen.plugin.zsh
lib/termsupport.zsh creates titles for screen which take precedence over
titles set by the screen plugin. Unsetting the title() function within
the screen plugin prevent this "race-condition".
=> Prevent screen plugin title being overwritten by omz core

plugins/timer/timer.plugin.zsh
- fix(timer): Add check to see if last command that was run was `clear` and if so, don’t print the output of the timer. 
The current behavior of the timer plugin is that it outputs the result of the timer even when the last command is the `clear` command. This poses a problem because once the screen has been cleared, it adds one more line to print the timer at the top of the screen before then printing out the terminal prompt. To fix this, I have added a simple check to see if the last command run is the `clear` command and if so, do not print the result of the timer.
=> fix(timer): skip timer after running `clear`

lib/history.zsh
- Fixes logic error from 35a6725 when using `history -c`
- Prompting for confirmation causes history to be deleted when typing anything but explicitly `n`, `N`, or sending `\n`. 
- New logic no longer proceeds with deletion when pressing wrong key and only deletes history when sending `y` or `Y`.
Copying @mcornella as he was assigned to the original issue
=> fix(history): fix logic error in prompt for `history -c` (ohmyzsh#12472)

plugins/alias-finder/README.md
Being new to ohmyzsh it wasn't immediately obvious to me what this plugin did or how to use it. I've added some examples to hopefully make it more obvious to future readers.
- Add usage info to alias-finder plugin
=> docs(alias-finder): add some examples

themes/essembeh.zsh-theme
- with latest nixos zsh/ohmyzsh update, git informations in prompt were not displayed
- [...]
...
=> fix(essembeh): fix git info in prompt

plugins/bun/bun.plugin.zsh
- fix(bun): bun completions should explicitly set SHELL
`bun completions` results in a file according to the current `$SHELL`, but if you don´t have ZSH as your `$SHELL`(for example, because you didn't or couldn't run chsh), the plugin will create a bash script as the completions script. This commit fixes this.
Users with broken completions probably need to remove their `$ZSH_CACHE_DIR/completions/_bun` so it is created again properly.
=> fix(bun): set `SHELL` when generating completions

plugins/command-not-found/README.md
SUSE's /usr/bin/command-not-found works for Gentoo, too
Just a small comment that mentions that this works out of the box on gentoo.
I'm not sure whether to link to the github page of the package or to the actual package on https://packages.gentoo.org. I think users would find the github page more useful because it also mentions that pfl should be installed.
=> docs(command-not-found): mention gentoo support

themes/pygmalion.zsh-theme
The Pygmalion theme previously had some logic for counting line length and taking action based on line length. The action was removed in c52441b624c0b1fa075bc6110032bd4e75311909, but the counting still needlessly happens. 
This commit removes the code to count line length, and simplifies the Pygmalion theme by moving the "precmd" into the setup. 
As a bonus unintended side effect, this makes the Pygmalion theme compatible with the current async prompting logic (i.e. after this change, Pygmalion is no longer affected by https://github.com/ohmyzsh/ohmyzsh/issues/12328)
=> Simplify Pygmalion Theme

plugins/docker-compose/docker-compose.plugin.zsh
Before
`(( ${+commands[docker-compose]} )) && dccmd='docker-compose' || dccmd='docker compose'`
After
`[[ -x "$(command -v docker-compose)" ]] && dccmd='docker-compose' || dccmd='docker compose'`
Fixes https://github.com/ohmyzsh/ohmyzsh/issues/12553
To test, on MacOS with latest Docker Desktop. Can be replicated on any Linux, just use appropriate path.
Create failing symlink
```sh
rm -rf /usr/local/bin/docker-compose
ln -s  /Applications/Docker.app/Contents/Resources/bin/docker-compose /usr/local/bin/docker-compose
[[ -x "$(command -v docker-compose)" ]] && dccmd='docker-compose' || dccmd='docker compose'
#check output
echo $dccmd
rm -rf /usr/local/bin/docker-compose
ln -s  /Applications/Docker.app/Contents/Resources/cli-plugins/docker-compose /usr/local/bin/docker-compose
[[ -x …
```
=> fix(docker-compose): fix test for `docker-compose` executable

plugins/eza/README.md
The docs to enable the `hyperlink`-flag described setting the wrong variable. Probably just copy-pasted from the other part of the docs.
In the script where the variable is used, it's checking for the correct name. So it only seems to be a doc issue.
https://github.com/ohmyzsh/ohmyzsh/blob/be10a9127731e7c6a9a57f8c8c1789e233117ae9/plugins/eza/eza.plugin.zsh#L41-L43
-
=> docs(eza): fix variable name to enable hyperlink flag

plugins/kubectl/kubectl.plugin.zsh
- Fixes #12562
This PR creates a wrapper completion function that sets the right parameters and calls the `kubectl` completion. This way the official completions are loaded and it works again.
=> fix(kubectl): fix kubectl completion for `kj`, `kjx` and `ky` aliases

plugins/dircycle/README.md, plugins/dircycle/dircycle.plugin.zsh
=> feat(dircycle): add bindings to go up or down in hierarchy

templates/zshrc.zsh-template
I changed the configuration line related to `Compilation flags` in the zshrc template (`zshrc.zsh-template`) file.
**ORIGINAL:**
```zsh
```
Instead of redefining this configuration line in the template, I propose using `uname -m`, which allows you to access this information without having to define it manually.
**MODIFICATION:**
```zsh
```
This way, if you are not using an `x86_64` architecture, you will no longer need to remember to change this detail, only to uncomment the configuration line.
This modification simplifies the configuration process and ensures compatibility with various architectures without manual intervention.
=> Update zshrc template to use `uname -m` for automatic architecture detection in ARCHFLAGS configuration

plugins/arduino-cli/README.md, plugins/arduino-cli/arduino-cli.plugin.zsh
- Adds autocompletion for [arduino-cli](https://github.com/arduino/arduino-cli)
- Uses the zsh command completion generated by arduino-cli itself like as kubectl does.
=> feat(arduino-cli): add completion plugin

plugins/toolbox/README.md, plugins/toolbox/toolbox.plugin.zsh
This allows the use of `$(toolbox_prompt_name)` function in order to display the toolbox name in prompt as such:
```
~ > toolbox enter fedora-40
fedora-40 ~ > exit
~ > toolbox enter xelatex
xelatex ~ >
```
=> feat(toolbox): add function to show toolbox name

plugins/colorize/colorize.plugin.zsh
This will allow users to select the lexer and consequently get some good ol' colouring when the input is from a pipe:
```shell
cat ~/.oh-my-zsh/plugins/colorize/colorize.plugin.zsh | ZSH_COLORIZE_TOOL=chroma ccat -lzsh # using chroma
cat ~/.oh-my-zsh/plugins/colorize/colorize.plugin.zsh | ZSH_COLORIZE_TOOL=pygmentize ccat -lzsh # using pygmentize
```
- [...]
...
=> fix(colorize): support args when input is stdin

plugins/catimg/README.md, plugins/catimg/catimg.plugin.zsh, plugins/catimg/catimg.sh
- Change deprecated in imagemagick v7 convert command to magick
https://github.com/ImageMagick/ImageMagick/commit/75a5c6d168379dd6e74f207468444cb2cff11720
=> fix(catimg): add support to `magick` binary

plugins/git/README.md, plugins/git/git.plugin.zsh
- Add `gmff` for `git merge --ff-only`
- Add `grpum(i?)` for `git pull --rebase (--interactive)? upstream $(git_main_branch)` (analogously to already existing `grpom(i?)`)
- Add `grbum` for `git rebase upstream $(git_main_branch)` (analogously to already existing `grbom`)
The first change for `--ff-only` merge is similar to the abandoned #8119.
The need behind these aliases stem from workflows where a dedicated central repository enforces things like linear history, but the conventional workflow involves the user itself having a fork where they exert total control. From my personal perspective, the project in question is [LLVM](http://github.com/llvm/llvm-project). In my local fork, I go wild with branches and merge commits, but the official upstream does **not** use pull requests and …
=> feat(git): add `gmff`, `gprum(i)`, `grbum` aliases to work with `upstream` remotes

lib/grep.zsh
Grep options are added twice when using `egrep` and `fgrep` aliases.
The options are added one time on the `grep` alias, and a second time on the `egrep` and `fgrep` aliases definitions.
=> fix(grep): remove duplicate options

plugins/extract/README.md, plugins/extract/extract.plugin.zsh
- Allows extracting `.vsix` files using `unzip`
=> feat(extract): add support for .vsix files (VS Code extension)

plugins/bedtools/_bedtools, plugins/brew/brew.plugin.zsh, plugins/docker/docker.plugin.zsh, plugins/emoji/update_emoji.py, plugins/gem/gem.plugin.zsh, plugins/history-substring-search/history-substring-search.zsh, plugins/hitchhiker/fortunes/hitchhiker, plugins/lpass/_lpass, plugins/python/python.plugin.zsh, plugins/rails/_rails, plugins/swiftpm/_swift, plugins/zsh-navigation-tools/README.md, plugins/zsh-navigation-tools/doc/n-preview
Fix typos
Used [CLI tool `typos`](https://github.com/crate-ci/typos) to find these - rejected some false positives.
=> Fix some typos

themes/awesomepanda.zsh-theme
- Reverts 80c114cb3a64044ea50b623f96a35bc022db5e8d which introduced escape sequences `%{%}` which prevents zsh from accurately counting UTF8 characters.
Fixes #12645
=> Revert "fix(awesomepanda): new line wrap"

plugins/extract/_extract, plugins/extract/extract.plugin.zsh
- Adds support for extracting `.crx` files (Chrome extension format)
- Refactors `_extract` into an array of extensions for improved DX
=> feat(extract): add support for `.crx` (Chrome extension format)

plugins/kubectl/README.md, plugins/kubectl/kubectl.plugin.zsh
- [ x ] The PR title is descriptive.
- [ x ] The PR doesn't replicate another PR which is already open.
- [ x ] I have read the contribution guide and followed all the instructions.
- [ x ] The code follows the code style guide detailed in the wiki.
- [ x ] The code is mine or it's from somewhere with an MIT-compatible license.
- [ x ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ x ] The code is stable and I have tested it myself, to the best of my abilities.
- [ x ] If the code introduces new aliases, I provide a valid use case for all plugin users down below.
Add 2 new kubectl aliases
...
=> feat(kubectl): show labels in aliases `kgpsl` (get pod) and `kgnosl` (get node)

plugins/web-search/README.md, plugins/web-search/web-search.plugin.zsh
- Add search with chatgpt --> "https://chat.openai.com?q=";
- Add new aliases in README.md ohmyzsh/plugins/web-search/README.md
ChatGPT like LLMs are a great developer resource while building stuff and I've been using it since a long time to debug stuff, would be great to have an util in the CLI as well.
We can do other LLMs as well like perplexity but not sure if they support search through query. 
Also it'll work with `!!` operator to search about last query using chatgpt (which works for all the other alias as well)
...
=> feat(web-search): add chatgpt

lib/git.zsh
- Files with short status `M` were incorrectly being considered as `ADDED` instead of `MODIFIED`. This updates the mapping to `MODIFIED`
=> fix(git): update prefix map for modified files

plugins/bgnotify/README.md, plugins/bgnotify/bgnotify.plugin.zsh
Add a new option `bgnotify_extraargs` for `bgnotify` to pass user defined args to notifier
It is useful for some notifier. e.g. `notify-send` will by default send a persistent notification keeping in notification bar. We can add an arg `-e` to `notify-send` so that the notification will be transient.
Other useful extra args for `notify-send` could be `--urgency` to specifies the urgency level
I believe in that it is also useful for other notifier than `notify-send`
=> feat(bgnotify): add config to pass extra args

plugins/terraform/README.md, plugins/terraform/terraform.plugin.zsh
- Added alias `tfaa` for `terraform apply -auto-approve` in terraform plugin.
=> feat (terraform): add `apply -auto-approve` alias

themes/gnzh.zsh-theme
- enable virtualenv plugin to see virtualenv
prompt correctly align with terminal prompt
...
=> feat(gnzh): add virtualenv prompt

plugins/systemadmin/README.md, plugins/systemadmin/systemadmin.plugin.zsh
- feat(systemadmin): Add alias for `ping6` adding a count limit
- Reason for new alias: `ping` already has the limit set, ipv6 becomes more and more widespread, hence `ping6` should receive the same treatment.
- Can't reopen #4997 so this is the new one.
=> feat(systemadmin): add `ping6` alias with count limit

plugins/ssh-agent/ssh-agent.plugin.zsh
- fix ssh-agent plugin trying to create a link to /tmp in termux, instead use $PREFIX/tmp
- I did not find an issue about this however it is an issue that I have, I could open an issue if requested.
=> fix(ssh-agent): use termux prefix for tmp

plugins/chezmoi/README.md, plugins/chezmoi/chezmoi.plugin.zsh
- Add plugin for `chezmoi` which adds autocomplete.
- No aliases added, this is handled in #12241.
- This implements/supersedes #8852.
=> feat(chezmoi): add completion plugin

plugins/fastfile/fastfile.plugin.zsh
'default' is not a standard command in zsh causing this plug-in to break in vanilla zsh. By substituting 'default' for zsh's built-in parameter expansion we are able to assign default values to unset variables while remaining compatible with vanilla zsh. Without this change, user's configs are liable to break.
- FIX: Two 'command not found' that broke the plug-in in vanilla zsh environments.
- REFACTOR: Replaced external command invocations with built-in zsh parameter expansions.
...
=> fix(fastfile): use idiomatic expressions

plugins/opentofu/README.md, plugins/opentofu/opentofu.plugin.zsh
- Added `apply -auto-approve` alias on opentofu.
Similar commit on terraform https://github.com/ohmyzsh/ohmyzsh/commit/865291cb7af2fef7e67128fd4294f3ffa9b08c3d
=> feat(opentofu): add `apply -auto-approve` alias

tools/theme_chooser.sh
When the zsh shell is installed at a non-default location like  `~/.nix-profile/bin/zsh` for installation via nix. I was getting
```console
zsh: ./.oh-my-zsh/tools/theme_chooser.sh: bad interpreter: /bin/zsh: no such file or directory
```
This change fixes that issue.
- Replaces the shebang to make it more portable
```suggestion
- #!/bin/zsh
+ #!/usr/bin/env zsh
```
=> fix(theme-chooser): use `env` in shebang

plugins/uv/README.md, plugins/uv/uv.plugin.zsh
- Add the `uv.plugin.zsh` file with the plugin for [`uv`](https://github.com/astral-sh/uv), a Python package manager (and more) akin to `poetry`.
- Aliases I added are based on the usual workflow with Python package managers, so it's fairly standard I'd say. Only debatable ones are `uvlu` and `uvlr`, which are (commonly used for me) variants of `uvl` (and same for `uvs`, `uvsu` and `uvsr`).
- I don't know how to properly split an `alias` into a multiline string to follow the 80 character limit. I didn't check the _code follows the code style guide_ entry because of this.
=> Add uv plugin

README.md, lib/git.zsh
With this changes users can force the registration of async callbacks for git prompt, escaping from the requirement of having it in the theme.
=> feat(git): add escape hatch to enable async prompt

plugins/poetry-env/poetry-env.plugin.zsh
Suppress the following if already deactivated:
```
_togglePoetryShell:11: command not found: deactivate
```
=> fix(poetry-env): only run `deactivate` if needed

themes/jonathan.zsh-theme
- Add support for virtualenv prompt mangling in Jonathan theme. Relies on `virtualenv` plugin.
Venv prompt mangling is a problem for themes with a horizontal bar over the prompt. It causes the first line of the prompt to overflow and wrap, turning into an unreadable mess. This PR fixes it for Jonathan, following the existing approach used to support Ruby prompts.
=> feat(jonathan): add virtualenv support

plugins/gem/gem.plugin.zsh
There was a typo setting completions for docker instead of gem. Fixing.
Closes #12725
=> fix(gem): regression with gem completion

plugins/ssh-agent/ssh-agent.plugin.zsh
This pull request enhances the `ssh-agent` plugin to add all files in the user's `~/.ssh/` directory that start with `-----BEGIN OPENSSH PRIVATE KEY-----`, regardless of their filenames.
Previously, the plugin only added keys with hardcoded names (e.g., `id_rsa`, `id_dsa`). This change addresses the issue where users with custom key names were unable to automatically load their keys through the plugin.
By including all valid OpenSSH private keys, this enhancement improves compatibility and flexibility for users who prefer to use custom key names or manage their keys in a non-standard way.
- Modified the `_add_identities` function in `plugins/ssh-agent/ssh-agent.plugin.zsh` to iterate through all files in `~/.ssh/` and add those that start with `-----BEGIN OPENSSH PRIVATE KEY-----` to the …
=> feat(ssh-agent): add keys regardless of filename

.github/workflows/dependencies/updater.py
Related: https://github.com/ohmyzsh/ohmyzsh/pull/12747#issuecomment-2410440748
- Use `new_version` (aware of tag version) instead of `short_sha` to generate commit subject
- Not tested!
=> ci(dependencies): use tag version in git commit if available

plugins/ssh-agent/ssh-agent.plugin.zsh
This reverts commit d2d5155d41cbe183ef172fef1e83a29d116a5af6.
Revert #12741 that brought several regressions.
From now on `identities` option has to be used to avoid loading undesired keys.
=> Revert "feat(ssh-agent): add keys regardless of filename (#12741)"

plugins/volta/volta.plugin.zsh
- fix the comment typo which doesn't match the plugin name
...
=> docs(volta): fix typo

plugins/web-search/web-search.plugin.zsh
Allow multi-word parameters, e.g. `chatgpt "hello there" "i am" carlo` behave the same way as `chatgpt hello there i am carlo`.
=> fix(websearch): allow multi-word parameters

plugins/vagrant-prompt/README.md, plugins/vagrant-prompt/vagrant-prompt.plugin.zsh
- Fixed the `sed` parser to get any possible state reported by `vagrant status`
- Updated the state to variable mapping
- Documented changes
Fixes #12193
=> fix(vagrant-prompt): make `vagrant_prompt_info` generic for any state

plugins/autojump/autojump.plugin.zsh
- Adds Termux install path which makes the autojump plugin usable on Termux when relying on autojump installed via the Termux package.
`$PREFIX` is preferable over `/data/data/com.termux/files/usr` as `$PREFIX` is defined by Termux and not hardcoding it allows forks of Termux with different paths such as `com.termuxfork` to have the support too.
This may accidentally enable autojump to also work on some other $PREFIX using systems
Note: shouldn't the array entries be quoted? I didn't quote the new entry as the older ones aren't quoted either. Is this a bash to zsh difference and zsh can't split strings there?
<details>
<summary>dpkg -L autojump for good measure</summary>
```
/.
/data
/data/data
/data/data/com.termux
/data/data/com.termux/files
/data/data/com.termux/files/usr …
```
=> feat(autojump): add `termux` install path

plugins/poetry-env/poetry-env.plugin.zsh
Properly deactivate shell if you move directly from one poetry env to another otherwise you get stuck in the old virtual env unless you hit a non-poetry directory first which would trigger the deactivate command.
- Changed && to || to properly trigger deactivation.
=> fix(poetry-env): switch venv between poetry dirs

plugins/pyenv/README.md, plugins/pyenv/pyenv.plugin.zsh
- feat(pyenv): add option to hide system Python version
- feat(pyenv): add prefix and suffix for pyenv_prompt_info
n/a
=> feat(pyenv): add prompt customization

plugins/tailscale/tailscale.plugin.zsh
- only changes on tailscale plugin, no new aliases introduced.
according to https://tailscale.com/kb/1080/cli?tab=macos, if a user is using App Store version of tailscale, it would be an alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale". Current tailscale plugin does not work in that case.
cc @lukeab
=> fix(tailscale): load completion when `tailscale` is an alias

plugins/pipenv/pipenv.plugin.zsh
This change uses traditional `activate` instead of `pipenv shell` so that transitions between pipenv projects happen in the same shell and it's possible to properly deactivate the shell.
Fixes #12184
=> fix(pipenv): fix auto-shell functionality when cd-ing out

plugins/bazel/README.md, plugins/bazel/bazel.plugin.zsh
For https://registry.bazel.build/ files and archives use an integrety value to proof that you get the correct artifact. However, getting this value is not that trivial and so far not yet documented. https://github.com/bazelbuild/bazel/issues/17124 is the issue for adding the documentation but is open for about 2 years.
This PR adds the generation as function to the bazel plugin.
- Add function for generating bzlmod integrety value
- Fix indention of the markdown table for the aliases
...
=> feat(bazel): add bzlmod integrity gen function

plugins/laravel/README.md, plugins/laravel/laravel.plugin.zsh
- Added alias paopc for the php artisan optimize:clear command in the Laravel plugin.
This alias provides a quick way to clear all cached data, streamlining the process and ensuring that the application runs with the latest configuration and optimized settings.
...
=> feat(laravel): add alias for `optimize:clear`

plugins/per-directory-history/README.md
- Add HISTORY_START_WITH_GLOBAL to the documentation to enable `per-directory-history` to start in global history mode (defaults to local history).
- reference to the variable https://github.com/jimhester/per-directory-history/blame/6363a60d2b63383eea4b42c1e115ff6c72a5cda9/per-directory-history.zsh#L60
=> docs(per-directory-history): add variable docs

themes/af-magic.zsh-theme
- Adds a fallback method for detecting Python virtualenv prompt for `af-magic` theme separator line. 
The current method seems to be broken in some cases. The previous version assumes that the name of the virtual environment is the venv directory itself (e.g., `.venv`), but this isn't always the case, as running `uv venv` names the virtualenv based on the directory where it was created.
=> fix(af-magic): add logic for virtualenv separator

plugins/rust/rust.plugin.zsh
On recent versions of `rustc`, the `+toolchain` option has disapear. To prevent the command from issuing an empty string, call `rustc` through `rustup run rustc`.
=> fix(rust): call `rustc` through `rustup run`

plugins/grc/grc.plugin.zsh
=> Fix: add linuxbrew path for grc

plugins/python/README.md, plugins/python/python.plugin.zsh
- Add `PYTHON_VENV_NAMES` array setting with defaults being `(venv .venv)`.
- Adapt `vrun` and `auto_vrun` functions to respect the setting.
- Add documentation
=> feat(python): allow multiple venvs via `$PYTHON_VENV_NAMES` setting

plugins/perl/README.md, plugins/perl/perl.plugin.zsh
- Add code to perl plugin to activate perlbrew if 'perlbrew' function not defined already 
Currently, the PERL plugin defines some aliases for perlbrew, but doesn't check or activate perlbrew.  This PR adds (optional) perlbrew activation to the plugin. It will check if the 'perlbrew' function is defined; and if not, attempt to source the activation code included in perlbrew. The perlbrew root directory can be defined by the standard PERLBREW_ROOT variable; and then entire activation can be disabled by setting PERLBREW_NO_AUTO_ADD to some value before sourcing oh-my-zsh.
=> feat(perl): add `perlbrew` auto activation

plugins/direnv/direnv.plugin.zsh
Instead of silently not installing the shell hooks, issue a warning (then keep doing nothing).
Follow-up of https://github.com/ohmyzsh/ohmyzsh/pull/8809#issuecomment-612344196 and https://github.com/ohmyzsh/ohmyzsh/issues/12798#issuecomment-2464749859.
=> Warn user if direnv not found

tools/changelog.sh
- This change keeps track whether it has shown any changes, and prints a message otherwise
- This is helpful for example if a release/update only has chore or other commits that are not noteworthy.
Fixes #12927
=> fix(changelog): show if there are no changes

README.md, lib/cli.zsh
- Removes the `omz update --unattended` flag, which should not be used.
- Adds the documentation to the README.
- Shows error if used.
- Shows breaking change notice.
Fixes #9808
Related: https://github.com/ohmyzsh/ohmyzsh/issues/12168#issuecomment-2313224758
=> fix(cli)!: remove harmful `--unattended` flag for `omz update`

.gitignore
Adds compiled `*.zwc` files to `.gitignore`.
I've found an old PR that also introduced this change along some other things, but it was closed by the submitter #9147.
=> chore: add `.zwc` files to `.gitignore`

plugins/terraform/terraform.plugin.zsh
- Enable prompt display with non default terraform data dir
cc @mcornella
=> feat(terraform): support `TF_DATA_DIR` in `tf_prompt_info`

plugins/mvn/mvn.plugin.zsh
Maven also supports putting a directory into `<relativePath>`, however, the current version of the plugin only supports references to files and produce the following error with directories:
```
sed: read error on XXXXXXXX: Is a directory
```
This PR fixes that.
Not sure who maintains the mvn plugin so I guess cc @mcornella from the git history?
=> fix(mvn): Handle directories in <relativePath>

plugins/chruby/chruby.plugin.zsh
- Fixes (and hopefully speeds up) the `chruby` plugin loading process on Apple Silicon macs where the default Homebrew prefix is `/opt/homebrew`
cc @mcornella @carlosala
=> fix(chruby): update brew sourcing for Apple Silicon

themes/agnoster.zsh-theme
This is a rebase of the excellent work @Kilobyte22 did in #3434. These were the initial features in that PR:
- Setting color for all kinds of elements, by setting an appropriate config variable to the color name in your zshrc. A full list of colors can be found in `themes/agnoster.zsh-theme`. Example:
AGNOSTER_GIT_DIRTY_BG=red # Set the git prompt background color to red for dirty repos
- Allowing to separate the git root and the relative path in your prompt by setting `AGNOSTER_GIT_INLINE` to `true`. You will then have a segment for the git root (ie. `~/.oh-my-zsh`) followed by the existing git branch segment (ie. `master`) and finally the relative directory path (ie. `themes`)
- By setting `AGNOSTER_STATUS_RETVAL_NUMERIC` to `true`, the return value in the status prompt will be the …
=> feat(agnoster): add color config and add some git stuff

themes/agnoster.zsh-theme
This makes them readable in light terminals too and not only dark ones.
- Prints white text rather than default-colored text on black segments (context and status)
=> fix(agnoster): print white text over black

themes/agnoster.zsh-theme
- Print white text over black only when `SOLARIZED_THEME` is set to `light`
Changes introduced by #12525 changes `AGNOSTER_CONTEXT_FG` and `AGNOSTER_STATUS_FG` text color from default to white under default configuration, which makes a difference when terminal default text color is not white.
This should be achieved by setting `SOLARIZED_THEME` to `light` or modifying `AGNOSTER_CONTEXT_FG` and `AGNOSTER_STATUS_FG` manually in .zshrc.
cc @Kekun @carlosala
=> fix(agnoster): print white text over black for light theme only

plugins/jj/jj.plugin.zsh
- Use `COMPLETE=zsh jj` to generate dynamic completions
See: https://jj-vcs.github.io/jj/latest/install-and-setup/#command-line-completion
=> feat(jj): enable dynamic completion

plugins/uv/uv.plugin.zsh
Adds `alias uv="noglob pip"` for the uv plugin , [following the `pip` plugin](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/pip/pip.plugin.zsh#L85-L89). This is especially useful when installing modules with extras: e.g. `pip install module[extra]`
=> feat(uv): add uv='noglob uv' alias

plugins/dirhistory/dirhistory.plugin.zsh
- Adds support for the Ghostty terminal to the dirhistory plugin.
=> feat(dirhistory) add support for ghostty terminal

plugins/tmux/tmux.plugin.zsh
This is handy for tmux users who work in interactive mode.  By default, tmux would pass through e.g. X11, SSH agent, etc. via global environment.
=> Make tmux plugin refresh tmux global environments automatically.

plugins/macos/README.md, plugins/macos/macos.plugin.zsh
- Added support for Ghostty terminal for the `macos` plugin.
Tested locally for `tab`, `split_tab` and `vsplit_tab`.
=> feat(macos): add support for Ghostty terminal

plugins/bgnotify/bgnotify.plugin.zsh
- Check if sway is actually running before calling swaymsg
I just tried out hyprland and noticed, that on every new terminal it prints this error:
`00:00:00.007 [ERROR] [swaymsg/main.c:494] Unable to retrieve socket path`
It also prints this error after every command that took longer than the threshold (5 seconds).
Obviously hyprland isn't sway, so it also doesn't have a sway socket. So I changed the code that it doesn't only check if swaymsg is installed, but also if the `$SWAYSOCK` env variable is set, which indicates it is running on sway and swaymsg should work without errors.
It would be even better if it did support hyprland directly, and I might create another PR if I end up switching to hyprland, but for now this at least fixes the error messages everywhere. It also doesn't only …
=> fix(bgnotify): detect if sway is running and not just installed

plugins/alias-finder/alias-finder.plugin.zsh
…ble part## Standards checklist:
- Fix bug in alias-finder: If the input command's length is 1 or less, return early instead of making an invalid regex format.
- fixes https://github.com/ohmyzsh/ohmyzsh/issues/13016
=> fix(alias-finder): Return early on very short command (1-length)

plugins/docker/README.md
- Add a small section in the README for podman-docker wrapper users: A podman-docker user could be frustrated because normal docker completion does not work for them even though the commands follow normal docker grammar.
- resolves https://github.com/ohmyzsh/ohmyzsh/issues/13020
=> docs(docker): Add guide for Podman's Docker wrapper users

plugins/alias-finder/alias-finder.plugin.zsh
- There's typo that I made. "=" should be replaced with "==".
=> fix(alias-finder): Typo for equals

plugins/dnf/_dnf5
- Fix `_dnf_rpm_files` to `_dnf5_rpm_files` to match actual function definition
Fixes #13037
=> Fix function call typo in the dnf5 plugin

plugins/asdf/README.md, plugins/asdf/asdf.plugin.zsh
- fix autoloading for asdf completion
- clean up redundant code (for < v0.16)
- update docs
Closes https://github.com/ohmyzsh/ohmyzsh/issues/13025
=> fix: asdf completion && clean up old completion code

lib/cli.zsh, tools/upgrade.sh
Closes #13032
Ensure that `omz update` can be called in `noexec` environments.
Closes #13032
=> fix(cli): support `noexec` environments

plugins/macos/macos.plugin.zsh
Now it's possible to set `man` as an alias to `man-preview` without causing recursion issues.
- Changed `for page in "${(@f)"$(man -w $@)"}"` to `for page in "${(@f)"$(command man -w $@)"}"`
=> Update macos.plugin.zsh - Made it possible to alias `man` to `man-preview`

plugins/git-prompt/gitstatus.py
Use `--git-common-dir` to load stash because worktrees don't have individualized stash files, so the current practice of `git rev-parse --git-dir` fails to find the correct file.
- fix(git-prompt): Use `--git-common-dir` to load stash count
=> fix(git-prompt): Use `--git-common-dir` to load stash count

plugins/archlinux/archlinux.plugin.zsh
Actually check repo version of keyring package on first run of upgrade...
- [...]
...
=> fix(archlinux): Actually check repo version of keyring

plugins/procs/procs.plugin.zsh
- Update cache completion to support newer versions of procs
- Update comment that suggests it is bound to minikube (artifact from copied boilerplate)
Fixes #13052
=> Fixes #13052: support legacy and new procs completion command

plugins/vi-mode/README.md
This documents how to enable additional text objects, e.g., quoted strings, using standard Zsh features.
I was searching for this functionality and found https://github.com/ohmyzsh/ohmyzsh/issues/12343 that put me in the right direction.
I guess it's worthwhile to document it.
This also fixes a small grammar mistake.
- This documents how to enable additional text objects, e.g., quoted strings, using standard Zsh features. It also fixes a small grammar mistake.
I was searching for this functionality and found https://github.com/ohmyzsh/ohmyzsh/issues/12343 that put me in the right direction.
I guess it's worthwhile to document it.
=> vi-mode: Document additional text objects

plugins/kamal/README.md, plugins/kamal/_kamal, plugins/kamal/kamal.plugin.zsh
- Added autocomplete for Kamal commands and sub-commands.
- Added alias `kad` to the `kamal deploy` command. It stands for `KAmal Deploy` and looks similar to the Capistrano `cap` command which was a deployment standard in Ruby for many years.
=> feat(kamal): add autocomplete support and aliases for Kamal (https://kamal-deploy.org/)

lib/termsupport.zsh
This adds TERM=wezterm to the list of supported terminals.
https://wezterm.org/recipes/passing-data.html?h=osc#user-vars
WezTerm uses TERM=xterm-256color by default, but it endorses users to use TERM=wezterm in their configuration:
https://wezterm.org/config/lua/config/term.html
With this patch, oh-my-zsh will still support setting the window and tab name.
- add TERM=wezterm to the list of supported terminals in [lib/termsupport.zsh](https://github.com/tobii-dev/ohmyzsh/blob/78cfcccce4ae5c8c551e72e8f32eec11776c0dc6/lib/termsupport.zsh#L20)
=> feat(termsupport): add WezTerm window/tab title support (OSC 1, 2)

lib/history.zsh
- handle HIST_STAMPS with whitespace in timestamp format
```sh
$ echo $HIST_STAMPS
%y-%d-%m %T
$ which history
history: aliased to omz_history -t '%y-%d-%m %T'
$ typeset -ft omz_history
```
Without fix:
```sh
$ history > /dev/null
+ history.zsh:4 @omz_history:2> local clear list stamp REPLY
+ history.zsh:5 @omz_history:3> zparseopts -E -D 'c=clear' 'l=list' 'f=stamp' 'E=stamp' 'i=stamp' 't:=stamp'
+ history.zsh:7 @omz_history:5> [[ -n '' ]]
+ history.zsh:19 @omz_history:17> [[ 0 -eq 0 ]]
+ history.zsh:21 @omz_history:19> fc -t %y-%d-%m %T -l 1
omz_history:fc:19: event not found: %T
```
With fix:
```sh
$ history > /dev/null
+ history.zsh:4 @omz_history:2> local clear list stamp REPLY
+ history.zsh:5 @omz_history:3> zparseopts -E -D 'c=clear' 'l=list' 'f=stamp' 'E=stamp' 'i=stamp' …
```
=> fix(history): handle HIST_STAMPS with whitespace in timestamp format

themes/blinks.zsh-theme
- Make blinks theme respect user background color in dark mode
Tested on my local systems extensively on several different variants of Linux (Arch, Debian, and Ubuntu).
Before fix:
After fix:
=> [Bug Fix] Make blinks theme respect user background color in dark mode

lib/git.zsh
Moved `_omz_git_prompt_status` definition to ensure it's available before attempting registration. It couldn't be registered via `_omz_register_handler` previously because it was not yet defined at the time of registration.
=> Move _omz_git_prompt_status to be able to register as async handler

lib/cli.zsh
- Added a flag to `omz plugin list` which allows users to list only enabled plugins by category (built-in vs. custom)
Should be relatively efficient due to use of regex comparison as opposed to double `for` loops.
=> feat(cli) Add flag to `omz plugin list` to show only enabled plugins

themes/agnoster.zsh-theme
- Add a agnoster subtheme on conda supported
effect:
(Sorry, I can't upload pictures right now...)
such as:
```shell
zcx@zcx-workpc  🐍 ecloud  ~/.oh-my-zsh/themes   master  conda deactivate
zcx@zcx-workpc  🐍 base  ~/.oh-my-zsh/themes   master  conda deactivate
zcx@zcx-workpc  ~/.oh-my-zsh/themes   master  vim ../.zshrc
```
=> feat(theme): Make agnoster support conda environment

lib/functions.zsh
Use `open_command` on WSL to open a URL in the browser.
```zsh
open_command "https://example.com/test?arg=value&key=value"
```
Currently, this is executed with `cmd.exe`, which considers `&` (amongst others) as special characters that are not escaped.
The result of this is that the actual URL that is opened is truncated at the first special character. 
A prevalent case where this occurs is with multiple URL arguments, as shown in the above example.
- If detecting WSL, look for URLs (using the same definition for using `BROWSER`), and escape any of the following characters: `&|()<>^` with the `^` escape character (for cmd.exe)
* I am making use of `sed -E` here, are there any requirements about if `sed` with extended regular expressions is an expected dependency or not?
=> fix(open_command,wsl): Escape cmd.exe special chars for URLs in open_command when using WSL

plugins/ubuntu/README.md, plugins/ubuntu/ubuntu.plugin.zsh
• Enhanced the ubuntu plugin to detect and use apt-fast when available, providing faster package operations
• Maintains backward compatibility by falling back to apt or apt-get when apt-fast is not installed
=> feat(ubuntu): add apt-fast support for faster package management

plugins/rbw/rbw.plugin.zsh
- Only wipe `rbwpw` content if it is the latest one to be added. This avoids getting passwords wiped when chaining requests.
=> fix(rbw): do not wipe `rbwpw` items if newer are copied

themes/af-magic.zsh-theme
- Fixes dash calculation for Python virtualenv prompt for `af-magic` theme separator line.
Additional fix for #12875, where now I noticed that the prompt was still broken without the subtraction of the parentheses.
=> fix(af-magic): fix virtual env prompt fallback to take into account parentheses

plugins/web-search/README.md, plugins/web-search/web-search.plugin.zsh
- Add [RubyGems.org](https://rubygems.org) websearch to plugin.
...
=> feat(web-search): add RubyGems.org

lib/termsupport.zsh
When DISABLE_AUTO_TITLE is set to true, the code shouldn't return with a non-zero exit code. Yet if you don't explicitly return 0, at least on my macbook, the method returns a non-zero exit code.
Here's a quick file to test this behavior:
```zsh
#!/usr/bin/env zsh
function broken_preexec {
[[ "${DISABLE_AUTO_TITLE:-}" != true ]] || return  # Missing return code
echo "This line should run when DISABLE_AUTO_TITLE is false"
}
function fixed_preexec {
[[ "${DISABLE_AUTO_TITLE:-}" != true ]] || return 0  # Proper return code
echo "This line should run when DISABLE_AUTO_TITLE is false"
}
echo "=== Testing with DISABLE_AUTO_TITLE=true ==="
export DISABLE_AUTO_TITLE=true
echo "Testing broken function:"
broken_preexec
echo "Exit code: $?"
echo "Testing fixed function:"
fixed_preexec  
echo "Exit …
```
=> Fixed issue where the exit code becomes non-zero if DISABLE_AUTO_TITLE=1

plugins/tmux/tmux.plugin.zsh
- Detects if the terminal was started with [zed](https://zed.dev/) editor checking the $ZED_TERM env variable. If the terminal was started with zed, tmux is not started.
=> feat: dont start tmux if in zed terminal

plugins/alias-finder/README.md, plugins/alias-finder/alias-finder.plugin.zsh
basic grep is too slow for very long command. ripgrep can easily remediate this issue.
- Use ripgrep if possible
- resolves https://github.com/ohmyzsh/ohmyzsh/issues/13036
- resolves https://github.com/ohmyzsh/ohmyzsh/issues/13039
```sh
❯❯❯ brew install ripgrep
❯❯❯ alias X='echo test && echo test && echo test && echo test && echo test && echo test && echo test && echo test && echo test && echo test'
❯❯❯ alias-finder 'echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && echo "test" && …
```
=> feat(alias-finder): Use ripgrep if possible

plugins/extract/README.md, plugins/extract/_extract, plugins/extract/extract.plugin.zsh
7a0aa439e81e5fbc345bd25072ec975efdf07630
feat(extract): Add support for file extension aliases .pk{3,4,7} which are just renamed zip/7zip files.
File extensions .pk3 and .pk4 are renamed zip archives and the file extension .pk7 is a renamed 7zip file. They can be handled in the same way as zip and 7zip files.
https://doomwiki.org/wiki/PK3  
https://doomwiki.org/wiki/PK4
---
0c7b74a0f6846a4b9ef36695a910a8fd70af2113
chore(extract): Fix alphabetical sorting of supported file extensions in README.md having been case sensitive.
Previously the sorting was case sensitive (A-Z then a-z) in `README.md` but not in the completions file `_extract`, now both are case insensitive.
=> feat(extract): Support .pk{3,4,7} alias file extensions

plugins/poetry-env/poetry-env.plugin.zsh
- Fixed poetry-env plugin for projects without [tool.poetry] in their pyproject.toml file.
Resolves #13259 
With this change, the plugin will check for `pyproject.toml` and `poetry.lock` files to reliably check if it's a poetry project. Tested with poetry versions 1.8.5, 2.0.1 and 2.1.2.
PR based on #12985 which was closed by the owner before being seen by a maintainer.
=> fix(poetry-env): fix env detection for pyproject without [tool.poetry]

plugins/asdf/asdf.plugin.zsh
-  don't add `$ASDF_DATA_DIR/shims` to the path if already present
This is just a minor change to prevent `$ASDF_DATA_DIR/shims` from being added to the path multiple times (for example, if you `exec zsh`, your shims directory will keep getting added).
@RobLoach
=> bug(asdf): don't add $ASDF_DATA_DIR/shims to the path if already present

.gitpod.Dockerfile, .gitpod.yml, README.md
- Remove all references to gitpod
gitpod.io has transitioned to ona.com. The old badge no longer works, and we don't have to manually maintain a Dockerfile. We already have a [devcontainer config](https://github.com/ohmyzsh/ohmyzsh/blob/master/.devcontainer/devcontainer.json), and [github.dev also works out of the box](https://github.dev/ohmyzsh/ohmyzsh).
=> chore: remove obsolete gitpod integration

plugins/common-aliases/README.md
- Replace incorrect 'echo' command with 'tar -ztf' for listing tar.gz files
- This provides the correct command for users to list contents of gzip-compressed tar archives
- [...]
...
=> docs(common-aliases): fix tar.gz command in README
